export const brazilianStates = {
  AC: { name: 'Acre' },
  AL: { name: 'Alagoas' },
  AP: { name: 'Amapá' },
  AM: { name: 'Amazonas' },
  BA: { name: 'Bahia' },
  CE: { name: 'Ceará' },
  ES: { name: 'Espírito Santo' },
  GO: { name: 'Goiás' },
  MA: { name: 'Maranhão' },
  MT: { name: 'Mato Grosso' },
  MS: { name: 'Mato Grosso do Sul' },
  MG: { name: 'Minas Gerais' },
  PA: { name: 'Pará' },
  PB: { name: 'Paraíba' },
  PR: { name: 'Paraná' },
  PE: { name: 'Pernambuco' },
  PI: { name: 'Piauí' },
  RJ: { name: 'Rio de Janeiro' },
  RN: { name: 'Rio Grande do Norte' },
  RS: { name: 'Rio Grande do Sul' },
  RO: { name: 'Rondônia' },
  RR: { name: 'Roraima' },
  SC: { name: 'Santa Catarina' },
  SP: { name: 'São Paulo' },
  SE: { name: 'Sergipe' },
  TO: { name: 'Tocantins' },
  DF: { name: 'Distrito Federal' },
};
