export const cities = {
  acrelandia: { name: 'Acrelândia', state: 'AC' },
  'assis brasil': { name: 'Assis Brasil', state: 'AC' },
  brasileia: { name: 'Brasiléia', state: 'AC' },
  bujari: { name: 'Bujari', state: 'AC' },
  capixaba: { name: 'Capixaba', state: 'AC' },
  'cruzeiro do sul': { name: 'Cruzeiro do Sul', state: 'AC' },
  epitaciolandia: { name: 'Epitaciolândia', state: 'AC' },
  feijo: { name: 'Feijó', state: 'AC' },
  jordao: { name: 'Jordão', state: 'AC' },
  'mancio lima': { name: 'Mâncio Lima', state: 'AC' },
  'manoel urbano': { name: 'Manoel Urbano', state: 'AC' },
  'marechal thaumaturgo': { name: 'Marechal Thaumaturgo', state: 'AC' },
  'placido de castro': { name: 'Plácido de Castro', state: 'AC' },
  'porto acre': { name: 'Porto Acre', state: 'AC' },
  'porto walter': { name: 'Porto Walter', state: 'AC' },
  'rio branco': { name: 'Rio Branco', state: 'AC' },
  'rodrigues alves': { name: 'Rodrigues Alves', state: 'AC' },
  'santa rosa do purus': { name: 'Santa Rosa do Purus', state: 'AC' },
  'senador guiomard': { name: 'Senador Guiomard', state: 'AC' },
  'sena madureira': { name: 'Sena Madureira', state: 'AC' },
  tarauaca: { name: 'Tarauacá', state: 'AC' },
  xapuri: { name: 'Xapuri', state: 'AC' },
};
