export const cities = {
  alvaraes: { name: 'Alvarães', state: 'AM' },
  amatura: { name: 'Amaturá', state: 'AM' },
  anama: { name: 'Anamã', state: 'AM' },
  anori: { name: 'Anori', state: 'AM' },
  apui: { name: 'Apuí', state: 'AM' },
  'atalaia do norte': { name: 'Atalaia do Norte', state: 'AM' },
  autazes: { name: 'Autazes', state: 'AM' },
  barcelos: { name: 'Barcelos', state: 'AM' },
  barreirinha: { name: 'Barreirinha', state: 'AM' },
  'benjamin constant': { name: 'Benjamin Constant', state: 'AM' },
  beruri: { name: 'Beruri', state: 'AM' },
  'boa vista do ramos': { name: 'Boa Vista do Ramos', state: 'AM' },
  'boca do acre': { name: 'Boca do Acre', state: 'AM' },
  borba: { name: 'Borba', state: 'AM' },
  caapiranga: { name: 'Caapiranga', state: 'AM' },
  canutama: { name: 'Canutama', state: 'AM' },
  carauari: { name: 'Carauari', state: 'AM' },
  careiro: { name: 'Careiro', state: 'AM' },
  'careiro da varzea': { name: 'Careiro da Várzea', state: 'AM' },
  coari: { name: 'Coari', state: 'AM' },
  codajas: { name: 'Codajás', state: 'AM' },
  eirunepe: { name: 'Eirunepé', state: 'AM' },
  envira: { name: 'Envira', state: 'AM' },
  'fonte boa': { name: 'Fonte Boa', state: 'AM' },
  guajara: { name: 'Guajará', state: 'AM' },
  humaita: { name: 'Humaitá', state: 'AM' },
  ipixuna: { name: 'Ipixuna', state: 'AM' },
  iranduba: { name: 'Iranduba', state: 'AM' },
  itacoatiara: { name: 'Itacoatiara', state: 'AM' },
  itamarati: { name: 'Itamarati', state: 'AM' },
  itapiranga: { name: 'Itapiranga', state: 'AM' },
  japura: { name: 'Japurá', state: 'AM' },
  jurua: { name: 'Juruá', state: 'AM' },
  jutai: { name: 'Jutaí', state: 'AM' },
  labrea: { name: 'Lábrea', state: 'AM' },
  manacapuru: { name: 'Manacapuru', state: 'AM' },
  manaquiri: { name: 'Manaquiri', state: 'AM' },
  manaus: { name: 'Manaus', state: 'AM' },
  manicore: { name: 'Manicoré', state: 'AM' },
  maraa: { name: 'Maraã', state: 'AM' },
  maues: { name: 'Maués', state: 'AM' },
  nhamunda: { name: 'Nhamundá', state: 'AM' },
  'nova olinda do norte': { name: 'Nova Olinda do Norte', state: 'AM' },
  'novo aripuana': { name: 'Novo Aripuanã', state: 'AM' },
  'novo airao': { name: 'Novo Airão', state: 'AM' },
  parintins: { name: 'Parintins', state: 'AM' },
  pauini: { name: 'Pauini', state: 'AM' },
  'presidente figueiredo': { name: 'Presidente Figueiredo', state: 'AM' },
  'rio preto da eva': { name: 'Rio Preto da Eva', state: 'AM' },
  'santa isabel do rio negro': { name: 'Santa Isabel do Rio Negro', state: 'AM' },
  'santo antonio do ica': { name: 'Santo Antônio do Içá', state: 'AM' },
  'sao gabriel da cachoeira': { name: 'São Gabriel da Cachoeira', state: 'AM' },
  'sao paulo de olivenca': { name: 'São Paulo de Olivença', state: 'AM' },
  'sao sebastiao do uatuma': { name: 'São Sebastião do Uatumã', state: 'AM' },
  silves: { name: 'Silves', state: 'AM' },
  tabatinga: { name: 'Tabatinga', state: 'AM' },
  tapaua: { name: 'Tapauá', state: 'AM' },
  tefe: { name: 'Tefé', state: 'AM' },
  tonantins: { name: 'Tonantins', state: 'AM' },
  uarini: { name: 'Uarini', state: 'AM' },
  urucara: { name: 'Urucará', state: 'AM' },
  urucurituba: { name: 'Urucurituba', state: 'AM' },
};
