export const cities = {
  'agua clara': { name: 'Água Clara', state: 'MS' },
  alcinopolis: { name: 'Alcinópolis', state: 'MS' },
  amambai: { name: 'Amambai', state: 'MS' },
  anastacio: { name: 'Anastácio', state: 'MS' },
  anaurilandia: { name: 'Anaurilândia', state: 'MS' },
  angelica: { name: 'Angélica', state: 'MS' },
  'antonio joao': { name: 'Antônio João', state: 'MS' },
  'aparecida do taboado': { name: 'Aparecida do Taboado', state: 'MS' },
  aquidauana: { name: 'Aquidauana', state: 'MS' },
  'aral moreira': { name: 'Aral Moreira', state: 'MS' },
  bandeirantes: { name: 'Bandeirantes', state: 'MS' },
  bataguassu: { name: 'Bataguassu', state: 'MS' },
  bataypora: { name: 'Batayporã', state: 'MS' },
  'bela vista': { name: 'Bela Vista', state: 'MS' },
  bodoquena: { name: 'Bodoquena', state: 'MS' },
  bonito_: { name: 'Bonito', state: 'MS' },
  brasilandia: { name: 'Brasilândia', state: 'MS' },
  caarapo: { name: 'Caarapó', state: 'MS' },
  camapua: { name: 'Camapuã', state: 'MS' },
  'campo grande_': { name: 'Campo Grande', state: 'MS' },
  caracol: { name: 'Caracol', state: 'MS' },
  cassilandia: { name: 'Cassilândia', state: 'MS' },
  'chapadao do sul': { name: 'Chapadão do Sul', state: 'MS' },
  corguinho: { name: 'Corguinho', state: 'MS' },
  'coronel sapucaia': { name: 'Coronel Sapucaia', state: 'MS' },
  corumba: { name: 'Corumbá', state: 'MS' },
  'costa rica': { name: 'Costa Rica', state: 'MS' },
  coxim: { name: 'Coxim', state: 'MS' },
  deodapolis: { name: 'Deodápolis', state: 'MS' },
  'dois irmaos do buriti': { name: 'Dois Irmãos do Buriti', state: 'MS' },
  douradina: { name: 'Douradina', state: 'MS' },
  dourados: { name: 'Dourados', state: 'MS' },
  eldorado: { name: 'Eldorado', state: 'MS' },
  'fatima do sul': { name: 'Fátima do Sul', state: 'MS' },
  figueirao: { name: 'Figueirão', state: 'MS' },
  'gloria de dourados': { name: 'Glória de Dourados', state: 'MS' },
  'guia lopes da laguna': { name: 'Guia Lopes da Laguna', state: 'MS' },
  iguatemi: { name: 'Iguatemi', state: 'MS' },
  inocencia: { name: 'Inocência', state: 'MS' },
  itapora: { name: 'Itaporã', state: 'MS' },
  itaquirai: { name: 'Itaquiraí', state: 'MS' },
  ivinhema: { name: 'Ivinhema', state: 'MS' },
  japora: { name: 'Japorã', state: 'MS' },
  jaraguari: { name: 'Jaraguari', state: 'MS' },
  jardim_: { name: 'Jardim', state: 'MS' },
  jatei: { name: 'Jateí', state: 'MS' },
  juti: { name: 'Juti', state: 'MS' },
  ladario: { name: 'Ladário', state: 'MS' },
  'laguna carapa': { name: 'Laguna Carapã', state: 'MS' },
  maracaju: { name: 'Maracaju', state: 'MS' },
  miranda: { name: 'Miranda', state: 'MS' },
  'mundo novo__': { name: 'Mundo Novo', state: 'MS' },
  navirai: { name: 'Naviraí', state: 'MS' },
  nioaque: { name: 'Nioaque', state: 'MS' },
  'nova alvorada do sul': { name: 'Nova Alvorada do Sul', state: 'MS' },
  'nova andradina': { name: 'Nova Andradina', state: 'MS' },
  'novo horizonte do sul': { name: 'Novo Horizonte do Sul', state: 'MS' },
  'paraiso das aguas': { name: 'Paraíso das Águas', state: 'MS' },
  paranaiba: { name: 'Paranaíba', state: 'MS' },
  paranhos: { name: 'Paranhos', state: 'MS' },
  'pedro gomes': { name: 'Pedro Gomes', state: 'MS' },
  'ponta pora': { name: 'Ponta Porã', state: 'MS' },
  'porto murtinho': { name: 'Porto Murtinho', state: 'MS' },
  'ribas do rio pardo': { name: 'Ribas do Rio Pardo', state: 'MS' },
  'rio brilhante': { name: 'Rio Brilhante', state: 'MS' },
  'rio negro': { name: 'Rio Negro', state: 'MS' },
  'rio verde de mato grosso': { name: 'Rio Verde de Mato Grosso', state: 'MS' },
  rochedo: { name: 'Rochedo', state: 'MS' },
  'santa rita do pardo': { name: 'Santa Rita do Pardo', state: 'MS' },
  'sao gabriel do oeste': { name: 'São Gabriel do Oeste', state: 'MS' },
  selviria: { name: 'Selvíria', state: 'MS' },
  'sete quedas': { name: 'Sete Quedas', state: 'MS' },
  sidrolandia: { name: 'Sidrolândia', state: 'MS' },
  sonora: { name: 'Sonora', state: 'MS' },
  tacuru: { name: 'Tacuru', state: 'MS' },
  taquarussu: { name: 'Taquarussu', state: 'MS' },
  terenos: { name: 'Terenos', state: 'MS' },
  'tres lagoas': { name: 'Três Lagoas', state: 'MS' },
  vicentina: { name: 'Vicentina', state: 'MS' },
};
