export const cities = {
  abaetetuba: { name: 'Abaetetuba', state: 'PA' },
  'abel figueiredo': { name: 'Abel Figueiredo', state: 'PA' },
  acara: { name: 'Acará', state: 'PA' },
  afua: { name: 'Afuá', state: 'PA' },
  'agua azul do norte': { name: 'Água Azul do Norte', state: 'PA' },
  alenquer: { name: 'Alenquer', state: 'PA' },
  almeirim: { name: 'Almeirim', state: 'PA' },
  altamira: { name: 'Altamira', state: 'PA' },
  anajas: { name: 'Anajás', state: 'PA' },
  ananindeua: { name: 'Ananindeua', state: 'PA' },
  anapu: { name: 'Anapu', state: 'PA' },
  'augusto correa': { name: 'Augusto Corrêa', state: 'PA' },
  'aurora do para': { name: 'Aurora do Pará', state: 'PA' },
  aveiro: { name: 'Aveiro', state: 'PA' },
  bagre: { name: 'Bagre', state: 'PA' },
  baiao: { name: 'Baião', state: 'PA' },
  bannach: { name: 'Bannach', state: 'PA' },
  barcarena: { name: 'Barcarena', state: 'PA' },
  belem_: { name: 'Belém', state: 'PA' },
  belterra: { name: 'Belterra', state: 'PA' },
  benevides: { name: 'Benevides', state: 'PA' },
  'bom jesus do tocantins': { name: 'Bom Jesus do Tocantins', state: 'PA' },
  bonito__: { name: 'Bonito', state: 'PA' },
  braganca: { name: 'Bragança', state: 'PA' },
  'brasil novo': { name: 'Brasil Novo', state: 'PA' },
  'brejo grande do araguaia': { name: 'Brejo Grande do Araguaia', state: 'PA' },
  'breu branco': { name: 'Breu Branco', state: 'PA' },
  breves: { name: 'Breves', state: 'PA' },
  bujaru: { name: 'Bujaru', state: 'PA' },
  'cachoeira do arari': { name: 'Cachoeira do Arari', state: 'PA' },
  'cachoeira do piria': { name: 'Cachoeira do Piriá', state: 'PA' },
  cameta: { name: 'Cametá', state: 'PA' },
  'canaa dos carajas': { name: 'Canaã dos Carajás', state: 'PA' },
  capanema: { name: 'Capanema', state: 'PA' },
  'capitao poco': { name: 'Capitão Poço', state: 'PA' },
  castanhal: { name: 'Castanhal', state: 'PA' },
  chaves: { name: 'Chaves', state: 'PA' },
  colares: { name: 'Colares', state: 'PA' },
  'conceicao do araguaia': { name: 'Conceição do Araguaia', state: 'PA' },
  'concordia do para': { name: 'Concórdia do Pará', state: 'PA' },
  'cumaru do norte': { name: 'Cumaru do Norte', state: 'PA' },
  curionopolis: { name: 'Curionópolis', state: 'PA' },
  curralinho: { name: 'Curralinho', state: 'PA' },
  curua: { name: 'Curuá', state: 'PA' },
  curuca: { name: 'Curuçá', state: 'PA' },
  'dom eliseu': { name: 'Dom Eliseu', state: 'PA' },
  'eldorado do carajas': { name: 'Eldorado do Carajás', state: 'PA' },
  faro: { name: 'Faro', state: 'PA' },
  'floresta do araguaia': { name: 'Floresta do Araguaia', state: 'PA' },
  'garrafao do norte': { name: 'Garrafão do Norte', state: 'PA' },
  'goianesia do para': { name: 'Goianésia do Pará', state: 'PA' },
  gurupa: { name: 'Gurupá', state: 'PA' },
  'igarape-acu': { name: 'Igarapé-Açu', state: 'PA' },
  'igarape-miri': { name: 'Igarapé-Miri', state: 'PA' },
  inhangapi: { name: 'Inhangapi', state: 'PA' },
  'ipixuna do para': { name: 'Ipixuna do Pará', state: 'PA' },
  irituia: { name: 'Irituia', state: 'PA' },
  itaituba: { name: 'Itaituba', state: 'PA' },
  itupiranga: { name: 'Itupiranga', state: 'PA' },
  jacareacanga: { name: 'Jacareacanga', state: 'PA' },
  jacunda: { name: 'Jacundá', state: 'PA' },
  juruti: { name: 'Juruti', state: 'PA' },
  'limoeiro do ajuru': { name: 'Limoeiro do Ajuru', state: 'PA' },
  'mae do rio': { name: 'Mãe do Rio', state: 'PA' },
  'magalhaes barata': { name: 'Magalhães Barata', state: 'PA' },
  maraba: { name: 'Marabá', state: 'PA' },
  maracana: { name: 'Maracanã', state: 'PA' },
  marapanim: { name: 'Marapanim', state: 'PA' },
  marituba: { name: 'Marituba', state: 'PA' },
  medicilandia: { name: 'Medicilândia', state: 'PA' },
  melgaco: { name: 'Melgaço', state: 'PA' },
  mocajuba: { name: 'Mocajuba', state: 'PA' },
  moju: { name: 'Moju', state: 'PA' },
  'mojui dos campos': { name: 'Mojuí dos Campos', state: 'PA' },
  'monte alegre': { name: 'Monte Alegre', state: 'PA' },
  muana: { name: 'Muaná', state: 'PA' },
  'nova esperanca do piria': { name: 'Nova Esperança do Piriá', state: 'PA' },
  'nova ipixuna': { name: 'Nova Ipixuna', state: 'PA' },
  'nova timboteua': { name: 'Nova Timboteua', state: 'PA' },
  'novo progresso': { name: 'Novo Progresso', state: 'PA' },
  'novo repartimento': { name: 'Novo Repartimento', state: 'PA' },
  obidos: { name: 'Óbidos', state: 'PA' },
  'oeiras do para': { name: 'Oeiras do Pará', state: 'PA' },
  oriximina: { name: 'Oriximiná', state: 'PA' },
  ourem: { name: 'Ourém', state: 'PA' },
  'ourilandia do norte': { name: 'Ourilândia do Norte', state: 'PA' },
  pacaja: { name: 'Pacajá', state: 'PA' },
  'palestina do para': { name: 'Palestina do Pará', state: 'PA' },
  paragominas: { name: 'Paragominas', state: 'PA' },
  parauapebas: { name: 'Parauapebas', state: 'PA' },
  "pau-d'arco": { name: "Pau-d'Arco", state: 'PA' },
  'peixe-boi': { name: 'Peixe-Boi', state: 'PA' },
  picarra: { name: 'Piçarra', state: 'PA' },
  placas: { name: 'Placas', state: 'PA' },
  'ponta de pedras': { name: 'Ponta de Pedras', state: 'PA' },
  portel: { name: 'Portel', state: 'PA' },
  'porto de moz': { name: 'Porto de Moz', state: 'PA' },
  prainha: { name: 'Prainha', state: 'PA' },
  primavera: { name: 'Primavera', state: 'PA' },
  quatipuru: { name: 'Quatipuru', state: 'PA' },
  redencao_: { name: 'Redenção', state: 'PA' },
  'rio maria': { name: 'Rio Maria', state: 'PA' },
  'rondon do para': { name: 'Rondon do Pará', state: 'PA' },
  ruropolis: { name: 'Rurópolis', state: 'PA' },
  salinopolis: { name: 'Salinópolis', state: 'PA' },
  salvaterra: { name: 'Salvaterra', state: 'PA' },
  'santa barbara do para': { name: 'Santa Bárbara do Pará', state: 'PA' },
  'santa cruz do arari': { name: 'Santa Cruz do Arari', state: 'PA' },
  'santa izabel do para': { name: 'Santa Izabel do Pará', state: 'PA' },
  'santa luzia do para': { name: 'Santa Luzia do Pará', state: 'PA' },
  'santa maria das barreiras': { name: 'Santa Maria das Barreiras', state: 'PA' },
  'santa maria do para': { name: 'Santa Maria do Pará', state: 'PA' },
  'santana do araguaia': { name: 'Santana do Araguaia', state: 'PA' },
  santarem: { name: 'Santarém', state: 'PA' },
  'santarem novo': { name: 'Santarém Novo', state: 'PA' },
  'santo antonio do taua': { name: 'Santo Antônio do Tauá', state: 'PA' },
  'sao caetano de odivelas': { name: 'São Caetano de Odivelas', state: 'PA' },
  'sao domingos do araguaia': { name: 'São Domingos do Araguaia', state: 'PA' },
  'sao domingos do capim': { name: 'São Domingos do Capim', state: 'PA' },
  'sao felix do xingu': { name: 'São Félix do Xingu', state: 'PA' },
  'sao francisco do para': { name: 'São Francisco do Pará', state: 'PA' },
  'sao geraldo do araguaia': { name: 'São Geraldo do Araguaia', state: 'PA' },
  'sao joao da ponta': { name: 'São João da Ponta', state: 'PA' },
  'sao joao de pirabas': { name: 'São João de Pirabas', state: 'PA' },
  'sao joao do araguaia': { name: 'São João do Araguaia', state: 'PA' },
  'sao miguel do guama': { name: 'São Miguel do Guamá', state: 'PA' },
  'sao sebastiao da boa vista': { name: 'São Sebastião da Boa Vista', state: 'PA' },
  sapucaia: { name: 'Sapucaia', state: 'PA' },
  'senador jose porfirio': { name: 'Senador José Porfírio', state: 'PA' },
  soure: { name: 'Soure', state: 'PA' },
  tailandia: { name: 'Tailândia', state: 'PA' },
  'terra alta': { name: 'Terra Alta', state: 'PA' },
  'terra santa': { name: 'Terra Santa', state: 'PA' },
  'tome-acu': { name: 'Tomé-Açu', state: 'PA' },
  tracuateua: { name: 'Tracuateua', state: 'PA' },
  trairao: { name: 'Trairão', state: 'PA' },
  tucuma: { name: 'Tucumã', state: 'PA' },
  tucurui: { name: 'Tucuruí', state: 'PA' },
  ulianopolis: { name: 'Ulianópolis', state: 'PA' },
  uruara: { name: 'Uruará', state: 'PA' },
  vigia: { name: 'Vigia', state: 'PA' },
  'vitoria do xingu': { name: 'Vitória do Xingu', state: 'PA' },
  viseu: { name: 'Viseu', state: 'PA' },
  xinguara: { name: 'Xinguara', state: 'PA' },
};
