export const cities = {
  acaua: { name: 'Acauã', state: 'PI' },
  agricolandia: { name: 'Agricolândia', state: 'PI' },
  'agua branca__': { name: 'Água Branca', state: 'PI' },
  'alagoinha do piaui': { name: 'Alagoinha do Piauí', state: 'PI' },
  'alegrete do piaui': { name: 'Alegrete do Piauí', state: 'PI' },
  'alto longa': { name: 'Alto Longá', state: 'PI' },
  altos: { name: 'Altos', state: 'PI' },
  'alvorada do gurgueia': { name: 'Alvorada do Gurgueia', state: 'PI' },
  amarante: { name: 'Amarante', state: 'PI' },
  'angical do piaui': { name: 'Angical do Piauí', state: 'PI' },
  'anisio de abreu': { name: 'Anísio de Abreu', state: 'PI' },
  'antonio almeida': { name: 'Antônio Almeida', state: 'PI' },
  aroazes: { name: 'Aroazes', state: 'PI' },
  'aroeiras do itaim': { name: 'Aroeiras do Itaim', state: 'PI' },
  arraial: { name: 'Arraial', state: 'PI' },
  'assuncao do piaui': { name: 'Assunção do Piauí', state: 'PI' },
  'avelino lopes': { name: 'Avelino Lopes', state: 'PI' },
  'baixa grande do ribeiro': { name: 'Baixa Grande do Ribeiro', state: 'PI' },
  "barra d'alcantara": { name: "Barra d'Alcântara", state: 'PI' },
  barras: { name: 'Barras', state: 'PI' },
  'barreiras do piaui': { name: 'Barreiras do Piauí', state: 'PI' },
  'barro duro': { name: 'Barro Duro', state: 'PI' },
  batalha_: { name: 'Batalha', state: 'PI' },
  'bela vista do piaui': { name: 'Bela Vista do Piauí', state: 'PI' },
  'belem do piaui': { name: 'Belém do Piauí', state: 'PI' },
  beneditinos: { name: 'Beneditinos', state: 'PI' },
  bertolinia: { name: 'Bertolínia', state: 'PI' },
  'betania do piaui': { name: 'Betânia do Piauí', state: 'PI' },
  'boa hora': { name: 'Boa Hora', state: 'PI' },
  bocaina: { name: 'Bocaina', state: 'PI' },
  'bom jesus_': { name: 'Bom Jesus', state: 'PI' },
  'bom principio do piaui': { name: 'Bom Princípio do Piauí', state: 'PI' },
  'bonfim do piaui': { name: 'Bonfim do Piauí', state: 'PI' },
  'boqueirao do piaui': { name: 'Boqueirão do Piauí', state: 'PI' },
  brasileira: { name: 'Brasileira', state: 'PI' },
  'brejo do piaui': { name: 'Brejo do Piauí', state: 'PI' },
  'buriti dos lopes': { name: 'Buriti dos Lopes', state: 'PI' },
  'buriti dos montes': { name: 'Buriti dos Montes', state: 'PI' },
  'cabeceiras do piaui': { name: 'Cabeceiras do Piauí', state: 'PI' },
  'cajazeiras do piaui': { name: 'Cajazeiras do Piauí', state: 'PI' },
  'cajueiro da praia': { name: 'Cajueiro da Praia', state: 'PI' },
  'caldeirao grande do piaui': { name: 'Caldeirão Grande do Piauí', state: 'PI' },
  'campinas do piaui': { name: 'Campinas do Piauí', state: 'PI' },
  'campo alegre do fidalgo': { name: 'Campo Alegre do Fidalgo', state: 'PI' },
  'campo grande do piaui': { name: 'Campo Grande do Piauí', state: 'PI' },
  'campo largo do piaui': { name: 'Campo Largo do Piauí', state: 'PI' },
  'campo maior': { name: 'Campo Maior', state: 'PI' },
  canavieira: { name: 'Canavieira', state: 'PI' },
  'canto do buriti': { name: 'Canto do Buriti', state: 'PI' },
  'capitao de campos': { name: 'Capitão de Campos', state: 'PI' },
  'capitao gervasio oliveira': { name: 'Capitão Gervásio Oliveira', state: 'PI' },
  caracol_: { name: 'Caracol', state: 'PI' },
  'caraubas do piaui': { name: 'Caraúbas do Piauí', state: 'PI' },
  'caridade do piaui': { name: 'Caridade do Piauí', state: 'PI' },
  'castelo do piaui': { name: 'Castelo do Piauí', state: 'PI' },
  caxingo: { name: 'Caxingó', state: 'PI' },
  cocal: { name: 'Cocal', state: 'PI' },
  'cocal de telha': { name: 'Cocal de Telha', state: 'PI' },
  'cocal dos alves': { name: 'Cocal dos Alves', state: 'PI' },
  coivaras: { name: 'Coivaras', state: 'PI' },
  'colonia do gurgueia': { name: 'Colônia do Gurgueia', state: 'PI' },
  'colonia do piaui': { name: 'Colônia do Piauí', state: 'PI' },
  'conceicao do caninde': { name: 'Conceição do Canindé', state: 'PI' },
  'coronel jose dias': { name: 'Coronel José Dias', state: 'PI' },
  corrente: { name: 'Corrente', state: 'PI' },
  'cristalandia do piaui': { name: 'Cristalândia do Piauí', state: 'PI' },
  'cristino castro': { name: 'Cristino Castro', state: 'PI' },
  curimata: { name: 'Curimatá', state: 'PI' },
  currais: { name: 'Currais', state: 'PI' },
  curralinhos: { name: 'Curralinhos', state: 'PI' },
  'curral novo do piaui': { name: 'Curral Novo do Piauí', state: 'PI' },
  'demerval lobao': { name: 'Demerval Lobão', state: 'PI' },
  'dirceu arcoverde': { name: 'Dirceu Arcoverde', state: 'PI' },
  'dom expedito lopes': { name: 'Dom Expedito Lopes', state: 'PI' },
  'domingos mourao': { name: 'Domingos Mourão', state: 'PI' },
  'dom inocencio': { name: 'Dom Inocêncio', state: 'PI' },
  'elesbao veloso': { name: 'Elesbão Veloso', state: 'PI' },
  'eliseu martins': { name: 'Eliseu Martins', state: 'PI' },
  esperantina: { name: 'Esperantina', state: 'PI' },
  'fartura do piaui': { name: 'Fartura do Piauí', state: 'PI' },
  'flores do piaui': { name: 'Flores do Piauí', state: 'PI' },
  'floresta do piaui': { name: 'Floresta do Piauí', state: 'PI' },
  floriano: { name: 'Floriano', state: 'PI' },
  francinopolis: { name: 'Francinópolis', state: 'PI' },
  'francisco ayres': { name: 'Francisco Ayres', state: 'PI' },
  'francisco macedo': { name: 'Francisco Macedo', state: 'PI' },
  'francisco santos': { name: 'Francisco Santos', state: 'PI' },
  fronteiras: { name: 'Fronteiras', state: 'PI' },
  geminiano: { name: 'Geminiano', state: 'PI' },
  gilbues: { name: 'Gilbués', state: 'PI' },
  guadalupe: { name: 'Guadalupe', state: 'PI' },
  guaribas: { name: 'Guaribas', state: 'PI' },
  'hugo napoleao': { name: 'Hugo Napoleão', state: 'PI' },
  'ilha grande': { name: 'Ilha Grande', state: 'PI' },
  inhuma: { name: 'Inhuma', state: 'PI' },
  'ipiranga do piaui': { name: 'Ipiranga do Piauí', state: 'PI' },
  'isaias coelho': { name: 'Isaías Coelho', state: 'PI' },
  itainopolis: { name: 'Itainópolis', state: 'PI' },
  itaueira: { name: 'Itaueira', state: 'PI' },
  'jacobina do piaui': { name: 'Jacobina do Piauí', state: 'PI' },
  jaicos: { name: 'Jaicós', state: 'PI' },
  'jardim do mulato': { name: 'Jardim do Mulato', state: 'PI' },
  'jatoba do piaui': { name: 'Jatobá do Piauí', state: 'PI' },
  jerumenha: { name: 'Jerumenha', state: 'PI' },
  'joao costa': { name: 'João Costa', state: 'PI' },
  'joaquim pires': { name: 'Joaquim Pires', state: 'PI' },
  'joca marques': { name: 'Joca Marques', state: 'PI' },
  'jose de freitas': { name: 'José de Freitas', state: 'PI' },
  'juazeiro do piaui': { name: 'Juazeiro do Piauí', state: 'PI' },
  'julio borges': { name: 'Júlio Borges', state: 'PI' },
  jurema_: { name: 'Jurema', state: 'PI' },
  'lagoa alegre': { name: 'Lagoa Alegre', state: 'PI' },
  'lagoa de sao francisco': { name: 'Lagoa de São Francisco', state: 'PI' },
  'lagoa do barro do piaui': { name: 'Lagoa do Barro do Piauí', state: 'PI' },
  'lagoa do piaui': { name: 'Lagoa do Piauí', state: 'PI' },
  'lagoa do sitio': { name: 'Lagoa do Sítio', state: 'PI' },
  'lagoinha do piaui': { name: 'Lagoinha do Piauí', state: 'PI' },
  'landri sales': { name: 'Landri Sales', state: 'PI' },
  'luis correia': { name: 'Luís Correia', state: 'PI' },
  luzilandia: { name: 'Luzilândia', state: 'PI' },
  madeiro: { name: 'Madeiro', state: 'PI' },
  'manoel emidio': { name: 'Manoel Emídio', state: 'PI' },
  marcolandia: { name: 'Marcolândia', state: 'PI' },
  'marcos parente': { name: 'Marcos Parente', state: 'PI' },
  'massape do piaui': { name: 'Massapê do Piauí', state: 'PI' },
  'matias olimpio': { name: 'Matias Olímpio', state: 'PI' },
  'miguel alves': { name: 'Miguel Alves', state: 'PI' },
  'miguel leao': { name: 'Miguel Leão', state: 'PI' },
  'milton brandao': { name: 'Milton Brandão', state: 'PI' },
  'monsenhor gil': { name: 'Monsenhor Gil', state: 'PI' },
  'monsenhor hipolito': { name: 'Monsenhor Hipólito', state: 'PI' },
  'monte alegre do piaui': { name: 'Monte Alegre do Piauí', state: 'PI' },
  'morro cabeca no tempo': { name: 'Morro Cabeça no Tempo', state: 'PI' },
  'morro do chapeu do piaui': { name: 'Morro do Chapéu do Piauí', state: 'PI' },
  'murici dos portelas': { name: 'Murici dos Portelas', state: 'PI' },
  'nazare do piaui': { name: 'Nazaré do Piauí', state: 'PI' },
  nazaria: { name: 'Nazária', state: 'PI' },
  'nossa senhora de nazare': { name: 'Nossa Senhora de Nazaré', state: 'PI' },
  'nossa senhora dos remedios': { name: 'Nossa Senhora dos Remédios', state: 'PI' },
  'nova santa rita': { name: 'Nova Santa Rita', state: 'PI' },
  'novo oriente do piaui': { name: 'Novo Oriente do Piauí', state: 'PI' },
  'novo santo antonio_': { name: 'Novo Santo Antônio', state: 'PI' },
  oeiras: { name: 'Oeiras', state: 'PI' },
  "olho d'agua do piaui": { name: "Olho d'Água do Piauí", state: 'PI' },
  'padre marcos': { name: 'Padre Marcos', state: 'PI' },
  'paes landim': { name: 'Paes Landim', state: 'PI' },
  'pajeu do piaui': { name: 'Pajeú do Piauí', state: 'PI' },
  'palmeira do piaui': { name: 'Palmeira do Piauí', state: 'PI' },
  palmeirais: { name: 'Palmeirais', state: 'PI' },
  paqueta: { name: 'Paquetá', state: 'PI' },
  parnagua: { name: 'Parnaguá', state: 'PI' },
  parnaiba: { name: 'Parnaíba', state: 'PI' },
  'passagem franca do piaui': { name: 'Passagem Franca do Piauí', state: 'PI' },
  'patos do piaui': { name: 'Patos do Piauí', state: 'PI' },
  "pau d'arco do piaui": { name: "Pau d'Arco do Piauí", state: 'PI' },
  paulistana: { name: 'Paulistana', state: 'PI' },
  pavussu: { name: 'Pavussu', state: 'PI' },
  'pedro ii': { name: 'Pedro II', state: 'PI' },
  'pedro laurentino': { name: 'Pedro Laurentino', state: 'PI' },
  picos: { name: 'Picos', state: 'PI' },
  pimenteiras: { name: 'Pimenteiras', state: 'PI' },
  'pio ix': { name: 'Pio IX', state: 'PI' },
  piracuruca: { name: 'Piracuruca', state: 'PI' },
  piripiri: { name: 'Piripiri', state: 'PI' },
  porto: { name: 'Porto', state: 'PI' },
  'porto alegre do piaui': { name: 'Porto Alegre do Piauí', state: 'PI' },
  'prata do piaui': { name: 'Prata do Piauí', state: 'PI' },
  'queimada nova': { name: 'Queimada Nova', state: 'PI' },
  'redencao do gurgueia': { name: 'Redenção do Gurgueia', state: 'PI' },
  regeneracao: { name: 'Regeneração', state: 'PI' },
  'riacho frio': { name: 'Riacho Frio', state: 'PI' },
  'ribeira do piaui': { name: 'Ribeira do Piauí', state: 'PI' },
  'ribeiro goncalves': { name: 'Ribeiro Gonçalves', state: 'PI' },
  'rio grande do piaui': { name: 'Rio Grande do Piauí', state: 'PI' },
  'santa cruz do piaui': { name: 'Santa Cruz do Piauí', state: 'PI' },
  'santa cruz dos milagres': { name: 'Santa Cruz dos Milagres', state: 'PI' },
  'santa filomena_': { name: 'Santa Filomena', state: 'PI' },
  'santa luz': { name: 'Santa Luz', state: 'PI' },
  'santana do piaui': { name: 'Santana do Piauí', state: 'PI' },
  'santa rosa do piaui': { name: 'Santa Rosa do Piauí', state: 'PI' },
  'santo antonio de lisboa': { name: 'Santo Antônio de Lisboa', state: 'PI' },
  'santo antonio dos milagres': { name: 'Santo Antônio dos Milagres', state: 'PI' },
  'santo inacio do piaui': { name: 'Santo Inácio do Piauí', state: 'PI' },
  'sao braz do piaui': { name: 'São Braz do Piauí', state: 'PI' },
  'sao felix do piaui': { name: 'São Félix do Piauí', state: 'PI' },
  'sao francisco de assis do piaui': { name: 'São Francisco de Assis do Piauí', state: 'PI' },
  'sao francisco do piaui': { name: 'São Francisco do Piauí', state: 'PI' },
  'sao goncalo do gurgueia': { name: 'São Gonçalo do Gurgueia', state: 'PI' },
  'sao goncalo do piaui': { name: 'São Gonçalo do Piauí', state: 'PI' },
  'sao joao da canabrava': { name: 'São João da Canabrava', state: 'PI' },
  'sao joao da fronteira': { name: 'São João da Fronteira', state: 'PI' },
  'sao joao da serra': { name: 'São João da Serra', state: 'PI' },
  'sao joao da varjota': { name: 'São João da Varjota', state: 'PI' },
  'sao joao do arraial': { name: 'São João do Arraial', state: 'PI' },
  'sao joao do piaui': { name: 'São João do Piauí', state: 'PI' },
  'sao jose do divino_': { name: 'São José do Divino', state: 'PI' },
  'sao jose do peixe': { name: 'São José do Peixe', state: 'PI' },
  'sao jose do piaui': { name: 'São José do Piauí', state: 'PI' },
  'sao juliao': { name: 'São Julião', state: 'PI' },
  'sao lourenco do piaui': { name: 'São Lourenço do Piauí', state: 'PI' },
  'sao luis do piaui': { name: 'São Luís do Piauí', state: 'PI' },
  'sao miguel da baixa grande': { name: 'São Miguel da Baixa Grande', state: 'PI' },
  'sao miguel do fidalgo': { name: 'São Miguel do Fidalgo', state: 'PI' },
  'sao miguel do tapuio': { name: 'São Miguel do Tapuio', state: 'PI' },
  'sao pedro do piaui': { name: 'São Pedro do Piauí', state: 'PI' },
  'sao raimundo nonato': { name: 'São Raimundo Nonato', state: 'PI' },
  'sebastiao barros': { name: 'Sebastião Barros', state: 'PI' },
  'sebastiao leal': { name: 'Sebastião Leal', state: 'PI' },
  'sigefredo pacheco': { name: 'Sigefredo Pacheco', state: 'PI' },
  simoes: { name: 'Simões', state: 'PI' },
  'simplicio mendes': { name: 'Simplício Mendes', state: 'PI' },
  'socorro do piaui': { name: 'Socorro do Piauí', state: 'PI' },
  sussuapara: { name: 'Sussuapara', state: 'PI' },
  'tamboril do piaui': { name: 'Tamboril do Piauí', state: 'PI' },
  'tanque do piaui': { name: 'Tanque do Piauí', state: 'PI' },
  teresina: { name: 'Teresina', state: 'PI' },
  uniao: { name: 'União', state: 'PI' },
  urucui: { name: 'Uruçuí', state: 'PI' },
  'valenca do piaui': { name: 'Valença do Piauí', state: 'PI' },
  'varzea branca': { name: 'Várzea Branca', state: 'PI' },
  'varzea grande_': { name: 'Várzea Grande', state: 'PI' },
  'vera mendes': { name: 'Vera Mendes', state: 'PI' },
  'vila nova do piaui': { name: 'Vila Nova do Piauí', state: 'PI' },
  'wall ferraz': { name: 'Wall Ferraz', state: 'PI' },
};
