export const cities = {
  acari: { name: 'Acari', state: 'RN' },
  'afonso bezerra': { name: 'Afonso Bezerra', state: 'RN' },
  'agua nova': { name: 'Água Nova', state: 'RN' },
  alexandria: { name: 'Alexandria', state: 'RN' },
  'almino afonso': { name: 'Almino Afonso', state: 'RN' },
  'alto do rodrigues': { name: 'Alto do Rodrigues', state: 'RN' },
  angicos: { name: 'Angicos', state: 'RN' },
  'antonio martins': { name: 'Antônio Martins', state: 'RN' },
  apodi: { name: 'Apodi', state: 'RN' },
  'areia branca': { name: 'Areia Branca', state: 'RN' },
  'arez (rio grande do norte)': { name: 'Arez (Rio Grande do Norte)', state: 'RN' },
  assu: { name: 'Assu', state: 'RN' },
  'baia formosa': { name: 'Baía Formosa', state: 'RN' },
  barauna_: { name: 'Baraúna', state: 'RN' },
  barcelona: { name: 'Barcelona', state: 'RN' },
  'bento fernandes': { name: 'Bento Fernandes', state: 'RN' },
  'boa saude': { name: 'Boa Saúde', state: 'RN' },
  bodo: { name: 'Bodó', state: 'RN' },
  'bom jesus__': { name: 'Bom Jesus', state: 'RN' },
  brejinho_: { name: 'Brejinho', state: 'RN' },
  'caicara do norte': { name: 'Caiçara do Norte', state: 'RN' },
  'caicara do rio do vento': { name: 'Caiçara do Rio do Vento', state: 'RN' },
  caico: { name: 'Caicó', state: 'RN' },
  'campo grande__': { name: 'Campo Grande', state: 'RN' },
  'campo redondo': { name: 'Campo Redondo', state: 'RN' },
  canguaretama: { name: 'Canguaretama', state: 'RN' },
  caraubas_: { name: 'Caraúbas', state: 'RN' },
  'carnauba dos dantas': { name: 'Carnaúba dos Dantas', state: 'RN' },
  carnaubais: { name: 'Carnaubais', state: 'RN' },
  'ceara-mirim': { name: 'Ceará-Mirim', state: 'RN' },
  'cerro cora': { name: 'Cerro Corá', state: 'RN' },
  'coronel ezequiel': { name: 'Coronel Ezequiel', state: 'RN' },
  'coronel joao pessoa': { name: 'Coronel João Pessoa', state: 'RN' },
  cruzeta: { name: 'Cruzeta', state: 'RN' },
  'currais novos': { name: 'Currais Novos', state: 'RN' },
  'doutor severiano': { name: 'Doutor Severiano', state: 'RN' },
  encanto: { name: 'Encanto', state: 'RN' },
  equador: { name: 'Equador', state: 'RN' },
  'espirito santo': { name: 'Espírito Santo', state: 'RN' },
  extremoz: { name: 'Extremoz', state: 'RN' },
  'felipe guerra': { name: 'Felipe Guerra', state: 'RN' },
  'fernando pedroza': { name: 'Fernando Pedroza', state: 'RN' },
  florania: { name: 'Florânia', state: 'RN' },
  'francisco dantas': { name: 'Francisco Dantas', state: 'RN' },
  'frutuoso gomes': { name: 'Frutuoso Gomes', state: 'RN' },
  galinhos: { name: 'Galinhos', state: 'RN' },
  goianinha: { name: 'Goianinha', state: 'RN' },
  'governador dix-sept rosado': { name: 'Governador Dix-Sept Rosado', state: 'RN' },
  grossos: { name: 'Grossos', state: 'RN' },
  guamare: { name: 'Guamaré', state: 'RN' },
  'ielmo marinho': { name: 'Ielmo Marinho', state: 'RN' },
  ipanguacu: { name: 'Ipanguaçu', state: 'RN' },
  ipueira: { name: 'Ipueira', state: 'RN' },
  itaja_: { name: 'Itajá', state: 'RN' },
  itau: { name: 'Itaú', state: 'RN' },
  jacana: { name: 'Jaçanã', state: 'RN' },
  jandaira_: { name: 'Jandaíra', state: 'RN' },
  janduis: { name: 'Janduís', state: 'RN' },
  japi: { name: 'Japi', state: 'RN' },
  'jardim de angicos': { name: 'Jardim de Angicos', state: 'RN' },
  'jardim de piranhas': { name: 'Jardim de Piranhas', state: 'RN' },
  'jardim do serido': { name: 'Jardim do Seridó', state: 'RN' },
  'joao camara': { name: 'João Câmara', state: 'RN' },
  'joao dias': { name: 'João Dias', state: 'RN' },
  'jose da penha': { name: 'José da Penha', state: 'RN' },
  jucurutu: { name: 'Jucurutu', state: 'RN' },
  jundia_: { name: 'Jundiá', state: 'RN' },
  "lagoa d'anta": { name: "Lagoa d'Anta", state: 'RN' },
  'lagoa de pedras': { name: 'Lagoa de Pedras', state: 'RN' },
  'lagoa de velhos': { name: 'Lagoa de Velhos', state: 'RN' },
  'lagoa nova': { name: 'Lagoa Nova', state: 'RN' },
  'lagoa salgada': { name: 'Lagoa Salgada', state: 'RN' },
  lajes: { name: 'Lajes', state: 'RN' },
  'lajes pintadas': { name: 'Lajes Pintadas', state: 'RN' },
  lucrecia: { name: 'Lucrécia', state: 'RN' },
  'luis gomes': { name: 'Luís Gomes', state: 'RN' },
  macaiba: { name: 'Macaíba', state: 'RN' },
  macau: { name: 'Macau', state: 'RN' },
  'major sales': { name: 'Major Sales', state: 'RN' },
  'marcelino vieira': { name: 'Marcelino Vieira', state: 'RN' },
  martins: { name: 'Martins', state: 'RN' },
  maxaranguape: { name: 'Maxaranguape', state: 'RN' },
  'messias targino': { name: 'Messias Targino', state: 'RN' },
  montanhas: { name: 'Montanhas', state: 'RN' },
  'monte alegre_': { name: 'Monte Alegre', state: 'RN' },
  'monte das gameleiras': { name: 'Monte das Gameleiras', state: 'RN' },
  mossoro: { name: 'Mossoró', state: 'RN' },
  natal: { name: 'Natal', state: 'RN' },
  'nisia floresta': { name: 'Nísia Floresta', state: 'RN' },
  'nova cruz': { name: 'Nova Cruz', state: 'RN' },
  "olho d'agua do borges": { name: "Olho d'Água do Borges", state: 'RN' },
  'ouro branco__': { name: 'Ouro Branco', state: 'RN' },
  parana: { name: 'Paraná', state: 'RN' },
  parau: { name: 'Paraú', state: 'RN' },
  parazinho: { name: 'Parazinho', state: 'RN' },
  parelhas: { name: 'Parelhas', state: 'RN' },
  parnamirim_: { name: 'Parnamirim', state: 'RN' },
  'passa-e-fica': { name: 'Passa-e-Fica', state: 'RN' },
  passagem_: { name: 'Passagem', state: 'RN' },
  patu: { name: 'Patu', state: 'RN' },
  'pau dos ferros': { name: 'Pau dos Ferros', state: 'RN' },
  'pedra grande': { name: 'Pedra Grande', state: 'RN' },
  'pedra preta_': { name: 'Pedra Preta', state: 'RN' },
  'pedro avelino': { name: 'Pedro Avelino', state: 'RN' },
  'pedro velho': { name: 'Pedro Velho', state: 'RN' },
  pendencias: { name: 'Pendências', state: 'RN' },
  piloes_: { name: 'Pilões', state: 'RN' },
  'poco branco': { name: 'Poço Branco', state: 'RN' },
  portalegre: { name: 'Portalegre', state: 'RN' },
  'porto do mangue': { name: 'Porto do Mangue', state: 'RN' },
  pureza: { name: 'Pureza', state: 'RN' },
  'rafael fernandes': { name: 'Rafael Fernandes', state: 'RN' },
  'rafael godeiro': { name: 'Rafael Godeiro', state: 'RN' },
  'riacho da cruz': { name: 'Riacho da Cruz', state: 'RN' },
  'riacho de santana_': { name: 'Riacho de Santana', state: 'RN' },
  riachuelo: { name: 'Riachuelo', state: 'RN' },
  'rio do fogo': { name: 'Rio do Fogo', state: 'RN' },
  'rodolfo fernandes': { name: 'Rodolfo Fernandes', state: 'RN' },
  'ruy barbosa_': { name: 'Ruy Barbosa', state: 'RN' },
  'santa cruz__': { name: 'Santa Cruz', state: 'RN' },
  'santa maria': { name: 'Santa Maria', state: 'RN' },
  'santana do matos': { name: 'Santana do Matos', state: 'RN' },
  'santana do serido': { name: 'Santana do Seridó', state: 'RN' },
  'santo antonio': { name: 'Santo Antônio', state: 'RN' },
  'sao bento do norte': { name: 'São Bento do Norte', state: 'RN' },
  'sao bento do trairi': { name: 'São Bento do Trairi', state: 'RN' },
  'sao fernando': { name: 'São Fernando', state: 'RN' },
  'sao francisco do oeste': { name: 'São Francisco do Oeste', state: 'RN' },
  'sao goncalo do amarante_': { name: 'São Gonçalo do Amarante', state: 'RN' },
  'sao joao do sabugi': { name: 'São João do Sabugi', state: 'RN' },
  'sao jose de mipibu': { name: 'São José de Mipibu', state: 'RN' },
  'sao jose do campestre': { name: 'São José do Campestre', state: 'RN' },
  'sao jose do serido': { name: 'São José do Seridó', state: 'RN' },
  'sao miguel': { name: 'São Miguel', state: 'RN' },
  'sao miguel do gostoso': { name: 'São Miguel do Gostoso', state: 'RN' },
  'sao paulo do potengi': { name: 'São Paulo do Potengi', state: 'RN' },
  'sao pedro': { name: 'São Pedro', state: 'RN' },
  'sao rafael': { name: 'São Rafael', state: 'RN' },
  'sao tome_': { name: 'São Tomé', state: 'RN' },
  'sao vicente': { name: 'São Vicente', state: 'RN' },
  'senador eloi de souza': { name: 'Senador Elói de Souza', state: 'RN' },
  'senador georgino avelino': { name: 'Senador Georgino Avelino', state: 'RN' },
  'serra caiada': { name: 'Serra Caiada', state: 'RN' },
  'serra de sao bento': { name: 'Serra de São Bento', state: 'RN' },
  'serra do mel': { name: 'Serra do Mel', state: 'RN' },
  'serra negra do norte': { name: 'Serra Negra do Norte', state: 'RN' },
  serrinha_: { name: 'Serrinha', state: 'RN' },
  'serrinha dos pintos': { name: 'Serrinha dos Pintos', state: 'RN' },
  'severiano melo': { name: 'Severiano Melo', state: 'RN' },
  'sitio novo_': { name: 'Sítio Novo', state: 'RN' },
  'taboleiro grande': { name: 'Taboleiro Grande', state: 'RN' },
  taipu: { name: 'Taipu', state: 'RN' },
  tangara: { name: 'Tangará', state: 'RN' },
  'tenente ananias': { name: 'Tenente Ananias', state: 'RN' },
  'tenente laurentino cruz': { name: 'Tenente Laurentino Cruz', state: 'RN' },
  'tibau do sul': { name: 'Tibau do Sul', state: 'RN' },
  tibau: { name: 'Tibau', state: 'RN' },
  'timbauba dos batistas': { name: 'Timbaúba dos Batistas', state: 'RN' },
  touros: { name: 'Touros', state: 'RN' },
  'triunfo potiguar': { name: 'Triunfo Potiguar', state: 'RN' },
  umarizal: { name: 'Umarizal', state: 'RN' },
  upanema: { name: 'Upanema', state: 'RN' },
  varzea_: { name: 'Várzea', state: 'RN' },
  'venha-ver': { name: 'Venha-Ver', state: 'RN' },
  'vera cruz_': { name: 'Vera Cruz', state: 'RN' },
  vicosa__: { name: 'Viçosa', state: 'RN' },
  'vila flor': { name: 'Vila Flor', state: 'RN' },
};
