export const cities = {
  'abdon batista': { name: 'Abdon Batista', state: 'SC' },
  'abelardo luz': { name: 'Abelardo Luz', state: 'SC' },
  agrolandia: { name: 'Agrolândia', state: 'SC' },
  agronomica: { name: 'Agronômica', state: 'SC' },
  'agua doce': { name: 'Água Doce', state: 'SC' },
  'aguas de chapeco': { name: 'Águas de Chapecó', state: 'SC' },
  'aguas frias': { name: 'Águas Frias', state: 'SC' },
  'aguas mornas': { name: 'Águas Mornas', state: 'SC' },
  'alfredo wagner': { name: 'Alfredo Wagner', state: 'SC' },
  'alto bela vista': { name: 'Alto Bela Vista', state: 'SC' },
  anchieta_: { name: 'Anchieta', state: 'SC' },
  angelina: { name: 'Angelina', state: 'SC' },
  'anita garibaldi': { name: 'Anita Garibaldi', state: 'SC' },
  anitapolis: { name: 'Anitápolis', state: 'SC' },
  'antonio carlos_': { name: 'Antônio Carlos', state: 'SC' },
  apiuna: { name: 'Apiúna', state: 'SC' },
  arabuta: { name: 'Arabutã', state: 'SC' },
  araquari: { name: 'Araquari', state: 'SC' },
  ararangua: { name: 'Araranguá', state: 'SC' },
  armazem: { name: 'Armazém', state: 'SC' },
  'arroio trinta': { name: 'Arroio Trinta', state: 'SC' },
  arvoredo: { name: 'Arvoredo', state: 'SC' },
  ascurra: { name: 'Ascurra', state: 'SC' },
  atalanta: { name: 'Atalanta', state: 'SC' },
  aurora_: { name: 'Aurora', state: 'SC' },
  'balneario arroio do silva': { name: 'Balneário Arroio do Silva', state: 'SC' },
  'balneario barra do sul': { name: 'Balneário Barra do Sul', state: 'SC' },
  'balneario camboriu': { name: 'Balneário Camboriú', state: 'SC' },
  'balneario gaivota': { name: 'Balneário Gaivota', state: 'SC' },
  'balneario picarras': { name: 'Balneário Piçarras', state: 'SC' },
  'balneario rincao': { name: 'Balneário Rincão', state: 'SC' },
  bandeirante: { name: 'Bandeirante', state: 'SC' },
  'barra bonita': { name: 'Barra Bonita', state: 'SC' },
  'barra velha': { name: 'Barra Velha', state: 'SC' },
  'bela vista do toldo': { name: 'Bela Vista do Toldo', state: 'SC' },
  belmonte_: { name: 'Belmonte', state: 'SC' },
  'benedito novo': { name: 'Benedito Novo', state: 'SC' },
  biguacu: { name: 'Biguaçu', state: 'SC' },
  blumenau: { name: 'Blumenau', state: 'SC' },
  'bocaina do sul': { name: 'Bocaina do Sul', state: 'SC' },
  bombinhas: { name: 'Bombinhas', state: 'SC' },
  'bom jardim da serra': { name: 'Bom Jardim da Serra', state: 'SC' },
  'bom jesus____': { name: 'Bom Jesus', state: 'SC' },
  'bom jesus do oeste': { name: 'Bom Jesus do Oeste', state: 'SC' },
  'bom retiro': { name: 'Bom Retiro', state: 'SC' },
  botuvera: { name: 'Botuverá', state: 'SC' },
  'braco do norte': { name: 'Braço do Norte', state: 'SC' },
  'braco do trombudo': { name: 'Braço do Trombudo', state: 'SC' },
  brunopolis: { name: 'Brunópolis', state: 'SC' },
  brusque: { name: 'Brusque', state: 'SC' },
  cacador: { name: 'Caçador', state: 'SC' },
  caibi: { name: 'Caibi', state: 'SC' },
  calmon: { name: 'Calmon', state: 'SC' },
  camboriu: { name: 'Camboriú', state: 'SC' },
  'campo alegre_': { name: 'Campo Alegre', state: 'SC' },
  'campo belo do sul': { name: 'Campo Belo do Sul', state: 'SC' },
  'campo ere': { name: 'Campo Erê', state: 'SC' },
  'campos novos': { name: 'Campos Novos', state: 'SC' },
  canelinha: { name: 'Canelinha', state: 'SC' },
  canoinhas: { name: 'Canoinhas', state: 'SC' },
  'capao alto': { name: 'Capão Alto', state: 'SC' },
  capinzal: { name: 'Capinzal', state: 'SC' },
  'capivari de baixo': { name: 'Capivari de Baixo', state: 'SC' },
  catanduvas_: { name: 'Catanduvas', state: 'SC' },
  'caxambu do sul': { name: 'Caxambu do Sul', state: 'SC' },
  'celso ramos': { name: 'Celso Ramos', state: 'SC' },
  'cerro negro': { name: 'Cerro Negro', state: 'SC' },
  'chapadao do lageado': { name: 'Chapadão do Lageado', state: 'SC' },
  chapeco: { name: 'Chapecó', state: 'SC' },
  'cocal do sul': { name: 'Cocal do Sul', state: 'SC' },
  concordia: { name: 'Concórdia', state: 'SC' },
  'cordilheira alta': { name: 'Cordilheira Alta', state: 'SC' },
  'coronel freitas': { name: 'Coronel Freitas', state: 'SC' },
  'coronel martins': { name: 'Coronel Martins', state: 'SC' },
  'correia pinto': { name: 'Correia Pinto', state: 'SC' },
  corupa: { name: 'Corupá', state: 'SC' },
  criciuma: { name: 'Criciúma', state: 'SC' },
  'cunha pora': { name: 'Cunha Porã', state: 'SC' },
  cunhatai: { name: 'Cunhataí', state: 'SC' },
  curitibanos: { name: 'Curitibanos', state: 'SC' },
  descanso: { name: 'Descanso', state: 'SC' },
  'dionisio cerqueira': { name: 'Dionísio Cerqueira', state: 'SC' },
  'dona emma': { name: 'Dona Emma', state: 'SC' },
  'doutor pedrinho': { name: 'Doutor Pedrinho', state: 'SC' },
  'entre rios_': { name: 'Entre Rios', state: 'SC' },
  ermo: { name: 'Ermo', state: 'SC' },
  'erval velho': { name: 'Erval Velho', state: 'SC' },
  'faxinal dos guedes': { name: 'Faxinal dos Guedes', state: 'SC' },
  'flor do sertao': { name: 'Flor do Sertão', state: 'SC' },
  florianopolis: { name: 'Florianópolis', state: 'SC' },
  'formosa do sul': { name: 'Formosa do Sul', state: 'SC' },
  forquilhinha: { name: 'Forquilhinha', state: 'SC' },
  fraiburgo: { name: 'Fraiburgo', state: 'SC' },
  'frei rogerio': { name: 'Frei Rogério', state: 'SC' },
  galvao: { name: 'Galvão', state: 'SC' },
  garopaba: { name: 'Garopaba', state: 'SC' },
  garuva: { name: 'Garuva', state: 'SC' },
  gaspar: { name: 'Gaspar', state: 'SC' },
  'governador celso ramos': { name: 'Governador Celso Ramos', state: 'SC' },
  'grao-para': { name: 'Grão-Pará', state: 'SC' },
  gravatal: { name: 'Gravatal', state: 'SC' },
  guabiruba: { name: 'Guabiruba', state: 'SC' },
  guaraciaba_: { name: 'Guaraciaba', state: 'SC' },
  guaramirim: { name: 'Guaramirim', state: 'SC' },
  'guaruja do sul': { name: 'Guarujá do Sul', state: 'SC' },
  guatambu: { name: 'Guatambu', state: 'SC' },
  "herval d'oeste": { name: "Herval d'Oeste", state: 'SC' },
  ibiam: { name: 'Ibiam', state: 'SC' },
  ibicare: { name: 'Ibicaré', state: 'SC' },
  ibirama: { name: 'Ibirama', state: 'SC' },
  icara: { name: 'Içara', state: 'SC' },
  ilhota: { name: 'Ilhota', state: 'SC' },
  imarui: { name: 'Imaruí', state: 'SC' },
  imbituba: { name: 'Imbituba', state: 'SC' },
  imbuia: { name: 'Imbuia', state: 'SC' },
  indaial: { name: 'Indaial', state: 'SC' },
  iomere: { name: 'Iomerê', state: 'SC' },
  ipira: { name: 'Ipira', state: 'SC' },
  'ipora do oeste': { name: 'Iporã do Oeste', state: 'SC' },
  ipuacu: { name: 'Ipuaçu', state: 'SC' },
  ipumirim: { name: 'Ipumirim', state: 'SC' },
  iraceminha: { name: 'Iraceminha', state: 'SC' },
  irani: { name: 'Irani', state: 'SC' },
  irati_: { name: 'Irati', state: 'SC' },
  irineopolis: { name: 'Irineópolis', state: 'SC' },
  ita: { name: 'Itá', state: 'SC' },
  itaiopolis: { name: 'Itaiópolis', state: 'SC' },
  itajai: { name: 'Itajaí', state: 'SC' },
  itapema: { name: 'Itapema', state: 'SC' },
  itapiranga_: { name: 'Itapiranga', state: 'SC' },
  itapoa: { name: 'Itapoá', state: 'SC' },
  ituporanga: { name: 'Ituporanga', state: 'SC' },
  jabora: { name: 'Jaborá', state: 'SC' },
  'jacinto machado': { name: 'Jacinto Machado', state: 'SC' },
  jaguaruna: { name: 'Jaguaruna', state: 'SC' },
  'jaragua do sul': { name: 'Jaraguá do Sul', state: 'SC' },
  jardinopolis: { name: 'Jardinópolis', state: 'SC' },
  joacaba: { name: 'Joaçaba', state: 'SC' },
  joinville: { name: 'Joinville', state: 'SC' },
  'jose boiteux': { name: 'José Boiteux', state: 'SC' },
  jupia: { name: 'Jupiá', state: 'SC' },
  lacerdopolis: { name: 'Lacerdópolis', state: 'SC' },
  lages: { name: 'Lages', state: 'SC' },
  laguna: { name: 'Laguna', state: 'SC' },
  'lajeado grande': { name: 'Lajeado Grande', state: 'SC' },
  laurentino: { name: 'Laurentino', state: 'SC' },
  'lauro muller': { name: 'Lauro Müller', state: 'SC' },
  'lebon regis': { name: 'Lebon Régis', state: 'SC' },
  'leoberto leal': { name: 'Leoberto Leal', state: 'SC' },
  'lindoia do sul': { name: 'Lindóia do Sul', state: 'SC' },
  lontras: { name: 'Lontras', state: 'SC' },
  'luiz alves': { name: 'Luiz Alves', state: 'SC' },
  luzerna: { name: 'Luzerna', state: 'SC' },
  macieira: { name: 'Macieira', state: 'SC' },
  mafra: { name: 'Mafra', state: 'SC' },
  'major gercino': { name: 'Major Gercino', state: 'SC' },
  'major vieira': { name: 'Major Vieira', state: 'SC' },
  maracaja: { name: 'Maracajá', state: 'SC' },
  maravilha_: { name: 'Maravilha', state: 'SC' },
  marema: { name: 'Marema', state: 'SC' },
  massaranduba_: { name: 'Massaranduba', state: 'SC' },
  'matos costa': { name: 'Matos Costa', state: 'SC' },
  meleiro: { name: 'Meleiro', state: 'SC' },
  'mirim doce': { name: 'Mirim Doce', state: 'SC' },
  modelo: { name: 'Modelo', state: 'SC' },
  mondai: { name: 'Mondaí', state: 'SC' },
  'monte carlo': { name: 'Monte Carlo', state: 'SC' },
  'monte castelo': { name: 'Monte Castelo', state: 'SC' },
  'morro da fumaca': { name: 'Morro da Fumaça', state: 'SC' },
  'morro grande': { name: 'Morro Grande', state: 'SC' },
  navegantes: { name: 'Navegantes', state: 'SC' },
  'nova erechim': { name: 'Nova Erechim', state: 'SC' },
  'nova itaberaba': { name: 'Nova Itaberaba', state: 'SC' },
  'nova trento': { name: 'Nova Trento', state: 'SC' },
  'nova veneza_': { name: 'Nova Veneza', state: 'SC' },
  'novo horizonte_': { name: 'Novo Horizonte', state: 'SC' },
  orleans: { name: 'Orleans', state: 'SC' },
  'otacilio costa': { name: 'Otacílio Costa', state: 'SC' },
  ouro: { name: 'Ouro', state: 'SC' },
  'ouro verde': { name: 'Ouro Verde', state: 'SC' },
  paial: { name: 'Paial', state: 'SC' },
  painel: { name: 'Painel', state: 'SC' },
  palhoca: { name: 'Palhoça', state: 'SC' },
  'palma sola': { name: 'Palma Sola', state: 'SC' },
  palmeira_: { name: 'Palmeira', state: 'SC' },
  palmitos: { name: 'Palmitos', state: 'SC' },
  papanduva: { name: 'Papanduva', state: 'SC' },
  paraiso: { name: 'Paraíso', state: 'SC' },
  'passo de torres': { name: 'Passo de Torres', state: 'SC' },
  'passos maia': { name: 'Passos Maia', state: 'SC' },
  'paulo lopes': { name: 'Paulo Lopes', state: 'SC' },
  'pedras grandes': { name: 'Pedras Grandes', state: 'SC' },
  penha: { name: 'Penha', state: 'SC' },
  peritiba: { name: 'Peritiba', state: 'SC' },
  'pescaria brava': { name: 'Pescaria Brava', state: 'SC' },
  petrolandia_: { name: 'Petrolândia', state: 'SC' },
  pinhalzinho: { name: 'Pinhalzinho', state: 'SC' },
  'pinheiro preto': { name: 'Pinheiro Preto', state: 'SC' },
  piratuba: { name: 'Piratuba', state: 'SC' },
  'planalto alegre': { name: 'Planalto Alegre', state: 'SC' },
  pomerode: { name: 'Pomerode', state: 'SC' },
  'ponte alta': { name: 'Ponte Alta', state: 'SC' },
  'ponte alta do norte': { name: 'Ponte Alta do Norte', state: 'SC' },
  'ponte serrada': { name: 'Ponte Serrada', state: 'SC' },
  'porto belo': { name: 'Porto Belo', state: 'SC' },
  'porto uniao': { name: 'Porto União', state: 'SC' },
  'pouso redondo': { name: 'Pouso Redondo', state: 'SC' },
  'praia grande': { name: 'Praia Grande', state: 'SC' },
  'presidente castello branco': { name: 'Presidente Castello Branco', state: 'SC' },
  'presidente getulio': { name: 'Presidente Getúlio', state: 'SC' },
  'presidente nereu': { name: 'Presidente Nereu', state: 'SC' },
  princesa: { name: 'Princesa', state: 'SC' },
  quilombo: { name: 'Quilombo', state: 'SC' },
  'rancho queimado': { name: 'Rancho Queimado', state: 'SC' },
  'rio das antas': { name: 'Rio das Antas', state: 'SC' },
  'rio do campo': { name: 'Rio do Campo', state: 'SC' },
  'rio do oeste': { name: 'Rio do Oeste', state: 'SC' },
  'rio dos cedros': { name: 'Rio dos Cedros', state: 'SC' },
  'rio do sul': { name: 'Rio do Sul', state: 'SC' },
  'rio fortuna': { name: 'Rio Fortuna', state: 'SC' },
  'rio negrinho': { name: 'Rio Negrinho', state: 'SC' },
  'rio rufino': { name: 'Rio Rufino', state: 'SC' },
  riqueza: { name: 'Riqueza', state: 'SC' },
  rodeio: { name: 'Rodeio', state: 'SC' },
  romelandia: { name: 'Romelândia', state: 'SC' },
  salete: { name: 'Salete', state: 'SC' },
  saltinho: { name: 'Saltinho', state: 'SC' },
  'salto veloso': { name: 'Salto Veloso', state: 'SC' },
  sangao: { name: 'Sangão', state: 'SC' },
  'santa cecilia_': { name: 'Santa Cecília', state: 'SC' },
  'santa helena___': { name: 'Santa Helena', state: 'SC' },
  'santa rosa de lima': { name: 'Santa Rosa de Lima', state: 'SC' },
  'santa rosa do sul': { name: 'Santa Rosa do Sul', state: 'SC' },
  'santa terezinha___': { name: 'Santa Terezinha', state: 'SC' },
  'santa terezinha do progresso': { name: 'Santa Terezinha do Progresso', state: 'SC' },
  'santiago do sul': { name: 'Santiago do Sul', state: 'SC' },
  'santo amaro da imperatriz': { name: 'Santo Amaro da Imperatriz', state: 'SC' },
  'sao bento do sul': { name: 'São Bento do Sul', state: 'SC' },
  'sao bernardino': { name: 'São Bernardino', state: 'SC' },
  'sao bonifacio': { name: 'São Bonifácio', state: 'SC' },
  'sao carlos': { name: 'São Carlos', state: 'SC' },
  'sao cristovao do sul': { name: 'São Cristóvão do Sul', state: 'SC' },
  'sao domingos___': { name: 'São Domingos', state: 'SC' },
  'sao francisco do sul': { name: 'São Francisco do Sul', state: 'SC' },
  'sao joao batista_': { name: 'São João Batista', state: 'SC' },
  'sao joao do itaperiu': { name: 'São João do Itaperiú', state: 'SC' },
  'sao joao do oeste': { name: 'São João do Oeste', state: 'SC' },
  'sao joao do sul': { name: 'São João do Sul', state: 'SC' },
  'sao joaquim': { name: 'São Joaquim', state: 'SC' },
  'sao jose': { name: 'São José', state: 'SC' },
  'sao jose do cedro': { name: 'São José do Cedro', state: 'SC' },
  'sao jose do cerrito': { name: 'São José do Cerrito', state: 'SC' },
  'sao lourenco do oeste': { name: 'São Lourenço do Oeste', state: 'SC' },
  'sao ludgero': { name: 'São Ludgero', state: 'SC' },
  'sao martinho_': { name: 'São Martinho', state: 'SC' },
  'sao miguel da boa vista': { name: 'São Miguel da Boa Vista', state: 'SC' },
  'sao miguel do oeste': { name: 'São Miguel do Oeste', state: 'SC' },
  'sao pedro de alcantara': { name: 'São Pedro de Alcântara', state: 'SC' },
  saudades: { name: 'Saudades', state: 'SC' },
  schroeder: { name: 'Schroeder', state: 'SC' },
  seara: { name: 'Seara', state: 'SC' },
  'serra alta': { name: 'Serra Alta', state: 'SC' },
  sideropolis: { name: 'Siderópolis', state: 'SC' },
  sombrio: { name: 'Sombrio', state: 'SC' },
  'sul brasil': { name: 'Sul Brasil', state: 'SC' },
  taio: { name: 'Taió', state: 'SC' },
  tangara_: { name: 'Tangará', state: 'SC' },
  tigrinhos: { name: 'Tigrinhos', state: 'SC' },
  tijucas: { name: 'Tijucas', state: 'SC' },
  'timbe do sul': { name: 'Timbé do Sul', state: 'SC' },
  timbo: { name: 'Timbó', state: 'SC' },
  'timbo grande': { name: 'Timbó Grande', state: 'SC' },
  'tres barras': { name: 'Três Barras', state: 'SC' },
  treviso: { name: 'Treviso', state: 'SC' },
  'treze de maio': { name: 'Treze de Maio', state: 'SC' },
  'treze tilias': { name: 'Treze Tílias', state: 'SC' },
  'trombudo central': { name: 'Trombudo Central', state: 'SC' },
  tubarao: { name: 'Tubarão', state: 'SC' },
  tunapolis: { name: 'Tunápolis', state: 'SC' },
  turvo_: { name: 'Turvo', state: 'SC' },
  'uniao do oeste': { name: 'União do Oeste', state: 'SC' },
  urubici: { name: 'Urubici', state: 'SC' },
  urupema: { name: 'Urupema', state: 'SC' },
  urussanga: { name: 'Urussanga', state: 'SC' },
  vargeao: { name: 'Vargeão', state: 'SC' },
  vargem: { name: 'Vargem', state: 'SC' },
  'vargem bonita_': { name: 'Vargem Bonita', state: 'SC' },
  'vidal ramos': { name: 'Vidal Ramos', state: 'SC' },
  videira: { name: 'Videira', state: 'SC' },
  'vitor meireles': { name: 'Vitor Meireles', state: 'SC' },
  witmarsum: { name: 'Witmarsum', state: 'SC' },
  xanxere: { name: 'Xanxerê', state: 'SC' },
  xavantina: { name: 'Xavantina', state: 'SC' },
  xaxim: { name: 'Xaxim', state: 'SC' },
  zortea: { name: 'Zortéa', state: 'SC' },
};
