export const cities = {
  adamantina: { name: 'Adamantina', state: 'SP' },
  adolfo: { name: 'Adolfo', state: 'SP' },
  aguai: { name: 'Aguaí', state: 'SP' },
  'aguas da prata': { name: 'Águas da Prata', state: 'SP' },
  'aguas de lindoia': { name: 'Águas de Lindóia', state: 'SP' },
  'aguas de santa barbara': { name: 'Águas de Santa Bárbara', state: 'SP' },
  'aguas de sao pedro': { name: 'Águas de São Pedro', state: 'SP' },
  agudos: { name: 'Agudos', state: 'SP' },
  alambari: { name: 'Alambari', state: 'SP' },
  'alfredo marcondes': { name: 'Alfredo Marcondes', state: 'SP' },
  altair: { name: 'Altair', state: 'SP' },
  altinopolis: { name: 'Altinópolis', state: 'SP' },
  'alto alegre__': { name: 'Alto Alegre', state: 'SP' },
  aluminio: { name: 'Alumínio', state: 'SP' },
  'alvares florence': { name: 'Álvares Florence', state: 'SP' },
  'alvares machado': { name: 'Álvares Machado', state: 'SP' },
  'alvaro de carvalho': { name: 'Álvaro de Carvalho', state: 'SP' },
  alvinlandia: { name: 'Alvinlândia', state: 'SP' },
  americana: { name: 'Americana', state: 'SP' },
  'americo brasiliense': { name: 'Américo Brasiliense', state: 'SP' },
  'americo de campos': { name: 'Américo de Campos', state: 'SP' },
  amparo_: { name: 'Amparo', state: 'SP' },
  analandia: { name: 'Analândia', state: 'SP' },
  andradina: { name: 'Andradina', state: 'SP' },
  angatuba: { name: 'Angatuba', state: 'SP' },
  anhembi: { name: 'Anhembi', state: 'SP' },
  anhumas: { name: 'Anhumas', state: 'SP' },
  aparecida_: { name: 'Aparecida', state: 'SP' },
  "aparecida d'oeste": { name: "Aparecida d'Oeste", state: 'SP' },
  apiai: { name: 'Apiaí', state: 'SP' },
  aracariguama: { name: 'Araçariguama', state: 'SP' },
  aracatuba: { name: 'Araçatuba', state: 'SP' },
  'aracoiaba da serra': { name: 'Araçoiaba da Serra', state: 'SP' },
  aramina: { name: 'Aramina', state: 'SP' },
  arandu: { name: 'Arandu', state: 'SP' },
  arapei: { name: 'Arapeí', state: 'SP' },
  araraquara: { name: 'Araraquara', state: 'SP' },
  araras: { name: 'Araras', state: 'SP' },
  'arco-iris': { name: 'Arco-Íris', state: 'SP' },
  arealva: { name: 'Arealva', state: 'SP' },
  areias: { name: 'Areias', state: 'SP' },
  areiopolis: { name: 'Areiópolis', state: 'SP' },
  ariranha: { name: 'Ariranha', state: 'SP' },
  'artur nogueira': { name: 'Artur Nogueira', state: 'SP' },
  aruja: { name: 'Arujá', state: 'SP' },
  aspasia: { name: 'Aspásia', state: 'SP' },
  assis: { name: 'Assis', state: 'SP' },
  atibaia: { name: 'Atibaia', state: 'SP' },
  auriflama: { name: 'Auriflama', state: 'SP' },
  avai: { name: 'Avaí', state: 'SP' },
  avanhandava: { name: 'Avanhandava', state: 'SP' },
  avare: { name: 'Avaré', state: 'SP' },
  'bady bassitt': { name: 'Bady Bassitt', state: 'SP' },
  balbinos: { name: 'Balbinos', state: 'SP' },
  balsamo: { name: 'Bálsamo', state: 'SP' },
  bananal: { name: 'Bananal', state: 'SP' },
  'barao de antonina': { name: 'Barão de Antonina', state: 'SP' },
  barbosa: { name: 'Barbosa', state: 'SP' },
  bariri: { name: 'Bariri', state: 'SP' },
  'barra bonita_': { name: 'Barra Bonita', state: 'SP' },
  'barra do chapeu': { name: 'Barra do Chapéu', state: 'SP' },
  'barra do turvo': { name: 'Barra do Turvo', state: 'SP' },
  barretos: { name: 'Barretos', state: 'SP' },
  barrinha: { name: 'Barrinha', state: 'SP' },
  barueri: { name: 'Barueri', state: 'SP' },
  bastos: { name: 'Bastos', state: 'SP' },
  batatais: { name: 'Batatais', state: 'SP' },
  bauru: { name: 'Bauru', state: 'SP' },
  bebedouro: { name: 'Bebedouro', state: 'SP' },
  'bento de abreu': { name: 'Bento de Abreu', state: 'SP' },
  'bernardino de campos': { name: 'Bernardino de Campos', state: 'SP' },
  bertioga: { name: 'Bertioga', state: 'SP' },
  bilac: { name: 'Bilac', state: 'SP' },
  birigui: { name: 'Birigui', state: 'SP' },
  'biritiba mirim': { name: 'Biritiba Mirim', state: 'SP' },
  'boa esperanca do sul': { name: 'Boa Esperança do Sul', state: 'SP' },
  bocaina_: { name: 'Bocaina', state: 'SP' },
  bofete: { name: 'Bofete', state: 'SP' },
  boituva: { name: 'Boituva', state: 'SP' },
  'bom jesus dos perdoes': { name: 'Bom Jesus dos Perdões', state: 'SP' },
  'bom sucesso de itarare': { name: 'Bom Sucesso de Itararé', state: 'SP' },
  bora: { name: 'Borá', state: 'SP' },
  boraceia: { name: 'Boraceia', state: 'SP' },
  borborema_: { name: 'Borborema', state: 'SP' },
  borebi: { name: 'Borebi', state: 'SP' },
  botucatu: { name: 'Botucatu', state: 'SP' },
  'braganca paulista': { name: 'Bragança Paulista', state: 'SP' },
  brauna: { name: 'Braúna', state: 'SP' },
  'brejo alegre': { name: 'Brejo Alegre', state: 'SP' },
  brodowski: { name: 'Brodowski', state: 'SP' },
  brotas: { name: 'Brotas', state: 'SP' },
  buri: { name: 'Buri', state: 'SP' },
  buritama: { name: 'Buritama', state: 'SP' },
  buritizal: { name: 'Buritizal', state: 'SP' },
  'cabralia paulista': { name: 'Cabrália Paulista', state: 'SP' },
  cabreuva: { name: 'Cabreúva', state: 'SP' },
  cacapava: { name: 'Caçapava', state: 'SP' },
  'cachoeira paulista': { name: 'Cachoeira Paulista', state: 'SP' },
  caconde: { name: 'Caconde', state: 'SP' },
  cafelandia_: { name: 'Cafelândia', state: 'SP' },
  caiabu: { name: 'Caiabu', state: 'SP' },
  caieiras: { name: 'Caieiras', state: 'SP' },
  caiua: { name: 'Caiuá', state: 'SP' },
  cajamar: { name: 'Cajamar', state: 'SP' },
  cajati: { name: 'Cajati', state: 'SP' },
  cajobi: { name: 'Cajobi', state: 'SP' },
  cajuru: { name: 'Cajuru', state: 'SP' },
  'campina do monte alegre': { name: 'Campina do Monte Alegre', state: 'SP' },
  campinas: { name: 'Campinas', state: 'SP' },
  'campo limpo paulista': { name: 'Campo Limpo Paulista', state: 'SP' },
  'campos do jordao': { name: 'Campos do Jordão', state: 'SP' },
  'campos novos paulista': { name: 'Campos Novos Paulista', state: 'SP' },
  cananeia: { name: 'Cananéia', state: 'SP' },
  canas: { name: 'Canas', state: 'SP' },
  'candido mota': { name: 'Cândido Mota', state: 'SP' },
  'candido rodrigues': { name: 'Cândido Rodrigues', state: 'SP' },
  canitar: { name: 'Canitar', state: 'SP' },
  'capao bonito': { name: 'Capão Bonito', state: 'SP' },
  'capela do alto': { name: 'Capela do Alto', state: 'SP' },
  capivari: { name: 'Capivari', state: 'SP' },
  caraguatatuba: { name: 'Caraguatatuba', state: 'SP' },
  carapicuiba: { name: 'Carapicuíba', state: 'SP' },
  cardoso: { name: 'Cardoso', state: 'SP' },
  'casa branca': { name: 'Casa Branca', state: 'SP' },
  'cassia dos coqueiros': { name: 'Cássia dos Coqueiros', state: 'SP' },
  castilho: { name: 'Castilho', state: 'SP' },
  catanduva: { name: 'Catanduva', state: 'SP' },
  catigua: { name: 'Catiguá', state: 'SP' },
  cedral_: { name: 'Cedral', state: 'SP' },
  'cerqueira cesar': { name: 'Cerqueira César', state: 'SP' },
  cerquilho: { name: 'Cerquilho', state: 'SP' },
  'cesario lange': { name: 'Cesário Lange', state: 'SP' },
  charqueada: { name: 'Charqueada', state: 'SP' },
  chavantes: { name: 'Chavantes', state: 'SP' },
  clementina: { name: 'Clementina', state: 'SP' },
  colina: { name: 'Colina', state: 'SP' },
  colombia: { name: 'Colômbia', state: 'SP' },
  conchal: { name: 'Conchal', state: 'SP' },
  conchas: { name: 'Conchas', state: 'SP' },
  cordeiropolis: { name: 'Cordeirópolis', state: 'SP' },
  coroados: { name: 'Coroados', state: 'SP' },
  'coronel macedo': { name: 'Coronel Macedo', state: 'SP' },
  corumbatai: { name: 'Corumbataí', state: 'SP' },
  cosmopolis: { name: 'Cosmópolis', state: 'SP' },
  cosmorama: { name: 'Cosmorama', state: 'SP' },
  cotia: { name: 'Cotia', state: 'SP' },
  cravinhos: { name: 'Cravinhos', state: 'SP' },
  'cristais paulista': { name: 'Cristais Paulista', state: 'SP' },
  cruzalia: { name: 'Cruzália', state: 'SP' },
  cruzeiro: { name: 'Cruzeiro', state: 'SP' },
  cubatao: { name: 'Cubatão', state: 'SP' },
  cunha: { name: 'Cunha', state: 'SP' },
  descalvado: { name: 'Descalvado', state: 'SP' },
  diadema: { name: 'Diadema', state: 'SP' },
  'dirce reis': { name: 'Dirce Reis', state: 'SP' },
  divinolandia: { name: 'Divinolândia', state: 'SP' },
  dobrada: { name: 'Dobrada', state: 'SP' },
  'dois corregos': { name: 'Dois Córregos', state: 'SP' },
  dolcinopolis: { name: 'Dolcinópolis', state: 'SP' },
  dourado: { name: 'Dourado', state: 'SP' },
  dracena: { name: 'Dracena', state: 'SP' },
  duartina: { name: 'Duartina', state: 'SP' },
  dumont: { name: 'Dumont', state: 'SP' },
  echapora: { name: 'Echaporã', state: 'SP' },
  eldorado_: { name: 'Eldorado', state: 'SP' },
  'elias fausto': { name: 'Elias Fausto', state: 'SP' },
  elisiario: { name: 'Elisiário', state: 'SP' },
  embauba: { name: 'Embaúba', state: 'SP' },
  'embu das artes': { name: 'Embu das Artes', state: 'SP' },
  'embu-guacu': { name: 'Embu-Guaçu', state: 'SP' },
  emilianopolis: { name: 'Emilianópolis', state: 'SP' },
  'engenheiro coelho': { name: 'Engenheiro Coelho', state: 'SP' },
  'espirito santo do pinhal': { name: 'Espírito Santo do Pinhal', state: 'SP' },
  'espirito santo do turvo': { name: 'Espírito Santo do Turvo', state: 'SP' },
  'estiva gerbi': { name: 'Estiva Gerbi', state: 'SP' },
  "estrela d'oeste": { name: "Estrela d'Oeste", state: 'SP' },
  'estrela do norte_': { name: 'Estrela do Norte', state: 'SP' },
  'euclides da cunha paulista': { name: 'Euclides da Cunha Paulista', state: 'SP' },
  fartura: { name: 'Fartura', state: 'SP' },
  fernandopolis: { name: 'Fernandópolis', state: 'SP' },
  'fernando prestes': { name: 'Fernando Prestes', state: 'SP' },
  fernao: { name: 'Fernão', state: 'SP' },
  'ferraz de vasconcelos': { name: 'Ferraz de Vasconcelos', state: 'SP' },
  'flora rica': { name: 'Flora Rica', state: 'SP' },
  floreal: { name: 'Floreal', state: 'SP' },
  'florida paulista': { name: 'Flórida Paulista', state: 'SP' },
  florinea: { name: 'Florínea', state: 'SP' },
  franca: { name: 'Franca', state: 'SP' },
  'francisco morato': { name: 'Francisco Morato', state: 'SP' },
  'franco da rocha': { name: 'Franco da Rocha', state: 'SP' },
  'gabriel monteiro': { name: 'Gabriel Monteiro', state: 'SP' },
  galia: { name: 'Gália', state: 'SP' },
  garca: { name: 'Garça', state: 'SP' },
  'gastao vidigal': { name: 'Gastão Vidigal', state: 'SP' },
  'gaviao peixoto': { name: 'Gavião Peixoto', state: 'SP' },
  'general salgado': { name: 'General Salgado', state: 'SP' },
  getulina: { name: 'Getulina', state: 'SP' },
  glicerio: { name: 'Glicério', state: 'SP' },
  guaicara: { name: 'Guaiçara', state: 'SP' },
  guaimbe: { name: 'Guaimbê', state: 'SP' },
  guaira_: { name: 'Guaíra', state: 'SP' },
  guapiacu: { name: 'Guapiaçu', state: 'SP' },
  guapiara: { name: 'Guapiara', state: 'SP' },
  guara: { name: 'Guará', state: 'SP' },
  guaracai: { name: 'Guaraçaí', state: 'SP' },
  guaraci_: { name: 'Guaraci', state: 'SP' },
  "guarani d'oeste": { name: "Guarani d'Oeste", state: 'SP' },
  guaranta: { name: 'Guarantã', state: 'SP' },
  guararapes: { name: 'Guararapes', state: 'SP' },
  guararema: { name: 'Guararema', state: 'SP' },
  guaratingueta: { name: 'Guaratinguetá', state: 'SP' },
  guarei: { name: 'Guareí', state: 'SP' },
  guariba: { name: 'Guariba', state: 'SP' },
  guaruja: { name: 'Guarujá', state: 'SP' },
  guarulhos: { name: 'Guarulhos', state: 'SP' },
  guatapara: { name: 'Guatapará', state: 'SP' },
  guzolandia: { name: 'Guzolândia', state: 'SP' },
  herculandia: { name: 'Herculândia', state: 'SP' },
  holambra: { name: 'Holambra', state: 'SP' },
  hortolandia: { name: 'Hortolândia', state: 'SP' },
  iacanga: { name: 'Iacanga', state: 'SP' },
  iacri: { name: 'Iacri', state: 'SP' },
  iaras: { name: 'Iaras', state: 'SP' },
  ibate: { name: 'Ibaté', state: 'SP' },
  ibira: { name: 'Ibirá', state: 'SP' },
  ibirarema: { name: 'Ibirarema', state: 'SP' },
  ibitinga: { name: 'Ibitinga', state: 'SP' },
  ibiuna: { name: 'Ibiúna', state: 'SP' },
  icem: { name: 'Icém', state: 'SP' },
  iepe: { name: 'Iepê', state: 'SP' },
  'igaracu do tiete': { name: 'Igaraçu do Tietê', state: 'SP' },
  igarapava: { name: 'Igarapava', state: 'SP' },
  igarata: { name: 'Igaratá', state: 'SP' },
  iguape: { name: 'Iguape', state: 'SP' },
  ilhabela: { name: 'Ilhabela', state: 'SP' },
  'ilha comprida': { name: 'Ilha Comprida', state: 'SP' },
  'ilha solteira': { name: 'Ilha Solteira', state: 'SP' },
  indaiatuba: { name: 'Indaiatuba', state: 'SP' },
  indiana: { name: 'Indiana', state: 'SP' },
  indiapora: { name: 'Indiaporã', state: 'SP' },
  'inubia paulista': { name: 'Inúbia Paulista', state: 'SP' },
  ipaussu: { name: 'Ipaussu', state: 'SP' },
  ipero: { name: 'Iperó', state: 'SP' },
  ipeuna: { name: 'Ipeúna', state: 'SP' },
  ipigua: { name: 'Ipiguá', state: 'SP' },
  iporanga: { name: 'Iporanga', state: 'SP' },
  ipua: { name: 'Ipuã', state: 'SP' },
  iracemapolis: { name: 'Iracemápolis', state: 'SP' },
  irapua: { name: 'Irapuã', state: 'SP' },
  irapuru: { name: 'Irapuru', state: 'SP' },
  itabera: { name: 'Itaberá', state: 'SP' },
  itai: { name: 'Itaí', state: 'SP' },
  itajobi: { name: 'Itajobi', state: 'SP' },
  itaju: { name: 'Itaju', state: 'SP' },
  itanhaem: { name: 'Itanhaém', state: 'SP' },
  itaoca: { name: 'Itaoca', state: 'SP' },
  'itapecerica da serra': { name: 'Itapecerica da Serra', state: 'SP' },
  itapetininga: { name: 'Itapetininga', state: 'SP' },
  itapeva_: { name: 'Itapeva', state: 'SP' },
  itapevi: { name: 'Itapevi', state: 'SP' },
  itapira: { name: 'Itapira', state: 'SP' },
  'itapirapua paulista': { name: 'Itapirapuã Paulista', state: 'SP' },
  itapolis: { name: 'Itápolis', state: 'SP' },
  itaporanga_: { name: 'Itaporanga', state: 'SP' },
  itapui: { name: 'Itapuí', state: 'SP' },
  itapura: { name: 'Itapura', state: 'SP' },
  itaquaquecetuba: { name: 'Itaquaquecetuba', state: 'SP' },
  itarare: { name: 'Itararé', state: 'SP' },
  itariri: { name: 'Itariri', state: 'SP' },
  itatiba: { name: 'Itatiba', state: 'SP' },
  itatinga: { name: 'Itatinga', state: 'SP' },
  itirapina: { name: 'Itirapina', state: 'SP' },
  itirapua: { name: 'Itirapuã', state: 'SP' },
  itobi: { name: 'Itobi', state: 'SP' },
  itu: { name: 'Itu', state: 'SP' },
  itupeva: { name: 'Itupeva', state: 'SP' },
  ituverava: { name: 'Ituverava', state: 'SP' },
  jaborandi_: { name: 'Jaborandi', state: 'SP' },
  jaboticabal: { name: 'Jaboticabal', state: 'SP' },
  jacarei: { name: 'Jacareí', state: 'SP' },
  jaci: { name: 'Jaci', state: 'SP' },
  jacupiranga: { name: 'Jacupiranga', state: 'SP' },
  jaguariuna: { name: 'Jaguariúna', state: 'SP' },
  jales: { name: 'Jales', state: 'SP' },
  jambeiro: { name: 'Jambeiro', state: 'SP' },
  jandira: { name: 'Jandira', state: 'SP' },
  jardinopolis_: { name: 'Jardinópolis', state: 'SP' },
  jarinu: { name: 'Jarinu', state: 'SP' },
  jau: { name: 'Jaú', state: 'SP' },
  jeriquara: { name: 'Jeriquara', state: 'SP' },
  joanopolis: { name: 'Joanópolis', state: 'SP' },
  'joao ramalho': { name: 'João Ramalho', state: 'SP' },
  'jose bonifacio': { name: 'José Bonifácio', state: 'SP' },
  'julio mesquita': { name: 'Júlio Mesquita', state: 'SP' },
  jumirim: { name: 'Jumirim', state: 'SP' },
  jundiai: { name: 'Jundiaí', state: 'SP' },
  junqueiropolis: { name: 'Junqueirópolis', state: 'SP' },
  juquia: { name: 'Juquiá', state: 'SP' },
  juquitiba: { name: 'Juquitiba', state: 'SP' },
  lagoinha: { name: 'Lagoinha', state: 'SP' },
  'laranjal paulista': { name: 'Laranjal Paulista', state: 'SP' },
  lavinia: { name: 'Lavínia', state: 'SP' },
  lavrinhas: { name: 'Lavrinhas', state: 'SP' },
  leme: { name: 'Leme', state: 'SP' },
  'lencois paulista': { name: 'Lençóis Paulista', state: 'SP' },
  limeira: { name: 'Limeira', state: 'SP' },
  lindoia: { name: 'Lindóia', state: 'SP' },
  lins: { name: 'Lins', state: 'SP' },
  lorena: { name: 'Lorena', state: 'SP' },
  lourdes: { name: 'Lourdes', state: 'SP' },
  louveira: { name: 'Louveira', state: 'SP' },
  lucelia: { name: 'Lucélia', state: 'SP' },
  lucianopolis: { name: 'Lucianópolis', state: 'SP' },
  'luiz antonio': { name: 'Luiz Antônio', state: 'SP' },
  luisiania: { name: 'Luisiânia', state: 'SP' },
  lupercio: { name: 'Lupércio', state: 'SP' },
  lutecia: { name: 'Lutécia', state: 'SP' },
  macatuba: { name: 'Macatuba', state: 'SP' },
  macaubal: { name: 'Macaubal', state: 'SP' },
  macedonia: { name: 'Macedônia', state: 'SP' },
  magda: { name: 'Magda', state: 'SP' },
  mairinque: { name: 'Mairinque', state: 'SP' },
  mairipora: { name: 'Mairiporã', state: 'SP' },
  manduri: { name: 'Manduri', state: 'SP' },
  'maraba paulista': { name: 'Marabá Paulista', state: 'SP' },
  maracai: { name: 'Maracaí', state: 'SP' },
  marapoama: { name: 'Marapoama', state: 'SP' },
  mariapolis: { name: 'Mariápolis', state: 'SP' },
  marilia: { name: 'Marília', state: 'SP' },
  marinopolis: { name: 'Marinópolis', state: 'SP' },
  martinopolis: { name: 'Martinópolis', state: 'SP' },
  matao: { name: 'Matão', state: 'SP' },
  maua: { name: 'Mauá', state: 'SP' },
  mendonca: { name: 'Mendonça', state: 'SP' },
  meridiano: { name: 'Meridiano', state: 'SP' },
  mesopolis: { name: 'Mesópolis', state: 'SP' },
  miguelopolis: { name: 'Miguelópolis', state: 'SP' },
  'mineiros do tiete': { name: 'Mineiros do Tietê', state: 'SP' },
  miracatu: { name: 'Miracatu', state: 'SP' },
  'mira estrela': { name: 'Mira Estrela', state: 'SP' },
  mirandopolis: { name: 'Mirandópolis', state: 'SP' },
  'mirante do paranapanema': { name: 'Mirante do Paranapanema', state: 'SP' },
  mirassol: { name: 'Mirassol', state: 'SP' },
  mirassolandia: { name: 'Mirassolândia', state: 'SP' },
  mococa: { name: 'Mococa', state: 'SP' },
  'mogi das cruzes': { name: 'Mogi das Cruzes', state: 'SP' },
  'mogi guacu': { name: 'Mogi Guaçu', state: 'SP' },
  'mogi mirim': { name: 'Mogi Mirim', state: 'SP' },
  mombuca: { name: 'Mombuca', state: 'SP' },
  moncoes: { name: 'Monções', state: 'SP' },
  mongagua: { name: 'Mongaguá', state: 'SP' },
  'monte alegre do sul': { name: 'Monte Alegre do Sul', state: 'SP' },
  'monte alto': { name: 'Monte Alto', state: 'SP' },
  'monte aprazivel': { name: 'Monte Aprazível', state: 'SP' },
  'monte azul paulista': { name: 'Monte Azul Paulista', state: 'SP' },
  'monte castelo_': { name: 'Monte Castelo', state: 'SP' },
  'monteiro lobato': { name: 'Monteiro Lobato', state: 'SP' },
  'monte mor': { name: 'Monte Mor', state: 'SP' },
  'morro agudo': { name: 'Morro Agudo', state: 'SP' },
  morungaba: { name: 'Morungaba', state: 'SP' },
  motuca: { name: 'Motuca', state: 'SP' },
  'murutinga do sul': { name: 'Murutinga do Sul', state: 'SP' },
  nantes: { name: 'Nantes', state: 'SP' },
  narandiba: { name: 'Narandiba', state: 'SP' },
  'natividade da serra': { name: 'Natividade da Serra', state: 'SP' },
  'nazare paulista': { name: 'Nazaré Paulista', state: 'SP' },
  'neves paulista': { name: 'Neves Paulista', state: 'SP' },
  nhandeara: { name: 'Nhandeara', state: 'SP' },
  nipoa: { name: 'Nipoã', state: 'SP' },
  'nova alianca': { name: 'Nova Aliança', state: 'SP' },
  'nova campina': { name: 'Nova Campina', state: 'SP' },
  'nova canaa paulista': { name: 'Nova Canaã Paulista', state: 'SP' },
  'nova castilho': { name: 'Nova Castilho', state: 'SP' },
  'nova europa': { name: 'Nova Europa', state: 'SP' },
  'nova granada': { name: 'Nova Granada', state: 'SP' },
  'nova guataporanga': { name: 'Nova Guataporanga', state: 'SP' },
  'nova independencia': { name: 'Nova Independência', state: 'SP' },
  novais: { name: 'Novais', state: 'SP' },
  'nova luzitania': { name: 'Nova Luzitânia', state: 'SP' },
  'nova odessa': { name: 'Nova Odessa', state: 'SP' },
  'novo horizonte__': { name: 'Novo Horizonte', state: 'SP' },
  nuporanga: { name: 'Nuporanga', state: 'SP' },
  ocaucu: { name: 'Ocauçu', state: 'SP' },
  oleo: { name: 'Óleo', state: 'SP' },
  olimpia: { name: 'Olímpia', state: 'SP' },
  'onda verde': { name: 'Onda Verde', state: 'SP' },
  oriente: { name: 'Oriente', state: 'SP' },
  orindiuva: { name: 'Orindiúva', state: 'SP' },
  orlandia: { name: 'Orlândia', state: 'SP' },
  osasco: { name: 'Osasco', state: 'SP' },
  'oscar bressane': { name: 'Oscar Bressane', state: 'SP' },
  'osvaldo cruz': { name: 'Osvaldo Cruz', state: 'SP' },
  ourinhos: { name: 'Ourinhos', state: 'SP' },
  ouroeste: { name: 'Ouroeste', state: 'SP' },
  'ouro verde_': { name: 'Ouro Verde', state: 'SP' },
  pacaembu: { name: 'Pacaembu', state: 'SP' },
  palestina_: { name: 'Palestina', state: 'SP' },
  'palmares paulista': { name: 'Palmares Paulista', state: 'SP' },
  "palmeira d'oeste": { name: "Palmeira d'Oeste", state: 'SP' },
  palmital_: { name: 'Palmital', state: 'SP' },
  panorama: { name: 'Panorama', state: 'SP' },
  'paraguacu paulista': { name: 'Paraguaçu Paulista', state: 'SP' },
  paraibuna: { name: 'Paraibuna', state: 'SP' },
  paraiso_: { name: 'Paraíso', state: 'SP' },
  paranapanema: { name: 'Paranapanema', state: 'SP' },
  paranapua: { name: 'Paranapuã', state: 'SP' },
  parapua: { name: 'Parapuã', state: 'SP' },
  pardinho: { name: 'Pardinho', state: 'SP' },
  'pariquera-acu': { name: 'Pariquera-Açu', state: 'SP' },
  parisi: { name: 'Parisi', state: 'SP' },
  'patrocinio paulista': { name: 'Patrocínio Paulista', state: 'SP' },
  pauliceia: { name: 'Paulicéia', state: 'SP' },
  paulinia: { name: 'Paulínia', state: 'SP' },
  paulistania: { name: 'Paulistânia', state: 'SP' },
  'paulo de faria': { name: 'Paulo de Faria', state: 'SP' },
  pederneiras: { name: 'Pederneiras', state: 'SP' },
  'pedra bela': { name: 'Pedra Bela', state: 'SP' },
  pedranopolis: { name: 'Pedranópolis', state: 'SP' },
  pedregulho: { name: 'Pedregulho', state: 'SP' },
  pedreira: { name: 'Pedreira', state: 'SP' },
  'pedrinhas paulista': { name: 'Pedrinhas Paulista', state: 'SP' },
  'pedro de toledo': { name: 'Pedro de Toledo', state: 'SP' },
  penapolis: { name: 'Penápolis', state: 'SP' },
  'pereira barreto': { name: 'Pereira Barreto', state: 'SP' },
  pereiras: { name: 'Pereiras', state: 'SP' },
  peruibe: { name: 'Peruíbe', state: 'SP' },
  piacatu: { name: 'Piacatu', state: 'SP' },
  piedade: { name: 'Piedade', state: 'SP' },
  'pilar do sul': { name: 'Pilar do Sul', state: 'SP' },
  pindamonhangaba: { name: 'Pindamonhangaba', state: 'SP' },
  pindorama: { name: 'Pindorama', state: 'SP' },
  pinhalzinho_: { name: 'Pinhalzinho', state: 'SP' },
  piquerobi: { name: 'Piquerobi', state: 'SP' },
  piquete: { name: 'Piquete', state: 'SP' },
  piracaia: { name: 'Piracaia', state: 'SP' },
  piracicaba: { name: 'Piracicaba', state: 'SP' },
  piraju: { name: 'Piraju', state: 'SP' },
  pirajui: { name: 'Pirajuí', state: 'SP' },
  pirangi: { name: 'Pirangi', state: 'SP' },
  'pirapora do bom jesus': { name: 'Pirapora do Bom Jesus', state: 'SP' },
  pirapozinho: { name: 'Pirapozinho', state: 'SP' },
  pirassununga: { name: 'Pirassununga', state: 'SP' },
  piratininga: { name: 'Piratininga', state: 'SP' },
  pitangueiras_: { name: 'Pitangueiras', state: 'SP' },
  planalto___: { name: 'Planalto', state: 'SP' },
  platina: { name: 'Platina', state: 'SP' },
  poa: { name: 'Poá', state: 'SP' },
  poloni: { name: 'Poloni', state: 'SP' },
  pompeia: { name: 'Pompeia', state: 'SP' },
  pongai: { name: 'Pongaí', state: 'SP' },
  pontal: { name: 'Pontal', state: 'SP' },
  pontalinda: { name: 'Pontalinda', state: 'SP' },
  'pontes gestal': { name: 'Pontes Gestal', state: 'SP' },
  populina: { name: 'Populina', state: 'SP' },
  porangaba: { name: 'Porangaba', state: 'SP' },
  'porto feliz': { name: 'Porto Feliz', state: 'SP' },
  'porto ferreira': { name: 'Porto Ferreira', state: 'SP' },
  potim: { name: 'Potim', state: 'SP' },
  potirendaba: { name: 'Potirendaba', state: 'SP' },
  pracinha: { name: 'Pracinha', state: 'SP' },
  pradopolis: { name: 'Pradópolis', state: 'SP' },
  'praia grande_': { name: 'Praia Grande', state: 'SP' },
  pratania: { name: 'Pratânia', state: 'SP' },
  'presidente alves': { name: 'Presidente Alves', state: 'SP' },
  'presidente bernardes_': { name: 'Presidente Bernardes', state: 'SP' },
  'presidente epitacio': { name: 'Presidente Epitácio', state: 'SP' },
  'presidente prudente': { name: 'Presidente Prudente', state: 'SP' },
  'presidente venceslau': { name: 'Presidente Venceslau', state: 'SP' },
  promissao: { name: 'Promissão', state: 'SP' },
  quadra: { name: 'Quadra', state: 'SP' },
  quata: { name: 'Quatá', state: 'SP' },
  queiroz: { name: 'Queiroz', state: 'SP' },
  queluz: { name: 'Queluz', state: 'SP' },
  quintana: { name: 'Quintana', state: 'SP' },
  rafard: { name: 'Rafard', state: 'SP' },
  rancharia: { name: 'Rancharia', state: 'SP' },
  'redencao da serra': { name: 'Redenção da Serra', state: 'SP' },
  'regente feijo': { name: 'Regente Feijó', state: 'SP' },
  reginopolis: { name: 'Reginópolis', state: 'SP' },
  registro: { name: 'Registro', state: 'SP' },
  restinga: { name: 'Restinga', state: 'SP' },
  ribeira: { name: 'Ribeira', state: 'SP' },
  'ribeirao bonito': { name: 'Ribeirão Bonito', state: 'SP' },
  'ribeirao branco': { name: 'Ribeirão Branco', state: 'SP' },
  'ribeirao corrente': { name: 'Ribeirão Corrente', state: 'SP' },
  'ribeirao dos indios': { name: 'Ribeirão dos Índios', state: 'SP' },
  'ribeirao do sul': { name: 'Ribeirão do Sul', state: 'SP' },
  'ribeirao grande': { name: 'Ribeirão Grande', state: 'SP' },
  'ribeirao pires': { name: 'Ribeirão Pires', state: 'SP' },
  'ribeirao preto': { name: 'Ribeirão Preto', state: 'SP' },
  rifaina: { name: 'Rifaina', state: 'SP' },
  rincao: { name: 'Rincão', state: 'SP' },
  rinopolis: { name: 'Rinópolis', state: 'SP' },
  'rio claro_': { name: 'Rio Claro', state: 'SP' },
  'rio das pedras': { name: 'Rio das Pedras', state: 'SP' },
  'rio grande da serra': { name: 'Rio Grande da Serra', state: 'SP' },
  riolandia: { name: 'Riolândia', state: 'SP' },
  riversul: { name: 'Riversul', state: 'SP' },
  rosana: { name: 'Rosana', state: 'SP' },
  roseira: { name: 'Roseira', state: 'SP' },
  rubiacea: { name: 'Rubiácea', state: 'SP' },
  rubineia: { name: 'Rubineia', state: 'SP' },
  sabino: { name: 'Sabino', state: 'SP' },
  sagres: { name: 'Sagres', state: 'SP' },
  sales: { name: 'Sales', state: 'SP' },
  'sales oliveira': { name: 'Sales Oliveira', state: 'SP' },
  salesopolis: { name: 'Salesópolis', state: 'SP' },
  salmourao: { name: 'Salmourão', state: 'SP' },
  saltinho_: { name: 'Saltinho', state: 'SP' },
  salto: { name: 'Salto', state: 'SP' },
  'salto de pirapora': { name: 'Salto de Pirapora', state: 'SP' },
  'salto grande': { name: 'Salto Grande', state: 'SP' },
  sandovalina: { name: 'Sandovalina', state: 'SP' },
  'santa adelia': { name: 'Santa Adélia', state: 'SP' },
  'santa albertina': { name: 'Santa Albertina', state: 'SP' },
  "santa barbara d'oeste": { name: "Santa Bárbara d'Oeste", state: 'SP' },
  'santa branca': { name: 'Santa Branca', state: 'SP' },
  "santa clara d'oeste": { name: "Santa Clara d'Oeste", state: 'SP' },
  'santa cruz da conceicao': { name: 'Santa Cruz da Conceição', state: 'SP' },
  'santa cruz da esperanca': { name: 'Santa Cruz da Esperança', state: 'SP' },
  'santa cruz das palmeiras': { name: 'Santa Cruz das Palmeiras', state: 'SP' },
  'santa cruz do rio pardo': { name: 'Santa Cruz do Rio Pardo', state: 'SP' },
  'santa ernestina': { name: 'Santa Ernestina', state: 'SP' },
  'santa fe do sul': { name: 'Santa Fé do Sul', state: 'SP' },
  'santa gertrudes': { name: 'Santa Gertrudes', state: 'SP' },
  'santa isabel_': { name: 'Santa Isabel', state: 'SP' },
  'santa lucia_': { name: 'Santa Lúcia', state: 'SP' },
  'santa maria da serra': { name: 'Santa Maria da Serra', state: 'SP' },
  'santa mercedes': { name: 'Santa Mercedes', state: 'SP' },
  'santana da ponte pensa': { name: 'Santana da Ponte Pensa', state: 'SP' },
  'santana de parnaiba': { name: 'Santana de Parnaíba', state: 'SP' },
  "santa rita d'oeste": { name: "Santa Rita d'Oeste", state: 'SP' },
  'santa rita do passa quatro': { name: 'Santa Rita do Passa Quatro', state: 'SP' },
  'santa rosa de viterbo': { name: 'Santa Rosa de Viterbo', state: 'SP' },
  'santa salete': { name: 'Santa Salete', state: 'SP' },
  'santo anastacio': { name: 'Santo Anastácio', state: 'SP' },
  'santo andre_': { name: 'Santo André', state: 'SP' },
  'santo antonio da alegria': { name: 'Santo Antônio da Alegria', state: 'SP' },
  'santo antonio de posse': { name: 'Santo Antônio de Posse', state: 'SP' },
  'santo antonio do aracangua': { name: 'Santo Antônio do Aracanguá', state: 'SP' },
  'santo antonio do jardim': { name: 'Santo Antônio do Jardim', state: 'SP' },
  'santo antonio do pinhal': { name: 'Santo Antônio do Pinhal', state: 'SP' },
  'santo expedito': { name: 'Santo Expedito', state: 'SP' },
  'santopolis do aguapei': { name: 'Santópolis do Aguapeí', state: 'SP' },
  santos: { name: 'Santos', state: 'SP' },
  'sao bento do sapucai': { name: 'São Bento do Sapucaí', state: 'SP' },
  'sao bernardo do campo': { name: 'São Bernardo do Campo', state: 'SP' },
  'sao caetano do sul': { name: 'São Caetano do Sul', state: 'SP' },
  'sao carlos_': { name: 'São Carlos', state: 'SP' },
  'sao francisco___': { name: 'São Francisco', state: 'SP' },
  'sao joao da boa vista': { name: 'São João da Boa Vista', state: 'SP' },
  'sao joao das duas pontes': { name: 'São João das Duas Pontes', state: 'SP' },
  'sao joao de iracema': { name: 'São João de Iracema', state: 'SP' },
  "sao joao do pau-d'alho": { name: "São João do Pau-d'Alho", state: 'SP' },
  'sao joaquim da barra': { name: 'São Joaquim da Barra', state: 'SP' },
  'sao jose da bela vista': { name: 'São José da Bela Vista', state: 'SP' },
  'sao jose do barreiro': { name: 'São José do Barreiro', state: 'SP' },
  'sao jose do rio pardo': { name: 'São José do Rio Pardo', state: 'SP' },
  'sao jose do rio preto': { name: 'São José do Rio Preto', state: 'SP' },
  'sao jose dos campos': { name: 'São José dos Campos', state: 'SP' },
  'sao lourenco da serra': { name: 'São Lourenço da Serra', state: 'SP' },
  'sao luiz do paraitinga': { name: 'São Luiz do Paraitinga', state: 'SP' },
  'sao manuel': { name: 'São Manuel', state: 'SP' },
  'sao miguel arcanjo': { name: 'São Miguel Arcanjo', state: 'SP' },
  'sao paulo': { name: 'São Paulo', state: 'SP' },
  'sao pedro_': { name: 'São Pedro', state: 'SP' },
  'sao pedro do turvo': { name: 'São Pedro do Turvo', state: 'SP' },
  'sao roque': { name: 'São Roque', state: 'SP' },
  'sao sebastiao_': { name: 'São Sebastião', state: 'SP' },
  'sao sebastiao da grama': { name: 'São Sebastião da Grama', state: 'SP' },
  'sao simao_': { name: 'São Simão', state: 'SP' },
  'sao vicente_': { name: 'São Vicente', state: 'SP' },
  sarapui: { name: 'Sarapuí', state: 'SP' },
  sarutaia: { name: 'Sarutaiá', state: 'SP' },
  'sebastianopolis do sul': { name: 'Sebastianópolis do Sul', state: 'SP' },
  'serra azul': { name: 'Serra Azul', state: 'SP' },
  serrana: { name: 'Serrana', state: 'SP' },
  'serra negra': { name: 'Serra Negra', state: 'SP' },
  sertaozinho_: { name: 'Sertãozinho', state: 'SP' },
  'sete barras': { name: 'Sete Barras', state: 'SP' },
  severinia: { name: 'Severínia', state: 'SP' },
  silveiras: { name: 'Silveiras', state: 'SP' },
  socorro: { name: 'Socorro', state: 'SP' },
  sorocaba: { name: 'Sorocaba', state: 'SP' },
  'sud mennucci': { name: 'Sud Mennucci', state: 'SP' },
  sumare: { name: 'Sumaré', state: 'SP' },
  suzanapolis: { name: 'Suzanápolis', state: 'SP' },
  suzano: { name: 'Suzano', state: 'SP' },
  tabapua: { name: 'Tabapuã', state: 'SP' },
  tabatinga_: { name: 'Tabatinga', state: 'SP' },
  'taboao da serra': { name: 'Taboão da Serra', state: 'SP' },
  taciba: { name: 'Taciba', state: 'SP' },
  taguai: { name: 'Taguaí', state: 'SP' },
  taiacu: { name: 'Taiaçu', state: 'SP' },
  taiuva: { name: 'Taiuva', state: 'SP' },
  tambau: { name: 'Tambaú', state: 'SP' },
  tanabi: { name: 'Tanabi', state: 'SP' },
  tapirai_: { name: 'Tapiraí', state: 'SP' },
  tapiratiba: { name: 'Tapiratiba', state: 'SP' },
  taquaral: { name: 'Taquaral', state: 'SP' },
  taquaritinga: { name: 'Taquaritinga', state: 'SP' },
  taquarituba: { name: 'Taquarituba', state: 'SP' },
  taquarivai: { name: 'Taquarivaí', state: 'SP' },
  tarabai: { name: 'Tarabai', state: 'SP' },
  taruma: { name: 'Tarumã', state: 'SP' },
  tatui: { name: 'Tatuí', state: 'SP' },
  taubate: { name: 'Taubaté', state: 'SP' },
  tejupa: { name: 'Tejupá', state: 'SP' },
  'teodoro sampaio_': { name: 'Teodoro Sampaio', state: 'SP' },
  'terra roxa_': { name: 'Terra Roxa', state: 'SP' },
  tiete: { name: 'Tietê', state: 'SP' },
  timburi: { name: 'Timburi', state: 'SP' },
  'torre de pedra': { name: 'Torre de Pedra', state: 'SP' },
  torrinha: { name: 'Torrinha', state: 'SP' },
  trabiju: { name: 'Trabiju', state: 'SP' },
  tremembe: { name: 'Tremembé', state: 'SP' },
  'tres fronteiras': { name: 'Três Fronteiras', state: 'SP' },
  tuiuti: { name: 'Tuiuti', state: 'SP' },
  tupa: { name: 'Tupã', state: 'SP' },
  'tupi paulista': { name: 'Tupi Paulista', state: 'SP' },
  turiuba: { name: 'Turiúba', state: 'SP' },
  turmalina_: { name: 'Turmalina', state: 'SP' },
  ubarana: { name: 'Ubarana', state: 'SP' },
  ubatuba: { name: 'Ubatuba', state: 'SP' },
  ubirajara: { name: 'Ubirajara', state: 'SP' },
  uchoa: { name: 'Uchoa', state: 'SP' },
  'uniao paulista': { name: 'União Paulista', state: 'SP' },
  urania: { name: 'Urânia', state: 'SP' },
  uru: { name: 'Uru', state: 'SP' },
  urupes: { name: 'Urupês', state: 'SP' },
  'valentim gentil': { name: 'Valentim Gentil', state: 'SP' },
  valinhos: { name: 'Valinhos', state: 'SP' },
  valparaiso: { name: 'Valparaíso', state: 'SP' },
  vargem_: { name: 'Vargem', state: 'SP' },
  'vargem grande do sul': { name: 'Vargem Grande do Sul', state: 'SP' },
  'vargem grande paulista': { name: 'Vargem Grande Paulista', state: 'SP' },
  'varzea paulista': { name: 'Várzea Paulista', state: 'SP' },
  'vera cruz___': { name: 'Vera Cruz', state: 'SP' },
  vinhedo: { name: 'Vinhedo', state: 'SP' },
  viradouro: { name: 'Viradouro', state: 'SP' },
  'vista alegre do alto': { name: 'Vista Alegre do Alto', state: 'SP' },
  'vitoria brasil': { name: 'Vitória Brasil', state: 'SP' },
  votorantim: { name: 'Votorantim', state: 'SP' },
  votuporanga: { name: 'Votuporanga', state: 'SP' },
  zacarias: { name: 'Zacarias', state: 'SP' },
};
