export const cities = {
  acrelandia: 'Acrelândia',
  'assis brasil': 'Assis Brasil',
  brasileia: 'Brasiléia',
  bujari: 'Bujari',
  capixaba: 'Capixaba',
  'cruzeiro do sul': 'Cruzeiro do Sul',
  epitaciolandia: 'Epitaciolândia',
  feijo: 'Feijó',
  jordao: 'Jordão',
  'mancio lima': 'Mâncio Lima',
  'manoel urbano': 'Manoel Urbano',
  'marechal thaumaturgo': 'Marechal Thaumaturgo',
  'placido de castro': 'Plácido de Castro',
  'porto acre': 'Porto Acre',
  'porto walter': 'Porto Walter',
  'rio branco': 'Rio Branco',
  'rodrigues alves': 'Rodrigues Alves',
  'santa rosa do purus': 'Santa Rosa do Purus',
  'senador guiomard': 'Senador Guiomard',
  'sena madureira': 'Sena Madureira',
  tarauaca: 'Tarauacá',
  xapuri: 'Xapuri',
};
