export const cities = {
  'agua branca': 'Água Branca',
  anadia: 'Anadia',
  arapiraca: 'Arapiraca',
  atalaia: 'Atalaia',
  'barra de santo antonio': 'Barra de Santo Antônio',
  'barra de sao miguel': 'Barra de São Miguel',
  batalha: 'Batalha',
  belem: 'Belém',
  'belo monte': 'Belo Monte',
  'boca da mata': 'Boca da Mata',
  branquinha: 'Branquinha',
  cacimbinhas: 'Cacimbinhas',
  cajueiro: 'Cajueiro',
  campestre: 'Campestre',
  'campo alegre': 'Campo Alegre',
  'campo grande': 'Campo Grande',
  canapi: 'Canapi',
  capela: 'Capela',
  carneiros: 'Carneiros',
  'cha preta': 'Chã Preta',
  'coite do noia': 'Coité do Noia',
  'colonia leopoldina': 'Colônia Leopoldina',
  'coqueiro seco': 'Coqueiro Seco',
  coruripe: 'Coruripe',
  craibas: 'Craíbas',
  'delmiro gouveia': 'Delmiro Gouveia',
  'dois riachos': 'Dois Riachos',
  'estrela de alagoas': 'Estrela de Alagoas',
  'feira grande': 'Feira Grande',
  'feliz deserto': 'Feliz Deserto',
  flexeiras: 'Flexeiras',
  'girau do ponciano': 'Girau do Ponciano',
  ibateguara: 'Ibateguara',
  igaci: 'Igaci',
  'igreja nova': 'Igreja Nova',
  inhapi: 'Inhapi',
  'jacare dos homens': 'Jacaré dos Homens',
  jacuipe: 'Jacuípe',
  japaratinga: 'Japaratinga',
  jaramataia: 'Jaramataia',
  'jequia da praia': 'Jequiá da Praia',
  'joaquim gomes': 'Joaquim Gomes',
  jundia: 'Jundiá',
  junqueiro: 'Junqueiro',
  'lagoa da canoa': 'Lagoa da Canoa',
  'limoeiro de anadia': 'Limoeiro de Anadia',
  maceio: 'Maceió',
  'major izidoro': 'Major Izidoro',
  maragogi: 'Maragogi',
  maravilha: 'Maravilha',
  'marechal deodoro': 'Marechal Deodoro',
  maribondo: 'Maribondo',
  'mar vermelho': 'Mar Vermelho',
  'mata grande': 'Mata Grande',
  'matriz de camaragibe': 'Matriz de Camaragibe',
  messias: 'Messias',
  'minador do negrao': 'Minador do Negrão',
  monteiropolis: 'Monteirópolis',
  murici: 'Murici',
  'novo lino': 'Novo Lino',
  "olho d'agua das flores": "Olho d'Água das Flores",
  "olho d'agua do casado": "Olho d'Água do Casado",
  "olho d'agua grande": "Olho d'Água Grande",
  olivenca: 'Olivença',
  'ouro branco': 'Ouro Branco',
  palestina: 'Palestina',
  'palmeira dos indios': 'Palmeira dos Índios',
  'pao de acucar': 'Pão de Açúcar',
  pariconha: 'Pariconha',
  paripueira: 'Paripueira',
  'passo de camaragibe': 'Passo de Camaragibe',
  'paulo jacinto': 'Paulo Jacinto',
  penedo: 'Penedo',
  piacabucu: 'Piaçabuçu',
  pilar: 'Pilar',
  pindoba: 'Pindoba',
  piranhas: 'Piranhas',
  'poco das trincheiras': 'Poço das Trincheiras',
  'porto calvo': 'Porto Calvo',
  'porto de pedras': 'Porto de Pedras',
  'porto real do colegio': 'Porto Real do Colégio',
  quebrangulo: 'Quebrangulo',
  'rio largo': 'Rio Largo',
  roteiro: 'Roteiro',
  'santa luzia do norte': 'Santa Luzia do Norte',
  'santana do ipanema': 'Santana do Ipanema',
  'santana do mundau': 'Santana do Mundaú',
  'sao bras': 'São Brás',
  'sao jose da laje': 'São José da Laje',
  'sao jose da tapera': 'São José da Tapera',
  'sao luis do quitunde': 'São Luís do Quitunde',
  'sao miguel dos campos': 'São Miguel dos Campos',
  'sao miguel dos milagres': 'São Miguel dos Milagres',
  'sao sebastiao': 'São Sebastião',
  satuba: 'Satuba',
  'senador rui palmeira': 'Senador Rui Palmeira',
  "tanque d'arca": "Tanque d'Arca",
  taquarana: 'Taquarana',
  'teotonio vilela': 'Teotônio Vilela',
  traipu: 'Traipu',
  'uniao dos palmares': 'União dos Palmares',
  vicosa: 'Viçosa',
};
