export const cities = {
  'agua branca': { name: 'Água Branca', state: 'AL' },
  anadia: { name: 'Anadia', state: 'AL' },
  arapiraca: { name: 'Arapiraca', state: 'AL' },
  atalaia: { name: 'Atalaia', state: 'AL' },
  'barra de santo antonio': { name: 'Barra de Santo Antônio', state: 'AL' },
  'barra de sao miguel': { name: 'Barra de São Miguel', state: 'AL' },
  batalha: { name: 'Batalha', state: 'AL' },
  belem: { name: 'Belém', state: 'AL' },
  'belo monte': { name: 'Belo Monte', state: 'AL' },
  'boca da mata': { name: 'Boca da Mata', state: 'AL' },
  branquinha: { name: 'Branquinha', state: 'AL' },
  cacimbinhas: { name: 'Cacimbinhas', state: 'AL' },
  cajueiro: { name: 'Cajueiro', state: 'AL' },
  campestre: { name: 'Campestre', state: 'AL' },
  'campo alegre': { name: 'Campo Alegre', state: 'AL' },
  'campo grande': { name: 'Campo Grande', state: 'AL' },
  canapi: { name: 'Canapi', state: 'AL' },
  capela: { name: 'Capela', state: 'AL' },
  carneiros: { name: 'Carneiros', state: 'AL' },
  'cha preta': { name: 'Chã Preta', state: 'AL' },
  'coite do noia': { name: 'Coité do Noia', state: 'AL' },
  'colonia leopoldina': { name: 'Colônia Leopoldina', state: 'AL' },
  'coqueiro seco': { name: 'Coqueiro Seco', state: 'AL' },
  coruripe: { name: 'Coruripe', state: 'AL' },
  craibas: { name: 'Craíbas', state: 'AL' },
  'delmiro gouveia': { name: 'Delmiro Gouveia', state: 'AL' },
  'dois riachos': { name: 'Dois Riachos', state: 'AL' },
  'estrela de alagoas': { name: 'Estrela de Alagoas', state: 'AL' },
  'feira grande': { name: 'Feira Grande', state: 'AL' },
  'feliz deserto': { name: 'Feliz Deserto', state: 'AL' },
  flexeiras: { name: 'Flexeiras', state: 'AL' },
  'girau do ponciano': { name: 'Girau do Ponciano', state: 'AL' },
  ibateguara: { name: 'Ibateguara', state: 'AL' },
  igaci: { name: 'Igaci', state: 'AL' },
  'igreja nova': { name: 'Igreja Nova', state: 'AL' },
  inhapi: { name: 'Inhapi', state: 'AL' },
  'jacare dos homens': { name: 'Jacaré dos Homens', state: 'AL' },
  jacuipe: { name: 'Jacuípe', state: 'AL' },
  japaratinga: { name: 'Japaratinga', state: 'AL' },
  jaramataia: { name: 'Jaramataia', state: 'AL' },
  'jequia da praia': { name: 'Jequiá da Praia', state: 'AL' },
  'joaquim gomes': { name: 'Joaquim Gomes', state: 'AL' },
  jundia: { name: 'Jundiá', state: 'AL' },
  junqueiro: { name: 'Junqueiro', state: 'AL' },
  'lagoa da canoa': { name: 'Lagoa da Canoa', state: 'AL' },
  'limoeiro de anadia': { name: 'Limoeiro de Anadia', state: 'AL' },
  maceio: { name: 'Maceió', state: 'AL' },
  'major izidoro': { name: 'Major Izidoro', state: 'AL' },
  maragogi: { name: 'Maragogi', state: 'AL' },
  maravilha: { name: 'Maravilha', state: 'AL' },
  'marechal deodoro': { name: 'Marechal Deodoro', state: 'AL' },
  maribondo: { name: 'Maribondo', state: 'AL' },
  'mar vermelho': { name: 'Mar Vermelho', state: 'AL' },
  'mata grande': { name: 'Mata Grande', state: 'AL' },
  'matriz de camaragibe': { name: 'Matriz de Camaragibe', state: 'AL' },
  messias: { name: 'Messias', state: 'AL' },
  'minador do negrao': { name: 'Minador do Negrão', state: 'AL' },
  monteiropolis: { name: 'Monteirópolis', state: 'AL' },
  murici: { name: 'Murici', state: 'AL' },
  'novo lino': { name: 'Novo Lino', state: 'AL' },
  "olho d'agua das flores": { name: "Olho d'Água das Flores", state: 'AL' },
  "olho d'agua do casado": { name: "Olho d'Água do Casado", state: 'AL' },
  "olho d'agua grande": { name: "Olho d'Água Grande", state: 'AL' },
  olivenca: { name: 'Olivença', state: 'AL' },
  'ouro branco': { name: 'Ouro Branco', state: 'AL' },
  palestina: { name: 'Palestina', state: 'AL' },
  'palmeira dos indios': { name: 'Palmeira dos Índios', state: 'AL' },
  'pao de acucar': { name: 'Pão de Açúcar', state: 'AL' },
  pariconha: { name: 'Pariconha', state: 'AL' },
  paripueira: { name: 'Paripueira', state: 'AL' },
  'passo de camaragibe': { name: 'Passo de Camaragibe', state: 'AL' },
  'paulo jacinto': { name: 'Paulo Jacinto', state: 'AL' },
  penedo: { name: 'Penedo', state: 'AL' },
  piacabucu: { name: 'Piaçabuçu', state: 'AL' },
  pilar: { name: 'Pilar', state: 'AL' },
  pindoba: { name: 'Pindoba', state: 'AL' },
  piranhas: { name: 'Piranhas', state: 'AL' },
  'poco das trincheiras': { name: 'Poço das Trincheiras', state: 'AL' },
  'porto calvo': { name: 'Porto Calvo', state: 'AL' },
  'porto de pedras': { name: 'Porto de Pedras', state: 'AL' },
  'porto real do colegio': { name: 'Porto Real do Colégio', state: 'AL' },
  quebrangulo: { name: 'Quebrangulo', state: 'AL' },
  'rio largo': { name: 'Rio Largo', state: 'AL' },
  roteiro: { name: 'Roteiro', state: 'AL' },
  'santa luzia do norte': { name: 'Santa Luzia do Norte', state: 'AL' },
  'santana do ipanema': { name: 'Santana do Ipanema', state: 'AL' },
  'santana do mundau': { name: 'Santana do Mundaú', state: 'AL' },
  'sao bras': { name: 'São Brás', state: 'AL' },
  'sao jose da laje': { name: 'São José da Laje', state: 'AL' },
  'sao jose da tapera': { name: 'São José da Tapera', state: 'AL' },
  'sao luis do quitunde': { name: 'São Luís do Quitunde', state: 'AL' },
  'sao miguel dos campos': { name: 'São Miguel dos Campos', state: 'AL' },
  'sao miguel dos milagres': { name: 'São Miguel dos Milagres', state: 'AL' },
  'sao sebastiao': { name: 'São Sebastião', state: 'AL' },
  satuba: { name: 'Satuba', state: 'AL' },
  'senador rui palmeira': { name: 'Senador Rui Palmeira', state: 'AL' },
  "tanque d'arca": { name: "Tanque d'Arca", state: 'AL' },
  taquarana: { name: 'Taquarana', state: 'AL' },
  'teotonio vilela': { name: 'Teotônio Vilela', state: 'AL' },
  traipu: { name: 'Traipu', state: 'AL' },
  'uniao dos palmares': { name: 'União dos Palmares', state: 'AL' },
  vicosa: { name: 'Viçosa', state: 'AL' },
};
