export const cities = {
  alvaraes: 'Alvarães',
  amatura: 'Amaturá',
  anama: 'Anamã',
  anori: 'Anori',
  apui: 'Apuí',
  'atalaia do norte': 'Atalaia do Norte',
  autazes: 'Autazes',
  barcelos: 'Barcelos',
  barreirinha: 'Barreirinha',
  'benjamin constant': 'Benjamin Constant',
  beruri: 'Beruri',
  'boa vista do ramos': 'Boa Vista do Ramos',
  'boca do acre': 'Boca do Acre',
  borba: 'Borba',
  caapiranga: 'Caapiranga',
  canutama: 'Canutama',
  carauari: 'Carauari',
  careiro: 'Careiro',
  'careiro da varzea': 'Careiro da Várzea',
  coari: 'Coari',
  codajas: 'Codajás',
  eirunepe: 'Eirunepé',
  envira: 'Envira',
  'fonte boa': 'Fonte Boa',
  guajara: 'Guajará',
  humaita: 'Humaitá',
  ipixuna: 'Ipixuna',
  iranduba: 'Iranduba',
  itacoatiara: 'Itacoatiara',
  itamarati: 'Itamarati',
  itapiranga: 'Itapiranga',
  japura: 'Japurá',
  jurua: 'Juruá',
  jutai: 'Jutaí',
  labrea: 'Lábrea',
  manacapuru: 'Manacapuru',
  manaquiri: 'Manaquiri',
  manaus: 'Manaus',
  manicore: 'Manicoré',
  maraa: 'Maraã',
  maues: 'Maués',
  nhamunda: 'Nhamundá',
  'nova olinda do norte': 'Nova Olinda do Norte',
  'novo aripuana': 'Novo Aripuanã',
  'novo airao': 'Novo Airão',
  parintins: 'Parintins',
  pauini: 'Pauini',
  'presidente figueiredo': 'Presidente Figueiredo',
  'rio preto da eva': 'Rio Preto da Eva',
  'santa isabel do rio negro': 'Santa Isabel do Rio Negro',
  'santo antonio do ica': 'Santo Antônio do Içá',
  'sao gabriel da cachoeira': 'São Gabriel da Cachoeira',
  'sao paulo de olivenca': 'São Paulo de Olivença',
  'sao sebastiao do uatuma': 'São Sebastião do Uatumã',
  silves: 'Silves',
  tabatinga: 'Tabatinga',
  tapaua: 'Tapauá',
  tefe: 'Tefé',
  tonantins: 'Tonantins',
  uarini: 'Uarini',
  urucara: 'Urucará',
  urucurituba: 'Urucurituba',
};
