export const cities = {
  amapa: 'Amapá',
  calcoene: 'Calçoene',
  cutias: 'Cutias',
  'ferreira gomes': 'Ferreira Gomes',
  itaubal: 'Itaubal',
  'laranjal do jari': 'Laranjal do Jari',
  macapa: 'Macapá',
  mazagao: 'Mazagão',
  oiapoque: 'Oiapoque',
  'pedra branca do amapari': 'Pedra Branca do Amapari',
  'porto grande': 'Porto Grande',
  pracuuba: 'Pracuúba',
  santana: 'Santana',
  'serra do navio': 'Serra do Navio',
  tartarugalzinho: 'Tartarugalzinho',
  'vitoria do jari': 'Vitória do Jari',
};
