export const cities = {
  abaira: { name: 'Abaíra', state: 'BA' },
  abare: { name: 'Abaré', state: 'BA' },
  acajutiba: { name: 'Acajutiba', state: 'BA' },
  adustina: { name: 'Adustina', state: 'BA' },
  'agua fria': { name: 'Água Fria', state: 'BA' },
  aiquara: { name: 'Aiquara', state: 'BA' },
  alagoinhas: { name: 'Alagoinhas', state: 'BA' },
  alcobaca: { name: 'Alcobaça', state: 'BA' },
  almadina: { name: 'Almadina', state: 'BA' },
  amargosa: { name: 'Amargosa', state: 'BA' },
  'amelia rodrigues': { name: 'Amélia Rodrigues', state: 'BA' },
  'america dourada': { name: 'América Dourada', state: 'BA' },
  anage: { name: 'Anagé', state: 'BA' },
  andarai: { name: 'Andaraí', state: 'BA' },
  andorinha: { name: 'Andorinha', state: 'BA' },
  angical: { name: 'Angical', state: 'BA' },
  anguera: { name: 'Anguera', state: 'BA' },
  antas: { name: 'Antas', state: 'BA' },
  'antonio cardoso': { name: 'Antônio Cardoso', state: 'BA' },
  'antonio goncalves': { name: 'Antônio Gonçalves', state: 'BA' },
  apora: { name: 'Aporá', state: 'BA' },
  apuarema: { name: 'Apuarema', state: 'BA' },
  aracas: { name: 'Araçás', state: 'BA' },
  aracatu: { name: 'Aracatu', state: 'BA' },
  araci: { name: 'Araci', state: 'BA' },
  aramari: { name: 'Aramari', state: 'BA' },
  arataca: { name: 'Arataca', state: 'BA' },
  aratuipe: { name: 'Aratuípe', state: 'BA' },
  'aurelino leal': { name: 'Aurelino Leal', state: 'BA' },
  baianopolis: { name: 'Baianópolis', state: 'BA' },
  'baixa grande': { name: 'Baixa Grande', state: 'BA' },
  banzae: { name: 'Banzaê', state: 'BA' },
  barra: { name: 'Barra', state: 'BA' },
  'barra da estiva': { name: 'Barra da Estiva', state: 'BA' },
  'barra do choca': { name: 'Barra do Choça', state: 'BA' },
  'barra do mendes': { name: 'Barra do Mendes', state: 'BA' },
  'barra do rocha': { name: 'Barra do Rocha', state: 'BA' },
  barreiras: { name: 'Barreiras', state: 'BA' },
  'barro alto': { name: 'Barro Alto', state: 'BA' },
  barrocas: { name: 'Barrocas', state: 'BA' },
  'barro preto': { name: 'Barro Preto', state: 'BA' },
  belmonte: { name: 'Belmonte', state: 'BA' },
  'belo campo': { name: 'Belo Campo', state: 'BA' },
  biritinga: { name: 'Biritinga', state: 'BA' },
  'boa nova': { name: 'Boa Nova', state: 'BA' },
  'boa vista do tupim': { name: 'Boa Vista do Tupim', state: 'BA' },
  'bom jesus da lapa': { name: 'Bom Jesus da Lapa', state: 'BA' },
  'bom jesus da serra': { name: 'Bom Jesus da Serra', state: 'BA' },
  boninal: { name: 'Boninal', state: 'BA' },
  bonito: { name: 'Bonito', state: 'BA' },
  boquira: { name: 'Boquira', state: 'BA' },
  botupora: { name: 'Botuporã', state: 'BA' },
  brejoes: { name: 'Brejões', state: 'BA' },
  brejolandia: { name: 'Brejolândia', state: 'BA' },
  'brotas de macaubas': { name: 'Brotas de Macaúbas', state: 'BA' },
  brumado: { name: 'Brumado', state: 'BA' },
  buerarema: { name: 'Buerarema', state: 'BA' },
  buritirama: { name: 'Buritirama', state: 'BA' },
  caatiba: { name: 'Caatiba', state: 'BA' },
  'cabaceiras do paraguacu': { name: 'Cabaceiras do Paraguaçu', state: 'BA' },
  cachoeira: { name: 'Cachoeira', state: 'BA' },
  cacule: { name: 'Caculé', state: 'BA' },
  caem: { name: 'Caém', state: 'BA' },
  caetanos: { name: 'Caetanos', state: 'BA' },
  caetite: { name: 'Caetité', state: 'BA' },
  cafarnaum: { name: 'Cafarnaum', state: 'BA' },
  cairu: { name: 'Cairu', state: 'BA' },
  'caldeirao grande': { name: 'Caldeirão Grande', state: 'BA' },
  camacan: { name: 'Camacan', state: 'BA' },
  camacari: { name: 'Camaçari', state: 'BA' },
  camamu: { name: 'Camamu', state: 'BA' },
  'campo alegre de lourdes': { name: 'Campo Alegre de Lourdes', state: 'BA' },
  'campo formoso': { name: 'Campo Formoso', state: 'BA' },
  canapolis: { name: 'Canápolis', state: 'BA' },
  canarana: { name: 'Canarana', state: 'BA' },
  canavieiras: { name: 'Canavieiras', state: 'BA' },
  candeal: { name: 'Candeal', state: 'BA' },
  candeias: { name: 'Candeias', state: 'BA' },
  candiba: { name: 'Candiba', state: 'BA' },
  'candido sales': { name: 'Cândido Sales', state: 'BA' },
  cansancao: { name: 'Cansanção', state: 'BA' },
  canudos: { name: 'Canudos', state: 'BA' },
  'capela do alto alegre': { name: 'Capela do Alto Alegre', state: 'BA' },
  'capim grosso': { name: 'Capim Grosso', state: 'BA' },
  caraibas: { name: 'Caraíbas', state: 'BA' },
  caravelas: { name: 'Caravelas', state: 'BA' },
  'cardeal da silva': { name: 'Cardeal da Silva', state: 'BA' },
  carinhanha: { name: 'Carinhanha', state: 'BA' },
  'casa nova': { name: 'Casa Nova', state: 'BA' },
  'castro alves': { name: 'Castro Alves', state: 'BA' },
  catolandia: { name: 'Catolândia', state: 'BA' },
  catu: { name: 'Catu', state: 'BA' },
  caturama: { name: 'Caturama', state: 'BA' },
  central: { name: 'Central', state: 'BA' },
  chorrocho: { name: 'Chorrochó', state: 'BA' },
  'cicero dantas': { name: 'Cícero Dantas', state: 'BA' },
  cipo: { name: 'Cipó', state: 'BA' },
  coaraci: { name: 'Coaraci', state: 'BA' },
  cocos: { name: 'Cocos', state: 'BA' },
  'conceicao da feira': { name: 'Conceição da Feira', state: 'BA' },
  'conceicao do almeida': { name: 'Conceição do Almeida', state: 'BA' },
  'conceicao do coite': { name: 'Conceição do Coité', state: 'BA' },
  'conceicao do jacuipe': { name: 'Conceição do Jacuípe', state: 'BA' },
  conde: { name: 'Conde', state: 'BA' },
  condeuba: { name: 'Condeúba', state: 'BA' },
  'contendas do sincora': { name: 'Contendas do Sincorá', state: 'BA' },
  'coracao de maria': { name: 'Coração de Maria', state: 'BA' },
  cordeiros: { name: 'Cordeiros', state: 'BA' },
  coribe: { name: 'Coribe', state: 'BA' },
  'coronel joao sa': { name: 'Coronel João Sá', state: 'BA' },
  correntina: { name: 'Correntina', state: 'BA' },
  cotegipe: { name: 'Cotegipe', state: 'BA' },
  cravolandia: { name: 'Cravolândia', state: 'BA' },
  crisopolis: { name: 'Crisópolis', state: 'BA' },
  cristopolis: { name: 'Cristópolis', state: 'BA' },
  'cruz das almas': { name: 'Cruz das Almas', state: 'BA' },
  curaca: { name: 'Curaçá', state: 'BA' },
  'dario meira': { name: 'Dário Meira', state: 'BA' },
  "dias d'avila": { name: "Dias d'Ávila", state: 'BA' },
  'dom basilio': { name: 'Dom Basílio', state: 'BA' },
  'dom macedo costa': { name: 'Dom Macedo Costa', state: 'BA' },
  'elisio medrado': { name: 'Elísio Medrado', state: 'BA' },
  encruzilhada: { name: 'Encruzilhada', state: 'BA' },
  'entre rios': { name: 'Entre Rios', state: 'BA' },
  'erico cardoso': { name: 'Érico Cardoso', state: 'BA' },
  esplanada: { name: 'Esplanada', state: 'BA' },
  'euclides da cunha': { name: 'Euclides da Cunha', state: 'BA' },
  eunapolis: { name: 'Eunápolis', state: 'BA' },
  fatima: { name: 'Fátima', state: 'BA' },
  'feira da mata': { name: 'Feira da Mata', state: 'BA' },
  'feira de santana': { name: 'Feira de Santana', state: 'BA' },
  filadelfia: { name: 'Filadélfia', state: 'BA' },
  'firmino alves': { name: 'Firmino Alves', state: 'BA' },
  'floresta azul': { name: 'Floresta Azul', state: 'BA' },
  'formosa do rio preto': { name: 'Formosa do Rio Preto', state: 'BA' },
  gandu: { name: 'Gandu', state: 'BA' },
  gaviao: { name: 'Gavião', state: 'BA' },
  'gentio do ouro': { name: 'Gentio do Ouro', state: 'BA' },
  gloria: { name: 'Glória', state: 'BA' },
  gongogi: { name: 'Gongogi', state: 'BA' },
  'governador mangabeira': { name: 'Governador Mangabeira', state: 'BA' },
  guajeru: { name: 'Guajeru', state: 'BA' },
  guanambi: { name: 'Guanambi', state: 'BA' },
  guaratinga: { name: 'Guaratinga', state: 'BA' },
  heliopolis: { name: 'Heliópolis', state: 'BA' },
  iacu: { name: 'Iaçu', state: 'BA' },
  ibiassuce: { name: 'Ibiassucê', state: 'BA' },
  ibicarai: { name: 'Ibicaraí', state: 'BA' },
  ibicoara: { name: 'Ibicoara', state: 'BA' },
  ibicui: { name: 'Ibicuí', state: 'BA' },
  ibipeba: { name: 'Ibipeba', state: 'BA' },
  ibipitanga: { name: 'Ibipitanga', state: 'BA' },
  ibiquera: { name: 'Ibiquera', state: 'BA' },
  ibirapitanga: { name: 'Ibirapitanga', state: 'BA' },
  ibirapua: { name: 'Ibirapuã', state: 'BA' },
  ibirataia: { name: 'Ibirataia', state: 'BA' },
  ibitiara: { name: 'Ibitiara', state: 'BA' },
  ibitita: { name: 'Ibititá', state: 'BA' },
  ibotirama: { name: 'Ibotirama', state: 'BA' },
  ichu: { name: 'Ichu', state: 'BA' },
  igapora: { name: 'Igaporã', state: 'BA' },
  igrapiuna: { name: 'Igrapiúna', state: 'BA' },
  iguai: { name: 'Iguaí', state: 'BA' },
  ilheus: { name: 'Ilhéus', state: 'BA' },
  inhambupe: { name: 'Inhambupe', state: 'BA' },
  ipecaeta: { name: 'Ipecaetá', state: 'BA' },
  ipiau: { name: 'Ipiaú', state: 'BA' },
  ipira_: { name: 'Ipirá', state: 'BA' },
  ipupiara: { name: 'Ipupiara', state: 'BA' },
  irajuba: { name: 'Irajuba', state: 'BA' },
  iramaia: { name: 'Iramaia', state: 'BA' },
  iraquara: { name: 'Iraquara', state: 'BA' },
  irara: { name: 'Irará', state: 'BA' },
  irece: { name: 'Irecê', state: 'BA' },
  itabela: { name: 'Itabela', state: 'BA' },
  itaberaba: { name: 'Itaberaba', state: 'BA' },
  itabuna: { name: 'Itabuna', state: 'BA' },
  itacare: { name: 'Itacaré', state: 'BA' },
  itaete: { name: 'Itaetê', state: 'BA' },
  itagi: { name: 'Itagi', state: 'BA' },
  itagiba: { name: 'Itagibá', state: 'BA' },
  itagimirim: { name: 'Itagimirim', state: 'BA' },
  'itaguacu da bahia': { name: 'Itaguaçu da Bahia', state: 'BA' },
  'itaju do colonia': { name: 'Itaju do Colônia', state: 'BA' },
  itajuipe: { name: 'Itajuípe', state: 'BA' },
  itamaraju: { name: 'Itamaraju', state: 'BA' },
  itamari: { name: 'Itamari', state: 'BA' },
  itambe: { name: 'Itambé', state: 'BA' },
  itanagra: { name: 'Itanagra', state: 'BA' },
  itanhem: { name: 'Itanhém', state: 'BA' },
  itaparica: { name: 'Itaparica', state: 'BA' },
  itape: { name: 'Itapé', state: 'BA' },
  itapebi: { name: 'Itapebi', state: 'BA' },
  itapetinga: { name: 'Itapetinga', state: 'BA' },
  itapicuru: { name: 'Itapicuru', state: 'BA' },
  itapitanga: { name: 'Itapitanga', state: 'BA' },
  itaquara: { name: 'Itaquara', state: 'BA' },
  itarantim: { name: 'Itarantim', state: 'BA' },
  itatim: { name: 'Itatim', state: 'BA' },
  itirucu: { name: 'Itiruçu', state: 'BA' },
  itiuba: { name: 'Itiúba', state: 'BA' },
  itororo: { name: 'Itororó', state: 'BA' },
  ituacu: { name: 'Ituaçu', state: 'BA' },
  itubera: { name: 'Ituberá', state: 'BA' },
  iuiu: { name: 'Iuiú', state: 'BA' },
  jaborandi: { name: 'Jaborandi', state: 'BA' },
  jacaraci: { name: 'Jacaraci', state: 'BA' },
  jacobina: { name: 'Jacobina', state: 'BA' },
  jaguaquara: { name: 'Jaguaquara', state: 'BA' },
  jaguarari: { name: 'Jaguarari', state: 'BA' },
  jaguaripe: { name: 'Jaguaripe', state: 'BA' },
  jandaira: { name: 'Jandaíra', state: 'BA' },
  jequie: { name: 'Jequié', state: 'BA' },
  jeremoabo: { name: 'Jeremoabo', state: 'BA' },
  jiquirica: { name: 'Jiquiriçá', state: 'BA' },
  jitauna: { name: 'Jitaúna', state: 'BA' },
  'joao dourado': { name: 'João Dourado', state: 'BA' },
  juazeiro: { name: 'Juazeiro', state: 'BA' },
  jucurucu: { name: 'Jucuruçu', state: 'BA' },
  jussara: { name: 'Jussara', state: 'BA' },
  jussari: { name: 'Jussari', state: 'BA' },
  jussiape: { name: 'Jussiape', state: 'BA' },
  'lafaiete coutinho': { name: 'Lafaiete Coutinho', state: 'BA' },
  'lagoa real': { name: 'Lagoa Real', state: 'BA' },
  laje: { name: 'Laje', state: 'BA' },
  lajedao: { name: 'Lajedão', state: 'BA' },
  lajedinho: { name: 'Lajedinho', state: 'BA' },
  'lajedo do tabocal': { name: 'Lajedo do Tabocal', state: 'BA' },
  lamarao: { name: 'Lamarão', state: 'BA' },
  lapao: { name: 'Lapão', state: 'BA' },
  'lauro de freitas': { name: 'Lauro de Freitas', state: 'BA' },
  lencois: { name: 'Lençóis', state: 'BA' },
  'licinio de almeida': { name: 'Licínio de Almeida', state: 'BA' },
  'livramento de nossa senhora': { name: 'Livramento de Nossa Senhora', state: 'BA' },
  'luis eduardo magalhaes': { name: 'Luís Eduardo Magalhães', state: 'BA' },
  macajuba: { name: 'Macajuba', state: 'BA' },
  macarani: { name: 'Macarani', state: 'BA' },
  macaubas: { name: 'Macaúbas', state: 'BA' },
  macurure: { name: 'Macururé', state: 'BA' },
  'madre de deus': { name: 'Madre de Deus', state: 'BA' },
  maetinga: { name: 'Maetinga', state: 'BA' },
  maiquinique: { name: 'Maiquinique', state: 'BA' },
  mairi: { name: 'Mairi', state: 'BA' },
  malhada: { name: 'Malhada', state: 'BA' },
  'malhada de pedras': { name: 'Malhada de Pedras', state: 'BA' },
  'manoel vitorino': { name: 'Manoel Vitorino', state: 'BA' },
  mansidao: { name: 'Mansidão', state: 'BA' },
  maracas: { name: 'Maracás', state: 'BA' },
  maragogipe: { name: 'Maragogipe', state: 'BA' },
  marau: { name: 'Maraú', state: 'BA' },
  'marcionilio souza': { name: 'Marcionílio Souza', state: 'BA' },
  mascote: { name: 'Mascote', state: 'BA' },
  'mata de sao joao': { name: 'Mata de São João', state: 'BA' },
  matina: { name: 'Matina', state: 'BA' },
  'medeiros neto': { name: 'Medeiros Neto', state: 'BA' },
  'miguel calmon': { name: 'Miguel Calmon', state: 'BA' },
  milagres: { name: 'Milagres', state: 'BA' },
  mirangaba: { name: 'Mirangaba', state: 'BA' },
  mirante: { name: 'Mirante', state: 'BA' },
  'monte santo': { name: 'Monte Santo', state: 'BA' },
  morpara: { name: 'Morpará', state: 'BA' },
  'morro do chapeu': { name: 'Morro do Chapéu', state: 'BA' },
  mortugaba: { name: 'Mortugaba', state: 'BA' },
  mucuge: { name: 'Mucugê', state: 'BA' },
  mucuri: { name: 'Mucuri', state: 'BA' },
  'mulungu do morro': { name: 'Mulungu do Morro', state: 'BA' },
  'mundo novo': { name: 'Mundo Novo', state: 'BA' },
  'muniz ferreira': { name: 'Muniz Ferreira', state: 'BA' },
  'muquem do sao francisco': { name: 'Muquém do São Francisco', state: 'BA' },
  muritiba: { name: 'Muritiba', state: 'BA' },
  mutuipe: { name: 'Mutuípe', state: 'BA' },
  nazare: { name: 'Nazaré', state: 'BA' },
  'nilo pecanha': { name: 'Nilo Peçanha', state: 'BA' },
  nordestina: { name: 'Nordestina', state: 'BA' },
  'nova canaa': { name: 'Nova Canaã', state: 'BA' },
  'nova fatima': { name: 'Nova Fátima', state: 'BA' },
  'nova ibia': { name: 'Nova Ibiá', state: 'BA' },
  'nova itarana': { name: 'Nova Itarana', state: 'BA' },
  'nova redencao': { name: 'Nova Redenção', state: 'BA' },
  'nova soure': { name: 'Nova Soure', state: 'BA' },
  'nova vicosa': { name: 'Nova Viçosa', state: 'BA' },
  'novo horizonte': { name: 'Novo Horizonte', state: 'BA' },
  'novo triunfo': { name: 'Novo Triunfo', state: 'BA' },
  olindina: { name: 'Olindina', state: 'BA' },
  'oliveira dos brejinhos': { name: 'Oliveira dos Brejinhos', state: 'BA' },
  ouricangas: { name: 'Ouriçangas', state: 'BA' },
  ourolandia: { name: 'Ourolândia', state: 'BA' },
  'palmas de monte alto': { name: 'Palmas de Monte Alto', state: 'BA' },
  palmeiras: { name: 'Palmeiras', state: 'BA' },
  paramirim: { name: 'Paramirim', state: 'BA' },
  paratinga: { name: 'Paratinga', state: 'BA' },
  paripiranga: { name: 'Paripiranga', state: 'BA' },
  'pau brasil': { name: 'Pau Brasil', state: 'BA' },
  'paulo afonso': { name: 'Paulo Afonso', state: 'BA' },
  'pe de serra': { name: 'Pé de Serra', state: 'BA' },
  pedrao: { name: 'Pedrão', state: 'BA' },
  'pedro alexandre': { name: 'Pedro Alexandre', state: 'BA' },
  piata: { name: 'Piatã', state: 'BA' },
  'pilao arcado': { name: 'Pilão Arcado', state: 'BA' },
  pindai: { name: 'Pindaí', state: 'BA' },
  pindobacu: { name: 'Pindobaçu', state: 'BA' },
  pintadas: { name: 'Pintadas', state: 'BA' },
  'pirai do norte': { name: 'Piraí do Norte', state: 'BA' },
  piripa: { name: 'Piripá', state: 'BA' },
  piritiba: { name: 'Piritiba', state: 'BA' },
  planaltino: { name: 'Planaltino', state: 'BA' },
  planalto: { name: 'Planalto', state: 'BA' },
  pocoes: { name: 'Poções', state: 'BA' },
  pojuca: { name: 'Pojuca', state: 'BA' },
  'ponto novo': { name: 'Ponto Novo', state: 'BA' },
  'porto seguro': { name: 'Porto Seguro', state: 'BA' },
  potiragua: { name: 'Potiraguá', state: 'BA' },
  prado: { name: 'Prado', state: 'BA' },
  'presidente dutra': { name: 'Presidente Dutra', state: 'BA' },
  'presidente janio quadros': { name: 'Presidente Jânio Quadros', state: 'BA' },
  'presidente tancredo neves': { name: 'Presidente Tancredo Neves', state: 'BA' },
  queimadas: { name: 'Queimadas', state: 'BA' },
  quijingue: { name: 'Quijingue', state: 'BA' },
  quixabeira: { name: 'Quixabeira', state: 'BA' },
  'rafael jambeiro': { name: 'Rafael Jambeiro', state: 'BA' },
  remanso: { name: 'Remanso', state: 'BA' },
  retirolandia: { name: 'Retirolândia', state: 'BA' },
  'riachao das neves': { name: 'Riachão das Neves', state: 'BA' },
  'riachao do jacuipe': { name: 'Riachão do Jacuípe', state: 'BA' },
  'riacho de santana': { name: 'Riacho de Santana', state: 'BA' },
  'ribeira do amparo': { name: 'Ribeira do Amparo', state: 'BA' },
  'ribeira do pombal': { name: 'Ribeira do Pombal', state: 'BA' },
  'ribeirao do largo': { name: 'Ribeirão do Largo', state: 'BA' },
  'rio de contas': { name: 'Rio de Contas', state: 'BA' },
  'rio do antonio': { name: 'Rio do Antônio', state: 'BA' },
  'rio do pires': { name: 'Rio do Pires', state: 'BA' },
  'rio real': { name: 'Rio Real', state: 'BA' },
  rodelas: { name: 'Rodelas', state: 'BA' },
  'ruy barbosa': { name: 'Ruy Barbosa', state: 'BA' },
  'salinas da margarida': { name: 'Salinas da Margarida', state: 'BA' },
  salvador: { name: 'Salvador', state: 'BA' },
  'santa barbara': { name: 'Santa Bárbara', state: 'BA' },
  'santa brigida': { name: 'Santa Brígida', state: 'BA' },
  'santa cruz cabralia': { name: 'Santa Cruz Cabrália', state: 'BA' },
  'santa cruz da vitoria': { name: 'Santa Cruz da Vitória', state: 'BA' },
  'santa ines': { name: 'Santa Inês', state: 'BA' },
  santaluz: { name: 'Santaluz', state: 'BA' },
  'santa luzia': { name: 'Santa Luzia', state: 'BA' },
  'santa maria da vitoria': { name: 'Santa Maria da Vitória', state: 'BA' },
  santana_: { name: 'Santana', state: 'BA' },
  santanopolis: { name: 'Santanópolis', state: 'BA' },
  'santa rita de cassia': { name: 'Santa Rita de Cássia', state: 'BA' },
  'santa teresinha': { name: 'Santa Teresinha', state: 'BA' },
  'santo amaro': { name: 'Santo Amaro', state: 'BA' },
  'santo antonio de jesus': { name: 'Santo Antônio de Jesus', state: 'BA' },
  'santo estevao': { name: 'Santo Estêvão', state: 'BA' },
  'sao desiderio': { name: 'São Desidério', state: 'BA' },
  'sao domingos': { name: 'São Domingos', state: 'BA' },
  'sao felipe': { name: 'São Felipe', state: 'BA' },
  'sao felix': { name: 'São Félix', state: 'BA' },
  'sao felix do coribe': { name: 'São Félix do Coribe', state: 'BA' },
  'sao francisco do conde': { name: 'São Francisco do Conde', state: 'BA' },
  'sao gabriel': { name: 'São Gabriel', state: 'BA' },
  'sao goncalo dos campos': { name: 'São Gonçalo dos Campos', state: 'BA' },
  'sao jose da vitoria': { name: 'São José da Vitória', state: 'BA' },
  'sao jose do jacuipe': { name: 'São José do Jacuípe', state: 'BA' },
  'sao miguel das matas': { name: 'São Miguel das Matas', state: 'BA' },
  'sao sebastiao do passe': { name: 'São Sebastião do Passé', state: 'BA' },
  sapeacu: { name: 'Sapeaçu', state: 'BA' },
  'satiro dias': { name: 'Sátiro Dias', state: 'BA' },
  saubara: { name: 'Saubara', state: 'BA' },
  saude: { name: 'Saúde', state: 'BA' },
  seabra: { name: 'Seabra', state: 'BA' },
  'sebastiao laranjeiras': { name: 'Sebastião Laranjeiras', state: 'BA' },
  'senhor do bonfim': { name: 'Senhor do Bonfim', state: 'BA' },
  'sento se': { name: 'Sento Sé', state: 'BA' },
  'serra do ramalho': { name: 'Serra do Ramalho', state: 'BA' },
  'serra dourada': { name: 'Serra Dourada', state: 'BA' },
  'serra preta': { name: 'Serra Preta', state: 'BA' },
  serrinha: { name: 'Serrinha', state: 'BA' },
  serrolandia: { name: 'Serrolândia', state: 'BA' },
  'simoes filho': { name: 'Simões Filho', state: 'BA' },
  'sitio do mato': { name: 'Sítio do Mato', state: 'BA' },
  'sitio do quinto': { name: 'Sítio do Quinto', state: 'BA' },
  sobradinho: { name: 'Sobradinho', state: 'BA' },
  'souto soares': { name: 'Souto Soares', state: 'BA' },
  'tabocas do brejo velho': { name: 'Tabocas do Brejo Velho', state: 'BA' },
  tanhacu: { name: 'Tanhaçu', state: 'BA' },
  'tanque novo': { name: 'Tanque Novo', state: 'BA' },
  tanquinho: { name: 'Tanquinho', state: 'BA' },
  taperoa: { name: 'Taperoá', state: 'BA' },
  tapiramuta: { name: 'Tapiramutá', state: 'BA' },
  'teixeira de freitas': { name: 'Teixeira de Freitas', state: 'BA' },
  'teodoro sampaio': { name: 'Teodoro Sampaio', state: 'BA' },
  teofilandia: { name: 'Teofilândia', state: 'BA' },
  teolandia: { name: 'Teolândia', state: 'BA' },
  'terra nova': { name: 'Terra Nova', state: 'BA' },
  tremedal: { name: 'Tremedal', state: 'BA' },
  tucano: { name: 'Tucano', state: 'BA' },
  uaua: { name: 'Uauá', state: 'BA' },
  ubaira: { name: 'Ubaíra', state: 'BA' },
  ubaitaba: { name: 'Ubaitaba', state: 'BA' },
  ubata: { name: 'Ubatã', state: 'BA' },
  uibai: { name: 'Uibaí', state: 'BA' },
  umburanas: { name: 'Umburanas', state: 'BA' },
  una: { name: 'Una', state: 'BA' },
  urandi: { name: 'Urandi', state: 'BA' },
  urucuca: { name: 'Uruçuca', state: 'BA' },
  utinga: { name: 'Utinga', state: 'BA' },
  valenca: { name: 'Valença', state: 'BA' },
  valente: { name: 'Valente', state: 'BA' },
  'varzea da roca': { name: 'Várzea da Roça', state: 'BA' },
  'varzea do poco': { name: 'Várzea do Poço', state: 'BA' },
  'varzea nova': { name: 'Várzea Nova', state: 'BA' },
  varzedo: { name: 'Varzedo', state: 'BA' },
  'vera cruz': { name: 'Vera Cruz', state: 'BA' },
  vereda: { name: 'Vereda', state: 'BA' },
  'vitoria da conquista': { name: 'Vitória da Conquista', state: 'BA' },
  wagner: { name: 'Wagner', state: 'BA' },
  wanderley: { name: 'Wanderley', state: 'BA' },
  'wenceslau guimaraes': { name: 'Wenceslau Guimarães', state: 'BA' },
  'xique-xique': { name: 'Xique-Xique', state: 'BA' },
};
