export const cities = {
  abaira: 'Abaíra',
  abare: 'Abaré',
  acajutiba: 'Acajutiba',
  adustina: 'Adustina',
  'agua fria': 'Água Fria',
  aiquara: 'Aiquara',
  alagoinhas: 'Alagoinhas',
  alcobaca: 'Alcobaça',
  almadina: 'Almadina',
  amargosa: 'Amargosa',
  'amelia rodrigues': 'Amélia Rodrigues',
  'america dourada': 'América Dourada',
  anage: 'Anagé',
  andarai: 'Andaraí',
  andorinha: 'Andorinha',
  angical: 'Angical',
  anguera: 'Anguera',
  antas: 'Antas',
  'antonio cardoso': 'Antônio Cardoso',
  'antonio goncalves': 'Antônio Gonçalves',
  apora: 'Aporá',
  apuarema: 'Apuarema',
  aracas: 'Araçás',
  aracatu: 'Aracatu',
  araci: 'Araci',
  aramari: 'Aramari',
  arataca: 'Arataca',
  aratuipe: 'Aratuípe',
  'aurelino leal': 'Aurelino Leal',
  baianopolis: 'Baianópolis',
  'baixa grande': 'Baixa Grande',
  banzae: 'Banzaê',
  barra: 'Barra',
  'barra da estiva': 'Barra da Estiva',
  'barra do choca': 'Barra do Choça',
  'barra do mendes': 'Barra do Mendes',
  'barra do rocha': 'Barra do Rocha',
  barreiras: 'Barreiras',
  'barro alto': 'Barro Alto',
  barrocas: 'Barrocas',
  'barro preto': 'Barro Preto',
  belmonte: 'Belmonte',
  'belo campo': 'Belo Campo',
  biritinga: 'Biritinga',
  'boa nova': 'Boa Nova',
  'boa vista do tupim': 'Boa Vista do Tupim',
  'bom jesus da lapa': 'Bom Jesus da Lapa',
  'bom jesus da serra': 'Bom Jesus da Serra',
  boninal: 'Boninal',
  bonito: 'Bonito',
  boquira: 'Boquira',
  botupora: 'Botuporã',
  brejoes: 'Brejões',
  brejolandia: 'Brejolândia',
  'brotas de macaubas': 'Brotas de Macaúbas',
  brumado: 'Brumado',
  buerarema: 'Buerarema',
  buritirama: 'Buritirama',
  caatiba: 'Caatiba',
  'cabaceiras do paraguacu': 'Cabaceiras do Paraguaçu',
  cachoeira: 'Cachoeira',
  cacule: 'Caculé',
  caem: 'Caém',
  caetanos: 'Caetanos',
  caetite: 'Caetité',
  cafarnaum: 'Cafarnaum',
  cairu: 'Cairu',
  'caldeirao grande': 'Caldeirão Grande',
  camacan: 'Camacan',
  camacari: 'Camaçari',
  camamu: 'Camamu',
  'campo alegre de lourdes': 'Campo Alegre de Lourdes',
  'campo formoso': 'Campo Formoso',
  canapolis: 'Canápolis',
  canarana: 'Canarana',
  canavieiras: 'Canavieiras',
  candeal: 'Candeal',
  candeias: 'Candeias',
  candiba: 'Candiba',
  'candido sales': 'Cândido Sales',
  cansancao: 'Cansanção',
  canudos: 'Canudos',
  'capela do alto alegre': 'Capela do Alto Alegre',
  'capim grosso': 'Capim Grosso',
  caraibas: 'Caraíbas',
  caravelas: 'Caravelas',
  'cardeal da silva': 'Cardeal da Silva',
  carinhanha: 'Carinhanha',
  'casa nova': 'Casa Nova',
  'castro alves': 'Castro Alves',
  catolandia: 'Catolândia',
  catu: 'Catu',
  caturama: 'Caturama',
  central: 'Central',
  chorrocho: 'Chorrochó',
  'cicero dantas': 'Cícero Dantas',
  cipo: 'Cipó',
  coaraci: 'Coaraci',
  cocos: 'Cocos',
  'conceicao da feira': 'Conceição da Feira',
  'conceicao do almeida': 'Conceição do Almeida',
  'conceicao do coite': 'Conceição do Coité',
  'conceicao do jacuipe': 'Conceição do Jacuípe',
  conde: 'Conde',
  condeuba: 'Condeúba',
  'contendas do sincora': 'Contendas do Sincorá',
  'coracao de maria': 'Coração de Maria',
  cordeiros: 'Cordeiros',
  coribe: 'Coribe',
  'coronel joao sa': 'Coronel João Sá',
  correntina: 'Correntina',
  cotegipe: 'Cotegipe',
  cravolandia: 'Cravolândia',
  crisopolis: 'Crisópolis',
  cristopolis: 'Cristópolis',
  'cruz das almas': 'Cruz das Almas',
  curaca: 'Curaçá',
  'dario meira': 'Dário Meira',
  "dias d'avila": "Dias d'Ávila",
  'dom basilio': 'Dom Basílio',
  'dom macedo costa': 'Dom Macedo Costa',
  'elisio medrado': 'Elísio Medrado',
  encruzilhada: 'Encruzilhada',
  'entre rios': 'Entre Rios',
  'erico cardoso': 'Érico Cardoso',
  esplanada: 'Esplanada',
  'euclides da cunha': 'Euclides da Cunha',
  eunapolis: 'Eunápolis',
  fatima: 'Fátima',
  'feira da mata': 'Feira da Mata',
  'feira de santana': 'Feira de Santana',
  filadelfia: 'Filadélfia',
  'firmino alves': 'Firmino Alves',
  'floresta azul': 'Floresta Azul',
  'formosa do rio preto': 'Formosa do Rio Preto',
  gandu: 'Gandu',
  gaviao: 'Gavião',
  'gentio do ouro': 'Gentio do Ouro',
  gloria: 'Glória',
  gongogi: 'Gongogi',
  'governador mangabeira': 'Governador Mangabeira',
  guajeru: 'Guajeru',
  guanambi: 'Guanambi',
  guaratinga: 'Guaratinga',
  heliopolis: 'Heliópolis',
  iacu: 'Iaçu',
  ibiassuce: 'Ibiassucê',
  ibicarai: 'Ibicaraí',
  ibicoara: 'Ibicoara',
  ibicui: 'Ibicuí',
  ibipeba: 'Ibipeba',
  ibipitanga: 'Ibipitanga',
  ibiquera: 'Ibiquera',
  ibirapitanga: 'Ibirapitanga',
  ibirapua: 'Ibirapuã',
  ibirataia: 'Ibirataia',
  ibitiara: 'Ibitiara',
  ibitita: 'Ibititá',
  ibotirama: 'Ibotirama',
  ichu: 'Ichu',
  igapora: 'Igaporã',
  igrapiuna: 'Igrapiúna',
  iguai: 'Iguaí',
  ilheus: 'Ilhéus',
  inhambupe: 'Inhambupe',
  ipecaeta: 'Ipecaetá',
  ipiau: 'Ipiaú',
  ipira_: 'Ipirá',
  ipupiara: 'Ipupiara',
  irajuba: 'Irajuba',
  iramaia: 'Iramaia',
  iraquara: 'Iraquara',
  irara: 'Irará',
  irece: 'Irecê',
  itabela: 'Itabela',
  itaberaba: 'Itaberaba',
  itabuna: 'Itabuna',
  itacare: 'Itacaré',
  itaete: 'Itaetê',
  itagi: 'Itagi',
  itagiba: 'Itagibá',
  itagimirim: 'Itagimirim',
  'itaguacu da bahia': 'Itaguaçu da Bahia',
  'itaju do colonia': 'Itaju do Colônia',
  itajuipe: 'Itajuípe',
  itamaraju: 'Itamaraju',
  itamari: 'Itamari',
  itambe: 'Itambé',
  itanagra: 'Itanagra',
  itanhem: 'Itanhém',
  itaparica: 'Itaparica',
  itape: 'Itapé',
  itapebi: 'Itapebi',
  itapetinga: 'Itapetinga',
  itapicuru: 'Itapicuru',
  itapitanga: 'Itapitanga',
  itaquara: 'Itaquara',
  itarantim: 'Itarantim',
  itatim: 'Itatim',
  itirucu: 'Itiruçu',
  itiuba: 'Itiúba',
  itororo: 'Itororó',
  ituacu: 'Ituaçu',
  itubera: 'Ituberá',
  iuiu: 'Iuiú',
  jaborandi: 'Jaborandi',
  jacaraci: 'Jacaraci',
  jacobina: 'Jacobina',
  jaguaquara: 'Jaguaquara',
  jaguarari: 'Jaguarari',
  jaguaripe: 'Jaguaripe',
  jandaira: 'Jandaíra',
  jequie: 'Jequié',
  jeremoabo: 'Jeremoabo',
  jiquirica: 'Jiquiriçá',
  jitauna: 'Jitaúna',
  'joao dourado': 'João Dourado',
  juazeiro: 'Juazeiro',
  jucurucu: 'Jucuruçu',
  jussara: 'Jussara',
  jussari: 'Jussari',
  jussiape: 'Jussiape',
  'lafaiete coutinho': 'Lafaiete Coutinho',
  'lagoa real': 'Lagoa Real',
  laje: 'Laje',
  lajedao: 'Lajedão',
  lajedinho: 'Lajedinho',
  'lajedo do tabocal': 'Lajedo do Tabocal',
  lamarao: 'Lamarão',
  lapao: 'Lapão',
  'lauro de freitas': 'Lauro de Freitas',
  lencois: 'Lençóis',
  'licinio de almeida': 'Licínio de Almeida',
  'livramento de nossa senhora': 'Livramento de Nossa Senhora',
  'luis eduardo magalhaes': 'Luís Eduardo Magalhães',
  macajuba: 'Macajuba',
  macarani: 'Macarani',
  macaubas: 'Macaúbas',
  macurure: 'Macururé',
  'madre de deus': 'Madre de Deus',
  maetinga: 'Maetinga',
  maiquinique: 'Maiquinique',
  mairi: 'Mairi',
  malhada: 'Malhada',
  'malhada de pedras': 'Malhada de Pedras',
  'manoel vitorino': 'Manoel Vitorino',
  mansidao: 'Mansidão',
  maracas: 'Maracás',
  maragogipe: 'Maragogipe',
  marau: 'Maraú',
  'marcionilio souza': 'Marcionílio Souza',
  mascote: 'Mascote',
  'mata de sao joao': 'Mata de São João',
  matina: 'Matina',
  'medeiros neto': 'Medeiros Neto',
  'miguel calmon': 'Miguel Calmon',
  milagres: 'Milagres',
  mirangaba: 'Mirangaba',
  mirante: 'Mirante',
  'monte santo': 'Monte Santo',
  morpara: 'Morpará',
  'morro do chapeu': 'Morro do Chapéu',
  mortugaba: 'Mortugaba',
  mucuge: 'Mucugê',
  mucuri: 'Mucuri',
  'mulungu do morro': 'Mulungu do Morro',
  'mundo novo': 'Mundo Novo',
  'muniz ferreira': 'Muniz Ferreira',
  'muquem do sao francisco': 'Muquém do São Francisco',
  muritiba: 'Muritiba',
  mutuipe: 'Mutuípe',
  nazare: 'Nazaré',
  'nilo pecanha': 'Nilo Peçanha',
  nordestina: 'Nordestina',
  'nova canaa': 'Nova Canaã',
  'nova fatima': 'Nova Fátima',
  'nova ibia': 'Nova Ibiá',
  'nova itarana': 'Nova Itarana',
  'nova redencao': 'Nova Redenção',
  'nova soure': 'Nova Soure',
  'nova vicosa': 'Nova Viçosa',
  'novo horizonte': 'Novo Horizonte',
  'novo triunfo': 'Novo Triunfo',
  olindina: 'Olindina',
  'oliveira dos brejinhos': 'Oliveira dos Brejinhos',
  ouricangas: 'Ouriçangas',
  ourolandia: 'Ourolândia',
  'palmas de monte alto': 'Palmas de Monte Alto',
  palmeiras: 'Palmeiras',
  paramirim: 'Paramirim',
  paratinga: 'Paratinga',
  paripiranga: 'Paripiranga',
  'pau brasil': 'Pau Brasil',
  'paulo afonso': 'Paulo Afonso',
  'pe de serra': 'Pé de Serra',
  pedrao: 'Pedrão',
  'pedro alexandre': 'Pedro Alexandre',
  piata: 'Piatã',
  'pilao arcado': 'Pilão Arcado',
  pindai: 'Pindaí',
  pindobacu: 'Pindobaçu',
  pintadas: 'Pintadas',
  'pirai do norte': 'Piraí do Norte',
  piripa: 'Piripá',
  piritiba: 'Piritiba',
  planaltino: 'Planaltino',
  planalto: 'Planalto',
  pocoes: 'Poções',
  pojuca: 'Pojuca',
  'ponto novo': 'Ponto Novo',
  'porto seguro': 'Porto Seguro',
  potiragua: 'Potiraguá',
  prado: 'Prado',
  'presidente dutra': 'Presidente Dutra',
  'presidente janio quadros': 'Presidente Jânio Quadros',
  'presidente tancredo neves': 'Presidente Tancredo Neves',
  queimadas: 'Queimadas',
  quijingue: 'Quijingue',
  quixabeira: 'Quixabeira',
  'rafael jambeiro': 'Rafael Jambeiro',
  remanso: 'Remanso',
  retirolandia: 'Retirolândia',
  'riachao das neves': 'Riachão das Neves',
  'riachao do jacuipe': 'Riachão do Jacuípe',
  'riacho de santana': 'Riacho de Santana',
  'ribeira do amparo': 'Ribeira do Amparo',
  'ribeira do pombal': 'Ribeira do Pombal',
  'ribeirao do largo': 'Ribeirão do Largo',
  'rio de contas': 'Rio de Contas',
  'rio do antonio': 'Rio do Antônio',
  'rio do pires': 'Rio do Pires',
  'rio real': 'Rio Real',
  rodelas: 'Rodelas',
  'ruy barbosa': 'Ruy Barbosa',
  'salinas da margarida': 'Salinas da Margarida',
  salvador: 'Salvador',
  'santa barbara': 'Santa Bárbara',
  'santa brigida': 'Santa Brígida',
  'santa cruz cabralia': 'Santa Cruz Cabrália',
  'santa cruz da vitoria': 'Santa Cruz da Vitória',
  'santa ines': 'Santa Inês',
  santaluz: 'Santaluz',
  'santa luzia': 'Santa Luzia',
  'santa maria da vitoria': 'Santa Maria da Vitória',
  santana_: 'Santana',
  santanopolis: 'Santanópolis',
  'santa rita de cassia': 'Santa Rita de Cássia',
  'santa teresinha': 'Santa Teresinha',
  'santo amaro': 'Santo Amaro',
  'santo antonio de jesus': 'Santo Antônio de Jesus',
  'santo estevao': 'Santo Estêvão',
  'sao desiderio': 'São Desidério',
  'sao domingos': 'São Domingos',
  'sao felipe': 'São Felipe',
  'sao felix': 'São Félix',
  'sao felix do coribe': 'São Félix do Coribe',
  'sao francisco do conde': 'São Francisco do Conde',
  'sao gabriel': 'São Gabriel',
  'sao goncalo dos campos': 'São Gonçalo dos Campos',
  'sao jose da vitoria': 'São José da Vitória',
  'sao jose do jacuipe': 'São José do Jacuípe',
  'sao miguel das matas': 'São Miguel das Matas',
  'sao sebastiao do passe': 'São Sebastião do Passé',
  sapeacu: 'Sapeaçu',
  'satiro dias': 'Sátiro Dias',
  saubara: 'Saubara',
  saude: 'Saúde',
  seabra: 'Seabra',
  'sebastiao laranjeiras': 'Sebastião Laranjeiras',
  'senhor do bonfim': 'Senhor do Bonfim',
  'sento se': 'Sento Sé',
  'serra do ramalho': 'Serra do Ramalho',
  'serra dourada': 'Serra Dourada',
  'serra preta': 'Serra Preta',
  serrinha: 'Serrinha',
  serrolandia: 'Serrolândia',
  'simoes filho': 'Simões Filho',
  'sitio do mato': 'Sítio do Mato',
  'sitio do quinto': 'Sítio do Quinto',
  sobradinho: 'Sobradinho',
  'souto soares': 'Souto Soares',
  'tabocas do brejo velho': 'Tabocas do Brejo Velho',
  tanhacu: 'Tanhaçu',
  'tanque novo': 'Tanque Novo',
  tanquinho: 'Tanquinho',
  taperoa: 'Taperoá',
  tapiramuta: 'Tapiramutá',
  'teixeira de freitas': 'Teixeira de Freitas',
  'teodoro sampaio': 'Teodoro Sampaio',
  teofilandia: 'Teofilândia',
  teolandia: 'Teolândia',
  'terra nova': 'Terra Nova',
  tremedal: 'Tremedal',
  tucano: 'Tucano',
  uaua: 'Uauá',
  ubaira: 'Ubaíra',
  ubaitaba: 'Ubaitaba',
  ubata: 'Ubatã',
  uibai: 'Uibaí',
  umburanas: 'Umburanas',
  una: 'Una',
  urandi: 'Urandi',
  urucuca: 'Uruçuca',
  utinga: 'Utinga',
  valenca: 'Valença',
  valente: 'Valente',
  'varzea da roca': 'Várzea da Roça',
  'varzea do poco': 'Várzea do Poço',
  'varzea nova': 'Várzea Nova',
  varzedo: 'Varzedo',
  'vera cruz': 'Vera Cruz',
  vereda: 'Vereda',
  'vitoria da conquista': 'Vitória da Conquista',
  wagner: 'Wagner',
  wanderley: 'Wanderley',
  'wenceslau guimaraes': 'Wenceslau Guimarães',
  'xique-xique': 'Xique-Xique',
};
