export const cities = {
  abaiara: 'Abaiara',
  acarape: 'Acarape',
  acarau: 'Acaraú',
  acopiara: 'Acopiara',
  aiuaba: 'Aiuaba',
  alcantaras: 'Alcântaras',
  altaneira: 'Altaneira',
  'alto santo': 'Alto Santo',
  amontada: 'Amontada',
  'antonina do norte': 'Antonina do Norte',
  apuiares: 'Apuiarés',
  aquiraz: 'Aquiraz',
  aracati: 'Aracati',
  aracoiaba_: 'Aracoiaba',
  ararenda: 'Ararendá',
  araripe: 'Araripe',
  aratuba: 'Aratuba',
  arneiroz: 'Arneiroz',
  assare: 'Assaré',
  aurora: 'Aurora',
  baixio: 'Baixio',
  banabuiu: 'Banabuiú',
  barbalha: 'Barbalha',
  barreira: 'Barreira',
  barro: 'Barro',
  barroquinha: 'Barroquinha',
  baturite: 'Baturité',
  beberibe: 'Beberibe',
  'bela cruz': 'Bela Cruz',
  'boa viagem': 'Boa Viagem',
  'brejo santo': 'Brejo Santo',
  camocim: 'Camocim',
  'campos sales': 'Campos Sales',
  caninde: 'Canindé',
  capistrano: 'Capistrano',
  caridade: 'Caridade',
  carire: 'Cariré',
  caririacu: 'Caririaçu',
  carius: 'Cariús',
  carnaubal: 'Carnaubal',
  cascavel: 'Cascavel',
  catarina: 'Catarina',
  catunda: 'Catunda',
  caucaia: 'Caucaia',
  cedro: 'Cedro',
  chaval: 'Chaval',
  choro: 'Choró',
  chorozinho: 'Chorozinho',
  coreau: 'Coreaú',
  crateus: 'Crateús',
  crato: 'Crato',
  croata: 'Croatá',
  cruz: 'Cruz',
  'deputado irapuan pinheiro': 'Deputado Irapuan Pinheiro',
  erere: 'Ereré',
  eusebio: 'Eusébio',
  'farias brito': 'Farias Brito',
  forquilha: 'Forquilha',
  fortaleza: 'Fortaleza',
  fortim: 'Fortim',
  frecheirinha: 'Frecheirinha',
  'general sampaio': 'General Sampaio',
  graca: 'Graça',
  granja: 'Granja',
  granjeiro: 'Granjeiro',
  groairas: 'Groaíras',
  guaiuba: 'Guaiúba',
  'guaraciaba do norte': 'Guaraciaba do Norte',
  guaramiranga: 'Guaramiranga',
  hidrolandia: 'Hidrolândia',
  horizonte: 'Horizonte',
  ibaretama: 'Ibaretama',
  ibiapina: 'Ibiapina',
  ibicuitinga: 'Ibicuitinga',
  icapui: 'Icapuí',
  ico: 'Icó',
  iguatu: 'Iguatu',
  independencia: 'Independência',
  ipaporanga: 'Ipaporanga',
  ipaumirim: 'Ipaumirim',
  ipu: 'Ipu',
  ipueiras: 'Ipueiras',
  iracema: 'Iracema',
  iraucuba: 'Irauçuba',
  itaicaba: 'Itaiçaba',
  itaitinga: 'Itaitinga',
  itapaje: 'Itapajé',
  itapipoca: 'Itapipoca',
  itapiuna: 'Itapiúna',
  itarema: 'Itarema',
  itatira: 'Itatira',
  jaguaretama: 'Jaguaretama',
  jaguaribara: 'Jaguaribara',
  jaguaribe: 'Jaguaribe',
  jaguaruana: 'Jaguaruana',
  jardim: 'Jardim',
  jati: 'Jati',
  'jijoca de jericoacoara': 'Jijoca de Jericoacoara',
  'juazeiro do norte': 'Juazeiro do Norte',
  jucas: 'Jucás',
  'lavras da mangabeira': 'Lavras da Mangabeira',
  'limoeiro do norte': 'Limoeiro do Norte',
  madalena: 'Madalena',
  maracanau: 'Maracanaú',
  maranguape: 'Maranguape',
  marco: 'Marco',
  martinopole: 'Martinópole',
  massape: 'Massapê',
  mauriti: 'Mauriti',
  meruoca: 'Meruoca',
  milagres_: 'Milagres',
  milha: 'Milhã',
  miraima: 'Miraíma',
  'missao velha': 'Missão Velha',
  mombaca: 'Mombaça',
  'monsenhor tabosa': 'Monsenhor Tabosa',
  'morada nova': 'Morada Nova',
  moraujo: 'Moraújo',
  morrinhos: 'Morrinhos',
  mucambo: 'Mucambo',
  mulungu: 'Mulungu',
  'nova olinda': 'Nova Olinda',
  'nova russas': 'Nova Russas',
  'novo oriente': 'Novo Oriente',
  ocara: 'Ocara',
  oros: 'Orós',
  pacajus: 'Pacajus',
  pacatuba: 'Pacatuba',
  pacoti: 'Pacoti',
  pacuja: 'Pacujá',
  palhano: 'Palhano',
  palmacia: 'Palmácia',
  paracuru: 'Paracuru',
  paraipaba: 'Paraipaba',
  parambu: 'Parambu',
  paramoti: 'Paramoti',
  'pedra branca': 'Pedra Branca',
  penaforte: 'Penaforte',
  pentecoste: 'Pentecoste',
  pereiro: 'Pereiro',
  pindoretama: 'Pindoretama',
  'piquet carneiro': 'Piquet Carneiro',
  'pires ferreira': 'Pires Ferreira',
  poranga: 'Poranga',
  porteiras: 'Porteiras',
  potengi: 'Potengi',
  potiretama: 'Potiretama',
  quiterianopolis: 'Quiterianópolis',
  quixada: 'Quixadá',
  quixelo: 'Quixelô',
  quixeramobim: 'Quixeramobim',
  quixere: 'Quixeré',
  redencao: 'Redenção',
  reriutaba: 'Reriutaba',
  russas: 'Russas',
  saboeiro: 'Saboeiro',
  salitre: 'Salitre',
  'santana do acarau': 'Santana do Acaraú',
  'santana do cariri': 'Santana do Cariri',
  'santa quiteria': 'Santa Quitéria',
  'sao benedito': 'São Benedito',
  'sao goncalo do amarante': 'São Gonçalo do Amarante',
  'sao joao do jaguaribe': 'São João do Jaguaribe',
  'sao luis do curu': 'São Luís do Curu',
  'senador pompeu': 'Senador Pompeu',
  'senador sa': 'Senador Sá',
  sobral: 'Sobral',
  solonopole: 'Solonópole',
  'tabuleiro do norte': 'Tabuleiro do Norte',
  tamboril: 'Tamboril',
  tarrafas: 'Tarrafas',
  taua: 'Tauá',
  tejucuoca: 'Tejuçuoca',
  tiangua: 'Tianguá',
  trairi: 'Trairi',
  tururu: 'Tururu',
  ubajara: 'Ubajara',
  umari: 'Umari',
  umirim: 'Umirim',
  uruburetama: 'Uruburetama',
  uruoca: 'Uruoca',
  varjota: 'Varjota',
  'varzea alegre': 'Várzea Alegre',
  'vicosa do ceara': 'Viçosa do Ceará',
};
