export const cities = {
  abaiara: { name: 'Abaiara', state: 'CE' },
  acarape: { name: 'Acarape', state: 'CE' },
  acarau: { name: 'Acaraú', state: 'CE' },
  acopiara: { name: 'Acopiara', state: 'CE' },
  aiuaba: { name: 'Aiuaba', state: 'CE' },
  alcantaras: { name: 'Alcântaras', state: 'CE' },
  altaneira: { name: 'Altaneira', state: 'CE' },
  'alto santo': { name: 'Alto Santo', state: 'CE' },
  amontada: { name: 'Amontada', state: 'CE' },
  'antonina do norte': { name: 'Antonina do Norte', state: 'CE' },
  apuiares: { name: 'Apuiarés', state: 'CE' },
  aquiraz: { name: 'Aquiraz', state: 'CE' },
  aracati: { name: 'Aracati', state: 'CE' },
  aracoiaba_: { name: 'Aracoiaba', state: 'CE' },
  ararenda: { name: 'Ararendá', state: 'CE' },
  araripe: { name: 'Araripe', state: 'CE' },
  aratuba: { name: 'Aratuba', state: 'CE' },
  arneiroz: { name: 'Arneiroz', state: 'CE' },
  assare: { name: 'Assaré', state: 'CE' },
  aurora: { name: 'Aurora', state: 'CE' },
  baixio: { name: 'Baixio', state: 'CE' },
  banabuiu: { name: 'Banabuiú', state: 'CE' },
  barbalha: { name: 'Barbalha', state: 'CE' },
  barreira: { name: 'Barreira', state: 'CE' },
  barro: { name: 'Barro', state: 'CE' },
  barroquinha: { name: 'Barroquinha', state: 'CE' },
  baturite: { name: 'Baturité', state: 'CE' },
  beberibe: { name: 'Beberibe', state: 'CE' },
  'bela cruz': { name: 'Bela Cruz', state: 'CE' },
  'boa viagem': { name: 'Boa Viagem', state: 'CE' },
  'brejo santo': { name: 'Brejo Santo', state: 'CE' },
  camocim: { name: 'Camocim', state: 'CE' },
  'campos sales': { name: 'Campos Sales', state: 'CE' },
  caninde: { name: 'Canindé', state: 'CE' },
  capistrano: { name: 'Capistrano', state: 'CE' },
  caridade: { name: 'Caridade', state: 'CE' },
  carire: { name: 'Cariré', state: 'CE' },
  caririacu: { name: 'Caririaçu', state: 'CE' },
  carius: { name: 'Cariús', state: 'CE' },
  carnaubal: { name: 'Carnaubal', state: 'CE' },
  cascavel: { name: 'Cascavel', state: 'CE' },
  catarina: { name: 'Catarina', state: 'CE' },
  catunda: { name: 'Catunda', state: 'CE' },
  caucaia: { name: 'Caucaia', state: 'CE' },
  cedro: { name: 'Cedro', state: 'CE' },
  chaval: { name: 'Chaval', state: 'CE' },
  choro: { name: 'Choró', state: 'CE' },
  chorozinho: { name: 'Chorozinho', state: 'CE' },
  coreau: { name: 'Coreaú', state: 'CE' },
  crateus: { name: 'Crateús', state: 'CE' },
  crato: { name: 'Crato', state: 'CE' },
  croata: { name: 'Croatá', state: 'CE' },
  cruz: { name: 'Cruz', state: 'CE' },
  'deputado irapuan pinheiro': { name: 'Deputado Irapuan Pinheiro', state: 'CE' },
  erere: { name: 'Ereré', state: 'CE' },
  eusebio: { name: 'Eusébio', state: 'CE' },
  'farias brito': { name: 'Farias Brito', state: 'CE' },
  forquilha: { name: 'Forquilha', state: 'CE' },
  fortaleza: { name: 'Fortaleza', state: 'CE' },
  fortim: { name: 'Fortim', state: 'CE' },
  frecheirinha: { name: 'Frecheirinha', state: 'CE' },
  'general sampaio': { name: 'General Sampaio', state: 'CE' },
  graca: { name: 'Graça', state: 'CE' },
  granja: { name: 'Granja', state: 'CE' },
  granjeiro: { name: 'Granjeiro', state: 'CE' },
  groairas: { name: 'Groaíras', state: 'CE' },
  guaiuba: { name: 'Guaiúba', state: 'CE' },
  'guaraciaba do norte': { name: 'Guaraciaba do Norte', state: 'CE' },
  guaramiranga: { name: 'Guaramiranga', state: 'CE' },
  hidrolandia: { name: 'Hidrolândia', state: 'CE' },
  horizonte: { name: 'Horizonte', state: 'CE' },
  ibaretama: { name: 'Ibaretama', state: 'CE' },
  ibiapina: { name: 'Ibiapina', state: 'CE' },
  ibicuitinga: { name: 'Ibicuitinga', state: 'CE' },
  icapui: { name: 'Icapuí', state: 'CE' },
  ico: { name: 'Icó', state: 'CE' },
  iguatu: { name: 'Iguatu', state: 'CE' },
  independencia: { name: 'Independência', state: 'CE' },
  ipaporanga: { name: 'Ipaporanga', state: 'CE' },
  ipaumirim: { name: 'Ipaumirim', state: 'CE' },
  ipu: { name: 'Ipu', state: 'CE' },
  ipueiras: { name: 'Ipueiras', state: 'CE' },
  iracema: { name: 'Iracema', state: 'CE' },
  iraucuba: { name: 'Irauçuba', state: 'CE' },
  itaicaba: { name: 'Itaiçaba', state: 'CE' },
  itaitinga: { name: 'Itaitinga', state: 'CE' },
  itapaje: { name: 'Itapajé', state: 'CE' },
  itapipoca: { name: 'Itapipoca', state: 'CE' },
  itapiuna: { name: 'Itapiúna', state: 'CE' },
  itarema: { name: 'Itarema', state: 'CE' },
  itatira: { name: 'Itatira', state: 'CE' },
  jaguaretama: { name: 'Jaguaretama', state: 'CE' },
  jaguaribara: { name: 'Jaguaribara', state: 'CE' },
  jaguaribe: { name: 'Jaguaribe', state: 'CE' },
  jaguaruana: { name: 'Jaguaruana', state: 'CE' },
  jardim: { name: 'Jardim', state: 'CE' },
  jati: { name: 'Jati', state: 'CE' },
  'jijoca de jericoacoara': { name: 'Jijoca de Jericoacoara', state: 'CE' },
  'juazeiro do norte': { name: 'Juazeiro do Norte', state: 'CE' },
  jucas: { name: 'Jucás', state: 'CE' },
  'lavras da mangabeira': { name: 'Lavras da Mangabeira', state: 'CE' },
  'limoeiro do norte': { name: 'Limoeiro do Norte', state: 'CE' },
  madalena: { name: 'Madalena', state: 'CE' },
  maracanau: { name: 'Maracanaú', state: 'CE' },
  maranguape: { name: 'Maranguape', state: 'CE' },
  marco: { name: 'Marco', state: 'CE' },
  martinopole: { name: 'Martinópole', state: 'CE' },
  massape: { name: 'Massapê', state: 'CE' },
  mauriti: { name: 'Mauriti', state: 'CE' },
  meruoca: { name: 'Meruoca', state: 'CE' },
  milagres_: { name: 'Milagres', state: 'CE' },
  milha: { name: 'Milhã', state: 'CE' },
  miraima: { name: 'Miraíma', state: 'CE' },
  'missao velha': { name: 'Missão Velha', state: 'CE' },
  mombaca: { name: 'Mombaça', state: 'CE' },
  'monsenhor tabosa': { name: 'Monsenhor Tabosa', state: 'CE' },
  'morada nova': { name: 'Morada Nova', state: 'CE' },
  moraujo: { name: 'Moraújo', state: 'CE' },
  morrinhos: { name: 'Morrinhos', state: 'CE' },
  mucambo: { name: 'Mucambo', state: 'CE' },
  mulungu: { name: 'Mulungu', state: 'CE' },
  'nova olinda': { name: 'Nova Olinda', state: 'CE' },
  'nova russas': { name: 'Nova Russas', state: 'CE' },
  'novo oriente': { name: 'Novo Oriente', state: 'CE' },
  ocara: { name: 'Ocara', state: 'CE' },
  oros: { name: 'Orós', state: 'CE' },
  pacajus: { name: 'Pacajus', state: 'CE' },
  pacatuba: { name: 'Pacatuba', state: 'CE' },
  pacoti: { name: 'Pacoti', state: 'CE' },
  pacuja: { name: 'Pacujá', state: 'CE' },
  palhano: { name: 'Palhano', state: 'CE' },
  palmacia: { name: 'Palmácia', state: 'CE' },
  paracuru: { name: 'Paracuru', state: 'CE' },
  paraipaba: { name: 'Paraipaba', state: 'CE' },
  parambu: { name: 'Parambu', state: 'CE' },
  paramoti: { name: 'Paramoti', state: 'CE' },
  'pedra branca': { name: 'Pedra Branca', state: 'CE' },
  penaforte: { name: 'Penaforte', state: 'CE' },
  pentecoste: { name: 'Pentecoste', state: 'CE' },
  pereiro: { name: 'Pereiro', state: 'CE' },
  pindoretama: { name: 'Pindoretama', state: 'CE' },
  'piquet carneiro': { name: 'Piquet Carneiro', state: 'CE' },
  'pires ferreira': { name: 'Pires Ferreira', state: 'CE' },
  poranga: { name: 'Poranga', state: 'CE' },
  porteiras: { name: 'Porteiras', state: 'CE' },
  potengi: { name: 'Potengi', state: 'CE' },
  potiretama: { name: 'Potiretama', state: 'CE' },
  quiterianopolis: { name: 'Quiterianópolis', state: 'CE' },
  quixada: { name: 'Quixadá', state: 'CE' },
  quixelo: { name: 'Quixelô', state: 'CE' },
  quixeramobim: { name: 'Quixeramobim', state: 'CE' },
  quixere: { name: 'Quixeré', state: 'CE' },
  redencao: { name: 'Redenção', state: 'CE' },
  reriutaba: { name: 'Reriutaba', state: 'CE' },
  russas: { name: 'Russas', state: 'CE' },
  saboeiro: { name: 'Saboeiro', state: 'CE' },
  salitre: { name: 'Salitre', state: 'CE' },
  'santana do acarau': { name: 'Santana do Acaraú', state: 'CE' },
  'santana do cariri': { name: 'Santana do Cariri', state: 'CE' },
  'santa quiteria': { name: 'Santa Quitéria', state: 'CE' },
  'sao benedito': { name: 'São Benedito', state: 'CE' },
  'sao goncalo do amarante': { name: 'São Gonçalo do Amarante', state: 'CE' },
  'sao joao do jaguaribe': { name: 'São João do Jaguaribe', state: 'CE' },
  'sao luis do curu': { name: 'São Luís do Curu', state: 'CE' },
  'senador pompeu': { name: 'Senador Pompeu', state: 'CE' },
  'senador sa': { name: 'Senador Sá', state: 'CE' },
  sobral: { name: 'Sobral', state: 'CE' },
  solonopole: { name: 'Solonópole', state: 'CE' },
  'tabuleiro do norte': { name: 'Tabuleiro do Norte', state: 'CE' },
  tamboril: { name: 'Tamboril', state: 'CE' },
  tarrafas: { name: 'Tarrafas', state: 'CE' },
  taua: { name: 'Tauá', state: 'CE' },
  tejucuoca: { name: 'Tejuçuoca', state: 'CE' },
  tiangua: { name: 'Tianguá', state: 'CE' },
  trairi: { name: 'Trairi', state: 'CE' },
  tururu: { name: 'Tururu', state: 'CE' },
  ubajara: { name: 'Ubajara', state: 'CE' },
  umari: { name: 'Umari', state: 'CE' },
  umirim: { name: 'Umirim', state: 'CE' },
  uruburetama: { name: 'Uruburetama', state: 'CE' },
  uruoca: { name: 'Uruoca', state: 'CE' },
  varjota: { name: 'Varjota', state: 'CE' },
  'varzea alegre': { name: 'Várzea Alegre', state: 'CE' },
  'vicosa do ceara': { name: 'Viçosa do Ceará', state: 'CE' },
};
