export const cities = {
  'afonso claudio': { name: 'Afonso Cláudio', state: 'ES' },
  'agua doce do norte': { name: 'Água Doce do Norte', state: 'ES' },
  'aguia branca': { name: 'Águia Branca', state: 'ES' },
  alegre: { name: 'Alegre', state: 'ES' },
  'alfredo chaves': { name: 'Alfredo Chaves', state: 'ES' },
  'alto rio novo': { name: 'Alto Rio Novo', state: 'ES' },
  anchieta: { name: 'Anchieta', state: 'ES' },
  apiaca: { name: 'Apiacá', state: 'ES' },
  aracruz: { name: 'Aracruz', state: 'ES' },
  'atilio vivacqua': { name: 'Atílio Vivácqua', state: 'ES' },
  'baixo guandu': { name: 'Baixo Guandu', state: 'ES' },
  'barra de sao francisco': { name: 'Barra de São Francisco', state: 'ES' },
  'boa esperanca': { name: 'Boa Esperança', state: 'ES' },
  'bom jesus do norte': { name: 'Bom Jesus do Norte', state: 'ES' },
  brejetuba: { name: 'Brejetuba', state: 'ES' },
  'cachoeiro de itapemirim': { name: 'Cachoeiro de Itapemirim', state: 'ES' },
  cariacica: { name: 'Cariacica', state: 'ES' },
  castelo: { name: 'Castelo', state: 'ES' },
  colatina: { name: 'Colatina', state: 'ES' },
  'conceicao da barra': { name: 'Conceição da Barra', state: 'ES' },
  'conceicao do castelo': { name: 'Conceição do Castelo', state: 'ES' },
  'divino de sao lourenco': { name: 'Divino de São Lourenço', state: 'ES' },
  'domingos martins': { name: 'Domingos Martins', state: 'ES' },
  'dores do rio preto': { name: 'Dores do Rio Preto', state: 'ES' },
  ecoporanga: { name: 'Ecoporanga', state: 'ES' },
  fundao: { name: 'Fundão', state: 'ES' },
  'governador lindenberg': { name: 'Governador Lindenberg', state: 'ES' },
  guacui: { name: 'Guaçuí', state: 'ES' },
  guarapari: { name: 'Guarapari', state: 'ES' },
  ibatiba: { name: 'Ibatiba', state: 'ES' },
  ibiracu: { name: 'Ibiraçu', state: 'ES' },
  ibitirama: { name: 'Ibitirama', state: 'ES' },
  iconha: { name: 'Iconha', state: 'ES' },
  irupi: { name: 'Irupi', state: 'ES' },
  itaguacu: { name: 'Itaguaçu', state: 'ES' },
  itapemirim: { name: 'Itapemirim', state: 'ES' },
  itarana: { name: 'Itarana', state: 'ES' },
  iuna: { name: 'Iúna', state: 'ES' },
  jaguare: { name: 'Jaguaré', state: 'ES' },
  'jeronimo monteiro': { name: 'Jerônimo Monteiro', state: 'ES' },
  'joao neiva': { name: 'João Neiva', state: 'ES' },
  'laranja da terra': { name: 'Laranja da Terra', state: 'ES' },
  linhares: { name: 'Linhares', state: 'ES' },
  mantenopolis: { name: 'Mantenópolis', state: 'ES' },
  marataizes: { name: 'Marataízes', state: 'ES' },
  'marechal floriano': { name: 'Marechal Floriano', state: 'ES' },
  marilandia: { name: 'Marilândia', state: 'ES' },
  'mimoso do sul': { name: 'Mimoso do Sul', state: 'ES' },
  montanha: { name: 'Montanha', state: 'ES' },
  mucurici: { name: 'Mucurici', state: 'ES' },
  'muniz freire': { name: 'Muniz Freire', state: 'ES' },
  muqui: { name: 'Muqui', state: 'ES' },
  'nova venecia': { name: 'Nova Venécia', state: 'ES' },
  pancas: { name: 'Pancas', state: 'ES' },
  'pedro canario': { name: 'Pedro Canário', state: 'ES' },
  pinheiros: { name: 'Pinheiros', state: 'ES' },
  piuma: { name: 'Piúma', state: 'ES' },
  'ponto belo': { name: 'Ponto Belo', state: 'ES' },
  'presidente kennedy': { name: 'Presidente Kennedy', state: 'ES' },
  'rio bananal': { name: 'Rio Bananal', state: 'ES' },
  'rio novo do sul': { name: 'Rio Novo do Sul', state: 'ES' },
  'santa leopoldina': { name: 'Santa Leopoldina', state: 'ES' },
  'santa maria de jetiba': { name: 'Santa Maria de Jetibá', state: 'ES' },
  'santa teresa': { name: 'Santa Teresa', state: 'ES' },
  'sao domingos do norte': { name: 'São Domingos do Norte', state: 'ES' },
  'sao gabriel da palha': { name: 'São Gabriel da Palha', state: 'ES' },
  'sao jose do calcado': { name: 'São José do Calçado', state: 'ES' },
  'sao mateus': { name: 'São Mateus', state: 'ES' },
  'sao roque do canaa': { name: 'São Roque do Canaã', state: 'ES' },
  serra: { name: 'Serra', state: 'ES' },
  sooretama: { name: 'Sooretama', state: 'ES' },
  'vargem alta': { name: 'Vargem Alta', state: 'ES' },
  'venda nova do imigrante': { name: 'Venda Nova do Imigrante', state: 'ES' },
  viana: { name: 'Viana', state: 'ES' },
  'vila pavao': { name: 'Vila Pavão', state: 'ES' },
  'vila valerio': { name: 'Vila Valério', state: 'ES' },
  'vila velha': { name: 'Vila Velha', state: 'ES' },
  vitoria: { name: 'Vitória', state: 'ES' },
};
