export const cities = {
  'abadia de goias': 'Abadia de Goiás',
  abadiania: 'Abadiânia',
  acreuna: 'Acreúna',
  adelandia: 'Adelândia',
  'agua fria de goias': 'Água Fria de Goiás',
  'agua limpa': 'Água Limpa',
  'aguas lindas de goias': 'Águas Lindas de Goiás',
  alexania: 'Alexânia',
  aloandia: 'Aloândia',
  'alto horizonte': 'Alto Horizonte',
  'alto paraiso de goias': 'Alto Paraíso de Goiás',
  'alvorada do norte': 'Alvorada do Norte',
  amaralina: 'Amaralina',
  'americano do brasil': 'Americano do Brasil',
  amorinopolis: 'Amorinópolis',
  anapolis: 'Anápolis',
  anhanguera: 'Anhanguera',
  anicuns: 'Anicuns',
  'aparecida de goiania': 'Aparecida de Goiânia',
  'aparecida do rio doce': 'Aparecida do Rio Doce',
  apore: 'Aporé',
  aracu: 'Araçu',
  aragarcas: 'Aragarças',
  aragoiania: 'Aragoiânia',
  araguapaz: 'Araguapaz',
  arenopolis: 'Arenópolis',
  aruana: 'Aruanã',
  aurilandia: 'Aurilândia',
  avelinopolis: 'Avelinópolis',
  baliza: 'Baliza',
  'barro alto_': 'Barro Alto',
  'bela vista de goias': 'Bela Vista de Goiás',
  'bom jardim de goias': 'Bom Jardim de Goiás',
  'bom jesus de goias': 'Bom Jesus de Goiás',
  bonfinopolis: 'Bonfinópolis',
  bonopolis: 'Bonópolis',
  brazabrantes: 'Brazabrantes',
  britania: 'Britânia',
  'buriti alegre': 'Buriti Alegre',
  'buriti de goias': 'Buriti de Goiás',
  buritinopolis: 'Buritinópolis',
  cabeceiras: 'Cabeceiras',
  'cachoeira alta': 'Cachoeira Alta',
  'cachoeira de goias': 'Cachoeira de Goiás',
  'cachoeira dourada': 'Cachoeira Dourada',
  cacu: 'Caçu',
  caiaponia: 'Caiapônia',
  'caldas novas': 'Caldas Novas',
  caldazinha: 'Caldazinha',
  'campestre de goias': 'Campestre de Goiás',
  campinacu: 'Campinaçu',
  campinorte: 'Campinorte',
  'campo alegre de goias': 'Campo Alegre de Goiás',
  'campo limpo de goias': 'Campo Limpo de Goiás',
  'campos belos': 'Campos Belos',
  'campos verdes': 'Campos Verdes',
  'carmo do rio verde': 'Carmo do Rio Verde',
  castelandia: 'Castelândia',
  catalao: 'Catalão',
  caturai: 'Caturaí',
  cavalcante: 'Cavalcante',
  ceres: 'Ceres',
  cezarina: 'Cezarina',
  'chapadao do ceu': 'Chapadão do Céu',
  'cidade ocidental': 'Cidade Ocidental',
  'cocalzinho de goias': 'Cocalzinho de Goiás',
  'colinas do sul': 'Colinas do Sul',
  'corrego do ouro': 'Córrego do Ouro',
  'corumba de goias': 'Corumbá de Goiás',
  corumbaiba: 'Corumbaíba',
  cristalina: 'Cristalina',
  cristianopolis: 'Cristianópolis',
  crixas: 'Crixás',
  crominia: 'Cromínia',
  cumari: 'Cumari',
  damianopolis: 'Damianópolis',
  damolandia: 'Damolândia',
  davinopolis: 'Davinópolis',
  diorama: 'Diorama',
  'divinopolis de goias': 'Divinópolis de Goiás',
  doverlandia: 'Doverlândia',
  edealina: 'Edealina',
  edeia: 'Edéia',
  'estrela do norte': 'Estrela do Norte',
  faina: 'Faina',
  'fazenda nova': 'Fazenda Nova',
  firminopolis: 'Firminópolis',
  'flores de goias': 'Flores de Goiás',
  formosa: 'Formosa',
  formoso: 'Formoso',
  'gameleira de goias': 'Gameleira de Goiás',
  goianapolis: 'Goianápolis',
  goiandira: 'Goiandira',
  goianesia: 'Goianésia',
  goiania: 'Goiânia',
  goianira: 'Goianira',
  goias: 'Goiás',
  goiatuba: 'Goiatuba',
  gouvelandia: 'Gouvelândia',
  guapo: 'Guapó',
  guaraita: 'Guaraíta',
  'guarani de goias': 'Guarani de Goiás',
  guarinos: 'Guarinos',
  heitorai: 'Heitoraí',
  hidrolandia_: 'Hidrolândia',
  hidrolina: 'Hidrolina',
  iaciara: 'Iaciara',
  inaciolandia: 'Inaciolândia',
  indiara: 'Indiara',
  inhumas: 'Inhumas',
  ipameri: 'Ipameri',
  'ipiranga de goias': 'Ipiranga de Goiás',
  ipora: 'Iporá',
  israelandia: 'Israelândia',
  itaberai: 'Itaberaí',
  itaguari: 'Itaguari',
  itaguaru: 'Itaguaru',
  itaja: 'Itajá',
  itapaci: 'Itapaci',
  itapirapua: 'Itapirapuã',
  itapuranga: 'Itapuranga',
  itaruma: 'Itarumã',
  itaucu: 'Itauçu',
  itumbiara: 'Itumbiara',
  ivolandia: 'Ivolândia',
  jandaia: 'Jandaia',
  jaragua: 'Jaraguá',
  jatai: 'Jataí',
  jaupaci: 'Jaupaci',
  jesupolis: 'Jesúpolis',
  joviania: 'Joviânia',
  jussara_: 'Jussara',
  'lagoa santa': 'Lagoa Santa',
  'leopoldo de bulhoes': 'Leopoldo de Bulhões',
  luziania: 'Luziânia',
  mairipotaba: 'Mairipotaba',
  mambai: 'Mambaí',
  'mara rosa': 'Mara Rosa',
  marzagao: 'Marzagão',
  matrincha: 'Matrinchã',
  maurilandia: 'Maurilândia',
  'mimoso de goias': 'Mimoso de Goiás',
  minacu: 'Minaçu',
  mineiros: 'Mineiros',
  moipora: 'Moiporá',
  'monte alegre de goias': 'Monte Alegre de Goiás',
  'montes claros de goias': 'Montes Claros de Goiás',
  montividiu: 'Montividiu',
  'montividiu do norte': 'Montividiu do Norte',
  morrinhos_: 'Morrinhos',
  'morro agudo de goias': 'Morro Agudo de Goiás',
  mossamedes: 'Mossâmedes',
  mozarlandia: 'Mozarlândia',
  'mundo novo_': 'Mundo Novo',
  mutunopolis: 'Mutunópolis',
  nazario: 'Nazário',
  neropolis: 'Nerópolis',
  niquelandia: 'Niquelândia',
  'nova america': 'Nova América',
  'nova aurora': 'Nova Aurora',
  'nova crixas': 'Nova Crixás',
  'nova gloria': 'Nova Glória',
  'nova iguacu de goias': 'Nova Iguaçu de Goiás',
  'nova roma': 'Nova Roma',
  'nova veneza': 'Nova Veneza',
  'novo brasil': 'Novo Brasil',
  'novo gama': 'Novo Gama',
  'novo planalto': 'Novo Planalto',
  orizona: 'Orizona',
  'ouro verde de goias': 'Ouro Verde de Goiás',
  ouvidor: 'Ouvidor',
  'padre bernardo': 'Padre Bernardo',
  'palestina de goias': 'Palestina de Goiás',
  'palmeiras de goias': 'Palmeiras de Goiás',
  palmelo: 'Palmelo',
  palminopolis: 'Palminópolis',
  panama: 'Panamá',
  paranaiguara: 'Paranaiguara',
  parauna: 'Paraúna',
  perolandia: 'Perolândia',
  'petrolina de goias': 'Petrolina de Goiás',
  'pilar de goias': 'Pilar de Goiás',
  piracanjuba: 'Piracanjuba',
  piranhas_: 'Piranhas',
  pirenopolis: 'Pirenópolis',
  'pires do rio': 'Pires do Rio',
  planaltina: 'Planaltina',
  pontalina: 'Pontalina',
  porangatu: 'Porangatu',
  porteirao: 'Porteirão',
  portelandia: 'Portelândia',
  posse: 'Posse',
  'professor jamil': 'Professor Jamil',
  quirinopolis: 'Quirinópolis',
  rialma: 'Rialma',
  rianapolis: 'Rianápolis',
  'rio quente': 'Rio Quente',
  'rio verde': 'Rio Verde',
  rubiataba: 'Rubiataba',
  sanclerlandia: 'Sanclerlândia',
  'santa barbara de goias': 'Santa Bárbara de Goiás',
  'santa cruz de goias': 'Santa Cruz de Goiás',
  'santa fe de goias': 'Santa Fé de Goiás',
  'santa helena de goias': 'Santa Helena de Goiás',
  'santa isabel': 'Santa Isabel',
  'santa rita do araguaia': 'Santa Rita do Araguaia',
  'santa rita do novo destino': 'Santa Rita do Novo Destino',
  'santa rosa de goias': 'Santa Rosa de Goiás',
  'santa tereza de goias': 'Santa Tereza de Goiás',
  'santa terezinha de goias': 'Santa Terezinha de Goiás',
  'santo antonio da barra': 'Santo Antônio da Barra',
  'santo antonio de goias': 'Santo Antônio de Goiás',
  'santo antonio do descoberto': 'Santo Antônio do Descoberto',
  'sao domingos_': 'São Domingos',
  'sao francisco de goias': 'São Francisco de Goiás',
  "sao joao d'alianca": "São João d'Aliança",
  'sao joao da parauna': 'São João da Paraúna',
  'sao luis de montes belos': 'São Luís de Montes Belos',
  'sao luiz do norte': 'São Luiz do Norte',
  'sao miguel do araguaia': 'São Miguel do Araguaia',
  'sao miguel do passa-quatro': 'São Miguel do Passa-Quatro',
  'sao patricio': 'São Patrício',
  'sao simao': 'São Simão',
  'senador canedo': 'Senador Canedo',
  serranopolis: 'Serranópolis',
  silvania: 'Silvânia',
  simolandia: 'Simolândia',
  "sitio d'abadia": "Sítio d'Abadia",
  'taquaral de goias': 'Taquaral de Goiás',
  'teresina de goias': 'Teresina de Goiás',
  'terezopolis de goias': 'Terezópolis de Goiás',
  'tres ranchos': 'Três Ranchos',
  trindade: 'Trindade',
  trombas: 'Trombas',
  turvania: 'Turvânia',
  turvelandia: 'Turvelândia',
  uirapuru: 'Uirapuru',
  uruacu: 'Uruaçu',
  uruana: 'Uruana',
  urutai: 'Urutaí',
  'valparaiso de goias': 'Valparaíso de Goiás',
  varjao: 'Varjão',
  vianopolis: 'Vianópolis',
  vicentinopolis: 'Vicentinópolis',
  'vila boa': 'Vila Boa',
  'vila propicio': 'Vila Propício',
};
