export const cities = {
  'abadia de goias': { name: 'Abadia de Goiás', state: 'GO' },
  abadiania: { name: 'Abadiânia', state: 'GO' },
  acreuna: { name: 'Acreúna', state: 'GO' },
  adelandia: { name: 'Adelândia', state: 'GO' },
  'agua fria de goias': { name: 'Água Fria de Goiás', state: 'GO' },
  'agua limpa': { name: 'Água Limpa', state: 'GO' },
  'aguas lindas de goias': { name: 'Águas Lindas de Goiás', state: 'GO' },
  alexania: { name: 'Alexânia', state: 'GO' },
  aloandia: { name: 'Aloândia', state: 'GO' },
  'alto horizonte': { name: 'Alto Horizonte', state: 'GO' },
  'alto paraiso de goias': { name: 'Alto Paraíso de Goiás', state: 'GO' },
  'alvorada do norte': { name: 'Alvorada do Norte', state: 'GO' },
  amaralina: { name: 'Amaralina', state: 'GO' },
  'americano do brasil': { name: 'Americano do Brasil', state: 'GO' },
  amorinopolis: { name: 'Amorinópolis', state: 'GO' },
  anapolis: { name: 'Anápolis', state: 'GO' },
  anhanguera: { name: 'Anhanguera', state: 'GO' },
  anicuns: { name: 'Anicuns', state: 'GO' },
  'aparecida de goiania': { name: 'Aparecida de Goiânia', state: 'GO' },
  'aparecida do rio doce': { name: 'Aparecida do Rio Doce', state: 'GO' },
  apore: { name: 'Aporé', state: 'GO' },
  aracu: { name: 'Araçu', state: 'GO' },
  aragarcas: { name: 'Aragarças', state: 'GO' },
  aragoiania: { name: 'Aragoiânia', state: 'GO' },
  araguapaz: { name: 'Araguapaz', state: 'GO' },
  arenopolis: { name: 'Arenópolis', state: 'GO' },
  aruana: { name: 'Aruanã', state: 'GO' },
  aurilandia: { name: 'Aurilândia', state: 'GO' },
  avelinopolis: { name: 'Avelinópolis', state: 'GO' },
  baliza: { name: 'Baliza', state: 'GO' },
  'barro alto_': { name: 'Barro Alto', state: 'GO' },
  'bela vista de goias': { name: 'Bela Vista de Goiás', state: 'GO' },
  'bom jardim de goias': { name: 'Bom Jardim de Goiás', state: 'GO' },
  'bom jesus de goias': { name: 'Bom Jesus de Goiás', state: 'GO' },
  bonfinopolis: { name: 'Bonfinópolis', state: 'GO' },
  bonopolis: { name: 'Bonópolis', state: 'GO' },
  brazabrantes: { name: 'Brazabrantes', state: 'GO' },
  britania: { name: 'Britânia', state: 'GO' },
  'buriti alegre': { name: 'Buriti Alegre', state: 'GO' },
  'buriti de goias': { name: 'Buriti de Goiás', state: 'GO' },
  buritinopolis: { name: 'Buritinópolis', state: 'GO' },
  cabeceiras: { name: 'Cabeceiras', state: 'GO' },
  'cachoeira alta': { name: 'Cachoeira Alta', state: 'GO' },
  'cachoeira de goias': { name: 'Cachoeira de Goiás', state: 'GO' },
  'cachoeira dourada': { name: 'Cachoeira Dourada', state: 'GO' },
  cacu: { name: 'Caçu', state: 'GO' },
  caiaponia: { name: 'Caiapônia', state: 'GO' },
  'caldas novas': { name: 'Caldas Novas', state: 'GO' },
  caldazinha: { name: 'Caldazinha', state: 'GO' },
  'campestre de goias': { name: 'Campestre de Goiás', state: 'GO' },
  campinacu: { name: 'Campinaçu', state: 'GO' },
  campinorte: { name: 'Campinorte', state: 'GO' },
  'campo alegre de goias': { name: 'Campo Alegre de Goiás', state: 'GO' },
  'campo limpo de goias': { name: 'Campo Limpo de Goiás', state: 'GO' },
  'campos belos': { name: 'Campos Belos', state: 'GO' },
  'campos verdes': { name: 'Campos Verdes', state: 'GO' },
  'carmo do rio verde': { name: 'Carmo do Rio Verde', state: 'GO' },
  castelandia: { name: 'Castelândia', state: 'GO' },
  catalao: { name: 'Catalão', state: 'GO' },
  caturai: { name: 'Caturaí', state: 'GO' },
  cavalcante: { name: 'Cavalcante', state: 'GO' },
  ceres: { name: 'Ceres', state: 'GO' },
  cezarina: { name: 'Cezarina', state: 'GO' },
  'chapadao do ceu': { name: 'Chapadão do Céu', state: 'GO' },
  'cidade ocidental': { name: 'Cidade Ocidental', state: 'GO' },
  'cocalzinho de goias': { name: 'Cocalzinho de Goiás', state: 'GO' },
  'colinas do sul': { name: 'Colinas do Sul', state: 'GO' },
  'corrego do ouro': { name: 'Córrego do Ouro', state: 'GO' },
  'corumba de goias': { name: 'Corumbá de Goiás', state: 'GO' },
  corumbaiba: { name: 'Corumbaíba', state: 'GO' },
  cristalina: { name: 'Cristalina', state: 'GO' },
  cristianopolis: { name: 'Cristianópolis', state: 'GO' },
  crixas: { name: 'Crixás', state: 'GO' },
  crominia: { name: 'Cromínia', state: 'GO' },
  cumari: { name: 'Cumari', state: 'GO' },
  damianopolis: { name: 'Damianópolis', state: 'GO' },
  damolandia: { name: 'Damolândia', state: 'GO' },
  davinopolis: { name: 'Davinópolis', state: 'GO' },
  diorama: { name: 'Diorama', state: 'GO' },
  'divinopolis de goias': { name: 'Divinópolis de Goiás', state: 'GO' },
  doverlandia: { name: 'Doverlândia', state: 'GO' },
  edealina: { name: 'Edealina', state: 'GO' },
  edeia: { name: 'Edéia', state: 'GO' },
  'estrela do norte': { name: 'Estrela do Norte', state: 'GO' },
  faina: { name: 'Faina', state: 'GO' },
  'fazenda nova': { name: 'Fazenda Nova', state: 'GO' },
  firminopolis: { name: 'Firminópolis', state: 'GO' },
  'flores de goias': { name: 'Flores de Goiás', state: 'GO' },
  formosa: { name: 'Formosa', state: 'GO' },
  formoso: { name: 'Formoso', state: 'GO' },
  'gameleira de goias': { name: 'Gameleira de Goiás', state: 'GO' },
  goianapolis: { name: 'Goianápolis', state: 'GO' },
  goiandira: { name: 'Goiandira', state: 'GO' },
  goianesia: { name: 'Goianésia', state: 'GO' },
  goiania: { name: 'Goiânia', state: 'GO' },
  goianira: { name: 'Goianira', state: 'GO' },
  goias: { name: 'Goiás', state: 'GO' },
  goiatuba: { name: 'Goiatuba', state: 'GO' },
  gouvelandia: { name: 'Gouvelândia', state: 'GO' },
  guapo: { name: 'Guapó', state: 'GO' },
  guaraita: { name: 'Guaraíta', state: 'GO' },
  'guarani de goias': { name: 'Guarani de Goiás', state: 'GO' },
  guarinos: { name: 'Guarinos', state: 'GO' },
  heitorai: { name: 'Heitoraí', state: 'GO' },
  hidrolandia_: { name: 'Hidrolândia', state: 'GO' },
  hidrolina: { name: 'Hidrolina', state: 'GO' },
  iaciara: { name: 'Iaciara', state: 'GO' },
  inaciolandia: { name: 'Inaciolândia', state: 'GO' },
  indiara: { name: 'Indiara', state: 'GO' },
  inhumas: { name: 'Inhumas', state: 'GO' },
  ipameri: { name: 'Ipameri', state: 'GO' },
  'ipiranga de goias': { name: 'Ipiranga de Goiás', state: 'GO' },
  ipora: { name: 'Iporá', state: 'GO' },
  israelandia: { name: 'Israelândia', state: 'GO' },
  itaberai: { name: 'Itaberaí', state: 'GO' },
  itaguari: { name: 'Itaguari', state: 'GO' },
  itaguaru: { name: 'Itaguaru', state: 'GO' },
  itaja: { name: 'Itajá', state: 'GO' },
  itapaci: { name: 'Itapaci', state: 'GO' },
  itapirapua: { name: 'Itapirapuã', state: 'GO' },
  itapuranga: { name: 'Itapuranga', state: 'GO' },
  itaruma: { name: 'Itarumã', state: 'GO' },
  itaucu: { name: 'Itauçu', state: 'GO' },
  itumbiara: { name: 'Itumbiara', state: 'GO' },
  ivolandia: { name: 'Ivolândia', state: 'GO' },
  jandaia: { name: 'Jandaia', state: 'GO' },
  jaragua: { name: 'Jaraguá', state: 'GO' },
  jatai: { name: 'Jataí', state: 'GO' },
  jaupaci: { name: 'Jaupaci', state: 'GO' },
  jesupolis: { name: 'Jesúpolis', state: 'GO' },
  joviania: { name: 'Joviânia', state: 'GO' },
  jussara_: { name: 'Jussara', state: 'GO' },
  'lagoa santa': { name: 'Lagoa Santa', state: 'GO' },
  'leopoldo de bulhoes': { name: 'Leopoldo de Bulhões', state: 'GO' },
  luziania: { name: 'Luziânia', state: 'GO' },
  mairipotaba: { name: 'Mairipotaba', state: 'GO' },
  mambai: { name: 'Mambaí', state: 'GO' },
  'mara rosa': { name: 'Mara Rosa', state: 'GO' },
  marzagao: { name: 'Marzagão', state: 'GO' },
  matrincha: { name: 'Matrinchã', state: 'GO' },
  maurilandia: { name: 'Maurilândia', state: 'GO' },
  'mimoso de goias': { name: 'Mimoso de Goiás', state: 'GO' },
  minacu: { name: 'Minaçu', state: 'GO' },
  mineiros: { name: 'Mineiros', state: 'GO' },
  moipora: { name: 'Moiporá', state: 'GO' },
  'monte alegre de goias': { name: 'Monte Alegre de Goiás', state: 'GO' },
  'montes claros de goias': { name: 'Montes Claros de Goiás', state: 'GO' },
  montividiu: { name: 'Montividiu', state: 'GO' },
  'montividiu do norte': { name: 'Montividiu do Norte', state: 'GO' },
  morrinhos_: { name: 'Morrinhos', state: 'GO' },
  'morro agudo de goias': { name: 'Morro Agudo de Goiás', state: 'GO' },
  mossamedes: { name: 'Mossâmedes', state: 'GO' },
  mozarlandia: { name: 'Mozarlândia', state: 'GO' },
  'mundo novo_': { name: 'Mundo Novo', state: 'GO' },
  mutunopolis: { name: 'Mutunópolis', state: 'GO' },
  nazario: { name: 'Nazário', state: 'GO' },
  neropolis: { name: 'Nerópolis', state: 'GO' },
  niquelandia: { name: 'Niquelândia', state: 'GO' },
  'nova america': { name: 'Nova América', state: 'GO' },
  'nova aurora': { name: 'Nova Aurora', state: 'GO' },
  'nova crixas': { name: 'Nova Crixás', state: 'GO' },
  'nova gloria': { name: 'Nova Glória', state: 'GO' },
  'nova iguacu de goias': { name: 'Nova Iguaçu de Goiás', state: 'GO' },
  'nova roma': { name: 'Nova Roma', state: 'GO' },
  'nova veneza': { name: 'Nova Veneza', state: 'GO' },
  'novo brasil': { name: 'Novo Brasil', state: 'GO' },
  'novo gama': { name: 'Novo Gama', state: 'GO' },
  'novo planalto': { name: 'Novo Planalto', state: 'GO' },
  orizona: { name: 'Orizona', state: 'GO' },
  'ouro verde de goias': { name: 'Ouro Verde de Goiás', state: 'GO' },
  ouvidor: { name: 'Ouvidor', state: 'GO' },
  'padre bernardo': { name: 'Padre Bernardo', state: 'GO' },
  'palestina de goias': { name: 'Palestina de Goiás', state: 'GO' },
  'palmeiras de goias': { name: 'Palmeiras de Goiás', state: 'GO' },
  palmelo: { name: 'Palmelo', state: 'GO' },
  palminopolis: { name: 'Palminópolis', state: 'GO' },
  panama: { name: 'Panamá', state: 'GO' },
  paranaiguara: { name: 'Paranaiguara', state: 'GO' },
  parauna: { name: 'Paraúna', state: 'GO' },
  perolandia: { name: 'Perolândia', state: 'GO' },
  'petrolina de goias': { name: 'Petrolina de Goiás', state: 'GO' },
  'pilar de goias': { name: 'Pilar de Goiás', state: 'GO' },
  piracanjuba: { name: 'Piracanjuba', state: 'GO' },
  piranhas_: { name: 'Piranhas', state: 'GO' },
  pirenopolis: { name: 'Pirenópolis', state: 'GO' },
  'pires do rio': { name: 'Pires do Rio', state: 'GO' },
  planaltina: { name: 'Planaltina', state: 'GO' },
  pontalina: { name: 'Pontalina', state: 'GO' },
  porangatu: { name: 'Porangatu', state: 'GO' },
  porteirao: { name: 'Porteirão', state: 'GO' },
  portelandia: { name: 'Portelândia', state: 'GO' },
  posse: { name: 'Posse', state: 'GO' },
  'professor jamil': { name: 'Professor Jamil', state: 'GO' },
  quirinopolis: { name: 'Quirinópolis', state: 'GO' },
  rialma: { name: 'Rialma', state: 'GO' },
  rianapolis: { name: 'Rianápolis', state: 'GO' },
  'rio quente': { name: 'Rio Quente', state: 'GO' },
  'rio verde': { name: 'Rio Verde', state: 'GO' },
  rubiataba: { name: 'Rubiataba', state: 'GO' },
  sanclerlandia: { name: 'Sanclerlândia', state: 'GO' },
  'santa barbara de goias': { name: 'Santa Bárbara de Goiás', state: 'GO' },
  'santa cruz de goias': { name: 'Santa Cruz de Goiás', state: 'GO' },
  'santa fe de goias': { name: 'Santa Fé de Goiás', state: 'GO' },
  'santa helena de goias': { name: 'Santa Helena de Goiás', state: 'GO' },
  'santa isabel': { name: 'Santa Isabel', state: 'GO' },
  'santa rita do araguaia': { name: 'Santa Rita do Araguaia', state: 'GO' },
  'santa rita do novo destino': { name: 'Santa Rita do Novo Destino', state: 'GO' },
  'santa rosa de goias': { name: 'Santa Rosa de Goiás', state: 'GO' },
  'santa tereza de goias': { name: 'Santa Tereza de Goiás', state: 'GO' },
  'santa terezinha de goias': { name: 'Santa Terezinha de Goiás', state: 'GO' },
  'santo antonio da barra': { name: 'Santo Antônio da Barra', state: 'GO' },
  'santo antonio de goias': { name: 'Santo Antônio de Goiás', state: 'GO' },
  'santo antonio do descoberto': { name: 'Santo Antônio do Descoberto', state: 'GO' },
  'sao domingos_': { name: 'São Domingos', state: 'GO' },
  'sao francisco de goias': { name: 'São Francisco de Goiás', state: 'GO' },
  "sao joao d'alianca": { name: "São João d'Aliança", state: 'GO' },
  'sao joao da parauna': { name: 'São João da Paraúna', state: 'GO' },
  'sao luis de montes belos': { name: 'São Luís de Montes Belos', state: 'GO' },
  'sao luiz do norte': { name: 'São Luiz do Norte', state: 'GO' },
  'sao miguel do araguaia': { name: 'São Miguel do Araguaia', state: 'GO' },
  'sao miguel do passa-quatro': { name: 'São Miguel do Passa-Quatro', state: 'GO' },
  'sao patricio': { name: 'São Patrício', state: 'GO' },
  'sao simao': { name: 'São Simão', state: 'GO' },
  'senador canedo': { name: 'Senador Canedo', state: 'GO' },
  serranopolis: { name: 'Serranópolis', state: 'GO' },
  silvania: { name: 'Silvânia', state: 'GO' },
  simolandia: { name: 'Simolândia', state: 'GO' },
  "sitio d'abadia": { name: "Sítio d'Abadia", state: 'GO' },
  'taquaral de goias': { name: 'Taquaral de Goiás', state: 'GO' },
  'teresina de goias': { name: 'Teresina de Goiás', state: 'GO' },
  'terezopolis de goias': { name: 'Terezópolis de Goiás', state: 'GO' },
  'tres ranchos': { name: 'Três Ranchos', state: 'GO' },
  trindade: { name: 'Trindade', state: 'GO' },
  trombas: { name: 'Trombas', state: 'GO' },
  turvania: { name: 'Turvânia', state: 'GO' },
  turvelandia: { name: 'Turvelândia', state: 'GO' },
  uirapuru: { name: 'Uirapuru', state: 'GO' },
  uruacu: { name: 'Uruaçu', state: 'GO' },
  uruana: { name: 'Uruana', state: 'GO' },
  urutai: { name: 'Urutaí', state: 'GO' },
  'valparaiso de goias': { name: 'Valparaíso de Goiás', state: 'GO' },
  varjao: { name: 'Varjão', state: 'GO' },
  vianopolis: { name: 'Vianópolis', state: 'GO' },
  vicentinopolis: { name: 'Vicentinópolis', state: 'GO' },
  'vila boa': { name: 'Vila Boa', state: 'GO' },
  'vila propicio': { name: 'Vila Propício', state: 'GO' },
};
