export const cities = {
  acailandia: { name: 'Açailândia', state: 'MA' },
  'afonso cunha': { name: 'Afonso Cunha', state: 'MA' },
  'agua doce do maranhao': { name: 'Água Doce do Maranhão', state: 'MA' },
  alcantara: { name: 'Alcântara', state: 'MA' },
  'aldeias altas': { name: 'Aldeias Altas', state: 'MA' },
  'altamira do maranhao': { name: 'Altamira do Maranhão', state: 'MA' },
  'alto alegre do maranhao': { name: 'Alto Alegre do Maranhão', state: 'MA' },
  'alto alegre do pindare': { name: 'Alto Alegre do Pindaré', state: 'MA' },
  'alto parnaiba': { name: 'Alto Parnaíba', state: 'MA' },
  'amapa do maranhao': { name: 'Amapá do Maranhão', state: 'MA' },
  'amarante do maranhao': { name: 'Amarante do Maranhão', state: 'MA' },
  anajatuba: { name: 'Anajatuba', state: 'MA' },
  anapurus: { name: 'Anapurus', state: 'MA' },
  'apicum-acu': { name: 'Apicum-Açu', state: 'MA' },
  araguana: { name: 'Araguanã', state: 'MA' },
  araioses: { name: 'Araioses', state: 'MA' },
  arame: { name: 'Arame', state: 'MA' },
  arari: { name: 'Arari', state: 'MA' },
  axixa: { name: 'Axixá', state: 'MA' },
  bacabal: { name: 'Bacabal', state: 'MA' },
  bacabeira: { name: 'Bacabeira', state: 'MA' },
  bacuri: { name: 'Bacuri', state: 'MA' },
  bacurituba: { name: 'Bacurituba', state: 'MA' },
  balsas: { name: 'Balsas', state: 'MA' },
  'barao de grajau': { name: 'Barão de Grajaú', state: 'MA' },
  'barra do corda': { name: 'Barra do Corda', state: 'MA' },
  barreirinhas: { name: 'Barreirinhas', state: 'MA' },
  belagua: { name: 'Belágua', state: 'MA' },
  'bela vista do maranhao': { name: 'Bela Vista do Maranhão', state: 'MA' },
  'benedito leite': { name: 'Benedito Leite', state: 'MA' },
  bequimao: { name: 'Bequimão', state: 'MA' },
  'bernardo do mearim': { name: 'Bernardo do Mearim', state: 'MA' },
  'boa vista do gurupi': { name: 'Boa Vista do Gurupi', state: 'MA' },
  'bom jardim': { name: 'Bom Jardim', state: 'MA' },
  'bom jesus das selvas': { name: 'Bom Jesus das Selvas', state: 'MA' },
  'bom lugar': { name: 'Bom Lugar', state: 'MA' },
  brejo: { name: 'Brejo', state: 'MA' },
  'brejo de areia': { name: 'Brejo de Areia', state: 'MA' },
  buriti: { name: 'Buriti', state: 'MA' },
  'buriti bravo': { name: 'Buriti Bravo', state: 'MA' },
  buriticupu: { name: 'Buriticupu', state: 'MA' },
  buritirana: { name: 'Buritirana', state: 'MA' },
  'cachoeira grande': { name: 'Cachoeira Grande', state: 'MA' },
  cajapio: { name: 'Cajapió', state: 'MA' },
  cajari: { name: 'Cajari', state: 'MA' },
  'campestre do maranhao': { name: 'Campestre do Maranhão', state: 'MA' },
  'candido mendes': { name: 'Cândido Mendes', state: 'MA' },
  cantanhede: { name: 'Cantanhede', state: 'MA' },
  'capinzal do norte': { name: 'Capinzal do Norte', state: 'MA' },
  carolina: { name: 'Carolina', state: 'MA' },
  carutapera: { name: 'Carutapera', state: 'MA' },
  caxias: { name: 'Caxias', state: 'MA' },
  cedral: { name: 'Cedral', state: 'MA' },
  'central do maranhao': { name: 'Central do Maranhão', state: 'MA' },
  'centro do guilherme': { name: 'Centro do Guilherme', state: 'MA' },
  'centro novo do maranhao': { name: 'Centro Novo do Maranhão', state: 'MA' },
  chapadinha: { name: 'Chapadinha', state: 'MA' },
  cidelandia: { name: 'Cidelândia', state: 'MA' },
  codo: { name: 'Codó', state: 'MA' },
  'coelho neto': { name: 'Coelho Neto', state: 'MA' },
  colinas: { name: 'Colinas', state: 'MA' },
  'conceicao do lago acu': { name: 'Conceição do Lago Açu', state: 'MA' },
  coroata: { name: 'Coroatá', state: 'MA' },
  cururupu: { name: 'Cururupu', state: 'MA' },
  davinopolis_: { name: 'Davinópolis', state: 'MA' },
  'dom pedro': { name: 'Dom Pedro', state: 'MA' },
  'duque bacelar': { name: 'Duque Bacelar', state: 'MA' },
  esperantinopolis: { name: 'Esperantinópolis', state: 'MA' },
  estreito: { name: 'Estreito', state: 'MA' },
  'feira nova do maranhao': { name: 'Feira Nova do Maranhão', state: 'MA' },
  'fernando falcao': { name: 'Fernando Falcão', state: 'MA' },
  'formosa da serra negra': { name: 'Formosa da Serra Negra', state: 'MA' },
  'fortaleza dos nogueiras': { name: 'Fortaleza dos Nogueiras', state: 'MA' },
  fortuna: { name: 'Fortuna', state: 'MA' },
  'godofredo viana': { name: 'Godofredo Viana', state: 'MA' },
  'goncalves dias': { name: 'Gonçalves Dias', state: 'MA' },
  'governador archer': { name: 'Governador Archer', state: 'MA' },
  'governador edison lobao': { name: 'Governador Edison Lobão', state: 'MA' },
  'governador eugenio barros': { name: 'Governador Eugênio Barros', state: 'MA' },
  'governador luiz rocha': { name: 'Governador Luiz Rocha', state: 'MA' },
  'governador newton bello': { name: 'Governador Newton Bello', state: 'MA' },
  'governador nunes freire': { name: 'Governador Nunes Freire', state: 'MA' },
  'graca aranha': { name: 'Graça Aranha', state: 'MA' },
  grajau: { name: 'Grajaú', state: 'MA' },
  guimaraes: { name: 'Guimarães', state: 'MA' },
  'humberto de campos': { name: 'Humberto de Campos', state: 'MA' },
  icatu: { name: 'Icatu', state: 'MA' },
  'igarape do meio': { name: 'Igarapé do Meio', state: 'MA' },
  'igarape grande': { name: 'Igarapé Grande', state: 'MA' },
  imperatriz: { name: 'Imperatriz', state: 'MA' },
  'itaipava do grajau': { name: 'Itaipava do Grajaú', state: 'MA' },
  'itapecuru-mirim': { name: 'Itapecuru-Mirim', state: 'MA' },
  'itinga do maranhao': { name: 'Itinga do Maranhão', state: 'MA' },
  jatoba: { name: 'Jatobá', state: 'MA' },
  'jenipapo dos vieiras': { name: 'Jenipapo dos Vieiras', state: 'MA' },
  'joao lisboa': { name: 'João Lisboa', state: 'MA' },
  joselandia: { name: 'Joselândia', state: 'MA' },
  'junco do maranhao': { name: 'Junco do Maranhão', state: 'MA' },
  'lagoa do mato': { name: 'Lagoa do Mato', state: 'MA' },
  'lagoa grande do maranhao': { name: 'Lagoa Grande do Maranhão', state: 'MA' },
  'lago da pedra': { name: 'Lago da Pedra', state: 'MA' },
  'lago do junco': { name: 'Lago do Junco', state: 'MA' },
  'lago dos rodrigues': { name: 'Lago dos Rodrigues', state: 'MA' },
  'lago verde': { name: 'Lago Verde', state: 'MA' },
  'lajeado novo': { name: 'Lajeado Novo', state: 'MA' },
  'lima campos': { name: 'Lima Campos', state: 'MA' },
  loreto: { name: 'Loreto', state: 'MA' },
  'luis domingues': { name: 'Luís Domingues', state: 'MA' },
  'magalhaes de almeida': { name: 'Magalhães de Almeida', state: 'MA' },
  maracacume: { name: 'Maracaçumé', state: 'MA' },
  'maraja do sena': { name: 'Marajá do Sena', state: 'MA' },
  maranhaozinho: { name: 'Maranhãozinho', state: 'MA' },
  'mata roma': { name: 'Mata Roma', state: 'MA' },
  matinha: { name: 'Matinha', state: 'MA' },
  matoes: { name: 'Matões', state: 'MA' },
  'matoes do norte': { name: 'Matões do Norte', state: 'MA' },
  'milagres do maranhao': { name: 'Milagres do Maranhão', state: 'MA' },
  mirador: { name: 'Mirador', state: 'MA' },
  'miranda do norte': { name: 'Miranda do Norte', state: 'MA' },
  mirinzal: { name: 'Mirinzal', state: 'MA' },
  moncao: { name: 'Monção', state: 'MA' },
  'montes altos': { name: 'Montes Altos', state: 'MA' },
  morros: { name: 'Morros', state: 'MA' },
  'nina rodrigues': { name: 'Nina Rodrigues', state: 'MA' },
  'nova colinas': { name: 'Nova Colinas', state: 'MA' },
  'nova iorque': { name: 'Nova Iorque', state: 'MA' },
  'nova olinda do maranhao': { name: 'Nova Olinda do Maranhão', state: 'MA' },
  "olho d'agua das cunhas": { name: "Olho d'Água das Cunhãs", state: 'MA' },
  'olinda nova do maranhao': { name: 'Olinda Nova do Maranhão', state: 'MA' },
  'paco do lumiar': { name: 'Paço do Lumiar', state: 'MA' },
  palmeirandia: { name: 'Palmeirândia', state: 'MA' },
  paraibano: { name: 'Paraibano', state: 'MA' },
  parnarama: { name: 'Parnarama', state: 'MA' },
  'passagem franca': { name: 'Passagem Franca', state: 'MA' },
  'pastos bons': { name: 'Pastos Bons', state: 'MA' },
  'paulino neves': { name: 'Paulino Neves', state: 'MA' },
  'paulo ramos': { name: 'Paulo Ramos', state: 'MA' },
  pedreiras: { name: 'Pedreiras', state: 'MA' },
  'pedro do rosario': { name: 'Pedro do Rosário', state: 'MA' },
  penalva: { name: 'Penalva', state: 'MA' },
  'peri mirim': { name: 'Peri Mirim', state: 'MA' },
  peritoro: { name: 'Peritoró', state: 'MA' },
  'pindare-mirim': { name: 'Pindaré-Mirim', state: 'MA' },
  pinheiro: { name: 'Pinheiro', state: 'MA' },
  'pio xii': { name: 'Pio XII', state: 'MA' },
  pirapemas: { name: 'Pirapemas', state: 'MA' },
  'pocao de pedras': { name: 'Poção de Pedras', state: 'MA' },
  'porto franco': { name: 'Porto Franco', state: 'MA' },
  'porto rico do maranhao': { name: 'Porto Rico do Maranhão', state: 'MA' },
  'presidente dutra_': { name: 'Presidente Dutra', state: 'MA' },
  'presidente juscelino': { name: 'Presidente Juscelino', state: 'MA' },
  'presidente medici': { name: 'Presidente Médici', state: 'MA' },
  'presidente sarney': { name: 'Presidente Sarney', state: 'MA' },
  'presidente vargas': { name: 'Presidente Vargas', state: 'MA' },
  'primeira cruz': { name: 'Primeira Cruz', state: 'MA' },
  raposa: { name: 'Raposa', state: 'MA' },
  riachao: { name: 'Riachão', state: 'MA' },
  'ribamar fiquene': { name: 'Ribamar Fiquene', state: 'MA' },
  rosario: { name: 'Rosário', state: 'MA' },
  sambaiba: { name: 'Sambaíba', state: 'MA' },
  'santa filomena do maranhao': { name: 'Santa Filomena do Maranhão', state: 'MA' },
  'santa helena': { name: 'Santa Helena', state: 'MA' },
  'santa ines_': { name: 'Santa Inês', state: 'MA' },
  'santa luzia_': { name: 'Santa Luzia', state: 'MA' },
  'santa luzia do parua': { name: 'Santa Luzia do Paruá', state: 'MA' },
  'santana do maranhao': { name: 'Santana do Maranhão', state: 'MA' },
  'santa quiteria do maranhao': { name: 'Santa Quitéria do Maranhão', state: 'MA' },
  'santa rita': { name: 'Santa Rita', state: 'MA' },
  'santo amaro do maranhao': { name: 'Santo Amaro do Maranhão', state: 'MA' },
  'santo antonio dos lopes': { name: 'Santo Antônio dos Lopes', state: 'MA' },
  'sao benedito do rio preto': { name: 'São Benedito do Rio Preto', state: 'MA' },
  'sao bento': { name: 'São Bento', state: 'MA' },
  'sao bernardo': { name: 'São Bernardo', state: 'MA' },
  'sao domingos do azeitao': { name: 'São Domingos do Azeitão', state: 'MA' },
  'sao domingos do maranhao': { name: 'São Domingos do Maranhão', state: 'MA' },
  'sao felix de balsas': { name: 'São Félix de Balsas', state: 'MA' },
  'sao francisco do brejao': { name: 'São Francisco do Brejão', state: 'MA' },
  'sao francisco do maranhao': { name: 'São Francisco do Maranhão', state: 'MA' },
  'sao joao batista': { name: 'São João Batista', state: 'MA' },
  'sao joao do caru': { name: 'São João do Caru', state: 'MA' },
  'sao joao do paraiso': { name: 'São João do Paraíso', state: 'MA' },
  'sao joao do soter': { name: 'São João do Soter', state: 'MA' },
  'sao joao dos patos': { name: 'São João dos Patos', state: 'MA' },
  'sao jose de ribamar': { name: 'São José de Ribamar', state: 'MA' },
  'sao jose dos basilios': { name: 'São José dos Basílios', state: 'MA' },
  'sao luis': { name: 'São Luís', state: 'MA' },
  'sao luis gonzaga do maranhao': { name: 'São Luís Gonzaga do Maranhão', state: 'MA' },
  'sao mateus do maranhao': { name: 'São Mateus do Maranhão', state: 'MA' },
  'sao pedro da agua branca': { name: 'São Pedro da Água Branca', state: 'MA' },
  'sao pedro dos crentes': { name: 'São Pedro dos Crentes', state: 'MA' },
  'sao raimundo das mangabeiras': { name: 'São Raimundo das Mangabeiras', state: 'MA' },
  'sao raimundo do doca bezerra': { name: 'São Raimundo do Doca Bezerra', state: 'MA' },
  'sao roberto': { name: 'São Roberto', state: 'MA' },
  'sao vicente ferrer': { name: 'São Vicente Ferrer', state: 'MA' },
  satubinha: { name: 'Satubinha', state: 'MA' },
  'senador alexandre costa': { name: 'Senador Alexandre Costa', state: 'MA' },
  'senador la rocque': { name: 'Senador La Rocque', state: 'MA' },
  'serrano do maranhao': { name: 'Serrano do Maranhão', state: 'MA' },
  'sitio novo': { name: 'Sítio Novo', state: 'MA' },
  'sucupira do norte': { name: 'Sucupira do Norte', state: 'MA' },
  'sucupira do riachao': { name: 'Sucupira do Riachão', state: 'MA' },
  'tasso fragoso': { name: 'Tasso Fragoso', state: 'MA' },
  timbiras: { name: 'Timbiras', state: 'MA' },
  timon: { name: 'Timon', state: 'MA' },
  'trizidela do vale': { name: 'Trizidela do Vale', state: 'MA' },
  tufilandia: { name: 'Tufilândia', state: 'MA' },
  tuntum: { name: 'Tuntum', state: 'MA' },
  turiacu: { name: 'Turiaçu', state: 'MA' },
  turilandia: { name: 'Turilândia', state: 'MA' },
  tutoia: { name: 'Tutóia', state: 'MA' },
  'urbano santos': { name: 'Urbano Santos', state: 'MA' },
  'vargem grande': { name: 'Vargem Grande', state: 'MA' },
  viana_: { name: 'Viana', state: 'MA' },
  'vila nova dos martirios': { name: 'Vila Nova dos Martírios', state: 'MA' },
  'vitoria do mearim': { name: 'Vitória do Mearim', state: 'MA' },
  'vitorino freire': { name: 'Vitorino Freire', state: 'MA' },
  'ze doca': { name: 'Zé Doca', state: 'MA' },
};
