export const cities = {
  acailandia: 'Açailândia',
  'afonso cunha': 'Afonso Cunha',
  'agua doce do maranhao': 'Água Doce do Maranhão',
  alcantara: 'Alcântara',
  'aldeias altas': 'Aldeias Altas',
  'altamira do maranhao': 'Altamira do Maranhão',
  'alto alegre do maranhao': 'Alto Alegre do Maranhão',
  'alto alegre do pindare': 'Alto Alegre do Pindaré',
  'alto parnaiba': 'Alto Parnaíba',
  'amapa do maranhao': 'Amapá do Maranhão',
  'amarante do maranhao': 'Amarante do Maranhão',
  anajatuba: 'Anajatuba',
  anapurus: 'Anapurus',
  'apicum-acu': 'Apicum-Açu',
  araguana: 'Araguanã',
  araioses: 'Araioses',
  arame: 'Arame',
  arari: 'Arari',
  axixa: 'Axixá',
  bacabal: 'Bacabal',
  bacabeira: 'Bacabeira',
  bacuri: 'Bacuri',
  bacurituba: 'Bacurituba',
  balsas: 'Balsas',
  'barao de grajau': 'Barão de Grajaú',
  'barra do corda': 'Barra do Corda',
  barreirinhas: 'Barreirinhas',
  belagua: 'Belágua',
  'bela vista do maranhao': 'Bela Vista do Maranhão',
  'benedito leite': 'Benedito Leite',
  bequimao: 'Bequimão',
  'bernardo do mearim': 'Bernardo do Mearim',
  'boa vista do gurupi': 'Boa Vista do Gurupi',
  'bom jardim': 'Bom Jardim',
  'bom jesus das selvas': 'Bom Jesus das Selvas',
  'bom lugar': 'Bom Lugar',
  brejo: 'Brejo',
  'brejo de areia': 'Brejo de Areia',
  buriti: 'Buriti',
  'buriti bravo': 'Buriti Bravo',
  buriticupu: 'Buriticupu',
  buritirana: 'Buritirana',
  'cachoeira grande': 'Cachoeira Grande',
  cajapio: 'Cajapió',
  cajari: 'Cajari',
  'campestre do maranhao': 'Campestre do Maranhão',
  'candido mendes': 'Cândido Mendes',
  cantanhede: 'Cantanhede',
  'capinzal do norte': 'Capinzal do Norte',
  carolina: 'Carolina',
  carutapera: 'Carutapera',
  caxias: 'Caxias',
  cedral: 'Cedral',
  'central do maranhao': 'Central do Maranhão',
  'centro do guilherme': 'Centro do Guilherme',
  'centro novo do maranhao': 'Centro Novo do Maranhão',
  chapadinha: 'Chapadinha',
  cidelandia: 'Cidelândia',
  codo: 'Codó',
  'coelho neto': 'Coelho Neto',
  colinas: 'Colinas',
  'conceicao do lago acu': 'Conceição do Lago Açu',
  coroata: 'Coroatá',
  cururupu: 'Cururupu',
  davinopolis_: 'Davinópolis',
  'dom pedro': 'Dom Pedro',
  'duque bacelar': 'Duque Bacelar',
  esperantinopolis: 'Esperantinópolis',
  estreito: 'Estreito',
  'feira nova do maranhao': 'Feira Nova do Maranhão',
  'fernando falcao': 'Fernando Falcão',
  'formosa da serra negra': 'Formosa da Serra Negra',
  'fortaleza dos nogueiras': 'Fortaleza dos Nogueiras',
  fortuna: 'Fortuna',
  'godofredo viana': 'Godofredo Viana',
  'goncalves dias': 'Gonçalves Dias',
  'governador archer': 'Governador Archer',
  'governador edison lobao': 'Governador Edison Lobão',
  'governador eugenio barros': 'Governador Eugênio Barros',
  'governador luiz rocha': 'Governador Luiz Rocha',
  'governador newton bello': 'Governador Newton Bello',
  'governador nunes freire': 'Governador Nunes Freire',
  'graca aranha': 'Graça Aranha',
  grajau: 'Grajaú',
  guimaraes: 'Guimarães',
  'humberto de campos': 'Humberto de Campos',
  icatu: 'Icatu',
  'igarape do meio': 'Igarapé do Meio',
  'igarape grande': 'Igarapé Grande',
  imperatriz: 'Imperatriz',
  'itaipava do grajau': 'Itaipava do Grajaú',
  'itapecuru-mirim': 'Itapecuru-Mirim',
  'itinga do maranhao': 'Itinga do Maranhão',
  jatoba: 'Jatobá',
  'jenipapo dos vieiras': 'Jenipapo dos Vieiras',
  'joao lisboa': 'João Lisboa',
  joselandia: 'Joselândia',
  'junco do maranhao': 'Junco do Maranhão',
  'lagoa do mato': 'Lagoa do Mato',
  'lagoa grande do maranhao': 'Lagoa Grande do Maranhão',
  'lago da pedra': 'Lago da Pedra',
  'lago do junco': 'Lago do Junco',
  'lago dos rodrigues': 'Lago dos Rodrigues',
  'lago verde': 'Lago Verde',
  'lajeado novo': 'Lajeado Novo',
  'lima campos': 'Lima Campos',
  loreto: 'Loreto',
  'luis domingues': 'Luís Domingues',
  'magalhaes de almeida': 'Magalhães de Almeida',
  maracacume: 'Maracaçumé',
  'maraja do sena': 'Marajá do Sena',
  maranhaozinho: 'Maranhãozinho',
  'mata roma': 'Mata Roma',
  matinha: 'Matinha',
  matoes: 'Matões',
  'matoes do norte': 'Matões do Norte',
  'milagres do maranhao': 'Milagres do Maranhão',
  mirador: 'Mirador',
  'miranda do norte': 'Miranda do Norte',
  mirinzal: 'Mirinzal',
  moncao: 'Monção',
  'montes altos': 'Montes Altos',
  morros: 'Morros',
  'nina rodrigues': 'Nina Rodrigues',
  'nova colinas': 'Nova Colinas',
  'nova iorque': 'Nova Iorque',
  'nova olinda do maranhao': 'Nova Olinda do Maranhão',
  "olho d'agua das cunhas": "Olho d'Água das Cunhãs",
  'olinda nova do maranhao': 'Olinda Nova do Maranhão',
  'paco do lumiar': 'Paço do Lumiar',
  palmeirandia: 'Palmeirândia',
  paraibano: 'Paraibano',
  parnarama: 'Parnarama',
  'passagem franca': 'Passagem Franca',
  'pastos bons': 'Pastos Bons',
  'paulino neves': 'Paulino Neves',
  'paulo ramos': 'Paulo Ramos',
  pedreiras: 'Pedreiras',
  'pedro do rosario': 'Pedro do Rosário',
  penalva: 'Penalva',
  'peri mirim': 'Peri Mirim',
  peritoro: 'Peritoró',
  'pindare-mirim': 'Pindaré-Mirim',
  pinheiro: 'Pinheiro',
  'pio xii': 'Pio XII',
  pirapemas: 'Pirapemas',
  'pocao de pedras': 'Poção de Pedras',
  'porto franco': 'Porto Franco',
  'porto rico do maranhao': 'Porto Rico do Maranhão',
  'presidente dutra_': 'Presidente Dutra',
  'presidente juscelino': 'Presidente Juscelino',
  'presidente medici': 'Presidente Médici',
  'presidente sarney': 'Presidente Sarney',
  'presidente vargas': 'Presidente Vargas',
  'primeira cruz': 'Primeira Cruz',
  raposa: 'Raposa',
  riachao: 'Riachão',
  'ribamar fiquene': 'Ribamar Fiquene',
  rosario: 'Rosário',
  sambaiba: 'Sambaíba',
  'santa filomena do maranhao': 'Santa Filomena do Maranhão',
  'santa helena': 'Santa Helena',
  'santa ines_': 'Santa Inês',
  'santa luzia_': 'Santa Luzia',
  'santa luzia do parua': 'Santa Luzia do Paruá',
  'santana do maranhao': 'Santana do Maranhão',
  'santa quiteria do maranhao': 'Santa Quitéria do Maranhão',
  'santa rita': 'Santa Rita',
  'santo amaro do maranhao': 'Santo Amaro do Maranhão',
  'santo antonio dos lopes': 'Santo Antônio dos Lopes',
  'sao benedito do rio preto': 'São Benedito do Rio Preto',
  'sao bento': 'São Bento',
  'sao bernardo': 'São Bernardo',
  'sao domingos do azeitao': 'São Domingos do Azeitão',
  'sao domingos do maranhao': 'São Domingos do Maranhão',
  'sao felix de balsas': 'São Félix de Balsas',
  'sao francisco do brejao': 'São Francisco do Brejão',
  'sao francisco do maranhao': 'São Francisco do Maranhão',
  'sao joao batista': 'São João Batista',
  'sao joao do caru': 'São João do Caru',
  'sao joao do paraiso': 'São João do Paraíso',
  'sao joao do soter': 'São João do Soter',
  'sao joao dos patos': 'São João dos Patos',
  'sao jose de ribamar': 'São José de Ribamar',
  'sao jose dos basilios': 'São José dos Basílios',
  'sao luis': 'São Luís',
  'sao luis gonzaga do maranhao': 'São Luís Gonzaga do Maranhão',
  'sao mateus do maranhao': 'São Mateus do Maranhão',
  'sao pedro da agua branca': 'São Pedro da Água Branca',
  'sao pedro dos crentes': 'São Pedro dos Crentes',
  'sao raimundo das mangabeiras': 'São Raimundo das Mangabeiras',
  'sao raimundo do doca bezerra': 'São Raimundo do Doca Bezerra',
  'sao roberto': 'São Roberto',
  'sao vicente ferrer': 'São Vicente Ferrer',
  satubinha: 'Satubinha',
  'senador alexandre costa': 'Senador Alexandre Costa',
  'senador la rocque': 'Senador La Rocque',
  'serrano do maranhao': 'Serrano do Maranhão',
  'sitio novo': 'Sítio Novo',
  'sucupira do norte': 'Sucupira do Norte',
  'sucupira do riachao': 'Sucupira do Riachão',
  'tasso fragoso': 'Tasso Fragoso',
  timbiras: 'Timbiras',
  timon: 'Timon',
  'trizidela do vale': 'Trizidela do Vale',
  tufilandia: 'Tufilândia',
  tuntum: 'Tuntum',
  turiacu: 'Turiaçu',
  turilandia: 'Turilândia',
  tutoia: 'Tutóia',
  'urbano santos': 'Urbano Santos',
  'vargem grande': 'Vargem Grande',
  viana_: 'Viana',
  'vila nova dos martirios': 'Vila Nova dos Martírios',
  'vitoria do mearim': 'Vitória do Mearim',
  'vitorino freire': 'Vitorino Freire',
  'ze doca': 'Zé Doca',
};
