export const cities = {
  'abadia dos dourados': 'Abadia dos Dourados',
  abaete: 'Abaeté',
  'abre campo': 'Abre Campo',
  acaiaca: 'Acaiaca',
  acucena: 'Açucena',
  'agua boa': 'Água Boa',
  'agua comprida': 'Água Comprida',
  aguanil: 'Aguanil',
  'aguas formosas': 'Águas Formosas',
  'aguas vermelhas': 'Águas Vermelhas',
  aimores: 'Aimorés',
  aiuruoca: 'Aiuruoca',
  alagoa: 'Alagoa',
  albertina: 'Albertina',
  'alem paraiba': 'Além Paraíba',
  alfenas: 'Alfenas',
  'alfredo vasconcelos': 'Alfredo Vasconcelos',
  almenara: 'Almenara',
  alpercata: 'Alpercata',
  alpinopolis: 'Alpinópolis',
  alterosa: 'Alterosa',
  'alto caparao': 'Alto Caparaó',
  'alto jequitiba': 'Alto Jequitibá',
  'alto rio doce': 'Alto Rio Doce',
  alvarenga: 'Alvarenga',
  alvinopolis: 'Alvinópolis',
  'alvorada de minas': 'Alvorada de Minas',
  'amparo da serra': 'Amparo da Serra',
  andradas: 'Andradas',
  andrelandia: 'Andrelândia',
  angelandia: 'Angelândia',
  'antonio carlos': 'Antônio Carlos',
  'antonio dias': 'Antônio Dias',
  'antonio prado de minas': 'Antônio Prado de Minas',
  aracai: 'Araçaí',
  aracitaba: 'Aracitaba',
  aracuai: 'Araçuaí',
  araguari: 'Araguari',
  arantina: 'Arantina',
  araponga: 'Araponga',
  arapora: 'Araporã',
  arapua: 'Arapuá',
  araujos: 'Araújos',
  araxa: 'Araxá',
  arceburgo: 'Arceburgo',
  arcos: 'Arcos',
  areado: 'Areado',
  argirita: 'Argirita',
  aricanduva: 'Aricanduva',
  arinos: 'Arinos',
  'astolfo dutra': 'Astolfo Dutra',
  ataleia: 'Ataléia',
  'augusto de lima': 'Augusto de Lima',
  baependi: 'Baependi',
  baldim: 'Baldim',
  bambui: 'Bambuí',
  bandeira: 'Bandeira',
  'bandeira do sul': 'Bandeira do Sul',
  'barao de cocais': 'Barão de Cocais',
  'barao de monte alto': 'Barão de Monte Alto',
  barbacena: 'Barbacena',
  'barra longa': 'Barra Longa',
  barroso: 'Barroso',
  'bela vista de minas': 'Bela Vista de Minas',
  'belmiro braga': 'Belmiro Braga',
  'belo horizonte': 'Belo Horizonte',
  'belo oriente': 'Belo Oriente',
  'belo vale': 'Belo Vale',
  berilo: 'Berilo',
  berizal: 'Berizal',
  bertopolis: 'Bertópolis',
  betim: 'Betim',
  'bias fortes': 'Bias Fortes',
  bicas: 'Bicas',
  biquinhas: 'Biquinhas',
  'boa esperanca_': 'Boa Esperança',
  'bocaina de minas': 'Bocaina de Minas',
  bocaiuva: 'Bocaiuva',
  'bom despacho': 'Bom Despacho',
  'bom jardim de minas': 'Bom Jardim de Minas',
  'bom jesus da penha': 'Bom Jesus da Penha',
  'bom jesus do amparo': 'Bom Jesus do Amparo',
  'bom jesus do galho': 'Bom Jesus do Galho',
  'bom repouso': 'Bom Repouso',
  'bom sucesso': 'Bom Sucesso',
  bonfim: 'Bonfim',
  'bonfinopolis de minas': 'Bonfinópolis de Minas',
  'bonito de minas': 'Bonito de Minas',
  'borda da mata': 'Borda da Mata',
  botelhos: 'Botelhos',
  botumirim: 'Botumirim',
  'brasilandia de minas': 'Brasilândia de Minas',
  'brasilia de minas': 'Brasília de Minas',
  brasopolis: 'Brasópolis',
  'bras pires': 'Brás Pires',
  braunas: 'Braúnas',
  brumadinho: 'Brumadinho',
  'bueno brandao': 'Bueno Brandão',
  buenopolis: 'Buenópolis',
  bugre: 'Bugre',
  buritis: 'Buritis',
  buritizeiro: 'Buritizeiro',
  'cabeceira grande': 'Cabeceira Grande',
  'cabo verde': 'Cabo Verde',
  'cachoeira da prata': 'Cachoeira da Prata',
  'cachoeira de minas': 'Cachoeira de Minas',
  'cachoeira de pajeu': 'Cachoeira de Pajeú',
  'cachoeira dourada_': 'Cachoeira Dourada',
  caetanopolis: 'Caetanópolis',
  caete: 'Caeté',
  caiana: 'Caiana',
  cajuri: 'Cajuri',
  caldas: 'Caldas',
  camacho: 'Camacho',
  camanducaia: 'Camanducaia',
  cambui: 'Cambuí',
  cambuquira: 'Cambuquira',
  campanario: 'Campanário',
  campanha: 'Campanha',
  campestre_: 'Campestre',
  'campina verde': 'Campina Verde',
  'campo azul': 'Campo Azul',
  'campo belo': 'Campo Belo',
  'campo do meio': 'Campo do Meio',
  'campo florido': 'Campo Florido',
  'campos altos': 'Campos Altos',
  'campos gerais': 'Campos Gerais',
  canaa: 'Canaã',
  canapolis_: 'Canápolis',
  'cana verde': 'Cana Verde',
  candeias_: 'Candeias',
  cantagalo: 'Cantagalo',
  caparao: 'Caparaó',
  'capela nova': 'Capela Nova',
  capelinha: 'Capelinha',
  capetinga: 'Capetinga',
  'capim branco': 'Capim Branco',
  capinopolis: 'Capinópolis',
  'capitao andrade': 'Capitão Andrade',
  'capitao eneas': 'Capitão Enéas',
  capitolio: 'Capitólio',
  caputira: 'Caputira',
  carai: 'Caraí',
  caranaiba: 'Caranaíba',
  carandai: 'Carandaí',
  carangola: 'Carangola',
  caratinga: 'Caratinga',
  carbonita: 'Carbonita',
  careacu: 'Careaçu',
  'carlos chagas': 'Carlos Chagas',
  carmesia: 'Carmésia',
  'carmo da cachoeira': 'Carmo da Cachoeira',
  'carmo da mata': 'Carmo da Mata',
  'carmo de minas': 'Carmo de Minas',
  'carmo do cajuru': 'Carmo do Cajuru',
  'carmo do paranaiba': 'Carmo do Paranaíba',
  'carmo do rio claro': 'Carmo do Rio Claro',
  'carmopolis de minas': 'Carmópolis de Minas',
  carneirinho: 'Carneirinho',
  carrancas: 'Carrancas',
  carvalhopolis: 'Carvalhópolis',
  carvalhos: 'Carvalhos',
  'casa grande': 'Casa Grande',
  'cascalho rico': 'Cascalho Rico',
  cassia: 'Cássia',
  cataguases: 'Cataguases',
  'catas altas': 'Catas Altas',
  'catas altas da noruega': 'Catas Altas da Noruega',
  catuji: 'Catuji',
  catuti: 'Catuti',
  caxambu: 'Caxambu',
  'cedro do abaete': 'Cedro do Abaeté',
  'central de minas': 'Central de Minas',
  centralina: 'Centralina',
  chacara: 'Chácara',
  chale: 'Chalé',
  'chapada do norte': 'Chapada do Norte',
  'chapada gaucha': 'Chapada Gaúcha',
  chiador: 'Chiador',
  cipotanea: 'Cipotânea',
  claraval: 'Claraval',
  'claro dos pocoes': 'Claro dos Poções',
  claudio: 'Cláudio',
  coimbra: 'Coimbra',
  coluna: 'Coluna',
  'comendador gomes': 'Comendador Gomes',
  comercinho: 'Comercinho',
  'conceicao da aparecida': 'Conceição da Aparecida',
  'conceicao da barra de minas': 'Conceição da Barra de Minas',
  'conceicao das alagoas': 'Conceição das Alagoas',
  'conceicao das pedras': 'Conceição das Pedras',
  'conceicao de ipanema': 'Conceição de Ipanema',
  'conceicao do mato dentro': 'Conceição do Mato Dentro',
  'conceicao do para': 'Conceição do Pará',
  'conceicao do rio verde': 'Conceição do Rio Verde',
  'conceicao dos ouros': 'Conceição dos Ouros',
  'conego marinho': 'Cônego Marinho',
  confins: 'Confins',
  congonhal: 'Congonhal',
  congonhas: 'Congonhas',
  'congonhas do norte': 'Congonhas do Norte',
  conquista: 'Conquista',
  'conselheiro lafaiete': 'Conselheiro Lafaiete',
  'conselheiro pena': 'Conselheiro Pena',
  consolacao: 'Consolação',
  contagem: 'Contagem',
  coqueiral: 'Coqueiral',
  'coracao de jesus': 'Coração de Jesus',
  cordisburgo: 'Cordisburgo',
  cordislandia: 'Cordislândia',
  corinto: 'Corinto',
  coroaci: 'Coroaci',
  coromandel: 'Coromandel',
  'coronel fabriciano': 'Coronel Fabriciano',
  'coronel murta': 'Coronel Murta',
  'coronel pacheco': 'Coronel Pacheco',
  'coronel xavier chaves': 'Coronel Xavier Chaves',
  'corrego danta': 'Córrego Danta',
  'corrego do bom jesus': 'Córrego do Bom Jesus',
  'corrego fundo': 'Córrego Fundo',
  'corrego novo': 'Córrego Novo',
  'couto de magalhaes de minas': 'Couto de Magalhães de Minas',
  crisolita: 'Crisólita',
  cristais: 'Cristais',
  cristalia: 'Cristália',
  'cristiano otoni': 'Cristiano Otoni',
  cristina: 'Cristina',
  crucilandia: 'Crucilândia',
  'cruzeiro da fortaleza': 'Cruzeiro da Fortaleza',
  cruzilia: 'Cruzília',
  cuparaque: 'Cuparaque',
  'curral de dentro': 'Curral de Dentro',
  curvelo: 'Curvelo',
  datas: 'Datas',
  'delfim moreira': 'Delfim Moreira',
  delfinopolis: 'Delfinópolis',
  delta: 'Delta',
  descoberto: 'Descoberto',
  'desterro de entre rios': 'Desterro de Entre Rios',
  'desterro do melo': 'Desterro do Melo',
  diamantina: 'Diamantina',
  'diogo de vasconcelos': 'Diogo de Vasconcelos',
  dionisio: 'Dionísio',
  divinesia: 'Divinésia',
  divino: 'Divino',
  'divino das laranjeiras': 'Divino das Laranjeiras',
  'divinolandia de minas': 'Divinolândia de Minas',
  divinopolis: 'Divinópolis',
  'divisa alegre': 'Divisa Alegre',
  'divisa nova': 'Divisa Nova',
  divisopolis: 'Divisópolis',
  'dom bosco': 'Dom Bosco',
  'dom cavati': 'Dom Cavati',
  'dom joaquim': 'Dom Joaquim',
  'dom silverio': 'Dom Silvério',
  'dom vicoso': 'Dom Viçoso',
  'dona euzebia': 'Dona Euzébia',
  'dores de campos': 'Dores de Campos',
  'dores de guanhaes': 'Dores de Guanhães',
  'dores do indaia': 'Dores do Indaiá',
  'dores do turvo': 'Dores do Turvo',
  doresopolis: 'Doresópolis',
  douradoquara: 'Douradoquara',
  durande: 'Durandé',
  'eloi mendes': 'Elói Mendes',
  'engenheiro caldas': 'Engenheiro Caldas',
  'engenheiro navarro': 'Engenheiro Navarro',
  'entre folhas': 'Entre Folhas',
  'entre rios de minas': 'Entre Rios de Minas',
  ervalia: 'Ervália',
  esmeraldas: 'Esmeraldas',
  'espera feliz': 'Espera Feliz',
  espinosa: 'Espinosa',
  'espirito santo do dourado': 'Espírito Santo do Dourado',
  estiva: 'Estiva',
  'estrela dalva': 'Estrela Dalva',
  'estrela do indaia': 'Estrela do Indaiá',
  'estrela do sul': 'Estrela do Sul',
  eugenopolis: 'Eugenópolis',
  'ewbank da camara': 'Ewbank da Câmara',
  extrema: 'Extrema',
  fama: 'Fama',
  'faria lemos': 'Faria Lemos',
  'felicio dos santos': 'Felício dos Santos',
  felisburgo: 'Felisburgo',
  felixlandia: 'Felixlândia',
  'fernandes tourinho': 'Fernandes Tourinho',
  ferros: 'Ferros',
  fervedouro: 'Fervedouro',
  florestal: 'Florestal',
  formiga: 'Formiga',
  formoso_: 'Formoso',
  'fortaleza de minas': 'Fortaleza de Minas',
  'fortuna de minas': 'Fortuna de Minas',
  'francisco badaro': 'Francisco Badaró',
  'francisco dumont': 'Francisco Dumont',
  franciscopolis: 'Franciscópolis',
  'francisco sa': 'Francisco Sá',
  'frei gaspar': 'Frei Gaspar',
  'frei inocencio': 'Frei Inocêncio',
  'frei lagonegro': 'Frei Lagonegro',
  fronteira: 'Fronteira',
  'fronteira dos vales': 'Fronteira dos Vales',
  'fruta de leite': 'Fruta de Leite',
  frutal: 'Frutal',
  funilandia: 'Funilândia',
  galileia: 'Galileia',
  gameleiras: 'Gameleiras',
  glaucilandia: 'Glaucilândia',
  goiabeira: 'Goiabeira',
  goiana_: 'Goianá',
  goncalves: 'Gonçalves',
  gonzaga: 'Gonzaga',
  gouveia: 'Gouveia',
  'governador valadares': 'Governador Valadares',
  'grao mogol': 'Grão Mogol',
  grupiara: 'Grupiara',
  guanhaes: 'Guanhães',
  guape: 'Guapé',
  guaraciaba: 'Guaraciaba',
  guaraciama: 'Guaraciama',
  guaranesia: 'Guaranésia',
  guarani: 'Guarani',
  guarara: 'Guarará',
  'guarda-mor': 'Guarda-Mor',
  guaxupe: 'Guaxupé',
  guidoval: 'Guidoval',
  guimarania: 'Guimarânia',
  guiricema: 'Guiricema',
  gurinhata: 'Gurinhatã',
  heliodora: 'Heliodora',
  iapu: 'Iapu',
  ibertioga: 'Ibertioga',
  ibia: 'Ibiá',
  ibiai: 'Ibiaí',
  ibiracatu: 'Ibiracatu',
  ibiraci: 'Ibiraci',
  ibirite: 'Ibirité',
  'ibitiura de minas': 'Ibitiúra de Minas',
  ibituruna: 'Ibituruna',
  'icarai de minas': 'Icaraí de Minas',
  igarape: 'Igarapé',
  igaratinga: 'Igaratinga',
  iguatama: 'Iguatama',
  ijaci: 'Ijaci',
  ilicinea: 'Ilicínea',
  'imbe de minas': 'Imbé de Minas',
  inconfidentes: 'Inconfidentes',
  indaiabira: 'Indaiabira',
  indianopolis: 'Indianópolis',
  ingai: 'Ingaí',
  inhapim: 'Inhapim',
  inhauma: 'Inhaúma',
  inimutaba: 'Inimutaba',
  ipaba: 'Ipaba',
  ipanema: 'Ipanema',
  ipatinga: 'Ipatinga',
  ipiacu: 'Ipiaçu',
  ipuiuna: 'Ipuiuna',
  'irai de minas': 'Iraí de Minas',
  itabira: 'Itabira',
  itabirinha: 'Itabirinha',
  itabirito: 'Itabirito',
  itacambira: 'Itacambira',
  itacarambi: 'Itacarambi',
  itaguara: 'Itaguara',
  itaipe: 'Itaipé',
  itajuba: 'Itajubá',
  itamarandiba: 'Itamarandiba',
  'itamarati de minas': 'Itamarati de Minas',
  itambacuri: 'Itambacuri',
  'itambe do mato dentro': 'Itambé do Mato Dentro',
  itamogi: 'Itamogi',
  itamonte: 'Itamonte',
  itanhandu: 'Itanhandu',
  itanhomi: 'Itanhomi',
  itaobim: 'Itaobim',
  itapagipe: 'Itapagipe',
  itapecerica: 'Itapecerica',
  itapeva: 'Itapeva',
  itatiaiucu: 'Itatiaiuçu',
  'itau de minas': 'Itaú de Minas',
  itauna: 'Itaúna',
  itaverava: 'Itaverava',
  itinga: 'Itinga',
  itueta: 'Itueta',
  ituiutaba: 'Ituiutaba',
  itumirim: 'Itumirim',
  iturama: 'Iturama',
  itutinga: 'Itutinga',
  jaboticatubas: 'Jaboticatubas',
  jacinto: 'Jacinto',
  jacui: 'Jacuí',
  jacutinga: 'Jacutinga',
  jaguaracu: 'Jaguaraçu',
  jaiba: 'Jaíba',
  jampruca: 'Jampruca',
  janauba: 'Janaúba',
  januaria: 'Januária',
  japaraiba: 'Japaraíba',
  japonvar: 'Japonvar',
  jeceaba: 'Jeceaba',
  'jenipapo de minas': 'Jenipapo de Minas',
  jequeri: 'Jequeri',
  jequitai: 'Jequitaí',
  jequitiba: 'Jequitibá',
  jequitinhonha: 'Jequitinhonha',
  jesuania: 'Jesuânia',
  joaima: 'Joaíma',
  joanesia: 'Joanésia',
  'joao monlevade': 'João Monlevade',
  'joao pinheiro': 'João Pinheiro',
  'joaquim felicio': 'Joaquim Felício',
  jordania: 'Jordânia',
  'jose goncalves de minas': 'José Gonçalves de Minas',
  josenopolis: 'Josenópolis',
  'jose raydan': 'José Raydan',
  juatuba: 'Juatuba',
  'juiz de fora': 'Juiz de Fora',
  juramento: 'Juramento',
  juruaia: 'Juruaia',
  juvenilia: 'Juvenília',
  ladainha: 'Ladainha',
  lagamar: 'Lagamar',
  'lagoa da prata': 'Lagoa da Prata',
  'lagoa dos patos': 'Lagoa dos Patos',
  'lagoa dourada': 'Lagoa Dourada',
  'lagoa formosa': 'Lagoa Formosa',
  'lagoa grande': 'Lagoa Grande',
  'lagoa santa_': 'Lagoa Santa',
  lajinha: 'Lajinha',
  lambari: 'Lambari',
  lamim: 'Lamim',
  laranjal: 'Laranjal',
  lassance: 'Lassance',
  lavras: 'Lavras',
  'leandro ferreira': 'Leandro Ferreira',
  'leme do prado': 'Leme do Prado',
  leopoldina: 'Leopoldina',
  liberdade: 'Liberdade',
  'lima duarte': 'Lima Duarte',
  'limeira do oeste': 'Limeira do Oeste',
  lontra: 'Lontra',
  luisburgo: 'Luisburgo',
  luislandia: 'Luislândia',
  luminarias: 'Luminárias',
  luz: 'Luz',
  machacalis: 'Machacalis',
  machado: 'Machado',
  'madre de deus de minas': 'Madre de Deus de Minas',
  malacacheta: 'Malacacheta',
  mamonas: 'Mamonas',
  manga: 'Manga',
  manhuacu: 'Manhuaçu',
  manhumirim: 'Manhumirim',
  mantena: 'Mantena',
  maravilhas: 'Maravilhas',
  'mar de espanha': 'Mar de Espanha',
  'maria da fe': 'Maria da Fé',
  mariana: 'Mariana',
  marilac: 'Marilac',
  'mario campos': 'Mário Campos',
  'maripa de minas': 'Maripá de Minas',
  marlieria: 'Marliéria',
  marmelopolis: 'Marmelópolis',
  'martinho campos': 'Martinho Campos',
  'martins soares': 'Martins Soares',
  'mata verde': 'Mata Verde',
  materlandia: 'Materlândia',
  'mateus leme': 'Mateus Leme',
  'mathias lobato': 'Mathias Lobato',
  'matias barbosa': 'Matias Barbosa',
  'matias cardoso': 'Matias Cardoso',
  matipo: 'Matipó',
  'mato verde': 'Mato Verde',
  matozinhos: 'Matozinhos',
  matutina: 'Matutina',
  medeiros: 'Medeiros',
  medina: 'Medina',
  'mendes pimentel': 'Mendes Pimentel',
  merces: 'Mercês',
  mesquita: 'Mesquita',
  'minas novas': 'Minas Novas',
  minduri: 'Minduri',
  mirabela: 'Mirabela',
  miradouro: 'Miradouro',
  mirai: 'Miraí',
  miravania: 'Miravânia',
  moeda: 'Moeda',
  moema: 'Moema',
  monjolos: 'Monjolos',
  'monsenhor paulo': 'Monsenhor Paulo',
  montalvania: 'Montalvânia',
  'monte alegre de minas': 'Monte Alegre de Minas',
  'monte azul': 'Monte Azul',
  'monte belo': 'Monte Belo',
  'monte carmelo': 'Monte Carmelo',
  'monte formoso': 'Monte Formoso',
  'monte santo de minas': 'Monte Santo de Minas',
  'montes claros': 'Montes Claros',
  'monte siao': 'Monte Sião',
  montezuma: 'Montezuma',
  'morada nova de minas': 'Morada Nova de Minas',
  'morro da garca': 'Morro da Garça',
  'morro do pilar': 'Morro do Pilar',
  munhoz: 'Munhoz',
  muriae: 'Muriaé',
  mutum: 'Mutum',
  muzambinho: 'Muzambinho',
  'nacip raydan': 'Nacip Raydan',
  nanuque: 'Nanuque',
  naque: 'Naque',
  natalandia: 'Natalândia',
  natercia: 'Natércia',
  nazareno: 'Nazareno',
  nepomuceno: 'Nepomuceno',
  ninheira: 'Ninheira',
  'nova belem': 'Nova Belém',
  'nova era': 'Nova Era',
  'nova lima': 'Nova Lima',
  'nova modica': 'Nova Módica',
  'nova ponte': 'Nova Ponte',
  'nova porteirinha': 'Nova Porteirinha',
  'nova resende': 'Nova Resende',
  'nova serrana': 'Nova Serrana',
  'nova uniao': 'Nova União',
  'novo cruzeiro': 'Novo Cruzeiro',
  'novo oriente de minas': 'Novo Oriente de Minas',
  novorizonte: 'Novorizonte',
  olaria: 'Olaria',
  "olhos-d'agua": "Olhos-d'Água",
  'olimpio noronha': 'Olímpio Noronha',
  oliveira: 'Oliveira',
  'oliveira fortes': 'Oliveira Fortes',
  'onca de pitangui': 'Onça de Pitangui',
  oratorios: 'Oratórios',
  orizania: 'Orizânia',
  'ouro branco_': 'Ouro Branco',
  'ouro fino': 'Ouro Fino',
  'ouro preto': 'Ouro Preto',
  'ouro verde de minas': 'Ouro Verde de Minas',
  'padre carvalho': 'Padre Carvalho',
  'padre paraiso': 'Padre Paraíso',
  paineiras: 'Paineiras',
  pains: 'Pains',
  'pai pedro': 'Pai Pedro',
  paiva: 'Paiva',
  palma: 'Palma',
  palmopolis: 'Palmópolis',
  papagaios: 'Papagaios',
  paracatu: 'Paracatu',
  'para de minas': 'Pará de Minas',
  paraguacu: 'Paraguaçu',
  paraisopolis: 'Paraisópolis',
  paraopeba: 'Paraopeba',
  passabem: 'Passabém',
  'passa quatro': 'Passa Quatro',
  'passa tempo': 'Passa Tempo',
  'passa vinte': 'Passa Vinte',
  passos: 'Passos',
  patis: 'Patis',
  'patos de minas': 'Patos de Minas',
  patrocinio: 'Patrocínio',
  'patrocinio do muriae': 'Patrocínio do Muriaé',
  'paula candido': 'Paula Cândido',
  paulistas: 'Paulistas',
  pavao: 'Pavão',
  pecanha: 'Peçanha',
  'pedra azul': 'Pedra Azul',
  'pedra bonita': 'Pedra Bonita',
  'pedra do anta': 'Pedra do Anta',
  'pedra do indaia': 'Pedra do Indaiá',
  'pedra dourada': 'Pedra Dourada',
  pedralva: 'Pedralva',
  'pedras de maria da cruz': 'Pedras de Maria da Cruz',
  pedrinopolis: 'Pedrinópolis',
  'pedro leopoldo': 'Pedro Leopoldo',
  'pedro teixeira': 'Pedro Teixeira',
  pequeri: 'Pequeri',
  pequi: 'Pequi',
  perdigao: 'Perdigão',
  perdizes: 'Perdizes',
  perdoes: 'Perdões',
  periquito: 'Periquito',
  pescador: 'Pescador',
  piau: 'Piau',
  'piedade de caratinga': 'Piedade de Caratinga',
  'piedade de ponte nova': 'Piedade de Ponte Nova',
  'piedade do rio grande': 'Piedade do Rio Grande',
  'piedade dos gerais': 'Piedade dos Gerais',
  pimenta: 'Pimenta',
  "pingo d'agua": "Pingo d'Água",
  pintopolis: 'Pintópolis',
  piracema: 'Piracema',
  pirajuba: 'Pirajuba',
  piranga: 'Piranga',
  pirangucu: 'Piranguçu',
  piranguinho: 'Piranguinho',
  pirapetinga: 'Pirapetinga',
  pirapora: 'Pirapora',
  pirauba: 'Piraúba',
  pitangui: 'Pitangui',
  piumhi: 'Piumhi',
  planura: 'Planura',
  'poco fundo': 'Poço Fundo',
  'pocos de caldas': 'Poços de Caldas',
  pocrane: 'Pocrane',
  pompeu: 'Pompéu',
  'ponte nova': 'Ponte Nova',
  'ponto chique': 'Ponto Chique',
  'ponto dos volantes': 'Ponto dos Volantes',
  porteirinha: 'Porteirinha',
  'porto firme': 'Porto Firme',
  pote: 'Poté',
  'pouso alegre': 'Pouso Alegre',
  'pouso alto': 'Pouso Alto',
  prados: 'Prados',
  prata: 'Prata',
  pratapolis: 'Pratápolis',
  pratinha: 'Pratinha',
  'presidente bernardes': 'Presidente Bernardes',
  'presidente juscelino_': 'Presidente Juscelino',
  'presidente kubitschek': 'Presidente Kubitschek',
  'presidente olegario': 'Presidente Olegário',
  'prudente de morais': 'Prudente de Morais',
  'quartel geral': 'Quartel Geral',
  queluzito: 'Queluzito',
  raposos: 'Raposos',
  'raul soares': 'Raul Soares',
  recreio: 'Recreio',
  reduto: 'Reduto',
  'resende costa': 'Resende Costa',
  resplendor: 'Resplendor',
  ressaquinha: 'Ressaquinha',
  riachinho: 'Riachinho',
  'riacho dos machados': 'Riacho dos Machados',
  'ribeirao das neves': 'Ribeirão das Neves',
  'ribeirao vermelho': 'Ribeirão Vermelho',
  'rio acima': 'Rio Acima',
  'rio casca': 'Rio Casca',
  'rio doce': 'Rio Doce',
  'rio do prado': 'Rio do Prado',
  'rio espera': 'Rio Espera',
  'rio manso': 'Rio Manso',
  'rio novo': 'Rio Novo',
  'rio paranaiba': 'Rio Paranaíba',
  'rio pardo de minas': 'Rio Pardo de Minas',
  'rio piracicaba': 'Rio Piracicaba',
  'rio pomba': 'Rio Pomba',
  'rio preto': 'Rio Preto',
  'rio vermelho': 'Rio Vermelho',
  ritapolis: 'Ritápolis',
  'rochedo de minas': 'Rochedo de Minas',
  rodeiro: 'Rodeiro',
  romaria: 'Romaria',
  'rosario da limeira': 'Rosário da Limeira',
  rubelita: 'Rubelita',
  rubim: 'Rubim',
  sabara: 'Sabará',
  sabinopolis: 'Sabinópolis',
  sacramento: 'Sacramento',
  salinas: 'Salinas',
  'salto da divisa': 'Salto da Divisa',
  'santa barbara_': 'Santa Bárbara',
  'santa barbara do leste': 'Santa Bárbara do Leste',
  'santa barbara do monte verde': 'Santa Bárbara do Monte Verde',
  'santa barbara do tugurio': 'Santa Bárbara do Tugúrio',
  'santa cruz de minas': 'Santa Cruz de Minas',
  'santa cruz de salinas': 'Santa Cruz de Salinas',
  'santa cruz do escalvado': 'Santa Cruz do Escalvado',
  'santa efigenia de minas': 'Santa Efigênia de Minas',
  'santa fe de minas': 'Santa Fé de Minas',
  'santa helena de minas': 'Santa Helena de Minas',
  'santa juliana': 'Santa Juliana',
  'santa luzia__': 'Santa Luzia',
  'santa margarida': 'Santa Margarida',
  'santa maria de itabira': 'Santa Maria de Itabira',
  'santa maria do salto': 'Santa Maria do Salto',
  'santa maria do suacui': 'Santa Maria do Suaçuí',
  'santana da vargem': 'Santana da Vargem',
  'santana de cataguases': 'Santana de Cataguases',
  'santana de pirapama': 'Santana de Pirapama',
  'santana do deserto': 'Santana do Deserto',
  'santana do garambeu': 'Santana do Garambéu',
  'santana do jacare': 'Santana do Jacaré',
  'santana do manhuacu': 'Santana do Manhuaçu',
  'santana do paraiso': 'Santana do Paraíso',
  'santana do riacho': 'Santana do Riacho',
  'santana dos montes': 'Santana dos Montes',
  'santa rita de caldas': 'Santa Rita de Caldas',
  'santa rita de jacutinga': 'Santa Rita de Jacutinga',
  'santa rita de minas': 'Santa Rita de Minas',
  'santa rita de ibitipoca': 'Santa Rita de Ibitipoca',
  'santa rita do itueto': 'Santa Rita do Itueto',
  'santa rita do sapucai': 'Santa Rita do Sapucaí',
  'santa rosa da serra': 'Santa Rosa da Serra',
  'santa vitoria': 'Santa Vitória',
  'santo antonio do amparo': 'Santo Antônio do Amparo',
  'santo antonio do aventureiro': 'Santo Antônio do Aventureiro',
  'santo antonio do grama': 'Santo Antônio do Grama',
  'santo antonio do itambe': 'Santo Antônio do Itambé',
  'santo antonio do jacinto': 'Santo Antônio do Jacinto',
  'santo antonio do monte': 'Santo Antônio do Monte',
  'santo antonio do retiro': 'Santo Antônio do Retiro',
  'santo antonio do rio abaixo': 'Santo Antônio do Rio Abaixo',
  'santo hipolito': 'Santo Hipólito',
  'santos dumont': 'Santos Dumont',
  'sao bento abade': 'São Bento Abade',
  'sao bras do suacui': 'São Brás do Suaçuí',
  'sao domingos das dores': 'São Domingos das Dores',
  'sao domingos do prata': 'São Domingos do Prata',
  'sao felix de minas': 'São Félix de Minas',
  'sao francisco': 'São Francisco',
  'sao francisco de paula': 'São Francisco de Paula',
  'sao francisco de sales': 'São Francisco de Sales',
  'sao francisco do gloria': 'São Francisco do Glória',
  'sao geraldo': 'São Geraldo',
  'sao geraldo da piedade': 'São Geraldo da Piedade',
  'sao geraldo do baixio': 'São Geraldo do Baixio',
  'sao goncalo do abaete': 'São Gonçalo do Abaeté',
  'sao goncalo do para': 'São Gonçalo do Pará',
  'sao goncalo do rio abaixo': 'São Gonçalo do Rio Abaixo',
  'sao goncalo do rio preto': 'São Gonçalo do Rio Preto',
  'sao goncalo do sapucai': 'São Gonçalo do Sapucaí',
  'sao gotardo': 'São Gotardo',
  'sao joao batista do gloria': 'São João Batista do Glória',
  'sao joao da lagoa': 'São João da Lagoa',
  'sao joao da mata': 'São João da Mata',
  'sao joao da ponte': 'São João da Ponte',
  'sao joao das missoes': 'São João das Missões',
  'sao joao del-rei': 'São João del-Rei',
  'sao joao do manhuacu': 'São João do Manhuaçu',
  'sao joao do manteninha': 'São João do Manteninha',
  'sao joao do oriente': 'São João do Oriente',
  'sao joao do pacui': 'São João do Pacuí',
  'sao joao do paraiso_': 'São João do Paraíso',
  'sao joao evangelista': 'São João Evangelista',
  'sao joao nepomuceno': 'São João Nepomuceno',
  'sao joaquim de bicas': 'São Joaquim de Bicas',
  'sao jose da barra': 'São José da Barra',
  'sao jose da lapa': 'São José da Lapa',
  'sao jose da safira': 'São José da Safira',
  'sao jose da varginha': 'São José da Varginha',
  'sao jose do alegre': 'São José do Alegre',
  'sao jose do divino': 'São José do Divino',
  'sao jose do goiabal': 'São José do Goiabal',
  'sao jose do jacuri': 'São José do Jacuri',
  'sao jose do mantimento': 'São José do Mantimento',
  'sao lourenco': 'São Lourenço',
  'sao miguel do anta': 'São Miguel do Anta',
  'sao pedro da uniao': 'São Pedro da União',
  'sao pedro dos ferros': 'São Pedro dos Ferros',
  'sao pedro do suacui': 'São Pedro do Suaçuí',
  'sao romao': 'São Romão',
  'sao roque de minas': 'São Roque de Minas',
  'sao sebastiao da bela vista': 'São Sebastião da Bela Vista',
  'sao sebastiao da vargem alegre': 'São Sebastião da Vargem Alegre',
  'sao sebastiao do anta': 'São Sebastião do Anta',
  'sao sebastiao do maranhao': 'São Sebastião do Maranhão',
  'sao sebastiao do oeste': 'São Sebastião do Oeste',
  'sao sebastiao do paraiso': 'São Sebastião do Paraíso',
  'sao sebastiao do rio preto': 'São Sebastião do Rio Preto',
  'sao sebastiao do rio verde': 'São Sebastião do Rio Verde',
  'sao tome das letras': 'São Tomé das Letras',
  'sao tiago': 'São Tiago',
  'sao tomas de aquino': 'São Tomás de Aquino',
  'sao vicente de minas': 'São Vicente de Minas',
  'sapucai-mirim': 'Sapucaí-Mirim',
  sardoa: 'Sardoá',
  sarzedo: 'Sarzedo',
  'sem-peixe': 'Sem-Peixe',
  'senador amaral': 'Senador Amaral',
  'senador cortes': 'Senador Cortes',
  'senador firmino': 'Senador Firmino',
  'senador jose bento': 'Senador José Bento',
  'senador modestino goncalves': 'Senador Modestino Gonçalves',
  'senhora de oliveira': 'Senhora de Oliveira',
  'senhora do porto': 'Senhora do Porto',
  'senhora dos remedios': 'Senhora dos Remédios',
  sericita: 'Sericita',
  seritinga: 'Seritinga',
  'serra azul de minas': 'Serra Azul de Minas',
  'serra da saudade': 'Serra da Saudade',
  'serra dos aimores': 'Serra dos Aimorés',
  'serra do salitre': 'Serra do Salitre',
  serrania: 'Serrania',
  'serranopolis de minas': 'Serranópolis de Minas',
  serranos: 'Serranos',
  serro: 'Serro',
  'sete lagoas': 'Sete Lagoas',
  setubinha: 'Setubinha',
  silveirania: 'Silveirânia',
  silvianopolis: 'Silvianópolis',
  'simao pereira': 'Simão Pereira',
  simonesia: 'Simonésia',
  sobralia: 'Sobrália',
  'soledade de minas': 'Soledade de Minas',
  tabuleiro: 'Tabuleiro',
  taiobeiras: 'Taiobeiras',
  taparuba: 'Taparuba',
  tapira: 'Tapira',
  tapirai: 'Tapiraí',
  'taquaracu de minas': 'Taquaraçu de Minas',
  tarumirim: 'Tarumirim',
  teixeiras: 'Teixeiras',
  'teofilo otoni': 'Teófilo Otoni',
  timoteo: 'Timóteo',
  tiradentes: 'Tiradentes',
  tiros: 'Tiros',
  tocantins: 'Tocantins',
  'tocos do moji': 'Tocos do Moji',
  toledo: 'Toledo',
  tombos: 'Tombos',
  'tres coracoes': 'Três Corações',
  'tres marias': 'Três Marias',
  'tres pontas': 'Três Pontas',
  tumiritinga: 'Tumiritinga',
  tupaciguara: 'Tupaciguara',
  turmalina: 'Turmalina',
  turvolandia: 'Turvolândia',
  uba: 'Ubá',
  ubai: 'Ubaí',
  ubaporanga: 'Ubaporanga',
  uberaba: 'Uberaba',
  uberlandia: 'Uberlândia',
  umburatiba: 'Umburatiba',
  unai: 'Unaí',
  'uniao de minas': 'União de Minas',
  'uruana de minas': 'Uruana de Minas',
  urucania: 'Urucânia',
  urucuia: 'Urucuia',
  'vargem alegre': 'Vargem Alegre',
  'vargem bonita': 'Vargem Bonita',
  'vargem grande do rio pardo': 'Vargem Grande do Rio Pardo',
  varginha: 'Varginha',
  'varjao de minas': 'Varjão de Minas',
  'varzea da palma': 'Várzea da Palma',
  varzelandia: 'Varzelândia',
  vazante: 'Vazante',
  verdelandia: 'Verdelândia',
  veredinha: 'Veredinha',
  verissimo: 'Veríssimo',
  'vermelho novo': 'Vermelho Novo',
  vespasiano: 'Vespasiano',
  vicosa_: 'Viçosa',
  vieiras: 'Vieiras',
  'virgem da lapa': 'Virgem da Lapa',
  virginia: 'Virgínia',
  virginopolis: 'Virginópolis',
  virgolandia: 'Virgolândia',
  'visconde do rio branco': 'Visconde do Rio Branco',
  'volta grande': 'Volta Grande',
  'wenceslau braz': 'Wenceslau Braz',
};
