export const cities = {
  'abadia dos dourados': { name: 'Abadia dos Dourados', state: 'MG' },
  abaete: { name: 'Abaeté', state: 'MG' },
  'abre campo': { name: 'Abre Campo', state: 'MG' },
  acaiaca: { name: 'Acaiaca', state: 'MG' },
  acucena: { name: 'Açucena', state: 'MG' },
  'agua boa': { name: 'Água Boa', state: 'MG' },
  'agua comprida': { name: 'Água Comprida', state: 'MG' },
  aguanil: { name: 'Aguanil', state: 'MG' },
  'aguas formosas': { name: 'Águas Formosas', state: 'MG' },
  'aguas vermelhas': { name: 'Águas Vermelhas', state: 'MG' },
  aimores: { name: 'Aimorés', state: 'MG' },
  aiuruoca: { name: 'Aiuruoca', state: 'MG' },
  alagoa: { name: 'Alagoa', state: 'MG' },
  albertina: { name: 'Albertina', state: 'MG' },
  'alem paraiba': { name: 'Além Paraíba', state: 'MG' },
  alfenas: { name: 'Alfenas', state: 'MG' },
  'alfredo vasconcelos': { name: 'Alfredo Vasconcelos', state: 'MG' },
  almenara: { name: 'Almenara', state: 'MG' },
  alpercata: { name: 'Alpercata', state: 'MG' },
  alpinopolis: { name: 'Alpinópolis', state: 'MG' },
  alterosa: { name: 'Alterosa', state: 'MG' },
  'alto caparao': { name: 'Alto Caparaó', state: 'MG' },
  'alto jequitiba': { name: 'Alto Jequitibá', state: 'MG' },
  'alto rio doce': { name: 'Alto Rio Doce', state: 'MG' },
  alvarenga: { name: 'Alvarenga', state: 'MG' },
  alvinopolis: { name: 'Alvinópolis', state: 'MG' },
  'alvorada de minas': { name: 'Alvorada de Minas', state: 'MG' },
  'amparo da serra': { name: 'Amparo da Serra', state: 'MG' },
  andradas: { name: 'Andradas', state: 'MG' },
  andrelandia: { name: 'Andrelândia', state: 'MG' },
  angelandia: { name: 'Angelândia', state: 'MG' },
  'antonio carlos': { name: 'Antônio Carlos', state: 'MG' },
  'antonio dias': { name: 'Antônio Dias', state: 'MG' },
  'antonio prado de minas': { name: 'Antônio Prado de Minas', state: 'MG' },
  aracai: { name: 'Araçaí', state: 'MG' },
  aracitaba: { name: 'Aracitaba', state: 'MG' },
  aracuai: { name: 'Araçuaí', state: 'MG' },
  araguari: { name: 'Araguari', state: 'MG' },
  arantina: { name: 'Arantina', state: 'MG' },
  araponga: { name: 'Araponga', state: 'MG' },
  arapora: { name: 'Araporã', state: 'MG' },
  arapua: { name: 'Arapuá', state: 'MG' },
  araujos: { name: 'Araújos', state: 'MG' },
  araxa: { name: 'Araxá', state: 'MG' },
  arceburgo: { name: 'Arceburgo', state: 'MG' },
  arcos: { name: 'Arcos', state: 'MG' },
  areado: { name: 'Areado', state: 'MG' },
  argirita: { name: 'Argirita', state: 'MG' },
  aricanduva: { name: 'Aricanduva', state: 'MG' },
  arinos: { name: 'Arinos', state: 'MG' },
  'astolfo dutra': { name: 'Astolfo Dutra', state: 'MG' },
  ataleia: { name: 'Ataléia', state: 'MG' },
  'augusto de lima': { name: 'Augusto de Lima', state: 'MG' },
  baependi: { name: 'Baependi', state: 'MG' },
  baldim: { name: 'Baldim', state: 'MG' },
  bambui: { name: 'Bambuí', state: 'MG' },
  bandeira: { name: 'Bandeira', state: 'MG' },
  'bandeira do sul': { name: 'Bandeira do Sul', state: 'MG' },
  'barao de cocais': { name: 'Barão de Cocais', state: 'MG' },
  'barao de monte alto': { name: 'Barão de Monte Alto', state: 'MG' },
  barbacena: { name: 'Barbacena', state: 'MG' },
  'barra longa': { name: 'Barra Longa', state: 'MG' },
  barroso: { name: 'Barroso', state: 'MG' },
  'bela vista de minas': { name: 'Bela Vista de Minas', state: 'MG' },
  'belmiro braga': { name: 'Belmiro Braga', state: 'MG' },
  'belo horizonte': { name: 'Belo Horizonte', state: 'MG' },
  'belo oriente': { name: 'Belo Oriente', state: 'MG' },
  'belo vale': { name: 'Belo Vale', state: 'MG' },
  berilo: { name: 'Berilo', state: 'MG' },
  berizal: { name: 'Berizal', state: 'MG' },
  bertopolis: { name: 'Bertópolis', state: 'MG' },
  betim: { name: 'Betim', state: 'MG' },
  'bias fortes': { name: 'Bias Fortes', state: 'MG' },
  bicas: { name: 'Bicas', state: 'MG' },
  biquinhas: { name: 'Biquinhas', state: 'MG' },
  'boa esperanca_': { name: 'Boa Esperança', state: 'MG' },
  'bocaina de minas': { name: 'Bocaina de Minas', state: 'MG' },
  bocaiuva: { name: 'Bocaiuva', state: 'MG' },
  'bom despacho': { name: 'Bom Despacho', state: 'MG' },
  'bom jardim de minas': { name: 'Bom Jardim de Minas', state: 'MG' },
  'bom jesus da penha': { name: 'Bom Jesus da Penha', state: 'MG' },
  'bom jesus do amparo': { name: 'Bom Jesus do Amparo', state: 'MG' },
  'bom jesus do galho': { name: 'Bom Jesus do Galho', state: 'MG' },
  'bom repouso': { name: 'Bom Repouso', state: 'MG' },
  'bom sucesso': { name: 'Bom Sucesso', state: 'MG' },
  bonfim: { name: 'Bonfim', state: 'MG' },
  'bonfinopolis de minas': { name: 'Bonfinópolis de Minas', state: 'MG' },
  'bonito de minas': { name: 'Bonito de Minas', state: 'MG' },
  'borda da mata': { name: 'Borda da Mata', state: 'MG' },
  botelhos: { name: 'Botelhos', state: 'MG' },
  botumirim: { name: 'Botumirim', state: 'MG' },
  'brasilandia de minas': { name: 'Brasilândia de Minas', state: 'MG' },
  'brasilia de minas': { name: 'Brasília de Minas', state: 'MG' },
  brasopolis: { name: 'Brasópolis', state: 'MG' },
  'bras pires': { name: 'Brás Pires', state: 'MG' },
  braunas: { name: 'Braúnas', state: 'MG' },
  brumadinho: { name: 'Brumadinho', state: 'MG' },
  'bueno brandao': { name: 'Bueno Brandão', state: 'MG' },
  buenopolis: { name: 'Buenópolis', state: 'MG' },
  bugre: { name: 'Bugre', state: 'MG' },
  buritis: { name: 'Buritis', state: 'MG' },
  buritizeiro: { name: 'Buritizeiro', state: 'MG' },
  'cabeceira grande': { name: 'Cabeceira Grande', state: 'MG' },
  'cabo verde': { name: 'Cabo Verde', state: 'MG' },
  'cachoeira da prata': { name: 'Cachoeira da Prata', state: 'MG' },
  'cachoeira de minas': { name: 'Cachoeira de Minas', state: 'MG' },
  'cachoeira de pajeu': { name: 'Cachoeira de Pajeú', state: 'MG' },
  'cachoeira dourada_': { name: 'Cachoeira Dourada', state: 'MG' },
  caetanopolis: { name: 'Caetanópolis', state: 'MG' },
  caete: { name: 'Caeté', state: 'MG' },
  caiana: { name: 'Caiana', state: 'MG' },
  cajuri: { name: 'Cajuri', state: 'MG' },
  caldas: { name: 'Caldas', state: 'MG' },
  camacho: { name: 'Camacho', state: 'MG' },
  camanducaia: { name: 'Camanducaia', state: 'MG' },
  cambui: { name: 'Cambuí', state: 'MG' },
  cambuquira: { name: 'Cambuquira', state: 'MG' },
  campanario: { name: 'Campanário', state: 'MG' },
  campanha: { name: 'Campanha', state: 'MG' },
  campestre_: { name: 'Campestre', state: 'MG' },
  'campina verde': { name: 'Campina Verde', state: 'MG' },
  'campo azul': { name: 'Campo Azul', state: 'MG' },
  'campo belo': { name: 'Campo Belo', state: 'MG' },
  'campo do meio': { name: 'Campo do Meio', state: 'MG' },
  'campo florido': { name: 'Campo Florido', state: 'MG' },
  'campos altos': { name: 'Campos Altos', state: 'MG' },
  'campos gerais': { name: 'Campos Gerais', state: 'MG' },
  canaa: { name: 'Canaã', state: 'MG' },
  canapolis_: { name: 'Canápolis', state: 'MG' },
  'cana verde': { name: 'Cana Verde', state: 'MG' },
  candeias_: { name: 'Candeias', state: 'MG' },
  cantagalo: { name: 'Cantagalo', state: 'MG' },
  caparao: { name: 'Caparaó', state: 'MG' },
  'capela nova': { name: 'Capela Nova', state: 'MG' },
  capelinha: { name: 'Capelinha', state: 'MG' },
  capetinga: { name: 'Capetinga', state: 'MG' },
  'capim branco': { name: 'Capim Branco', state: 'MG' },
  capinopolis: { name: 'Capinópolis', state: 'MG' },
  'capitao andrade': { name: 'Capitão Andrade', state: 'MG' },
  'capitao eneas': { name: 'Capitão Enéas', state: 'MG' },
  capitolio: { name: 'Capitólio', state: 'MG' },
  caputira: { name: 'Caputira', state: 'MG' },
  carai: { name: 'Caraí', state: 'MG' },
  caranaiba: { name: 'Caranaíba', state: 'MG' },
  carandai: { name: 'Carandaí', state: 'MG' },
  carangola: { name: 'Carangola', state: 'MG' },
  caratinga: { name: 'Caratinga', state: 'MG' },
  carbonita: { name: 'Carbonita', state: 'MG' },
  careacu: { name: 'Careaçu', state: 'MG' },
  'carlos chagas': { name: 'Carlos Chagas', state: 'MG' },
  carmesia: { name: 'Carmésia', state: 'MG' },
  'carmo da cachoeira': { name: 'Carmo da Cachoeira', state: 'MG' },
  'carmo da mata': { name: 'Carmo da Mata', state: 'MG' },
  'carmo de minas': { name: 'Carmo de Minas', state: 'MG' },
  'carmo do cajuru': { name: 'Carmo do Cajuru', state: 'MG' },
  'carmo do paranaiba': { name: 'Carmo do Paranaíba', state: 'MG' },
  'carmo do rio claro': { name: 'Carmo do Rio Claro', state: 'MG' },
  'carmopolis de minas': { name: 'Carmópolis de Minas', state: 'MG' },
  carneirinho: { name: 'Carneirinho', state: 'MG' },
  carrancas: { name: 'Carrancas', state: 'MG' },
  carvalhopolis: { name: 'Carvalhópolis', state: 'MG' },
  carvalhos: { name: 'Carvalhos', state: 'MG' },
  'casa grande': { name: 'Casa Grande', state: 'MG' },
  'cascalho rico': { name: 'Cascalho Rico', state: 'MG' },
  cassia: { name: 'Cássia', state: 'MG' },
  cataguases: { name: 'Cataguases', state: 'MG' },
  'catas altas': { name: 'Catas Altas', state: 'MG' },
  'catas altas da noruega': { name: 'Catas Altas da Noruega', state: 'MG' },
  catuji: { name: 'Catuji', state: 'MG' },
  catuti: { name: 'Catuti', state: 'MG' },
  caxambu: { name: 'Caxambu', state: 'MG' },
  'cedro do abaete': { name: 'Cedro do Abaeté', state: 'MG' },
  'central de minas': { name: 'Central de Minas', state: 'MG' },
  centralina: { name: 'Centralina', state: 'MG' },
  chacara: { name: 'Chácara', state: 'MG' },
  chale: { name: 'Chalé', state: 'MG' },
  'chapada do norte': { name: 'Chapada do Norte', state: 'MG' },
  'chapada gaucha': { name: 'Chapada Gaúcha', state: 'MG' },
  chiador: { name: 'Chiador', state: 'MG' },
  cipotanea: { name: 'Cipotânea', state: 'MG' },
  claraval: { name: 'Claraval', state: 'MG' },
  'claro dos pocoes': { name: 'Claro dos Poções', state: 'MG' },
  claudio: { name: 'Cláudio', state: 'MG' },
  coimbra: { name: 'Coimbra', state: 'MG' },
  coluna: { name: 'Coluna', state: 'MG' },
  'comendador gomes': { name: 'Comendador Gomes', state: 'MG' },
  comercinho: { name: 'Comercinho', state: 'MG' },
  'conceicao da aparecida': { name: 'Conceição da Aparecida', state: 'MG' },
  'conceicao da barra de minas': { name: 'Conceição da Barra de Minas', state: 'MG' },
  'conceicao das alagoas': { name: 'Conceição das Alagoas', state: 'MG' },
  'conceicao das pedras': { name: 'Conceição das Pedras', state: 'MG' },
  'conceicao de ipanema': { name: 'Conceição de Ipanema', state: 'MG' },
  'conceicao do mato dentro': { name: 'Conceição do Mato Dentro', state: 'MG' },
  'conceicao do para': { name: 'Conceição do Pará', state: 'MG' },
  'conceicao do rio verde': { name: 'Conceição do Rio Verde', state: 'MG' },
  'conceicao dos ouros': { name: 'Conceição dos Ouros', state: 'MG' },
  'conego marinho': { name: 'Cônego Marinho', state: 'MG' },
  confins: { name: 'Confins', state: 'MG' },
  congonhal: { name: 'Congonhal', state: 'MG' },
  congonhas: { name: 'Congonhas', state: 'MG' },
  'congonhas do norte': { name: 'Congonhas do Norte', state: 'MG' },
  conquista: { name: 'Conquista', state: 'MG' },
  'conselheiro lafaiete': { name: 'Conselheiro Lafaiete', state: 'MG' },
  'conselheiro pena': { name: 'Conselheiro Pena', state: 'MG' },
  consolacao: { name: 'Consolação', state: 'MG' },
  contagem: { name: 'Contagem', state: 'MG' },
  coqueiral: { name: 'Coqueiral', state: 'MG' },
  'coracao de jesus': { name: 'Coração de Jesus', state: 'MG' },
  cordisburgo: { name: 'Cordisburgo', state: 'MG' },
  cordislandia: { name: 'Cordislândia', state: 'MG' },
  corinto: { name: 'Corinto', state: 'MG' },
  coroaci: { name: 'Coroaci', state: 'MG' },
  coromandel: { name: 'Coromandel', state: 'MG' },
  'coronel fabriciano': { name: 'Coronel Fabriciano', state: 'MG' },
  'coronel murta': { name: 'Coronel Murta', state: 'MG' },
  'coronel pacheco': { name: 'Coronel Pacheco', state: 'MG' },
  'coronel xavier chaves': { name: 'Coronel Xavier Chaves', state: 'MG' },
  'corrego danta': { name: 'Córrego Danta', state: 'MG' },
  'corrego do bom jesus': { name: 'Córrego do Bom Jesus', state: 'MG' },
  'corrego fundo': { name: 'Córrego Fundo', state: 'MG' },
  'corrego novo': { name: 'Córrego Novo', state: 'MG' },
  'couto de magalhaes de minas': { name: 'Couto de Magalhães de Minas', state: 'MG' },
  crisolita: { name: 'Crisólita', state: 'MG' },
  cristais: { name: 'Cristais', state: 'MG' },
  cristalia: { name: 'Cristália', state: 'MG' },
  'cristiano otoni': { name: 'Cristiano Otoni', state: 'MG' },
  cristina: { name: 'Cristina', state: 'MG' },
  crucilandia: { name: 'Crucilândia', state: 'MG' },
  'cruzeiro da fortaleza': { name: 'Cruzeiro da Fortaleza', state: 'MG' },
  cruzilia: { name: 'Cruzília', state: 'MG' },
  cuparaque: { name: 'Cuparaque', state: 'MG' },
  'curral de dentro': { name: 'Curral de Dentro', state: 'MG' },
  curvelo: { name: 'Curvelo', state: 'MG' },
  datas: { name: 'Datas', state: 'MG' },
  'delfim moreira': { name: 'Delfim Moreira', state: 'MG' },
  delfinopolis: { name: 'Delfinópolis', state: 'MG' },
  delta: { name: 'Delta', state: 'MG' },
  descoberto: { name: 'Descoberto', state: 'MG' },
  'desterro de entre rios': { name: 'Desterro de Entre Rios', state: 'MG' },
  'desterro do melo': { name: 'Desterro do Melo', state: 'MG' },
  diamantina: { name: 'Diamantina', state: 'MG' },
  'diogo de vasconcelos': { name: 'Diogo de Vasconcelos', state: 'MG' },
  dionisio: { name: 'Dionísio', state: 'MG' },
  divinesia: { name: 'Divinésia', state: 'MG' },
  divino: { name: 'Divino', state: 'MG' },
  'divino das laranjeiras': { name: 'Divino das Laranjeiras', state: 'MG' },
  'divinolandia de minas': { name: 'Divinolândia de Minas', state: 'MG' },
  divinopolis: { name: 'Divinópolis', state: 'MG' },
  'divisa alegre': { name: 'Divisa Alegre', state: 'MG' },
  'divisa nova': { name: 'Divisa Nova', state: 'MG' },
  divisopolis: { name: 'Divisópolis', state: 'MG' },
  'dom bosco': { name: 'Dom Bosco', state: 'MG' },
  'dom cavati': { name: 'Dom Cavati', state: 'MG' },
  'dom joaquim': { name: 'Dom Joaquim', state: 'MG' },
  'dom silverio': { name: 'Dom Silvério', state: 'MG' },
  'dom vicoso': { name: 'Dom Viçoso', state: 'MG' },
  'dona euzebia': { name: 'Dona Euzébia', state: 'MG' },
  'dores de campos': { name: 'Dores de Campos', state: 'MG' },
  'dores de guanhaes': { name: 'Dores de Guanhães', state: 'MG' },
  'dores do indaia': { name: 'Dores do Indaiá', state: 'MG' },
  'dores do turvo': { name: 'Dores do Turvo', state: 'MG' },
  doresopolis: { name: 'Doresópolis', state: 'MG' },
  douradoquara: { name: 'Douradoquara', state: 'MG' },
  durande: { name: 'Durandé', state: 'MG' },
  'eloi mendes': { name: 'Elói Mendes', state: 'MG' },
  'engenheiro caldas': { name: 'Engenheiro Caldas', state: 'MG' },
  'engenheiro navarro': { name: 'Engenheiro Navarro', state: 'MG' },
  'entre folhas': { name: 'Entre Folhas', state: 'MG' },
  'entre rios de minas': { name: 'Entre Rios de Minas', state: 'MG' },
  ervalia: { name: 'Ervália', state: 'MG' },
  esmeraldas: { name: 'Esmeraldas', state: 'MG' },
  'espera feliz': { name: 'Espera Feliz', state: 'MG' },
  espinosa: { name: 'Espinosa', state: 'MG' },
  'espirito santo do dourado': { name: 'Espírito Santo do Dourado', state: 'MG' },
  estiva: { name: 'Estiva', state: 'MG' },
  'estrela dalva': { name: 'Estrela Dalva', state: 'MG' },
  'estrela do indaia': { name: 'Estrela do Indaiá', state: 'MG' },
  'estrela do sul': { name: 'Estrela do Sul', state: 'MG' },
  eugenopolis: { name: 'Eugenópolis', state: 'MG' },
  'ewbank da camara': { name: 'Ewbank da Câmara', state: 'MG' },
  extrema: { name: 'Extrema', state: 'MG' },
  fama: { name: 'Fama', state: 'MG' },
  'faria lemos': { name: 'Faria Lemos', state: 'MG' },
  'felicio dos santos': { name: 'Felício dos Santos', state: 'MG' },
  felisburgo: { name: 'Felisburgo', state: 'MG' },
  felixlandia: { name: 'Felixlândia', state: 'MG' },
  'fernandes tourinho': { name: 'Fernandes Tourinho', state: 'MG' },
  ferros: { name: 'Ferros', state: 'MG' },
  fervedouro: { name: 'Fervedouro', state: 'MG' },
  florestal: { name: 'Florestal', state: 'MG' },
  formiga: { name: 'Formiga', state: 'MG' },
  formoso_: { name: 'Formoso', state: 'MG' },
  'fortaleza de minas': { name: 'Fortaleza de Minas', state: 'MG' },
  'fortuna de minas': { name: 'Fortuna de Minas', state: 'MG' },
  'francisco badaro': { name: 'Francisco Badaró', state: 'MG' },
  'francisco dumont': { name: 'Francisco Dumont', state: 'MG' },
  franciscopolis: { name: 'Franciscópolis', state: 'MG' },
  'francisco sa': { name: 'Francisco Sá', state: 'MG' },
  'frei gaspar': { name: 'Frei Gaspar', state: 'MG' },
  'frei inocencio': { name: 'Frei Inocêncio', state: 'MG' },
  'frei lagonegro': { name: 'Frei Lagonegro', state: 'MG' },
  fronteira: { name: 'Fronteira', state: 'MG' },
  'fronteira dos vales': { name: 'Fronteira dos Vales', state: 'MG' },
  'fruta de leite': { name: 'Fruta de Leite', state: 'MG' },
  frutal: { name: 'Frutal', state: 'MG' },
  funilandia: { name: 'Funilândia', state: 'MG' },
  galileia: { name: 'Galileia', state: 'MG' },
  gameleiras: { name: 'Gameleiras', state: 'MG' },
  glaucilandia: { name: 'Glaucilândia', state: 'MG' },
  goiabeira: { name: 'Goiabeira', state: 'MG' },
  goiana_: { name: 'Goianá', state: 'MG' },
  goncalves: { name: 'Gonçalves', state: 'MG' },
  gonzaga: { name: 'Gonzaga', state: 'MG' },
  gouveia: { name: 'Gouveia', state: 'MG' },
  'governador valadares': { name: 'Governador Valadares', state: 'MG' },
  'grao mogol': { name: 'Grão Mogol', state: 'MG' },
  grupiara: { name: 'Grupiara', state: 'MG' },
  guanhaes: { name: 'Guanhães', state: 'MG' },
  guape: { name: 'Guapé', state: 'MG' },
  guaraciaba: { name: 'Guaraciaba', state: 'MG' },
  guaraciama: { name: 'Guaraciama', state: 'MG' },
  guaranesia: { name: 'Guaranésia', state: 'MG' },
  guarani: { name: 'Guarani', state: 'MG' },
  guarara: { name: 'Guarará', state: 'MG' },
  'guarda-mor': { name: 'Guarda-Mor', state: 'MG' },
  guaxupe: { name: 'Guaxupé', state: 'MG' },
  guidoval: { name: 'Guidoval', state: 'MG' },
  guimarania: { name: 'Guimarânia', state: 'MG' },
  guiricema: { name: 'Guiricema', state: 'MG' },
  gurinhata: { name: 'Gurinhatã', state: 'MG' },
  heliodora: { name: 'Heliodora', state: 'MG' },
  iapu: { name: 'Iapu', state: 'MG' },
  ibertioga: { name: 'Ibertioga', state: 'MG' },
  ibia: { name: 'Ibiá', state: 'MG' },
  ibiai: { name: 'Ibiaí', state: 'MG' },
  ibiracatu: { name: 'Ibiracatu', state: 'MG' },
  ibiraci: { name: 'Ibiraci', state: 'MG' },
  ibirite: { name: 'Ibirité', state: 'MG' },
  'ibitiura de minas': { name: 'Ibitiúra de Minas', state: 'MG' },
  ibituruna: { name: 'Ibituruna', state: 'MG' },
  'icarai de minas': { name: 'Icaraí de Minas', state: 'MG' },
  igarape: { name: 'Igarapé', state: 'MG' },
  igaratinga: { name: 'Igaratinga', state: 'MG' },
  iguatama: { name: 'Iguatama', state: 'MG' },
  ijaci: { name: 'Ijaci', state: 'MG' },
  ilicinea: { name: 'Ilicínea', state: 'MG' },
  'imbe de minas': { name: 'Imbé de Minas', state: 'MG' },
  inconfidentes: { name: 'Inconfidentes', state: 'MG' },
  indaiabira: { name: 'Indaiabira', state: 'MG' },
  indianopolis: { name: 'Indianópolis', state: 'MG' },
  ingai: { name: 'Ingaí', state: 'MG' },
  inhapim: { name: 'Inhapim', state: 'MG' },
  inhauma: { name: 'Inhaúma', state: 'MG' },
  inimutaba: { name: 'Inimutaba', state: 'MG' },
  ipaba: { name: 'Ipaba', state: 'MG' },
  ipanema: { name: 'Ipanema', state: 'MG' },
  ipatinga: { name: 'Ipatinga', state: 'MG' },
  ipiacu: { name: 'Ipiaçu', state: 'MG' },
  ipuiuna: { name: 'Ipuiuna', state: 'MG' },
  'irai de minas': { name: 'Iraí de Minas', state: 'MG' },
  itabira: { name: 'Itabira', state: 'MG' },
  itabirinha: { name: 'Itabirinha', state: 'MG' },
  itabirito: { name: 'Itabirito', state: 'MG' },
  itacambira: { name: 'Itacambira', state: 'MG' },
  itacarambi: { name: 'Itacarambi', state: 'MG' },
  itaguara: { name: 'Itaguara', state: 'MG' },
  itaipe: { name: 'Itaipé', state: 'MG' },
  itajuba: { name: 'Itajubá', state: 'MG' },
  itamarandiba: { name: 'Itamarandiba', state: 'MG' },
  'itamarati de minas': { name: 'Itamarati de Minas', state: 'MG' },
  itambacuri: { name: 'Itambacuri', state: 'MG' },
  'itambe do mato dentro': { name: 'Itambé do Mato Dentro', state: 'MG' },
  itamogi: { name: 'Itamogi', state: 'MG' },
  itamonte: { name: 'Itamonte', state: 'MG' },
  itanhandu: { name: 'Itanhandu', state: 'MG' },
  itanhomi: { name: 'Itanhomi', state: 'MG' },
  itaobim: { name: 'Itaobim', state: 'MG' },
  itapagipe: { name: 'Itapagipe', state: 'MG' },
  itapecerica: { name: 'Itapecerica', state: 'MG' },
  itapeva: { name: 'Itapeva', state: 'MG' },
  itatiaiucu: { name: 'Itatiaiuçu', state: 'MG' },
  'itau de minas': { name: 'Itaú de Minas', state: 'MG' },
  itauna: { name: 'Itaúna', state: 'MG' },
  itaverava: { name: 'Itaverava', state: 'MG' },
  itinga: { name: 'Itinga', state: 'MG' },
  itueta: { name: 'Itueta', state: 'MG' },
  ituiutaba: { name: 'Ituiutaba', state: 'MG' },
  itumirim: { name: 'Itumirim', state: 'MG' },
  iturama: { name: 'Iturama', state: 'MG' },
  itutinga: { name: 'Itutinga', state: 'MG' },
  jaboticatubas: { name: 'Jaboticatubas', state: 'MG' },
  jacinto: { name: 'Jacinto', state: 'MG' },
  jacui: { name: 'Jacuí', state: 'MG' },
  jacutinga: { name: 'Jacutinga', state: 'MG' },
  jaguaracu: { name: 'Jaguaraçu', state: 'MG' },
  jaiba: { name: 'Jaíba', state: 'MG' },
  jampruca: { name: 'Jampruca', state: 'MG' },
  janauba: { name: 'Janaúba', state: 'MG' },
  januaria: { name: 'Januária', state: 'MG' },
  japaraiba: { name: 'Japaraíba', state: 'MG' },
  japonvar: { name: 'Japonvar', state: 'MG' },
  jeceaba: { name: 'Jeceaba', state: 'MG' },
  'jenipapo de minas': { name: 'Jenipapo de Minas', state: 'MG' },
  jequeri: { name: 'Jequeri', state: 'MG' },
  jequitai: { name: 'Jequitaí', state: 'MG' },
  jequitiba: { name: 'Jequitibá', state: 'MG' },
  jequitinhonha: { name: 'Jequitinhonha', state: 'MG' },
  jesuania: { name: 'Jesuânia', state: 'MG' },
  joaima: { name: 'Joaíma', state: 'MG' },
  joanesia: { name: 'Joanésia', state: 'MG' },
  'joao monlevade': { name: 'João Monlevade', state: 'MG' },
  'joao pinheiro': { name: 'João Pinheiro', state: 'MG' },
  'joaquim felicio': { name: 'Joaquim Felício', state: 'MG' },
  jordania: { name: 'Jordânia', state: 'MG' },
  'jose goncalves de minas': { name: 'José Gonçalves de Minas', state: 'MG' },
  josenopolis: { name: 'Josenópolis', state: 'MG' },
  'jose raydan': { name: 'José Raydan', state: 'MG' },
  juatuba: { name: 'Juatuba', state: 'MG' },
  'juiz de fora': { name: 'Juiz de Fora', state: 'MG' },
  juramento: { name: 'Juramento', state: 'MG' },
  juruaia: { name: 'Juruaia', state: 'MG' },
  juvenilia: { name: 'Juvenília', state: 'MG' },
  ladainha: { name: 'Ladainha', state: 'MG' },
  lagamar: { name: 'Lagamar', state: 'MG' },
  'lagoa da prata': { name: 'Lagoa da Prata', state: 'MG' },
  'lagoa dos patos': { name: 'Lagoa dos Patos', state: 'MG' },
  'lagoa dourada': { name: 'Lagoa Dourada', state: 'MG' },
  'lagoa formosa': { name: 'Lagoa Formosa', state: 'MG' },
  'lagoa grande': { name: 'Lagoa Grande', state: 'MG' },
  'lagoa santa_': { name: 'Lagoa Santa', state: 'MG' },
  lajinha: { name: 'Lajinha', state: 'MG' },
  lambari: { name: 'Lambari', state: 'MG' },
  lamim: { name: 'Lamim', state: 'MG' },
  laranjal: { name: 'Laranjal', state: 'MG' },
  lassance: { name: 'Lassance', state: 'MG' },
  lavras: { name: 'Lavras', state: 'MG' },
  'leandro ferreira': { name: 'Leandro Ferreira', state: 'MG' },
  'leme do prado': { name: 'Leme do Prado', state: 'MG' },
  leopoldina: { name: 'Leopoldina', state: 'MG' },
  liberdade: { name: 'Liberdade', state: 'MG' },
  'lima duarte': { name: 'Lima Duarte', state: 'MG' },
  'limeira do oeste': { name: 'Limeira do Oeste', state: 'MG' },
  lontra: { name: 'Lontra', state: 'MG' },
  luisburgo: { name: 'Luisburgo', state: 'MG' },
  luislandia: { name: 'Luislândia', state: 'MG' },
  luminarias: { name: 'Luminárias', state: 'MG' },
  luz: { name: 'Luz', state: 'MG' },
  machacalis: { name: 'Machacalis', state: 'MG' },
  machado: { name: 'Machado', state: 'MG' },
  'madre de deus de minas': { name: 'Madre de Deus de Minas', state: 'MG' },
  malacacheta: { name: 'Malacacheta', state: 'MG' },
  mamonas: { name: 'Mamonas', state: 'MG' },
  manga: { name: 'Manga', state: 'MG' },
  manhuacu: { name: 'Manhuaçu', state: 'MG' },
  manhumirim: { name: 'Manhumirim', state: 'MG' },
  mantena: { name: 'Mantena', state: 'MG' },
  maravilhas: { name: 'Maravilhas', state: 'MG' },
  'mar de espanha': { name: 'Mar de Espanha', state: 'MG' },
  'maria da fe': { name: 'Maria da Fé', state: 'MG' },
  mariana: { name: 'Mariana', state: 'MG' },
  marilac: { name: 'Marilac', state: 'MG' },
  'mario campos': { name: 'Mário Campos', state: 'MG' },
  'maripa de minas': { name: 'Maripá de Minas', state: 'MG' },
  marlieria: { name: 'Marliéria', state: 'MG' },
  marmelopolis: { name: 'Marmelópolis', state: 'MG' },
  'martinho campos': { name: 'Martinho Campos', state: 'MG' },
  'martins soares': { name: 'Martins Soares', state: 'MG' },
  'mata verde': { name: 'Mata Verde', state: 'MG' },
  materlandia: { name: 'Materlândia', state: 'MG' },
  'mateus leme': { name: 'Mateus Leme', state: 'MG' },
  'mathias lobato': { name: 'Mathias Lobato', state: 'MG' },
  'matias barbosa': { name: 'Matias Barbosa', state: 'MG' },
  'matias cardoso': { name: 'Matias Cardoso', state: 'MG' },
  matipo: { name: 'Matipó', state: 'MG' },
  'mato verde': { name: 'Mato Verde', state: 'MG' },
  matozinhos: { name: 'Matozinhos', state: 'MG' },
  matutina: { name: 'Matutina', state: 'MG' },
  medeiros: { name: 'Medeiros', state: 'MG' },
  medina: { name: 'Medina', state: 'MG' },
  'mendes pimentel': { name: 'Mendes Pimentel', state: 'MG' },
  merces: { name: 'Mercês', state: 'MG' },
  mesquita: { name: 'Mesquita', state: 'MG' },
  'minas novas': { name: 'Minas Novas', state: 'MG' },
  minduri: { name: 'Minduri', state: 'MG' },
  mirabela: { name: 'Mirabela', state: 'MG' },
  miradouro: { name: 'Miradouro', state: 'MG' },
  mirai: { name: 'Miraí', state: 'MG' },
  miravania: { name: 'Miravânia', state: 'MG' },
  moeda: { name: 'Moeda', state: 'MG' },
  moema: { name: 'Moema', state: 'MG' },
  monjolos: { name: 'Monjolos', state: 'MG' },
  'monsenhor paulo': { name: 'Monsenhor Paulo', state: 'MG' },
  montalvania: { name: 'Montalvânia', state: 'MG' },
  'monte alegre de minas': { name: 'Monte Alegre de Minas', state: 'MG' },
  'monte azul': { name: 'Monte Azul', state: 'MG' },
  'monte belo': { name: 'Monte Belo', state: 'MG' },
  'monte carmelo': { name: 'Monte Carmelo', state: 'MG' },
  'monte formoso': { name: 'Monte Formoso', state: 'MG' },
  'monte santo de minas': { name: 'Monte Santo de Minas', state: 'MG' },
  'montes claros': { name: 'Montes Claros', state: 'MG' },
  'monte siao': { name: 'Monte Sião', state: 'MG' },
  montezuma: { name: 'Montezuma', state: 'MG' },
  'morada nova de minas': { name: 'Morada Nova de Minas', state: 'MG' },
  'morro da garca': { name: 'Morro da Garça', state: 'MG' },
  'morro do pilar': { name: 'Morro do Pilar', state: 'MG' },
  munhoz: { name: 'Munhoz', state: 'MG' },
  muriae: { name: 'Muriaé', state: 'MG' },
  mutum: { name: 'Mutum', state: 'MG' },
  muzambinho: { name: 'Muzambinho', state: 'MG' },
  'nacip raydan': { name: 'Nacip Raydan', state: 'MG' },
  nanuque: { name: 'Nanuque', state: 'MG' },
  naque: { name: 'Naque', state: 'MG' },
  natalandia: { name: 'Natalândia', state: 'MG' },
  natercia: { name: 'Natércia', state: 'MG' },
  nazareno: { name: 'Nazareno', state: 'MG' },
  nepomuceno: { name: 'Nepomuceno', state: 'MG' },
  ninheira: { name: 'Ninheira', state: 'MG' },
  'nova belem': { name: 'Nova Belém', state: 'MG' },
  'nova era': { name: 'Nova Era', state: 'MG' },
  'nova lima': { name: 'Nova Lima', state: 'MG' },
  'nova modica': { name: 'Nova Módica', state: 'MG' },
  'nova ponte': { name: 'Nova Ponte', state: 'MG' },
  'nova porteirinha': { name: 'Nova Porteirinha', state: 'MG' },
  'nova resende': { name: 'Nova Resende', state: 'MG' },
  'nova serrana': { name: 'Nova Serrana', state: 'MG' },
  'nova uniao': { name: 'Nova União', state: 'MG' },
  'novo cruzeiro': { name: 'Novo Cruzeiro', state: 'MG' },
  'novo oriente de minas': { name: 'Novo Oriente de Minas', state: 'MG' },
  novorizonte: { name: 'Novorizonte', state: 'MG' },
  olaria: { name: 'Olaria', state: 'MG' },
  "olhos-d'agua": { name: "Olhos-d'Água", state: 'MG' },
  'olimpio noronha': { name: 'Olímpio Noronha', state: 'MG' },
  oliveira: { name: 'Oliveira', state: 'MG' },
  'oliveira fortes': { name: 'Oliveira Fortes', state: 'MG' },
  'onca de pitangui': { name: 'Onça de Pitangui', state: 'MG' },
  oratorios: { name: 'Oratórios', state: 'MG' },
  orizania: { name: 'Orizânia', state: 'MG' },
  'ouro branco_': { name: 'Ouro Branco', state: 'MG' },
  'ouro fino': { name: 'Ouro Fino', state: 'MG' },
  'ouro preto': { name: 'Ouro Preto', state: 'MG' },
  'ouro verde de minas': { name: 'Ouro Verde de Minas', state: 'MG' },
  'padre carvalho': { name: 'Padre Carvalho', state: 'MG' },
  'padre paraiso': { name: 'Padre Paraíso', state: 'MG' },
  paineiras: { name: 'Paineiras', state: 'MG' },
  pains: { name: 'Pains', state: 'MG' },
  'pai pedro': { name: 'Pai Pedro', state: 'MG' },
  paiva: { name: 'Paiva', state: 'MG' },
  palma: { name: 'Palma', state: 'MG' },
  palmopolis: { name: 'Palmópolis', state: 'MG' },
  papagaios: { name: 'Papagaios', state: 'MG' },
  paracatu: { name: 'Paracatu', state: 'MG' },
  'para de minas': { name: 'Pará de Minas', state: 'MG' },
  paraguacu: { name: 'Paraguaçu', state: 'MG' },
  paraisopolis: { name: 'Paraisópolis', state: 'MG' },
  paraopeba: { name: 'Paraopeba', state: 'MG' },
  passabem: { name: 'Passabém', state: 'MG' },
  'passa quatro': { name: 'Passa Quatro', state: 'MG' },
  'passa tempo': { name: 'Passa Tempo', state: 'MG' },
  'passa vinte': { name: 'Passa Vinte', state: 'MG' },
  passos: { name: 'Passos', state: 'MG' },
  patis: { name: 'Patis', state: 'MG' },
  'patos de minas': { name: 'Patos de Minas', state: 'MG' },
  patrocinio: { name: 'Patrocínio', state: 'MG' },
  'patrocinio do muriae': { name: 'Patrocínio do Muriaé', state: 'MG' },
  'paula candido': { name: 'Paula Cândido', state: 'MG' },
  paulistas: { name: 'Paulistas', state: 'MG' },
  pavao: { name: 'Pavão', state: 'MG' },
  pecanha: { name: 'Peçanha', state: 'MG' },
  'pedra azul': { name: 'Pedra Azul', state: 'MG' },
  'pedra bonita': { name: 'Pedra Bonita', state: 'MG' },
  'pedra do anta': { name: 'Pedra do Anta', state: 'MG' },
  'pedra do indaia': { name: 'Pedra do Indaiá', state: 'MG' },
  'pedra dourada': { name: 'Pedra Dourada', state: 'MG' },
  pedralva: { name: 'Pedralva', state: 'MG' },
  'pedras de maria da cruz': { name: 'Pedras de Maria da Cruz', state: 'MG' },
  pedrinopolis: { name: 'Pedrinópolis', state: 'MG' },
  'pedro leopoldo': { name: 'Pedro Leopoldo', state: 'MG' },
  'pedro teixeira': { name: 'Pedro Teixeira', state: 'MG' },
  pequeri: { name: 'Pequeri', state: 'MG' },
  pequi: { name: 'Pequi', state: 'MG' },
  perdigao: { name: 'Perdigão', state: 'MG' },
  perdizes: { name: 'Perdizes', state: 'MG' },
  perdoes: { name: 'Perdões', state: 'MG' },
  periquito: { name: 'Periquito', state: 'MG' },
  pescador: { name: 'Pescador', state: 'MG' },
  piau: { name: 'Piau', state: 'MG' },
  'piedade de caratinga': { name: 'Piedade de Caratinga', state: 'MG' },
  'piedade de ponte nova': { name: 'Piedade de Ponte Nova', state: 'MG' },
  'piedade do rio grande': { name: 'Piedade do Rio Grande', state: 'MG' },
  'piedade dos gerais': { name: 'Piedade dos Gerais', state: 'MG' },
  pimenta: { name: 'Pimenta', state: 'MG' },
  "pingo d'agua": { name: "Pingo d'Água", state: 'MG' },
  pintopolis: { name: 'Pintópolis', state: 'MG' },
  piracema: { name: 'Piracema', state: 'MG' },
  pirajuba: { name: 'Pirajuba', state: 'MG' },
  piranga: { name: 'Piranga', state: 'MG' },
  pirangucu: { name: 'Piranguçu', state: 'MG' },
  piranguinho: { name: 'Piranguinho', state: 'MG' },
  pirapetinga: { name: 'Pirapetinga', state: 'MG' },
  pirapora: { name: 'Pirapora', state: 'MG' },
  pirauba: { name: 'Piraúba', state: 'MG' },
  pitangui: { name: 'Pitangui', state: 'MG' },
  piumhi: { name: 'Piumhi', state: 'MG' },
  planura: { name: 'Planura', state: 'MG' },
  'poco fundo': { name: 'Poço Fundo', state: 'MG' },
  'pocos de caldas': { name: 'Poços de Caldas', state: 'MG' },
  pocrane: { name: 'Pocrane', state: 'MG' },
  pompeu: { name: 'Pompéu', state: 'MG' },
  'ponte nova': { name: 'Ponte Nova', state: 'MG' },
  'ponto chique': { name: 'Ponto Chique', state: 'MG' },
  'ponto dos volantes': { name: 'Ponto dos Volantes', state: 'MG' },
  porteirinha: { name: 'Porteirinha', state: 'MG' },
  'porto firme': { name: 'Porto Firme', state: 'MG' },
  pote: { name: 'Poté', state: 'MG' },
  'pouso alegre': { name: 'Pouso Alegre', state: 'MG' },
  'pouso alto': { name: 'Pouso Alto', state: 'MG' },
  prados: { name: 'Prados', state: 'MG' },
  prata: { name: 'Prata', state: 'MG' },
  pratapolis: { name: 'Pratápolis', state: 'MG' },
  pratinha: { name: 'Pratinha', state: 'MG' },
  'presidente bernardes': { name: 'Presidente Bernardes', state: 'MG' },
  'presidente juscelino_': { name: 'Presidente Juscelino', state: 'MG' },
  'presidente kubitschek': { name: 'Presidente Kubitschek', state: 'MG' },
  'presidente olegario': { name: 'Presidente Olegário', state: 'MG' },
  'prudente de morais': { name: 'Prudente de Morais', state: 'MG' },
  'quartel geral': { name: 'Quartel Geral', state: 'MG' },
  queluzito: { name: 'Queluzito', state: 'MG' },
  raposos: { name: 'Raposos', state: 'MG' },
  'raul soares': { name: 'Raul Soares', state: 'MG' },
  recreio: { name: 'Recreio', state: 'MG' },
  reduto: { name: 'Reduto', state: 'MG' },
  'resende costa': { name: 'Resende Costa', state: 'MG' },
  resplendor: { name: 'Resplendor', state: 'MG' },
  ressaquinha: { name: 'Ressaquinha', state: 'MG' },
  riachinho: { name: 'Riachinho', state: 'MG' },
  'riacho dos machados': { name: 'Riacho dos Machados', state: 'MG' },
  'ribeirao das neves': { name: 'Ribeirão das Neves', state: 'MG' },
  'ribeirao vermelho': { name: 'Ribeirão Vermelho', state: 'MG' },
  'rio acima': { name: 'Rio Acima', state: 'MG' },
  'rio casca': { name: 'Rio Casca', state: 'MG' },
  'rio doce': { name: 'Rio Doce', state: 'MG' },
  'rio do prado': { name: 'Rio do Prado', state: 'MG' },
  'rio espera': { name: 'Rio Espera', state: 'MG' },
  'rio manso': { name: 'Rio Manso', state: 'MG' },
  'rio novo': { name: 'Rio Novo', state: 'MG' },
  'rio paranaiba': { name: 'Rio Paranaíba', state: 'MG' },
  'rio pardo de minas': { name: 'Rio Pardo de Minas', state: 'MG' },
  'rio piracicaba': { name: 'Rio Piracicaba', state: 'MG' },
  'rio pomba': { name: 'Rio Pomba', state: 'MG' },
  'rio preto': { name: 'Rio Preto', state: 'MG' },
  'rio vermelho': { name: 'Rio Vermelho', state: 'MG' },
  ritapolis: { name: 'Ritápolis', state: 'MG' },
  'rochedo de minas': { name: 'Rochedo de Minas', state: 'MG' },
  rodeiro: { name: 'Rodeiro', state: 'MG' },
  romaria: { name: 'Romaria', state: 'MG' },
  'rosario da limeira': { name: 'Rosário da Limeira', state: 'MG' },
  rubelita: { name: 'Rubelita', state: 'MG' },
  rubim: { name: 'Rubim', state: 'MG' },
  sabara: { name: 'Sabará', state: 'MG' },
  sabinopolis: { name: 'Sabinópolis', state: 'MG' },
  sacramento: { name: 'Sacramento', state: 'MG' },
  salinas: { name: 'Salinas', state: 'MG' },
  'salto da divisa': { name: 'Salto da Divisa', state: 'MG' },
  'santa barbara_': { name: 'Santa Bárbara', state: 'MG' },
  'santa barbara do leste': { name: 'Santa Bárbara do Leste', state: 'MG' },
  'santa barbara do monte verde': { name: 'Santa Bárbara do Monte Verde', state: 'MG' },
  'santa barbara do tugurio': { name: 'Santa Bárbara do Tugúrio', state: 'MG' },
  'santa cruz de minas': { name: 'Santa Cruz de Minas', state: 'MG' },
  'santa cruz de salinas': { name: 'Santa Cruz de Salinas', state: 'MG' },
  'santa cruz do escalvado': { name: 'Santa Cruz do Escalvado', state: 'MG' },
  'santa efigenia de minas': { name: 'Santa Efigênia de Minas', state: 'MG' },
  'santa fe de minas': { name: 'Santa Fé de Minas', state: 'MG' },
  'santa helena de minas': { name: 'Santa Helena de Minas', state: 'MG' },
  'santa juliana': { name: 'Santa Juliana', state: 'MG' },
  'santa luzia__': { name: 'Santa Luzia', state: 'MG' },
  'santa margarida': { name: 'Santa Margarida', state: 'MG' },
  'santa maria de itabira': { name: 'Santa Maria de Itabira', state: 'MG' },
  'santa maria do salto': { name: 'Santa Maria do Salto', state: 'MG' },
  'santa maria do suacui': { name: 'Santa Maria do Suaçuí', state: 'MG' },
  'santana da vargem': { name: 'Santana da Vargem', state: 'MG' },
  'santana de cataguases': { name: 'Santana de Cataguases', state: 'MG' },
  'santana de pirapama': { name: 'Santana de Pirapama', state: 'MG' },
  'santana do deserto': { name: 'Santana do Deserto', state: 'MG' },
  'santana do garambeu': { name: 'Santana do Garambéu', state: 'MG' },
  'santana do jacare': { name: 'Santana do Jacaré', state: 'MG' },
  'santana do manhuacu': { name: 'Santana do Manhuaçu', state: 'MG' },
  'santana do paraiso': { name: 'Santana do Paraíso', state: 'MG' },
  'santana do riacho': { name: 'Santana do Riacho', state: 'MG' },
  'santana dos montes': { name: 'Santana dos Montes', state: 'MG' },
  'santa rita de caldas': { name: 'Santa Rita de Caldas', state: 'MG' },
  'santa rita de jacutinga': { name: 'Santa Rita de Jacutinga', state: 'MG' },
  'santa rita de minas': { name: 'Santa Rita de Minas', state: 'MG' },
  'santa rita de ibitipoca': { name: 'Santa Rita de Ibitipoca', state: 'MG' },
  'santa rita do itueto': { name: 'Santa Rita do Itueto', state: 'MG' },
  'santa rita do sapucai': { name: 'Santa Rita do Sapucaí', state: 'MG' },
  'santa rosa da serra': { name: 'Santa Rosa da Serra', state: 'MG' },
  'santa vitoria': { name: 'Santa Vitória', state: 'MG' },
  'santo antonio do amparo': { name: 'Santo Antônio do Amparo', state: 'MG' },
  'santo antonio do aventureiro': { name: 'Santo Antônio do Aventureiro', state: 'MG' },
  'santo antonio do grama': { name: 'Santo Antônio do Grama', state: 'MG' },
  'santo antonio do itambe': { name: 'Santo Antônio do Itambé', state: 'MG' },
  'santo antonio do jacinto': { name: 'Santo Antônio do Jacinto', state: 'MG' },
  'santo antonio do monte': { name: 'Santo Antônio do Monte', state: 'MG' },
  'santo antonio do retiro': { name: 'Santo Antônio do Retiro', state: 'MG' },
  'santo antonio do rio abaixo': { name: 'Santo Antônio do Rio Abaixo', state: 'MG' },
  'santo hipolito': { name: 'Santo Hipólito', state: 'MG' },
  'santos dumont': { name: 'Santos Dumont', state: 'MG' },
  'sao bento abade': { name: 'São Bento Abade', state: 'MG' },
  'sao bras do suacui': { name: 'São Brás do Suaçuí', state: 'MG' },
  'sao domingos das dores': { name: 'São Domingos das Dores', state: 'MG' },
  'sao domingos do prata': { name: 'São Domingos do Prata', state: 'MG' },
  'sao felix de minas': { name: 'São Félix de Minas', state: 'MG' },
  'sao francisco': { name: 'São Francisco', state: 'MG' },
  'sao francisco de paula': { name: 'São Francisco de Paula', state: 'MG' },
  'sao francisco de sales': { name: 'São Francisco de Sales', state: 'MG' },
  'sao francisco do gloria': { name: 'São Francisco do Glória', state: 'MG' },
  'sao geraldo': { name: 'São Geraldo', state: 'MG' },
  'sao geraldo da piedade': { name: 'São Geraldo da Piedade', state: 'MG' },
  'sao geraldo do baixio': { name: 'São Geraldo do Baixio', state: 'MG' },
  'sao goncalo do abaete': { name: 'São Gonçalo do Abaeté', state: 'MG' },
  'sao goncalo do para': { name: 'São Gonçalo do Pará', state: 'MG' },
  'sao goncalo do rio abaixo': { name: 'São Gonçalo do Rio Abaixo', state: 'MG' },
  'sao goncalo do rio preto': { name: 'São Gonçalo do Rio Preto', state: 'MG' },
  'sao goncalo do sapucai': { name: 'São Gonçalo do Sapucaí', state: 'MG' },
  'sao gotardo': { name: 'São Gotardo', state: 'MG' },
  'sao joao batista do gloria': { name: 'São João Batista do Glória', state: 'MG' },
  'sao joao da lagoa': { name: 'São João da Lagoa', state: 'MG' },
  'sao joao da mata': { name: 'São João da Mata', state: 'MG' },
  'sao joao da ponte': { name: 'São João da Ponte', state: 'MG' },
  'sao joao das missoes': { name: 'São João das Missões', state: 'MG' },
  'sao joao del-rei': { name: 'São João del-Rei', state: 'MG' },
  'sao joao do manhuacu': { name: 'São João do Manhuaçu', state: 'MG' },
  'sao joao do manteninha': { name: 'São João do Manteninha', state: 'MG' },
  'sao joao do oriente': { name: 'São João do Oriente', state: 'MG' },
  'sao joao do pacui': { name: 'São João do Pacuí', state: 'MG' },
  'sao joao do paraiso_': { name: 'São João do Paraíso', state: 'MG' },
  'sao joao evangelista': { name: 'São João Evangelista', state: 'MG' },
  'sao joao nepomuceno': { name: 'São João Nepomuceno', state: 'MG' },
  'sao joaquim de bicas': { name: 'São Joaquim de Bicas', state: 'MG' },
  'sao jose da barra': { name: 'São José da Barra', state: 'MG' },
  'sao jose da lapa': { name: 'São José da Lapa', state: 'MG' },
  'sao jose da safira': { name: 'São José da Safira', state: 'MG' },
  'sao jose da varginha': { name: 'São José da Varginha', state: 'MG' },
  'sao jose do alegre': { name: 'São José do Alegre', state: 'MG' },
  'sao jose do divino': { name: 'São José do Divino', state: 'MG' },
  'sao jose do goiabal': { name: 'São José do Goiabal', state: 'MG' },
  'sao jose do jacuri': { name: 'São José do Jacuri', state: 'MG' },
  'sao jose do mantimento': { name: 'São José do Mantimento', state: 'MG' },
  'sao lourenco': { name: 'São Lourenço', state: 'MG' },
  'sao miguel do anta': { name: 'São Miguel do Anta', state: 'MG' },
  'sao pedro da uniao': { name: 'São Pedro da União', state: 'MG' },
  'sao pedro dos ferros': { name: 'São Pedro dos Ferros', state: 'MG' },
  'sao pedro do suacui': { name: 'São Pedro do Suaçuí', state: 'MG' },
  'sao romao': { name: 'São Romão', state: 'MG' },
  'sao roque de minas': { name: 'São Roque de Minas', state: 'MG' },
  'sao sebastiao da bela vista': { name: 'São Sebastião da Bela Vista', state: 'MG' },
  'sao sebastiao da vargem alegre': { name: 'São Sebastião da Vargem Alegre', state: 'MG' },
  'sao sebastiao do anta': { name: 'São Sebastião do Anta', state: 'MG' },
  'sao sebastiao do maranhao': { name: 'São Sebastião do Maranhão', state: 'MG' },
  'sao sebastiao do oeste': { name: 'São Sebastião do Oeste', state: 'MG' },
  'sao sebastiao do paraiso': { name: 'São Sebastião do Paraíso', state: 'MG' },
  'sao sebastiao do rio preto': { name: 'São Sebastião do Rio Preto', state: 'MG' },
  'sao sebastiao do rio verde': { name: 'São Sebastião do Rio Verde', state: 'MG' },
  'sao tome das letras': { name: 'São Tomé das Letras', state: 'MG' },
  'sao tiago': { name: 'São Tiago', state: 'MG' },
  'sao tomas de aquino': { name: 'São Tomás de Aquino', state: 'MG' },
  'sao vicente de minas': { name: 'São Vicente de Minas', state: 'MG' },
  'sapucai-mirim': { name: 'Sapucaí-Mirim', state: 'MG' },
  sardoa: { name: 'Sardoá', state: 'MG' },
  sarzedo: { name: 'Sarzedo', state: 'MG' },
  'sem-peixe': { name: 'Sem-Peixe', state: 'MG' },
  'senador amaral': { name: 'Senador Amaral', state: 'MG' },
  'senador cortes': { name: 'Senador Cortes', state: 'MG' },
  'senador firmino': { name: 'Senador Firmino', state: 'MG' },
  'senador jose bento': { name: 'Senador José Bento', state: 'MG' },
  'senador modestino goncalves': { name: 'Senador Modestino Gonçalves', state: 'MG' },
  'senhora de oliveira': { name: 'Senhora de Oliveira', state: 'MG' },
  'senhora do porto': { name: 'Senhora do Porto', state: 'MG' },
  'senhora dos remedios': { name: 'Senhora dos Remédios', state: 'MG' },
  sericita: { name: 'Sericita', state: 'MG' },
  seritinga: { name: 'Seritinga', state: 'MG' },
  'serra azul de minas': { name: 'Serra Azul de Minas', state: 'MG' },
  'serra da saudade': { name: 'Serra da Saudade', state: 'MG' },
  'serra dos aimores': { name: 'Serra dos Aimorés', state: 'MG' },
  'serra do salitre': { name: 'Serra do Salitre', state: 'MG' },
  serrania: { name: 'Serrania', state: 'MG' },
  'serranopolis de minas': { name: 'Serranópolis de Minas', state: 'MG' },
  serranos: { name: 'Serranos', state: 'MG' },
  serro: { name: 'Serro', state: 'MG' },
  'sete lagoas': { name: 'Sete Lagoas', state: 'MG' },
  setubinha: { name: 'Setubinha', state: 'MG' },
  silveirania: { name: 'Silveirânia', state: 'MG' },
  silvianopolis: { name: 'Silvianópolis', state: 'MG' },
  'simao pereira': { name: 'Simão Pereira', state: 'MG' },
  simonesia: { name: 'Simonésia', state: 'MG' },
  sobralia: { name: 'Sobrália', state: 'MG' },
  'soledade de minas': { name: 'Soledade de Minas', state: 'MG' },
  tabuleiro: { name: 'Tabuleiro', state: 'MG' },
  taiobeiras: { name: 'Taiobeiras', state: 'MG' },
  taparuba: { name: 'Taparuba', state: 'MG' },
  tapira: { name: 'Tapira', state: 'MG' },
  tapirai: { name: 'Tapiraí', state: 'MG' },
  'taquaracu de minas': { name: 'Taquaraçu de Minas', state: 'MG' },
  tarumirim: { name: 'Tarumirim', state: 'MG' },
  teixeiras: { name: 'Teixeiras', state: 'MG' },
  'teofilo otoni': { name: 'Teófilo Otoni', state: 'MG' },
  timoteo: { name: 'Timóteo', state: 'MG' },
  tiradentes: { name: 'Tiradentes', state: 'MG' },
  tiros: { name: 'Tiros', state: 'MG' },
  tocantins: { name: 'Tocantins', state: 'MG' },
  'tocos do moji': { name: 'Tocos do Moji', state: 'MG' },
  toledo: { name: 'Toledo', state: 'MG' },
  tombos: { name: 'Tombos', state: 'MG' },
  'tres coracoes': { name: 'Três Corações', state: 'MG' },
  'tres marias': { name: 'Três Marias', state: 'MG' },
  'tres pontas': { name: 'Três Pontas', state: 'MG' },
  tumiritinga: { name: 'Tumiritinga', state: 'MG' },
  tupaciguara: { name: 'Tupaciguara', state: 'MG' },
  turmalina: { name: 'Turmalina', state: 'MG' },
  turvolandia: { name: 'Turvolândia', state: 'MG' },
  uba: { name: 'Ubá', state: 'MG' },
  ubai: { name: 'Ubaí', state: 'MG' },
  ubaporanga: { name: 'Ubaporanga', state: 'MG' },
  uberaba: { name: 'Uberaba', state: 'MG' },
  uberlandia: { name: 'Uberlândia', state: 'MG' },
  umburatiba: { name: 'Umburatiba', state: 'MG' },
  unai: { name: 'Unaí', state: 'MG' },
  'uniao de minas': { name: 'União de Minas', state: 'MG' },
  'uruana de minas': { name: 'Uruana de Minas', state: 'MG' },
  urucania: { name: 'Urucânia', state: 'MG' },
  urucuia: { name: 'Urucuia', state: 'MG' },
  'vargem alegre': { name: 'Vargem Alegre', state: 'MG' },
  'vargem bonita': { name: 'Vargem Bonita', state: 'MG' },
  'vargem grande do rio pardo': { name: 'Vargem Grande do Rio Pardo', state: 'MG' },
  varginha: { name: 'Varginha', state: 'MG' },
  'varjao de minas': { name: 'Varjão de Minas', state: 'MG' },
  'varzea da palma': { name: 'Várzea da Palma', state: 'MG' },
  varzelandia: { name: 'Varzelândia', state: 'MG' },
  vazante: { name: 'Vazante', state: 'MG' },
  verdelandia: { name: 'Verdelândia', state: 'MG' },
  veredinha: { name: 'Veredinha', state: 'MG' },
  verissimo: { name: 'Veríssimo', state: 'MG' },
  'vermelho novo': { name: 'Vermelho Novo', state: 'MG' },
  vespasiano: { name: 'Vespasiano', state: 'MG' },
  vicosa_: { name: 'Viçosa', state: 'MG' },
  vieiras: { name: 'Vieiras', state: 'MG' },
  'virgem da lapa': { name: 'Virgem da Lapa', state: 'MG' },
  virginia: { name: 'Virgínia', state: 'MG' },
  virginopolis: { name: 'Virginópolis', state: 'MG' },
  virgolandia: { name: 'Virgolândia', state: 'MG' },
  'visconde do rio branco': { name: 'Visconde do Rio Branco', state: 'MG' },
  'volta grande': { name: 'Volta Grande', state: 'MG' },
  'wenceslau braz': { name: 'Wenceslau Braz', state: 'MG' },
};
