export const cities = {
  'agua clara': 'Água Clara',
  alcinopolis: 'Alcinópolis',
  amambai: 'Amambai',
  anastacio: 'Anastácio',
  anaurilandia: 'Anaurilândia',
  angelica: 'Angélica',
  'antonio joao': 'Antônio João',
  'aparecida do taboado': 'Aparecida do Taboado',
  aquidauana: 'Aquidauana',
  'aral moreira': 'Aral Moreira',
  bandeirantes: 'Bandeirantes',
  bataguassu: 'Bataguassu',
  bataypora: 'Batayporã',
  'bela vista': 'Bela Vista',
  bodoquena: 'Bodoquena',
  bonito_: 'Bonito',
  brasilandia: 'Brasilândia',
  caarapo: 'Caarapó',
  camapua: 'Camapuã',
  'campo grande_': 'Campo Grande',
  caracol: 'Caracol',
  cassilandia: 'Cassilândia',
  'chapadao do sul': 'Chapadão do Sul',
  corguinho: 'Corguinho',
  'coronel sapucaia': 'Coronel Sapucaia',
  corumba: 'Corumbá',
  'costa rica': 'Costa Rica',
  coxim: 'Coxim',
  deodapolis: 'Deodápolis',
  'dois irmaos do buriti': 'Dois Irmãos do Buriti',
  douradina: 'Douradina',
  dourados: 'Dourados',
  eldorado: 'Eldorado',
  'fatima do sul': 'Fátima do Sul',
  figueirao: 'Figueirão',
  'gloria de dourados': 'Glória de Dourados',
  'guia lopes da laguna': 'Guia Lopes da Laguna',
  iguatemi: 'Iguatemi',
  inocencia: 'Inocência',
  itapora: 'Itaporã',
  itaquirai: 'Itaquiraí',
  ivinhema: 'Ivinhema',
  japora: 'Japorã',
  jaraguari: 'Jaraguari',
  jardim_: 'Jardim',
  jatei: 'Jateí',
  juti: 'Juti',
  ladario: 'Ladário',
  'laguna carapa': 'Laguna Carapã',
  maracaju: 'Maracaju',
  miranda: 'Miranda',
  'mundo novo__': 'Mundo Novo',
  navirai: 'Naviraí',
  nioaque: 'Nioaque',
  'nova alvorada do sul': 'Nova Alvorada do Sul',
  'nova andradina': 'Nova Andradina',
  'novo horizonte do sul': 'Novo Horizonte do Sul',
  'paraiso das aguas': 'Paraíso das Águas',
  paranaiba: 'Paranaíba',
  paranhos: 'Paranhos',
  'pedro gomes': 'Pedro Gomes',
  'ponta pora': 'Ponta Porã',
  'porto murtinho': 'Porto Murtinho',
  'ribas do rio pardo': 'Ribas do Rio Pardo',
  'rio brilhante': 'Rio Brilhante',
  'rio negro': 'Rio Negro',
  'rio verde de mato grosso': 'Rio Verde de Mato Grosso',
  rochedo: 'Rochedo',
  'santa rita do pardo': 'Santa Rita do Pardo',
  'sao gabriel do oeste': 'São Gabriel do Oeste',
  selviria: 'Selvíria',
  'sete quedas': 'Sete Quedas',
  sidrolandia: 'Sidrolândia',
  sonora: 'Sonora',
  tacuru: 'Tacuru',
  taquarussu: 'Taquarussu',
  terenos: 'Terenos',
  'tres lagoas': 'Três Lagoas',
  vicentina: 'Vicentina',
};
