export const cities = {
  acorizal: { name: 'Acorizal', state: 'MT' },
  'agua boa_': { name: 'Água Boa', state: 'MT' },
  'alta floresta': { name: 'Alta Floresta', state: 'MT' },
  'alto araguaia': { name: 'Alto Araguaia', state: 'MT' },
  'alto da boa vista': { name: 'Alto da Boa Vista', state: 'MT' },
  'alto garcas': { name: 'Alto Garças', state: 'MT' },
  'alto paraguai': { name: 'Alto Paraguai', state: 'MT' },
  'alto taquari': { name: 'Alto Taquari', state: 'MT' },
  apiacas: { name: 'Apiacás', state: 'MT' },
  araguaiana: { name: 'Araguaiana', state: 'MT' },
  araguainha: { name: 'Araguainha', state: 'MT' },
  araputanga: { name: 'Araputanga', state: 'MT' },
  arenapolis: { name: 'Arenápolis', state: 'MT' },
  aripuana: { name: 'Aripuanã', state: 'MT' },
  'barao de melgaco': { name: 'Barão de Melgaço', state: 'MT' },
  'barra do bugres': { name: 'Barra do Bugres', state: 'MT' },
  'barra do garcas': { name: 'Barra do Garças', state: 'MT' },
  'bom jesus do araguaia': { name: 'Bom Jesus do Araguaia', state: 'MT' },
  brasnorte: { name: 'Brasnorte', state: 'MT' },
  caceres: { name: 'Cáceres', state: 'MT' },
  campinapolis: { name: 'Campinápolis', state: 'MT' },
  'campo novo do parecis': { name: 'Campo Novo do Parecis', state: 'MT' },
  'campos de julio': { name: 'Campos de Júlio', state: 'MT' },
  'campo verde': { name: 'Campo Verde', state: 'MT' },
  'canabrava do norte': { name: 'Canabrava do Norte', state: 'MT' },
  canarana_: { name: 'Canarana', state: 'MT' },
  carlinda: { name: 'Carlinda', state: 'MT' },
  castanheira: { name: 'Castanheira', state: 'MT' },
  'chapada dos guimaraes': { name: 'Chapada dos Guimarães', state: 'MT' },
  claudia: { name: 'Cláudia', state: 'MT' },
  cocalinho: { name: 'Cocalinho', state: 'MT' },
  colider: { name: 'Colíder', state: 'MT' },
  colniza: { name: 'Colniza', state: 'MT' },
  comodoro: { name: 'Comodoro', state: 'MT' },
  confresa: { name: 'Confresa', state: 'MT' },
  "conquista d'oeste": { name: "Conquista d'Oeste", state: 'MT' },
  cotriguacu: { name: 'Cotriguaçu', state: 'MT' },
  cuiaba: { name: 'Cuiabá', state: 'MT' },
  curvelandia: { name: 'Curvelândia', state: 'MT' },
  denise: { name: 'Denise', state: 'MT' },
  diamantino: { name: 'Diamantino', state: 'MT' },
  'dom aquino': { name: 'Dom Aquino', state: 'MT' },
  'feliz natal': { name: 'Feliz Natal', state: 'MT' },
  "figueiropolis d'oeste": { name: "Figueirópolis d'Oeste", state: 'MT' },
  'gaucha do norte': { name: 'Gaúcha do Norte', state: 'MT' },
  'general carneiro': { name: 'General Carneiro', state: 'MT' },
  "gloria d'oeste": { name: "Glória d'Oeste", state: 'MT' },
  'guaranta do norte': { name: 'Guarantã do Norte', state: 'MT' },
  guiratinga: { name: 'Guiratinga', state: 'MT' },
  indiavai: { name: 'Indiavaí', state: 'MT' },
  'ipiranga do norte': { name: 'Ipiranga do Norte', state: 'MT' },
  itanhanga: { name: 'Itanhangá', state: 'MT' },
  itauba: { name: 'Itaúba', state: 'MT' },
  itiquira: { name: 'Itiquira', state: 'MT' },
  jaciara: { name: 'Jaciara', state: 'MT' },
  jangada: { name: 'Jangada', state: 'MT' },
  jauru: { name: 'Jauru', state: 'MT' },
  juara: { name: 'Juara', state: 'MT' },
  juina: { name: 'Juína', state: 'MT' },
  juruena: { name: 'Juruena', state: 'MT' },
  juscimeira: { name: 'Juscimeira', state: 'MT' },
  "lambari d'oeste": { name: "Lambari d'Oeste", state: 'MT' },
  'lucas do rio verde': { name: 'Lucas do Rio Verde', state: 'MT' },
  luciara: { name: 'Luciara', state: 'MT' },
  marcelandia: { name: 'Marcelândia', state: 'MT' },
  matupa: { name: 'Matupá', state: 'MT' },
  "mirassol d'oeste": { name: "Mirassol d'Oeste", state: 'MT' },
  nobres: { name: 'Nobres', state: 'MT' },
  nortelandia: { name: 'Nortelândia', state: 'MT' },
  'nossa senhora do livramento': { name: 'Nossa Senhora do Livramento', state: 'MT' },
  'nova bandeirantes': { name: 'Nova Bandeirantes', state: 'MT' },
  'nova brasilandia': { name: 'Nova Brasilândia', state: 'MT' },
  'nova canaa do norte': { name: 'Nova Canaã do Norte', state: 'MT' },
  'nova guarita': { name: 'Nova Guarita', state: 'MT' },
  'nova lacerda': { name: 'Nova Lacerda', state: 'MT' },
  'nova marilandia': { name: 'Nova Marilândia', state: 'MT' },
  'nova maringa': { name: 'Nova Maringá', state: 'MT' },
  'nova monte verde': { name: 'Nova Monte Verde', state: 'MT' },
  'nova mutum': { name: 'Nova Mutum', state: 'MT' },
  'nova nazare': { name: 'Nova Nazaré', state: 'MT' },
  'nova olimpia': { name: 'Nova Olímpia', state: 'MT' },
  'nova santa helena': { name: 'Nova Santa Helena', state: 'MT' },
  'nova ubirata': { name: 'Nova Ubiratã', state: 'MT' },
  'nova xavantina': { name: 'Nova Xavantina', state: 'MT' },
  'novo horizonte do norte': { name: 'Novo Horizonte do Norte', state: 'MT' },
  'novo mundo': { name: 'Novo Mundo', state: 'MT' },
  'novo santo antonio': { name: 'Novo Santo Antônio', state: 'MT' },
  'novo sao joaquim': { name: 'Novo São Joaquim', state: 'MT' },
  paranaita: { name: 'Paranaíta', state: 'MT' },
  paranatinga: { name: 'Paranatinga', state: 'MT' },
  'pedra preta': { name: 'Pedra Preta', state: 'MT' },
  'peixoto de azevedo': { name: 'Peixoto de Azevedo', state: 'MT' },
  'planalto da serra': { name: 'Planalto da Serra', state: 'MT' },
  pocone: { name: 'Poconé', state: 'MT' },
  'pontal do araguaia': { name: 'Pontal do Araguaia', state: 'MT' },
  'ponte branca': { name: 'Ponte Branca', state: 'MT' },
  'pontes e lacerda': { name: 'Pontes e Lacerda', state: 'MT' },
  'porto alegre do norte': { name: 'Porto Alegre do Norte', state: 'MT' },
  'porto dos gauchos': { name: 'Porto dos Gaúchos', state: 'MT' },
  'porto esperidiao': { name: 'Porto Esperidião', state: 'MT' },
  'porto estrela': { name: 'Porto Estrela', state: 'MT' },
  poxoreu: { name: 'Poxoréu', state: 'MT' },
  'primavera do leste': { name: 'Primavera do Leste', state: 'MT' },
  querencia: { name: 'Querência', state: 'MT' },
  'reserva do cabacal': { name: 'Reserva do Cabaçal', state: 'MT' },
  'ribeirao cascalheira': { name: 'Ribeirão Cascalheira', state: 'MT' },
  ribeiraozinho: { name: 'Ribeirãozinho', state: 'MT' },
  'rio branco_': { name: 'Rio Branco', state: 'MT' },
  rondolandia: { name: 'Rondolândia', state: 'MT' },
  rondonopolis: { name: 'Rondonópolis', state: 'MT' },
  'rosario oeste': { name: 'Rosário Oeste', state: 'MT' },
  'salto do ceu': { name: 'Salto do Céu', state: 'MT' },
  'santa carmem': { name: 'Santa Carmem', state: 'MT' },
  'santa cruz do xingu': { name: 'Santa Cruz do Xingu', state: 'MT' },
  'santa rita do trivelato': { name: 'Santa Rita do Trivelato', state: 'MT' },
  'santa terezinha': { name: 'Santa Terezinha', state: 'MT' },
  'santo afonso': { name: 'Santo Afonso', state: 'MT' },
  'santo antonio do leste': { name: 'Santo Antônio do Leste', state: 'MT' },
  'santo antonio de leverger': { name: 'Santo Antônio de Leverger', state: 'MT' },
  'sao felix do araguaia': { name: 'São Félix do Araguaia', state: 'MT' },
  'sao jose do povo': { name: 'São José do Povo', state: 'MT' },
  'sao jose do rio claro': { name: 'São José do Rio Claro', state: 'MT' },
  'sao jose dos quatro marcos': { name: 'São José dos Quatro Marcos', state: 'MT' },
  'sao jose do xingu': { name: 'São José do Xingu', state: 'MT' },
  'sao pedro da cipa': { name: 'São Pedro da Cipa', state: 'MT' },
  sapezal: { name: 'Sapezal', state: 'MT' },
  'serra nova dourada': { name: 'Serra Nova Dourada', state: 'MT' },
  sinop: { name: 'Sinop', state: 'MT' },
  sorriso: { name: 'Sorriso', state: 'MT' },
  tabapora: { name: 'Tabaporã', state: 'MT' },
  'tangara da serra': { name: 'Tangará da Serra', state: 'MT' },
  tapurah: { name: 'Tapurah', state: 'MT' },
  'terra nova do norte': { name: 'Terra Nova do Norte', state: 'MT' },
  tesouro: { name: 'Tesouro', state: 'MT' },
  torixoreu: { name: 'Torixoréu', state: 'MT' },
  'uniao do sul': { name: 'União do Sul', state: 'MT' },
  'vale de sao domingos': { name: 'Vale de São Domingos', state: 'MT' },
  'varzea grande': { name: 'Várzea Grande', state: 'MT' },
  vera: { name: 'Vera', state: 'MT' },
  'vila bela da santissima trindade': { name: 'Vila Bela da Santíssima Trindade', state: 'MT' },
  'vila rica': { name: 'Vila Rica', state: 'MT' },
};
