export const cities = {
  acorizal: 'Acorizal',
  'agua boa_': 'Água Boa',
  'alta floresta': 'Alta Floresta',
  'alto araguaia': 'Alto Araguaia',
  'alto da boa vista': 'Alto da Boa Vista',
  'alto garcas': 'Alto Garças',
  'alto paraguai': 'Alto Paraguai',
  'alto taquari': 'Alto Taquari',
  apiacas: 'Apiacás',
  araguaiana: 'Araguaiana',
  araguainha: 'Araguainha',
  araputanga: 'Araputanga',
  arenapolis: 'Arenápolis',
  aripuana: 'Aripuanã',
  'barao de melgaco': 'Barão de Melgaço',
  'barra do bugres': 'Barra do Bugres',
  'barra do garcas': 'Barra do Garças',
  'bom jesus do araguaia': 'Bom Jesus do Araguaia',
  brasnorte: 'Brasnorte',
  caceres: 'Cáceres',
  campinapolis: 'Campinápolis',
  'campo novo do parecis': 'Campo Novo do Parecis',
  'campos de julio': 'Campos de Júlio',
  'campo verde': 'Campo Verde',
  'canabrava do norte': 'Canabrava do Norte',
  canarana_: 'Canarana',
  carlinda: 'Carlinda',
  castanheira: 'Castanheira',
  'chapada dos guimaraes': 'Chapada dos Guimarães',
  claudia: 'Cláudia',
  cocalinho: 'Cocalinho',
  colider: 'Colíder',
  colniza: 'Colniza',
  comodoro: 'Comodoro',
  confresa: 'Confresa',
  "conquista d'oeste": "Conquista d'Oeste",
  cotriguacu: 'Cotriguaçu',
  cuiaba: 'Cuiabá',
  curvelandia: 'Curvelândia',
  denise: 'Denise',
  diamantino: 'Diamantino',
  'dom aquino': 'Dom Aquino',
  'feliz natal': 'Feliz Natal',
  "figueiropolis d'oeste": "Figueirópolis d'Oeste",
  'gaucha do norte': 'Gaúcha do Norte',
  'general carneiro': 'General Carneiro',
  "gloria d'oeste": "Glória d'Oeste",
  'guaranta do norte': 'Guarantã do Norte',
  guiratinga: 'Guiratinga',
  indiavai: 'Indiavaí',
  'ipiranga do norte': 'Ipiranga do Norte',
  itanhanga: 'Itanhangá',
  itauba: 'Itaúba',
  itiquira: 'Itiquira',
  jaciara: 'Jaciara',
  jangada: 'Jangada',
  jauru: 'Jauru',
  juara: 'Juara',
  juina: 'Juína',
  juruena: 'Juruena',
  juscimeira: 'Juscimeira',
  "lambari d'oeste": "Lambari d'Oeste",
  'lucas do rio verde': 'Lucas do Rio Verde',
  luciara: 'Luciara',
  marcelandia: 'Marcelândia',
  matupa: 'Matupá',
  "mirassol d'oeste": "Mirassol d'Oeste",
  nobres: 'Nobres',
  nortelandia: 'Nortelândia',
  'nossa senhora do livramento': 'Nossa Senhora do Livramento',
  'nova bandeirantes': 'Nova Bandeirantes',
  'nova brasilandia': 'Nova Brasilândia',
  'nova canaa do norte': 'Nova Canaã do Norte',
  'nova guarita': 'Nova Guarita',
  'nova lacerda': 'Nova Lacerda',
  'nova marilandia': 'Nova Marilândia',
  'nova maringa': 'Nova Maringá',
  'nova monte verde': 'Nova Monte Verde',
  'nova mutum': 'Nova Mutum',
  'nova nazare': 'Nova Nazaré',
  'nova olimpia': 'Nova Olímpia',
  'nova santa helena': 'Nova Santa Helena',
  'nova ubirata': 'Nova Ubiratã',
  'nova xavantina': 'Nova Xavantina',
  'novo horizonte do norte': 'Novo Horizonte do Norte',
  'novo mundo': 'Novo Mundo',
  'novo santo antonio': 'Novo Santo Antônio',
  'novo sao joaquim': 'Novo São Joaquim',
  paranaita: 'Paranaíta',
  paranatinga: 'Paranatinga',
  'pedra preta': 'Pedra Preta',
  'peixoto de azevedo': 'Peixoto de Azevedo',
  'planalto da serra': 'Planalto da Serra',
  pocone: 'Poconé',
  'pontal do araguaia': 'Pontal do Araguaia',
  'ponte branca': 'Ponte Branca',
  'pontes e lacerda': 'Pontes e Lacerda',
  'porto alegre do norte': 'Porto Alegre do Norte',
  'porto dos gauchos': 'Porto dos Gaúchos',
  'porto esperidiao': 'Porto Esperidião',
  'porto estrela': 'Porto Estrela',
  poxoreu: 'Poxoréu',
  'primavera do leste': 'Primavera do Leste',
  querencia: 'Querência',
  'reserva do cabacal': 'Reserva do Cabaçal',
  'ribeirao cascalheira': 'Ribeirão Cascalheira',
  ribeiraozinho: 'Ribeirãozinho',
  'rio branco_': 'Rio Branco',
  rondolandia: 'Rondolândia',
  rondonopolis: 'Rondonópolis',
  'rosario oeste': 'Rosário Oeste',
  'salto do ceu': 'Salto do Céu',
  'santa carmem': 'Santa Carmem',
  'santa cruz do xingu': 'Santa Cruz do Xingu',
  'santa rita do trivelato': 'Santa Rita do Trivelato',
  'santa terezinha': 'Santa Terezinha',
  'santo afonso': 'Santo Afonso',
  'santo antonio do leste': 'Santo Antônio do Leste',
  'santo antonio de leverger': 'Santo Antônio de Leverger',
  'sao felix do araguaia': 'São Félix do Araguaia',
  'sao jose do povo': 'São José do Povo',
  'sao jose do rio claro': 'São José do Rio Claro',
  'sao jose dos quatro marcos': 'São José dos Quatro Marcos',
  'sao jose do xingu': 'São José do Xingu',
  'sao pedro da cipa': 'São Pedro da Cipa',
  sapezal: 'Sapezal',
  'serra nova dourada': 'Serra Nova Dourada',
  sinop: 'Sinop',
  sorriso: 'Sorriso',
  tabapora: 'Tabaporã',
  'tangara da serra': 'Tangará da Serra',
  tapurah: 'Tapurah',
  'terra nova do norte': 'Terra Nova do Norte',
  tesouro: 'Tesouro',
  torixoreu: 'Torixoréu',
  'uniao do sul': 'União do Sul',
  'vale de sao domingos': 'Vale de São Domingos',
  'varzea grande': 'Várzea Grande',
  vera: 'Vera',
  'vila bela da santissima trindade': 'Vila Bela da Santíssima Trindade',
  'vila rica': 'Vila Rica',
};
