export const cities = {
  abaetetuba: 'Abaetetuba',
  'abel figueiredo': 'Abel Figueiredo',
  acara: 'Acará',
  afua: 'Afuá',
  'agua azul do norte': 'Água Azul do Norte',
  alenquer: 'Alenquer',
  almeirim: 'Almeirim',
  altamira: 'Altamira',
  anajas: 'Anajás',
  ananindeua: 'Ananindeua',
  anapu: 'Anapu',
  'augusto correa': 'Augusto Corrêa',
  'aurora do para': 'Aurora do Pará',
  aveiro: 'Aveiro',
  bagre: 'Bagre',
  baiao: 'Baião',
  bannach: 'Bannach',
  barcarena: 'Barcarena',
  belem_: 'Belém',
  belterra: 'Belterra',
  benevides: 'Benevides',
  'bom jesus do tocantins': 'Bom Jesus do Tocantins',
  bonito__: 'Bonito',
  braganca: 'Bragança',
  'brasil novo': 'Brasil Novo',
  'brejo grande do araguaia': 'Brejo Grande do Araguaia',
  'breu branco': 'Breu Branco',
  breves: 'Breves',
  bujaru: 'Bujaru',
  'cachoeira do arari': 'Cachoeira do Arari',
  'cachoeira do piria': 'Cachoeira do Piriá',
  cameta: 'Cametá',
  'canaa dos carajas': 'Canaã dos Carajás',
  capanema: 'Capanema',
  'capitao poco': 'Capitão Poço',
  castanhal: 'Castanhal',
  chaves: 'Chaves',
  colares: 'Colares',
  'conceicao do araguaia': 'Conceição do Araguaia',
  'concordia do para': 'Concórdia do Pará',
  'cumaru do norte': 'Cumaru do Norte',
  curionopolis: 'Curionópolis',
  curralinho: 'Curralinho',
  curua: 'Curuá',
  curuca: 'Curuçá',
  'dom eliseu': 'Dom Eliseu',
  'eldorado do carajas': 'Eldorado do Carajás',
  faro: 'Faro',
  'floresta do araguaia': 'Floresta do Araguaia',
  'garrafao do norte': 'Garrafão do Norte',
  'goianesia do para': 'Goianésia do Pará',
  gurupa: 'Gurupá',
  'igarape-acu': 'Igarapé-Açu',
  'igarape-miri': 'Igarapé-Miri',
  inhangapi: 'Inhangapi',
  'ipixuna do para': 'Ipixuna do Pará',
  irituia: 'Irituia',
  itaituba: 'Itaituba',
  itupiranga: 'Itupiranga',
  jacareacanga: 'Jacareacanga',
  jacunda: 'Jacundá',
  juruti: 'Juruti',
  'limoeiro do ajuru': 'Limoeiro do Ajuru',
  'mae do rio': 'Mãe do Rio',
  'magalhaes barata': 'Magalhães Barata',
  maraba: 'Marabá',
  maracana: 'Maracanã',
  marapanim: 'Marapanim',
  marituba: 'Marituba',
  medicilandia: 'Medicilândia',
  melgaco: 'Melgaço',
  mocajuba: 'Mocajuba',
  moju: 'Moju',
  'mojui dos campos': 'Mojuí dos Campos',
  'monte alegre': 'Monte Alegre',
  muana: 'Muaná',
  'nova esperanca do piria': 'Nova Esperança do Piriá',
  'nova ipixuna': 'Nova Ipixuna',
  'nova timboteua': 'Nova Timboteua',
  'novo progresso': 'Novo Progresso',
  'novo repartimento': 'Novo Repartimento',
  obidos: 'Óbidos',
  'oeiras do para': 'Oeiras do Pará',
  oriximina: 'Oriximiná',
  ourem: 'Ourém',
  'ourilandia do norte': 'Ourilândia do Norte',
  pacaja: 'Pacajá',
  'palestina do para': 'Palestina do Pará',
  paragominas: 'Paragominas',
  parauapebas: 'Parauapebas',
  "pau-d'arco": "Pau-d'Arco",
  'peixe-boi': 'Peixe-Boi',
  picarra: 'Piçarra',
  placas: 'Placas',
  'ponta de pedras': 'Ponta de Pedras',
  portel: 'Portel',
  'porto de moz': 'Porto de Moz',
  prainha: 'Prainha',
  primavera: 'Primavera',
  quatipuru: 'Quatipuru',
  redencao_: 'Redenção',
  'rio maria': 'Rio Maria',
  'rondon do para': 'Rondon do Pará',
  ruropolis: 'Rurópolis',
  salinopolis: 'Salinópolis',
  salvaterra: 'Salvaterra',
  'santa barbara do para': 'Santa Bárbara do Pará',
  'santa cruz do arari': 'Santa Cruz do Arari',
  'santa izabel do para': 'Santa Izabel do Pará',
  'santa luzia do para': 'Santa Luzia do Pará',
  'santa maria das barreiras': 'Santa Maria das Barreiras',
  'santa maria do para': 'Santa Maria do Pará',
  'santana do araguaia': 'Santana do Araguaia',
  santarem: 'Santarém',
  'santarem novo': 'Santarém Novo',
  'santo antonio do taua': 'Santo Antônio do Tauá',
  'sao caetano de odivelas': 'São Caetano de Odivelas',
  'sao domingos do araguaia': 'São Domingos do Araguaia',
  'sao domingos do capim': 'São Domingos do Capim',
  'sao felix do xingu': 'São Félix do Xingu',
  'sao francisco do para': 'São Francisco do Pará',
  'sao geraldo do araguaia': 'São Geraldo do Araguaia',
  'sao joao da ponta': 'São João da Ponta',
  'sao joao de pirabas': 'São João de Pirabas',
  'sao joao do araguaia': 'São João do Araguaia',
  'sao miguel do guama': 'São Miguel do Guamá',
  'sao sebastiao da boa vista': 'São Sebastião da Boa Vista',
  sapucaia: 'Sapucaia',
  'senador jose porfirio': 'Senador José Porfírio',
  soure: 'Soure',
  tailandia: 'Tailândia',
  'terra alta': 'Terra Alta',
  'terra santa': 'Terra Santa',
  'tome-acu': 'Tomé-Açu',
  tracuateua: 'Tracuateua',
  trairao: 'Trairão',
  tucuma: 'Tucumã',
  tucurui: 'Tucuruí',
  ulianopolis: 'Ulianópolis',
  uruara: 'Uruará',
  vigia: 'Vigia',
  'vitoria do xingu': 'Vitória do Xingu',
  viseu: 'Viseu',
  xinguara: 'Xinguara',
};
