export const cities = {
  'agua branca_': 'Água Branca',
  aguiar: 'Aguiar',
  'alagoa grande': 'Alagoa Grande',
  'alagoa nova': 'Alagoa Nova',
  alagoinha: 'Alagoinha',
  alcantil: 'Alcantil',
  'algodao de jandaira': 'Algodão de Jandaíra',
  alhandra: 'Alhandra',
  amparo: 'Amparo',
  aparecida: 'Aparecida',
  aracagi: 'Araçagi',
  arara: 'Arara',
  araruna: 'Araruna',
  areia: 'Areia',
  'areia de baraunas': 'Areia de Baraúnas',
  areial: 'Areial',
  aroeiras: 'Aroeiras',
  assuncao: 'Assunção',
  'baia da traicao': 'Baía da Traição',
  bananeiras: 'Bananeiras',
  barauna: 'Baraúna',
  'barra de santana': 'Barra de Santana',
  'barra de santa rosa': 'Barra de Santa Rosa',
  'barra de sao miguel_': 'Barra de São Miguel',
  bayeux: 'Bayeux',
  belem__: 'Belém',
  'belem do brejo do cruz': 'Belém do Brejo do Cruz',
  'bernardino batista': 'Bernardino Batista',
  'boa ventura': 'Boa Ventura',
  'boa vista': 'Boa Vista',
  'bom jesus': 'Bom Jesus',
  'bom sucesso_': 'Bom Sucesso',
  'bonito de santa fe': 'Bonito de Santa Fé',
  boqueirao: 'Boqueirão',
  borborema: 'Borborema',
  'brejo do cruz': 'Brejo do Cruz',
  'brejo dos santos': 'Brejo dos Santos',
  caapora: 'Caaporã',
  cabaceiras: 'Cabaceiras',
  cabedelo: 'Cabedelo',
  'cachoeira dos indios': 'Cachoeira dos Índios',
  'cacimba de areia': 'Cacimba de Areia',
  'cacimba de dentro': 'Cacimba de Dentro',
  cacimbas: 'Cacimbas',
  caicara: 'Caiçara',
  cajazeiras: 'Cajazeiras',
  cajazeirinhas: 'Cajazeirinhas',
  'caldas brandao': 'Caldas Brandão',
  camalau: 'Camalaú',
  'campina grande': 'Campina Grande',
  capim: 'Capim',
  caraubas: 'Caraúbas',
  carrapateira: 'Carrapateira',
  casserengue: 'Casserengue',
  catingueira: 'Catingueira',
  'catole do rocha': 'Catolé do Rocha',
  caturite: 'Caturité',
  conceicao: 'Conceição',
  condado: 'Condado',
  conde_: 'Conde',
  congo: 'Congo',
  coremas: 'Coremas',
  coxixola: 'Coxixola',
  'cruz do espirito santo': 'Cruz do Espírito Santo',
  cubati: 'Cubati',
  cuite: 'Cuité',
  'cuite de mamanguape': 'Cuité de Mamanguape',
  cuitegi: 'Cuitegi',
  'curral de cima': 'Curral de Cima',
  'curral velho': 'Curral Velho',
  damiao: 'Damião',
  desterro: 'Desterro',
  diamante: 'Diamante',
  'dona ines': 'Dona Inês',
  'duas estradas': 'Duas Estradas',
  emas: 'Emas',
  esperanca: 'Esperança',
  fagundes: 'Fagundes',
  'frei martinho': 'Frei Martinho',
  'gado bravo': 'Gado Bravo',
  guarabira: 'Guarabira',
  gurinhem: 'Gurinhém',
  gurjao: 'Gurjão',
  ibiara: 'Ibiara',
  igaracy: 'Igaracy',
  imaculada: 'Imaculada',
  inga: 'Ingá',
  itabaiana: 'Itabaiana',
  itaporanga: 'Itaporanga',
  itapororoca: 'Itapororoca',
  itatuba: 'Itatuba',
  jacarau: 'Jacaraú',
  jerico: 'Jericó',
  'joao pessoa': 'João Pessoa',
  'joca claudino': 'Joca Claudino',
  'juarez tavora': 'Juarez Távora',
  juazeirinho: 'Juazeirinho',
  'junco do serido': 'Junco do Seridó',
  juripiranga: 'Juripiranga',
  juru: 'Juru',
  lagoa: 'Lagoa',
  'lagoa de dentro': 'Lagoa de Dentro',
  'lagoa seca': 'Lagoa Seca',
  lastro: 'Lastro',
  livramento: 'Livramento',
  logradouro: 'Logradouro',
  lucena: 'Lucena',
  "mae d'agua": "Mãe d'Água",
  malta: 'Malta',
  mamanguape: 'Mamanguape',
  manaira: 'Manaíra',
  marcacao: 'Marcação',
  mari: 'Mari',
  marizopolis: 'Marizópolis',
  massaranduba: 'Massaranduba',
  mataraca: 'Mataraca',
  matinhas: 'Matinhas',
  'mato grosso': 'Mato Grosso',
  matureia: 'Matureia',
  mogeiro: 'Mogeiro',
  montadas: 'Montadas',
  'monte horebe': 'Monte Horebe',
  monteiro: 'Monteiro',
  mulungu_: 'Mulungu',
  natuba: 'Natuba',
  nazarezinho: 'Nazarezinho',
  'nova floresta': 'Nova Floresta',
  'nova olinda_': 'Nova Olinda',
  'nova palmeira': 'Nova Palmeira',
  "olho d'agua": "Olho d'Água",
  olivedos: 'Olivedos',
  'ouro velho': 'Ouro Velho',
  parari: 'Parari',
  passagem: 'Passagem',
  patos: 'Patos',
  paulista: 'Paulista',
  'pedra branca_': 'Pedra Branca',
  'pedra lavrada': 'Pedra Lavrada',
  'pedras de fogo': 'Pedras de Fogo',
  'pedro regis': 'Pedro Régis',
  pianco: 'Piancó',
  picui: 'Picuí',
  pilar_: 'Pilar',
  piloes: 'Pilões',
  piloezinhos: 'Pilõezinhos',
  pirpirituba: 'Pirpirituba',
  pitimbu: 'Pitimbu',
  pocinhos: 'Pocinhos',
  'poco dantas': 'Poço Dantas',
  'poco de jose de moura': 'Poço de José de Moura',
  pombal: 'Pombal',
  prata_: 'Prata',
  'princesa isabel': 'Princesa Isabel',
  puxinana: 'Puxinanã',
  queimadas_: 'Queimadas',
  quixaba: 'Quixaba',
  remigio: 'Remígio',
  riachao_: 'Riachão',
  'riachao do bacamarte': 'Riachão do Bacamarte',
  'riachao do poco': 'Riachão do Poço',
  'riacho de santo antonio': 'Riacho de Santo Antônio',
  'riacho dos cavalos': 'Riacho dos Cavalos',
  'rio tinto': 'Rio Tinto',
  salgadinho: 'Salgadinho',
  'salgado de sao felix': 'Salgado de São Félix',
  'santa cecilia': 'Santa Cecília',
  'santa cruz': 'Santa Cruz',
  'santa helena_': 'Santa Helena',
  'santa ines__': 'Santa Inês',
  'santa luzia___': 'Santa Luzia',
  'santana de mangueira': 'Santana de Mangueira',
  'santana dos garrotes': 'Santana dos Garrotes',
  'santa rita_': 'Santa Rita',
  'santa terezinha_': 'Santa Terezinha',
  'santo andre': 'Santo André',
  'sao bento_': 'São Bento',
  'sao bento de pombal': 'São Bento de Pombal',
  'sao domingos__': 'São Domingos',
  'sao domingos do cariri': 'São Domingos do Cariri',
  'sao francisco_': 'São Francisco',
  'sao joao do cariri': 'São João do Cariri',
  'sao joao do rio do peixe': 'São João do Rio do Peixe',
  'sao joao do tigre': 'São João do Tigre',
  'sao jose da lagoa tapada': 'São José da Lagoa Tapada',
  'sao jose de caiana': 'São José de Caiana',
  'sao jose de espinharas': 'São José de Espinharas',
  'sao jose de piranhas': 'São José de Piranhas',
  'sao jose de princesa': 'São José de Princesa',
  'sao jose do bonfim': 'São José do Bonfim',
  'sao jose do brejo do cruz': 'São José do Brejo do Cruz',
  'sao jose do sabugi': 'São José do Sabugi',
  'sao jose dos cordeiros': 'São José dos Cordeiros',
  'sao jose dos ramos': 'São José dos Ramos',
  'sao mamede': 'São Mamede',
  'sao miguel de taipu': 'São Miguel de Taipu',
  'sao sebastiao de lagoa de roca': 'São Sebastião de Lagoa de Roça',
  'sao sebastiao do umbuzeiro': 'São Sebastião do Umbuzeiro',
  'sao vicente do serido': 'São Vicente do Seridó',
  sape: 'Sapé',
  'serra branca': 'Serra Branca',
  'serra da raiz': 'Serra da Raiz',
  'serra grande': 'Serra Grande',
  'serra redonda': 'Serra Redonda',
  serraria: 'Serraria',
  sertaozinho: 'Sertãozinho',
  sobrado: 'Sobrado',
  solanea: 'Solânea',
  soledade: 'Soledade',
  sossego: 'Sossêgo',
  sousa: 'Sousa',
  sume: 'Sumé',
  tacima: 'Tacima',
  taperoa_: 'Taperoá',
  tavares: 'Tavares',
  teixeira: 'Teixeira',
  tenorio: 'Tenório',
  triunfo: 'Triunfo',
  uirauna: 'Uiraúna',
  umbuzeiro: 'Umbuzeiro',
  varzea: 'Várzea',
  vieiropolis: 'Vieirópolis',
  'vista serrana': 'Vista Serrana',
  zabele: 'Zabelê',
};
