export const cities = {
  'agua branca_': { name: 'Água Branca', state: 'PB' },
  aguiar: { name: 'Aguiar', state: 'PB' },
  'alagoa grande': { name: 'Alagoa Grande', state: 'PB' },
  'alagoa nova': { name: 'Alagoa Nova', state: 'PB' },
  alagoinha: { name: 'Alagoinha', state: 'PB' },
  alcantil: { name: 'Alcantil', state: 'PB' },
  'algodao de jandaira': { name: 'Algodão de Jandaíra', state: 'PB' },
  alhandra: { name: 'Alhandra', state: 'PB' },
  amparo: { name: 'Amparo', state: 'PB' },
  aparecida: { name: 'Aparecida', state: 'PB' },
  aracagi: { name: 'Araçagi', state: 'PB' },
  arara: { name: 'Arara', state: 'PB' },
  araruna: { name: 'Araruna', state: 'PB' },
  areia: { name: 'Areia', state: 'PB' },
  'areia de baraunas': { name: 'Areia de Baraúnas', state: 'PB' },
  areial: { name: 'Areial', state: 'PB' },
  aroeiras: { name: 'Aroeiras', state: 'PB' },
  assuncao: { name: 'Assunção', state: 'PB' },
  'baia da traicao': { name: 'Baía da Traição', state: 'PB' },
  bananeiras: { name: 'Bananeiras', state: 'PB' },
  barauna: { name: 'Baraúna', state: 'PB' },
  'barra de santana': { name: 'Barra de Santana', state: 'PB' },
  'barra de santa rosa': { name: 'Barra de Santa Rosa', state: 'PB' },
  'barra de sao miguel_': { name: 'Barra de São Miguel', state: 'PB' },
  bayeux: { name: 'Bayeux', state: 'PB' },
  belem__: { name: 'Belém', state: 'PB' },
  'belem do brejo do cruz': { name: 'Belém do Brejo do Cruz', state: 'PB' },
  'bernardino batista': { name: 'Bernardino Batista', state: 'PB' },
  'boa ventura': { name: 'Boa Ventura', state: 'PB' },
  'boa vista': { name: 'Boa Vista', state: 'PB' },
  'bom jesus': { name: 'Bom Jesus', state: 'PB' },
  'bom sucesso_': { name: 'Bom Sucesso', state: 'PB' },
  'bonito de santa fe': { name: 'Bonito de Santa Fé', state: 'PB' },
  boqueirao: { name: 'Boqueirão', state: 'PB' },
  borborema: { name: 'Borborema', state: 'PB' },
  'brejo do cruz': { name: 'Brejo do Cruz', state: 'PB' },
  'brejo dos santos': { name: 'Brejo dos Santos', state: 'PB' },
  caapora: { name: 'Caaporã', state: 'PB' },
  cabaceiras: { name: 'Cabaceiras', state: 'PB' },
  cabedelo: { name: 'Cabedelo', state: 'PB' },
  'cachoeira dos indios': { name: 'Cachoeira dos Índios', state: 'PB' },
  'cacimba de areia': { name: 'Cacimba de Areia', state: 'PB' },
  'cacimba de dentro': { name: 'Cacimba de Dentro', state: 'PB' },
  cacimbas: { name: 'Cacimbas', state: 'PB' },
  caicara: { name: 'Caiçara', state: 'PB' },
  cajazeiras: { name: 'Cajazeiras', state: 'PB' },
  cajazeirinhas: { name: 'Cajazeirinhas', state: 'PB' },
  'caldas brandao': { name: 'Caldas Brandão', state: 'PB' },
  camalau: { name: 'Camalaú', state: 'PB' },
  'campina grande': { name: 'Campina Grande', state: 'PB' },
  capim: { name: 'Capim', state: 'PB' },
  caraubas: { name: 'Caraúbas', state: 'PB' },
  carrapateira: { name: 'Carrapateira', state: 'PB' },
  casserengue: { name: 'Casserengue', state: 'PB' },
  catingueira: { name: 'Catingueira', state: 'PB' },
  'catole do rocha': { name: 'Catolé do Rocha', state: 'PB' },
  caturite: { name: 'Caturité', state: 'PB' },
  conceicao: { name: 'Conceição', state: 'PB' },
  condado: { name: 'Condado', state: 'PB' },
  conde_: { name: 'Conde', state: 'PB' },
  congo: { name: 'Congo', state: 'PB' },
  coremas: { name: 'Coremas', state: 'PB' },
  coxixola: { name: 'Coxixola', state: 'PB' },
  'cruz do espirito santo': { name: 'Cruz do Espírito Santo', state: 'PB' },
  cubati: { name: 'Cubati', state: 'PB' },
  cuite: { name: 'Cuité', state: 'PB' },
  'cuite de mamanguape': { name: 'Cuité de Mamanguape', state: 'PB' },
  cuitegi: { name: 'Cuitegi', state: 'PB' },
  'curral de cima': { name: 'Curral de Cima', state: 'PB' },
  'curral velho': { name: 'Curral Velho', state: 'PB' },
  damiao: { name: 'Damião', state: 'PB' },
  desterro: { name: 'Desterro', state: 'PB' },
  diamante: { name: 'Diamante', state: 'PB' },
  'dona ines': { name: 'Dona Inês', state: 'PB' },
  'duas estradas': { name: 'Duas Estradas', state: 'PB' },
  emas: { name: 'Emas', state: 'PB' },
  esperanca: { name: 'Esperança', state: 'PB' },
  fagundes: { name: 'Fagundes', state: 'PB' },
  'frei martinho': { name: 'Frei Martinho', state: 'PB' },
  'gado bravo': { name: 'Gado Bravo', state: 'PB' },
  guarabira: { name: 'Guarabira', state: 'PB' },
  gurinhem: { name: 'Gurinhém', state: 'PB' },
  gurjao: { name: 'Gurjão', state: 'PB' },
  ibiara: { name: 'Ibiara', state: 'PB' },
  igaracy: { name: 'Igaracy', state: 'PB' },
  imaculada: { name: 'Imaculada', state: 'PB' },
  inga: { name: 'Ingá', state: 'PB' },
  itabaiana: { name: 'Itabaiana', state: 'PB' },
  itaporanga: { name: 'Itaporanga', state: 'PB' },
  itapororoca: { name: 'Itapororoca', state: 'PB' },
  itatuba: { name: 'Itatuba', state: 'PB' },
  jacarau: { name: 'Jacaraú', state: 'PB' },
  jerico: { name: 'Jericó', state: 'PB' },
  'joao pessoa': { name: 'João Pessoa', state: 'PB' },
  'joca claudino': { name: 'Joca Claudino', state: 'PB' },
  'juarez tavora': { name: 'Juarez Távora', state: 'PB' },
  juazeirinho: { name: 'Juazeirinho', state: 'PB' },
  'junco do serido': { name: 'Junco do Seridó', state: 'PB' },
  juripiranga: { name: 'Juripiranga', state: 'PB' },
  juru: { name: 'Juru', state: 'PB' },
  lagoa: { name: 'Lagoa', state: 'PB' },
  'lagoa de dentro': { name: 'Lagoa de Dentro', state: 'PB' },
  'lagoa seca': { name: 'Lagoa Seca', state: 'PB' },
  lastro: { name: 'Lastro', state: 'PB' },
  livramento: { name: 'Livramento', state: 'PB' },
  logradouro: { name: 'Logradouro', state: 'PB' },
  lucena: { name: 'Lucena', state: 'PB' },
  "mae d'agua": { name: "Mãe d'Água", state: 'PB' },
  malta: { name: 'Malta', state: 'PB' },
  mamanguape: { name: 'Mamanguape', state: 'PB' },
  manaira: { name: 'Manaíra', state: 'PB' },
  marcacao: { name: 'Marcação', state: 'PB' },
  mari: { name: 'Mari', state: 'PB' },
  marizopolis: { name: 'Marizópolis', state: 'PB' },
  massaranduba: { name: 'Massaranduba', state: 'PB' },
  mataraca: { name: 'Mataraca', state: 'PB' },
  matinhas: { name: 'Matinhas', state: 'PB' },
  'mato grosso': { name: 'Mato Grosso', state: 'PB' },
  matureia: { name: 'Matureia', state: 'PB' },
  mogeiro: { name: 'Mogeiro', state: 'PB' },
  montadas: { name: 'Montadas', state: 'PB' },
  'monte horebe': { name: 'Monte Horebe', state: 'PB' },
  monteiro: { name: 'Monteiro', state: 'PB' },
  mulungu_: { name: 'Mulungu', state: 'PB' },
  natuba: { name: 'Natuba', state: 'PB' },
  nazarezinho: { name: 'Nazarezinho', state: 'PB' },
  'nova floresta': { name: 'Nova Floresta', state: 'PB' },
  'nova olinda_': { name: 'Nova Olinda', state: 'PB' },
  'nova palmeira': { name: 'Nova Palmeira', state: 'PB' },
  "olho d'agua": { name: "Olho d'Água", state: 'PB' },
  olivedos: { name: 'Olivedos', state: 'PB' },
  'ouro velho': { name: 'Ouro Velho', state: 'PB' },
  parari: { name: 'Parari', state: 'PB' },
  passagem: { name: 'Passagem', state: 'PB' },
  patos: { name: 'Patos', state: 'PB' },
  paulista: { name: 'Paulista', state: 'PB' },
  'pedra branca_': { name: 'Pedra Branca', state: 'PB' },
  'pedra lavrada': { name: 'Pedra Lavrada', state: 'PB' },
  'pedras de fogo': { name: 'Pedras de Fogo', state: 'PB' },
  'pedro regis': { name: 'Pedro Régis', state: 'PB' },
  pianco: { name: 'Piancó', state: 'PB' },
  picui: { name: 'Picuí', state: 'PB' },
  pilar_: { name: 'Pilar', state: 'PB' },
  piloes: { name: 'Pilões', state: 'PB' },
  piloezinhos: { name: 'Pilõezinhos', state: 'PB' },
  pirpirituba: { name: 'Pirpirituba', state: 'PB' },
  pitimbu: { name: 'Pitimbu', state: 'PB' },
  pocinhos: { name: 'Pocinhos', state: 'PB' },
  'poco dantas': { name: 'Poço Dantas', state: 'PB' },
  'poco de jose de moura': { name: 'Poço de José de Moura', state: 'PB' },
  pombal: { name: 'Pombal', state: 'PB' },
  prata_: { name: 'Prata', state: 'PB' },
  'princesa isabel': { name: 'Princesa Isabel', state: 'PB' },
  puxinana: { name: 'Puxinanã', state: 'PB' },
  queimadas_: { name: 'Queimadas', state: 'PB' },
  quixaba: { name: 'Quixaba', state: 'PB' },
  remigio: { name: 'Remígio', state: 'PB' },
  riachao_: { name: 'Riachão', state: 'PB' },
  'riachao do bacamarte': { name: 'Riachão do Bacamarte', state: 'PB' },
  'riachao do poco': { name: 'Riachão do Poço', state: 'PB' },
  'riacho de santo antonio': { name: 'Riacho de Santo Antônio', state: 'PB' },
  'riacho dos cavalos': { name: 'Riacho dos Cavalos', state: 'PB' },
  'rio tinto': { name: 'Rio Tinto', state: 'PB' },
  salgadinho: { name: 'Salgadinho', state: 'PB' },
  'salgado de sao felix': { name: 'Salgado de São Félix', state: 'PB' },
  'santa cecilia': { name: 'Santa Cecília', state: 'PB' },
  'santa cruz': { name: 'Santa Cruz', state: 'PB' },
  'santa helena_': { name: 'Santa Helena', state: 'PB' },
  'santa ines__': { name: 'Santa Inês', state: 'PB' },
  'santa luzia___': { name: 'Santa Luzia', state: 'PB' },
  'santana de mangueira': { name: 'Santana de Mangueira', state: 'PB' },
  'santana dos garrotes': { name: 'Santana dos Garrotes', state: 'PB' },
  'santa rita_': { name: 'Santa Rita', state: 'PB' },
  'santa terezinha_': { name: 'Santa Terezinha', state: 'PB' },
  'santo andre': { name: 'Santo André', state: 'PB' },
  'sao bento_': { name: 'São Bento', state: 'PB' },
  'sao bento de pombal': { name: 'São Bento de Pombal', state: 'PB' },
  'sao domingos__': { name: 'São Domingos', state: 'PB' },
  'sao domingos do cariri': { name: 'São Domingos do Cariri', state: 'PB' },
  'sao francisco_': { name: 'São Francisco', state: 'PB' },
  'sao joao do cariri': { name: 'São João do Cariri', state: 'PB' },
  'sao joao do rio do peixe': { name: 'São João do Rio do Peixe', state: 'PB' },
  'sao joao do tigre': { name: 'São João do Tigre', state: 'PB' },
  'sao jose da lagoa tapada': { name: 'São José da Lagoa Tapada', state: 'PB' },
  'sao jose de caiana': { name: 'São José de Caiana', state: 'PB' },
  'sao jose de espinharas': { name: 'São José de Espinharas', state: 'PB' },
  'sao jose de piranhas': { name: 'São José de Piranhas', state: 'PB' },
  'sao jose de princesa': { name: 'São José de Princesa', state: 'PB' },
  'sao jose do bonfim': { name: 'São José do Bonfim', state: 'PB' },
  'sao jose do brejo do cruz': { name: 'São José do Brejo do Cruz', state: 'PB' },
  'sao jose do sabugi': { name: 'São José do Sabugi', state: 'PB' },
  'sao jose dos cordeiros': { name: 'São José dos Cordeiros', state: 'PB' },
  'sao jose dos ramos': { name: 'São José dos Ramos', state: 'PB' },
  'sao mamede': { name: 'São Mamede', state: 'PB' },
  'sao miguel de taipu': { name: 'São Miguel de Taipu', state: 'PB' },
  'sao sebastiao de lagoa de roca': { name: 'São Sebastião de Lagoa de Roça', state: 'PB' },
  'sao sebastiao do umbuzeiro': { name: 'São Sebastião do Umbuzeiro', state: 'PB' },
  'sao vicente do serido': { name: 'São Vicente do Seridó', state: 'PB' },
  sape: { name: 'Sapé', state: 'PB' },
  'serra branca': { name: 'Serra Branca', state: 'PB' },
  'serra da raiz': { name: 'Serra da Raiz', state: 'PB' },
  'serra grande': { name: 'Serra Grande', state: 'PB' },
  'serra redonda': { name: 'Serra Redonda', state: 'PB' },
  serraria: { name: 'Serraria', state: 'PB' },
  sertaozinho: { name: 'Sertãozinho', state: 'PB' },
  sobrado: { name: 'Sobrado', state: 'PB' },
  solanea: { name: 'Solânea', state: 'PB' },
  soledade: { name: 'Soledade', state: 'PB' },
  sossego: { name: 'Sossêgo', state: 'PB' },
  sousa: { name: 'Sousa', state: 'PB' },
  sume: { name: 'Sumé', state: 'PB' },
  tacima: { name: 'Tacima', state: 'PB' },
  taperoa_: { name: 'Taperoá', state: 'PB' },
  tavares: { name: 'Tavares', state: 'PB' },
  teixeira: { name: 'Teixeira', state: 'PB' },
  tenorio: { name: 'Tenório', state: 'PB' },
  triunfo: { name: 'Triunfo', state: 'PB' },
  uirauna: { name: 'Uiraúna', state: 'PB' },
  umbuzeiro: { name: 'Umbuzeiro', state: 'PB' },
  varzea: { name: 'Várzea', state: 'PB' },
  vieiropolis: { name: 'Vieirópolis', state: 'PB' },
  'vista serrana': { name: 'Vista Serrana', state: 'PB' },
  zabele: { name: 'Zabelê', state: 'PB' },
};
