export const cities = {
  'abreu e lima': { name: 'Abreu e Lima', state: 'PE' },
  'afogados da ingazeira': { name: 'Afogados da Ingazeira', state: 'PE' },
  afranio: { name: 'Afrânio', state: 'PE' },
  agrestina: { name: 'Agrestina', state: 'PE' },
  'agua preta': { name: 'Água Preta', state: 'PE' },
  'aguas belas': { name: 'Águas Belas', state: 'PE' },
  alagoinha_: { name: 'Alagoinha', state: 'PE' },
  alianca: { name: 'Aliança', state: 'PE' },
  altinho: { name: 'Altinho', state: 'PE' },
  amaraji: { name: 'Amaraji', state: 'PE' },
  angelim: { name: 'Angelim', state: 'PE' },
  aracoiaba__: { name: 'Araçoiaba', state: 'PE' },
  araripina: { name: 'Araripina', state: 'PE' },
  arcoverde: { name: 'Arcoverde', state: 'PE' },
  'barra de guabiraba': { name: 'Barra de Guabiraba', state: 'PE' },
  barreiros: { name: 'Barreiros', state: 'PE' },
  'belem de maria': { name: 'Belém de Maria', state: 'PE' },
  'belem do sao francisco': { name: 'Belém do São Francisco', state: 'PE' },
  'belo jardim': { name: 'Belo Jardim', state: 'PE' },
  betania: { name: 'Betânia', state: 'PE' },
  bezerros: { name: 'Bezerros', state: 'PE' },
  bodoco: { name: 'Bodocó', state: 'PE' },
  'bom conselho': { name: 'Bom Conselho', state: 'PE' },
  'bom jardim_': { name: 'Bom Jardim', state: 'PE' },
  bonito___: { name: 'Bonito', state: 'PE' },
  brejao: { name: 'Brejão', state: 'PE' },
  brejinho: { name: 'Brejinho', state: 'PE' },
  'brejo da madre de deus': { name: 'Brejo da Madre de Deus', state: 'PE' },
  'buenos aires': { name: 'Buenos Aires', state: 'PE' },
  buique: { name: 'Buíque', state: 'PE' },
  'cabo de santo agostinho': { name: 'Cabo de Santo Agostinho', state: 'PE' },
  cabrobo: { name: 'Cabrobó', state: 'PE' },
  cachoeirinha: { name: 'Cachoeirinha', state: 'PE' },
  caetes: { name: 'Caetés', state: 'PE' },
  calcado: { name: 'Calçado', state: 'PE' },
  calumbi: { name: 'Calumbi', state: 'PE' },
  camaragibe: { name: 'Camaragibe', state: 'PE' },
  'camocim de sao felix': { name: 'Camocim de São Félix', state: 'PE' },
  camutanga: { name: 'Camutanga', state: 'PE' },
  canhotinho: { name: 'Canhotinho', state: 'PE' },
  capoeiras: { name: 'Capoeiras', state: 'PE' },
  carnaiba: { name: 'Carnaíba', state: 'PE' },
  'carnaubeira da penha': { name: 'Carnaubeira da Penha', state: 'PE' },
  carpina: { name: 'Carpina', state: 'PE' },
  caruaru: { name: 'Caruaru', state: 'PE' },
  casinhas: { name: 'Casinhas', state: 'PE' },
  catende: { name: 'Catende', state: 'PE' },
  cedro_: { name: 'Cedro', state: 'PE' },
  'cha de alegria': { name: 'Chã de Alegria', state: 'PE' },
  'cha grande': { name: 'Chã Grande', state: 'PE' },
  condado_: { name: 'Condado', state: 'PE' },
  correntes: { name: 'Correntes', state: 'PE' },
  cortes: { name: 'Cortês', state: 'PE' },
  cumaru: { name: 'Cumaru', state: 'PE' },
  cupira: { name: 'Cupira', state: 'PE' },
  custodia: { name: 'Custódia', state: 'PE' },
  dormentes: { name: 'Dormentes', state: 'PE' },
  escada: { name: 'Escada', state: 'PE' },
  exu: { name: 'Exu', state: 'PE' },
  'feira nova': { name: 'Feira Nova', state: 'PE' },
  ferreiros: { name: 'Ferreiros', state: 'PE' },
  flores: { name: 'Flores', state: 'PE' },
  floresta: { name: 'Floresta', state: 'PE' },
  'frei miguelinho': { name: 'Frei Miguelinho', state: 'PE' },
  gameleira: { name: 'Gameleira', state: 'PE' },
  garanhuns: { name: 'Garanhuns', state: 'PE' },
  'gloria do goita': { name: 'Glória do Goitá', state: 'PE' },
  goiana: { name: 'Goiana', state: 'PE' },
  granito: { name: 'Granito', state: 'PE' },
  gravata: { name: 'Gravatá', state: 'PE' },
  iati: { name: 'Iati', state: 'PE' },
  ibimirim: { name: 'Ibimirim', state: 'PE' },
  ibirajuba: { name: 'Ibirajuba', state: 'PE' },
  igarassu: { name: 'Igarassu', state: 'PE' },
  iguaracy: { name: 'Iguaracy', state: 'PE' },
  'ilha de itamaraca': { name: 'Ilha de Itamaracá', state: 'PE' },
  inaja: { name: 'Inajá', state: 'PE' },
  ingazeira: { name: 'Ingazeira', state: 'PE' },
  ipojuca: { name: 'Ipojuca', state: 'PE' },
  ipubi: { name: 'Ipubi', state: 'PE' },
  itacuruba: { name: 'Itacuruba', state: 'PE' },
  itaiba: { name: 'Itaíba', state: 'PE' },
  itambe_: { name: 'Itambé', state: 'PE' },
  itapetim: { name: 'Itapetim', state: 'PE' },
  itapissuma: { name: 'Itapissuma', state: 'PE' },
  itaquitinga: { name: 'Itaquitinga', state: 'PE' },
  'jaboatao dos guararapes': { name: 'Jaboatão dos Guararapes', state: 'PE' },
  jaqueira: { name: 'Jaqueira', state: 'PE' },
  jatauba: { name: 'Jataúba', state: 'PE' },
  jatoba_: { name: 'Jatobá', state: 'PE' },
  'joao alfredo': { name: 'João Alfredo', state: 'PE' },
  'joaquim nabuco': { name: 'Joaquim Nabuco', state: 'PE' },
  jucati: { name: 'Jucati', state: 'PE' },
  jupi: { name: 'Jupi', state: 'PE' },
  jurema: { name: 'Jurema', state: 'PE' },
  'lagoa de itaenga': { name: 'Lagoa de Itaenga', state: 'PE' },
  'lagoa do carro': { name: 'Lagoa do Carro', state: 'PE' },
  'lagoa do ouro': { name: 'Lagoa do Ouro', state: 'PE' },
  'lagoa dos gatos': { name: 'Lagoa dos Gatos', state: 'PE' },
  'lagoa grande_': { name: 'Lagoa Grande', state: 'PE' },
  lajedo: { name: 'Lajedo', state: 'PE' },
  limoeiro: { name: 'Limoeiro', state: 'PE' },
  macaparana: { name: 'Macaparana', state: 'PE' },
  machados: { name: 'Machados', state: 'PE' },
  manari: { name: 'Manari', state: 'PE' },
  maraial: { name: 'Maraial', state: 'PE' },
  mirandiba: { name: 'Mirandiba', state: 'PE' },
  moreilandia: { name: 'Moreilândia', state: 'PE' },
  moreno: { name: 'Moreno', state: 'PE' },
  'nazare da mata': { name: 'Nazaré da Mata', state: 'PE' },
  olinda: { name: 'Olinda', state: 'PE' },
  orobo: { name: 'Orobó', state: 'PE' },
  oroco: { name: 'Orocó', state: 'PE' },
  ouricuri: { name: 'Ouricuri', state: 'PE' },
  palmares: { name: 'Palmares', state: 'PE' },
  palmeirina: { name: 'Palmeirina', state: 'PE' },
  panelas: { name: 'Panelas', state: 'PE' },
  paranatama: { name: 'Paranatama', state: 'PE' },
  parnamirim: { name: 'Parnamirim', state: 'PE' },
  passira: { name: 'Passira', state: 'PE' },
  paudalho: { name: 'Paudalho', state: 'PE' },
  paulista_: { name: 'Paulista', state: 'PE' },
  pedra: { name: 'Pedra', state: 'PE' },
  pesqueira: { name: 'Pesqueira', state: 'PE' },
  petrolandia: { name: 'Petrolândia', state: 'PE' },
  petrolina: { name: 'Petrolina', state: 'PE' },
  pocao: { name: 'Poção', state: 'PE' },
  pombos: { name: 'Pombos', state: 'PE' },
  primavera_: { name: 'Primavera', state: 'PE' },
  quipapa: { name: 'Quipapá', state: 'PE' },
  quixaba_: { name: 'Quixaba', state: 'PE' },
  recife: { name: 'Recife', state: 'PE' },
  'riacho das almas': { name: 'Riacho das Almas', state: 'PE' },
  ribeirao: { name: 'Ribeirão', state: 'PE' },
  'rio formoso': { name: 'Rio Formoso', state: 'PE' },
  saire: { name: 'Sairé', state: 'PE' },
  salgadinho_: { name: 'Salgadinho', state: 'PE' },
  salgueiro: { name: 'Salgueiro', state: 'PE' },
  saloa: { name: 'Saloá', state: 'PE' },
  sanharo: { name: 'Sanharó', state: 'PE' },
  'santa cruz_': { name: 'Santa Cruz', state: 'PE' },
  'santa cruz da baixa verde': { name: 'Santa Cruz da Baixa Verde', state: 'PE' },
  'santa cruz do capibaribe': { name: 'Santa Cruz do Capibaribe', state: 'PE' },
  'santa filomena': { name: 'Santa Filomena', state: 'PE' },
  'santa maria da boa vista': { name: 'Santa Maria da Boa Vista', state: 'PE' },
  'santa maria do cambuca': { name: 'Santa Maria do Cambucá', state: 'PE' },
  'santa terezinha__': { name: 'Santa Terezinha', state: 'PE' },
  'sao benedito do sul': { name: 'São Benedito do Sul', state: 'PE' },
  'sao bento do una': { name: 'São Bento do Una', state: 'PE' },
  'sao caetano': { name: 'São Caetano', state: 'PE' },
  'sao joao': { name: 'São João', state: 'PE' },
  'sao joaquim do monte': { name: 'São Joaquim do Monte', state: 'PE' },
  'sao jose da coroa grande': { name: 'São José da Coroa Grande', state: 'PE' },
  'sao jose do belmonte': { name: 'São José do Belmonte', state: 'PE' },
  'sao jose do egito': { name: 'São José do Egito', state: 'PE' },
  'sao lourenco da mata': { name: 'São Lourenço da Mata', state: 'PE' },
  'sao vicente ferrer_': { name: 'São Vicente Férrer', state: 'PE' },
  'serra talhada': { name: 'Serra Talhada', state: 'PE' },
  serrita: { name: 'Serrita', state: 'PE' },
  sertania: { name: 'Sertânia', state: 'PE' },
  sirinhaem: { name: 'Sirinhaém', state: 'PE' },
  solidao: { name: 'Solidão', state: 'PE' },
  surubim: { name: 'Surubim', state: 'PE' },
  tabira: { name: 'Tabira', state: 'PE' },
  tacaimbo: { name: 'Tacaimbó', state: 'PE' },
  tacaratu: { name: 'Tacaratu', state: 'PE' },
  tamandare: { name: 'Tamandaré', state: 'PE' },
  'taquaritinga do norte': { name: 'Taquaritinga do Norte', state: 'PE' },
  terezinha: { name: 'Terezinha', state: 'PE' },
  'terra nova_': { name: 'Terra Nova', state: 'PE' },
  timbauba: { name: 'Timbaúba', state: 'PE' },
  toritama: { name: 'Toritama', state: 'PE' },
  tracunhaem: { name: 'Tracunhaém', state: 'PE' },
  trindade_: { name: 'Trindade', state: 'PE' },
  triunfo_: { name: 'Triunfo', state: 'PE' },
  tupanatinga: { name: 'Tupanatinga', state: 'PE' },
  tuparetama: { name: 'Tuparetama', state: 'PE' },
  venturosa: { name: 'Venturosa', state: 'PE' },
  verdejante: { name: 'Verdejante', state: 'PE' },
  'vertente do lerio': { name: 'Vertente do Lério', state: 'PE' },
  vertentes: { name: 'Vertentes', state: 'PE' },
  vicencia: { name: 'Vicência', state: 'PE' },
  'vitoria de santo antao': { name: 'Vitória de Santo Antão', state: 'PE' },
  xexeu: { name: 'Xexéu', state: 'PE' },
};
