export const cities = {
  'abreu e lima': 'Abreu e Lima',
  'afogados da ingazeira': 'Afogados da Ingazeira',
  afranio: 'Afrânio',
  agrestina: 'Agrestina',
  'agua preta': 'Água Preta',
  'aguas belas': 'Águas Belas',
  alagoinha_: 'Alagoinha',
  alianca: 'Aliança',
  altinho: 'Altinho',
  amaraji: 'Amaraji',
  angelim: 'Angelim',
  aracoiaba__: 'Araçoiaba',
  araripina: 'Araripina',
  arcoverde: 'Arcoverde',
  'barra de guabiraba': 'Barra de Guabiraba',
  barreiros: 'Barreiros',
  'belem de maria': 'Belém de Maria',
  'belem do sao francisco': 'Belém do São Francisco',
  'belo jardim': 'Belo Jardim',
  betania: 'Betânia',
  bezerros: 'Bezerros',
  bodoco: 'Bodocó',
  'bom conselho': 'Bom Conselho',
  'bom jardim_': 'Bom Jardim',
  bonito___: 'Bonito',
  brejao: 'Brejão',
  brejinho: 'Brejinho',
  'brejo da madre de deus': 'Brejo da Madre de Deus',
  'buenos aires': 'Buenos Aires',
  buique: 'Buíque',
  'cabo de santo agostinho': 'Cabo de Santo Agostinho',
  cabrobo: 'Cabrobó',
  cachoeirinha: 'Cachoeirinha',
  caetes: 'Caetés',
  calcado: 'Calçado',
  calumbi: 'Calumbi',
  camaragibe: 'Camaragibe',
  'camocim de sao felix': 'Camocim de São Félix',
  camutanga: 'Camutanga',
  canhotinho: 'Canhotinho',
  capoeiras: 'Capoeiras',
  carnaiba: 'Carnaíba',
  'carnaubeira da penha': 'Carnaubeira da Penha',
  carpina: 'Carpina',
  caruaru: 'Caruaru',
  casinhas: 'Casinhas',
  catende: 'Catende',
  cedro_: 'Cedro',
  'cha de alegria': 'Chã de Alegria',
  'cha grande': 'Chã Grande',
  condado_: 'Condado',
  correntes: 'Correntes',
  cortes: 'Cortês',
  cumaru: 'Cumaru',
  cupira: 'Cupira',
  custodia: 'Custódia',
  dormentes: 'Dormentes',
  escada: 'Escada',
  exu: 'Exu',
  'feira nova': 'Feira Nova',
  ferreiros: 'Ferreiros',
  flores: 'Flores',
  floresta: 'Floresta',
  'frei miguelinho': 'Frei Miguelinho',
  gameleira: 'Gameleira',
  garanhuns: 'Garanhuns',
  'gloria do goita': 'Glória do Goitá',
  goiana: 'Goiana',
  granito: 'Granito',
  gravata: 'Gravatá',
  iati: 'Iati',
  ibimirim: 'Ibimirim',
  ibirajuba: 'Ibirajuba',
  igarassu: 'Igarassu',
  iguaracy: 'Iguaracy',
  'ilha de itamaraca': 'Ilha de Itamaracá',
  inaja: 'Inajá',
  ingazeira: 'Ingazeira',
  ipojuca: 'Ipojuca',
  ipubi: 'Ipubi',
  itacuruba: 'Itacuruba',
  itaiba: 'Itaíba',
  itambe_: 'Itambé',
  itapetim: 'Itapetim',
  itapissuma: 'Itapissuma',
  itaquitinga: 'Itaquitinga',
  'jaboatao dos guararapes': 'Jaboatão dos Guararapes',
  jaqueira: 'Jaqueira',
  jatauba: 'Jataúba',
  jatoba_: 'Jatobá',
  'joao alfredo': 'João Alfredo',
  'joaquim nabuco': 'Joaquim Nabuco',
  jucati: 'Jucati',
  jupi: 'Jupi',
  jurema: 'Jurema',
  'lagoa de itaenga': 'Lagoa de Itaenga',
  'lagoa do carro': 'Lagoa do Carro',
  'lagoa do ouro': 'Lagoa do Ouro',
  'lagoa dos gatos': 'Lagoa dos Gatos',
  'lagoa grande_': 'Lagoa Grande',
  lajedo: 'Lajedo',
  limoeiro: 'Limoeiro',
  macaparana: 'Macaparana',
  machados: 'Machados',
  manari: 'Manari',
  maraial: 'Maraial',
  mirandiba: 'Mirandiba',
  moreilandia: 'Moreilândia',
  moreno: 'Moreno',
  'nazare da mata': 'Nazaré da Mata',
  olinda: 'Olinda',
  orobo: 'Orobó',
  oroco: 'Orocó',
  ouricuri: 'Ouricuri',
  palmares: 'Palmares',
  palmeirina: 'Palmeirina',
  panelas: 'Panelas',
  paranatama: 'Paranatama',
  parnamirim: 'Parnamirim',
  passira: 'Passira',
  paudalho: 'Paudalho',
  paulista_: 'Paulista',
  pedra: 'Pedra',
  pesqueira: 'Pesqueira',
  petrolandia: 'Petrolândia',
  petrolina: 'Petrolina',
  pocao: 'Poção',
  pombos: 'Pombos',
  primavera_: 'Primavera',
  quipapa: 'Quipapá',
  quixaba_: 'Quixaba',
  recife: 'Recife',
  'riacho das almas': 'Riacho das Almas',
  ribeirao: 'Ribeirão',
  'rio formoso': 'Rio Formoso',
  saire: 'Sairé',
  salgadinho_: 'Salgadinho',
  salgueiro: 'Salgueiro',
  saloa: 'Saloá',
  sanharo: 'Sanharó',
  'santa cruz_': 'Santa Cruz',
  'santa cruz da baixa verde': 'Santa Cruz da Baixa Verde',
  'santa cruz do capibaribe': 'Santa Cruz do Capibaribe',
  'santa filomena': 'Santa Filomena',
  'santa maria da boa vista': 'Santa Maria da Boa Vista',
  'santa maria do cambuca': 'Santa Maria do Cambucá',
  'santa terezinha__': 'Santa Terezinha',
  'sao benedito do sul': 'São Benedito do Sul',
  'sao bento do una': 'São Bento do Una',
  'sao caetano': 'São Caetano',
  'sao joao': 'São João',
  'sao joaquim do monte': 'São Joaquim do Monte',
  'sao jose da coroa grande': 'São José da Coroa Grande',
  'sao jose do belmonte': 'São José do Belmonte',
  'sao jose do egito': 'São José do Egito',
  'sao lourenco da mata': 'São Lourenço da Mata',
  'sao vicente ferrer_': 'São Vicente Férrer',
  'serra talhada': 'Serra Talhada',
  serrita: 'Serrita',
  sertania: 'Sertânia',
  sirinhaem: 'Sirinhaém',
  solidao: 'Solidão',
  surubim: 'Surubim',
  tabira: 'Tabira',
  tacaimbo: 'Tacaimbó',
  tacaratu: 'Tacaratu',
  tamandare: 'Tamandaré',
  'taquaritinga do norte': 'Taquaritinga do Norte',
  terezinha: 'Terezinha',
  'terra nova_': 'Terra Nova',
  timbauba: 'Timbaúba',
  toritama: 'Toritama',
  tracunhaem: 'Tracunhaém',
  trindade_: 'Trindade',
  triunfo_: 'Triunfo',
  tupanatinga: 'Tupanatinga',
  tuparetama: 'Tuparetama',
  venturosa: 'Venturosa',
  verdejante: 'Verdejante',
  'vertente do lerio': 'Vertente do Lério',
  vertentes: 'Vertentes',
  vicencia: 'Vicência',
  'vitoria de santo antao': 'Vitória de Santo Antão',
  xexeu: 'Xexéu',
};
