export const cities = {
  acaua: 'Acauã',
  agricolandia: 'Agricolândia',
  'agua branca__': 'Água Branca',
  'alagoinha do piaui': 'Alagoinha do Piauí',
  'alegrete do piaui': 'Alegrete do Piauí',
  'alto longa': 'Alto Longá',
  altos: 'Altos',
  'alvorada do gurgueia': 'Alvorada do Gurgueia',
  amarante: 'Amarante',
  'angical do piaui': 'Angical do Piauí',
  'anisio de abreu': 'Anísio de Abreu',
  'antonio almeida': 'Antônio Almeida',
  aroazes: 'Aroazes',
  'aroeiras do itaim': 'Aroeiras do Itaim',
  arraial: 'Arraial',
  'assuncao do piaui': 'Assunção do Piauí',
  'avelino lopes': 'Avelino Lopes',
  'baixa grande do ribeiro': 'Baixa Grande do Ribeiro',
  "barra d'alcantara": "Barra d'Alcântara",
  barras: 'Barras',
  'barreiras do piaui': 'Barreiras do Piauí',
  'barro duro': 'Barro Duro',
  batalha_: 'Batalha',
  'bela vista do piaui': 'Bela Vista do Piauí',
  'belem do piaui': 'Belém do Piauí',
  beneditinos: 'Beneditinos',
  bertolinia: 'Bertolínia',
  'betania do piaui': 'Betânia do Piauí',
  'boa hora': 'Boa Hora',
  bocaina: 'Bocaina',
  'bom jesus_': 'Bom Jesus',
  'bom principio do piaui': 'Bom Princípio do Piauí',
  'bonfim do piaui': 'Bonfim do Piauí',
  'boqueirao do piaui': 'Boqueirão do Piauí',
  brasileira: 'Brasileira',
  'brejo do piaui': 'Brejo do Piauí',
  'buriti dos lopes': 'Buriti dos Lopes',
  'buriti dos montes': 'Buriti dos Montes',
  'cabeceiras do piaui': 'Cabeceiras do Piauí',
  'cajazeiras do piaui': 'Cajazeiras do Piauí',
  'cajueiro da praia': 'Cajueiro da Praia',
  'caldeirao grande do piaui': 'Caldeirão Grande do Piauí',
  'campinas do piaui': 'Campinas do Piauí',
  'campo alegre do fidalgo': 'Campo Alegre do Fidalgo',
  'campo grande do piaui': 'Campo Grande do Piauí',
  'campo largo do piaui': 'Campo Largo do Piauí',
  'campo maior': 'Campo Maior',
  canavieira: 'Canavieira',
  'canto do buriti': 'Canto do Buriti',
  'capitao de campos': 'Capitão de Campos',
  'capitao gervasio oliveira': 'Capitão Gervásio Oliveira',
  caracol_: 'Caracol',
  'caraubas do piaui': 'Caraúbas do Piauí',
  'caridade do piaui': 'Caridade do Piauí',
  'castelo do piaui': 'Castelo do Piauí',
  caxingo: 'Caxingó',
  cocal: 'Cocal',
  'cocal de telha': 'Cocal de Telha',
  'cocal dos alves': 'Cocal dos Alves',
  coivaras: 'Coivaras',
  'colonia do gurgueia': 'Colônia do Gurgueia',
  'colonia do piaui': 'Colônia do Piauí',
  'conceicao do caninde': 'Conceição do Canindé',
  'coronel jose dias': 'Coronel José Dias',
  corrente: 'Corrente',
  'cristalandia do piaui': 'Cristalândia do Piauí',
  'cristino castro': 'Cristino Castro',
  curimata: 'Curimatá',
  currais: 'Currais',
  curralinhos: 'Curralinhos',
  'curral novo do piaui': 'Curral Novo do Piauí',
  'demerval lobao': 'Demerval Lobão',
  'dirceu arcoverde': 'Dirceu Arcoverde',
  'dom expedito lopes': 'Dom Expedito Lopes',
  'domingos mourao': 'Domingos Mourão',
  'dom inocencio': 'Dom Inocêncio',
  'elesbao veloso': 'Elesbão Veloso',
  'eliseu martins': 'Eliseu Martins',
  esperantina: 'Esperantina',
  'fartura do piaui': 'Fartura do Piauí',
  'flores do piaui': 'Flores do Piauí',
  'floresta do piaui': 'Floresta do Piauí',
  floriano: 'Floriano',
  francinopolis: 'Francinópolis',
  'francisco ayres': 'Francisco Ayres',
  'francisco macedo': 'Francisco Macedo',
  'francisco santos': 'Francisco Santos',
  fronteiras: 'Fronteiras',
  geminiano: 'Geminiano',
  gilbues: 'Gilbués',
  guadalupe: 'Guadalupe',
  guaribas: 'Guaribas',
  'hugo napoleao': 'Hugo Napoleão',
  'ilha grande': 'Ilha Grande',
  inhuma: 'Inhuma',
  'ipiranga do piaui': 'Ipiranga do Piauí',
  'isaias coelho': 'Isaías Coelho',
  itainopolis: 'Itainópolis',
  itaueira: 'Itaueira',
  'jacobina do piaui': 'Jacobina do Piauí',
  jaicos: 'Jaicós',
  'jardim do mulato': 'Jardim do Mulato',
  'jatoba do piaui': 'Jatobá do Piauí',
  jerumenha: 'Jerumenha',
  'joao costa': 'João Costa',
  'joaquim pires': 'Joaquim Pires',
  'joca marques': 'Joca Marques',
  'jose de freitas': 'José de Freitas',
  'juazeiro do piaui': 'Juazeiro do Piauí',
  'julio borges': 'Júlio Borges',
  jurema_: 'Jurema',
  'lagoa alegre': 'Lagoa Alegre',
  'lagoa de sao francisco': 'Lagoa de São Francisco',
  'lagoa do barro do piaui': 'Lagoa do Barro do Piauí',
  'lagoa do piaui': 'Lagoa do Piauí',
  'lagoa do sitio': 'Lagoa do Sítio',
  'lagoinha do piaui': 'Lagoinha do Piauí',
  'landri sales': 'Landri Sales',
  'luis correia': 'Luís Correia',
  luzilandia: 'Luzilândia',
  madeiro: 'Madeiro',
  'manoel emidio': 'Manoel Emídio',
  marcolandia: 'Marcolândia',
  'marcos parente': 'Marcos Parente',
  'massape do piaui': 'Massapê do Piauí',
  'matias olimpio': 'Matias Olímpio',
  'miguel alves': 'Miguel Alves',
  'miguel leao': 'Miguel Leão',
  'milton brandao': 'Milton Brandão',
  'monsenhor gil': 'Monsenhor Gil',
  'monsenhor hipolito': 'Monsenhor Hipólito',
  'monte alegre do piaui': 'Monte Alegre do Piauí',
  'morro cabeca no tempo': 'Morro Cabeça no Tempo',
  'morro do chapeu do piaui': 'Morro do Chapéu do Piauí',
  'murici dos portelas': 'Murici dos Portelas',
  'nazare do piaui': 'Nazaré do Piauí',
  nazaria: 'Nazária',
  'nossa senhora de nazare': 'Nossa Senhora de Nazaré',
  'nossa senhora dos remedios': 'Nossa Senhora dos Remédios',
  'nova santa rita': 'Nova Santa Rita',
  'novo oriente do piaui': 'Novo Oriente do Piauí',
  'novo santo antonio_': 'Novo Santo Antônio',
  oeiras: 'Oeiras',
  "olho d'agua do piaui": "Olho d'Água do Piauí",
  'padre marcos': 'Padre Marcos',
  'paes landim': 'Paes Landim',
  'pajeu do piaui': 'Pajeú do Piauí',
  'palmeira do piaui': 'Palmeira do Piauí',
  palmeirais: 'Palmeirais',
  paqueta: 'Paquetá',
  parnagua: 'Parnaguá',
  parnaiba: 'Parnaíba',
  'passagem franca do piaui': 'Passagem Franca do Piauí',
  'patos do piaui': 'Patos do Piauí',
  "pau d'arco do piaui": "Pau d'Arco do Piauí",
  paulistana: 'Paulistana',
  pavussu: 'Pavussu',
  'pedro ii': 'Pedro II',
  'pedro laurentino': 'Pedro Laurentino',
  picos: 'Picos',
  pimenteiras: 'Pimenteiras',
  'pio ix': 'Pio IX',
  piracuruca: 'Piracuruca',
  piripiri: 'Piripiri',
  porto: 'Porto',
  'porto alegre do piaui': 'Porto Alegre do Piauí',
  'prata do piaui': 'Prata do Piauí',
  'queimada nova': 'Queimada Nova',
  'redencao do gurgueia': 'Redenção do Gurgueia',
  regeneracao: 'Regeneração',
  'riacho frio': 'Riacho Frio',
  'ribeira do piaui': 'Ribeira do Piauí',
  'ribeiro goncalves': 'Ribeiro Gonçalves',
  'rio grande do piaui': 'Rio Grande do Piauí',
  'santa cruz do piaui': 'Santa Cruz do Piauí',
  'santa cruz dos milagres': 'Santa Cruz dos Milagres',
  'santa filomena_': 'Santa Filomena',
  'santa luz': 'Santa Luz',
  'santana do piaui': 'Santana do Piauí',
  'santa rosa do piaui': 'Santa Rosa do Piauí',
  'santo antonio de lisboa': 'Santo Antônio de Lisboa',
  'santo antonio dos milagres': 'Santo Antônio dos Milagres',
  'santo inacio do piaui': 'Santo Inácio do Piauí',
  'sao braz do piaui': 'São Braz do Piauí',
  'sao felix do piaui': 'São Félix do Piauí',
  'sao francisco de assis do piaui': 'São Francisco de Assis do Piauí',
  'sao francisco do piaui': 'São Francisco do Piauí',
  'sao goncalo do gurgueia': 'São Gonçalo do Gurgueia',
  'sao goncalo do piaui': 'São Gonçalo do Piauí',
  'sao joao da canabrava': 'São João da Canabrava',
  'sao joao da fronteira': 'São João da Fronteira',
  'sao joao da serra': 'São João da Serra',
  'sao joao da varjota': 'São João da Varjota',
  'sao joao do arraial': 'São João do Arraial',
  'sao joao do piaui': 'São João do Piauí',
  'sao jose do divino_': 'São José do Divino',
  'sao jose do peixe': 'São José do Peixe',
  'sao jose do piaui': 'São José do Piauí',
  'sao juliao': 'São Julião',
  'sao lourenco do piaui': 'São Lourenço do Piauí',
  'sao luis do piaui': 'São Luís do Piauí',
  'sao miguel da baixa grande': 'São Miguel da Baixa Grande',
  'sao miguel do fidalgo': 'São Miguel do Fidalgo',
  'sao miguel do tapuio': 'São Miguel do Tapuio',
  'sao pedro do piaui': 'São Pedro do Piauí',
  'sao raimundo nonato': 'São Raimundo Nonato',
  'sebastiao barros': 'Sebastião Barros',
  'sebastiao leal': 'Sebastião Leal',
  'sigefredo pacheco': 'Sigefredo Pacheco',
  simoes: 'Simões',
  'simplicio mendes': 'Simplício Mendes',
  'socorro do piaui': 'Socorro do Piauí',
  sussuapara: 'Sussuapara',
  'tamboril do piaui': 'Tamboril do Piauí',
  'tanque do piaui': 'Tanque do Piauí',
  teresina: 'Teresina',
  uniao: 'União',
  urucui: 'Uruçuí',
  'valenca do piaui': 'Valença do Piauí',
  'varzea branca': 'Várzea Branca',
  'varzea grande_': 'Várzea Grande',
  'vera mendes': 'Vera Mendes',
  'vila nova do piaui': 'Vila Nova do Piauí',
  'wall ferraz': 'Wall Ferraz',
};
