export const cities = {
  abatia: 'Abatiá',
  adrianopolis: 'Adrianópolis',
  'agudos do sul': 'Agudos do Sul',
  'almirante tamandare': 'Almirante Tamandaré',
  'altamira do parana': 'Altamira do Paraná',
  altonia: 'Altônia',
  'alto paraiso': 'Alto Paraíso',
  'alto parana': 'Alto Paraná',
  'alto piquiri': 'Alto Piquiri',
  'alvorada do sul': 'Alvorada do Sul',
  amapora: 'Amaporã',
  ampere: 'Ampére',
  anahy: 'Anahy',
  andira: 'Andirá',
  angulo: 'Ângulo',
  antonina: 'Antonina',
  'antonio olinto': 'Antônio Olinto',
  apucarana: 'Apucarana',
  arapongas: 'Arapongas',
  arapoti: 'Arapoti',
  arapua_: 'Arapuã',
  araruna_: 'Araruna',
  araucaria: 'Araucária',
  'ariranha do ivai': 'Ariranha do Ivaí',
  assai: 'Assaí',
  'assis chateaubriand': 'Assis Chateaubriand',
  astorga: 'Astorga',
  atalaia_: 'Atalaia',
  'balsa nova': 'Balsa Nova',
  bandeirantes_: 'Bandeirantes',
  'barbosa ferraz': 'Barbosa Ferraz',
  barracao: 'Barracão',
  'barra do jacare': 'Barra do Jacaré',
  'bela vista da caroba': 'Bela Vista da Caroba',
  'bela vista do paraiso': 'Bela Vista do Paraíso',
  bituruna: 'Bituruna',
  'boa esperanca__': 'Boa Esperança',
  'boa esperanca do iguacu': 'Boa Esperança do Iguaçu',
  'boa ventura de sao roque': 'Boa Ventura de São Roque',
  'boa vista da aparecida': 'Boa Vista da Aparecida',
  'bocaiuva do sul': 'Bocaiúva do Sul',
  'bom jesus do sul': 'Bom Jesus do Sul',
  'bom sucesso__': 'Bom Sucesso',
  'bom sucesso do sul': 'Bom Sucesso do Sul',
  borrazopolis: 'Borrazópolis',
  braganey: 'Braganey',
  'brasilandia do sul': 'Brasilândia do Sul',
  cafeara: 'Cafeara',
  cafelandia: 'Cafelândia',
  'cafezal do sul': 'Cafezal do Sul',
  california: 'Califórnia',
  cambara: 'Cambará',
  cambe: 'Cambé',
  cambira: 'Cambira',
  'campina da lagoa': 'Campina da Lagoa',
  'campina do simao': 'Campina do Simão',
  'campina grande do sul': 'Campina Grande do Sul',
  'campo bonito': 'Campo Bonito',
  'campo do tenente': 'Campo do Tenente',
  'campo largo': 'Campo Largo',
  'campo magro': 'Campo Magro',
  'campo mourao': 'Campo Mourão',
  'candido de abreu': 'Cândido de Abreu',
  candoi: 'Candói',
  cantagalo_: 'Cantagalo',
  capanema_: 'Capanema',
  'capitao leonidas marques': 'Capitão Leônidas Marques',
  carambei: 'Carambeí',
  carlopolis: 'Carlópolis',
  cascavel_: 'Cascavel',
  castro: 'Castro',
  catanduvas: 'Catanduvas',
  'centenario do sul': 'Centenário do Sul',
  'cerro azul': 'Cerro Azul',
  'ceu azul': 'Céu Azul',
  chopinzinho: 'Chopinzinho',
  cianorte: 'Cianorte',
  'cidade gaucha': 'Cidade Gaúcha',
  clevelandia: 'Clevelândia',
  colombo: 'Colombo',
  colorado: 'Colorado',
  congonhinhas: 'Congonhinhas',
  'conselheiro mairinck': 'Conselheiro Mairinck',
  contenda: 'Contenda',
  corbelia: 'Corbélia',
  'cornelio procopio': 'Cornélio Procópio',
  'coronel domingos soares': 'Coronel Domingos Soares',
  'coronel vivida': 'Coronel Vivida',
  'corumbatai do sul': 'Corumbataí do Sul',
  'cruzeiro do iguacu': 'Cruzeiro do Iguaçu',
  'cruzeiro do oeste': 'Cruzeiro do Oeste',
  'cruzeiro do sul_': 'Cruzeiro do Sul',
  'cruz machado': 'Cruz Machado',
  cruzmaltina: 'Cruzmaltina',
  curitiba: 'Curitiba',
  curiuva: 'Curiúva',
  "diamante d'oeste": "Diamante d'Oeste",
  'diamante do norte': 'Diamante do Norte',
  'diamante do sul': 'Diamante do Sul',
  'dois vizinhos': 'Dois Vizinhos',
  douradina_: 'Douradina',
  'doutor camargo': 'Doutor Camargo',
  'doutor ulysses': 'Doutor Ulysses',
  'eneas marques': 'Enéas Marques',
  'engenheiro beltrao': 'Engenheiro Beltrão',
  'entre rios do oeste': 'Entre Rios do Oeste',
  'esperanca nova': 'Esperança Nova',
  'espigao alto do iguacu': 'Espigão Alto do Iguaçu',
  farol: 'Farol',
  faxinal: 'Faxinal',
  'fazenda rio grande': 'Fazenda Rio Grande',
  fenix: 'Fênix',
  'fernandes pinheiro': 'Fernandes Pinheiro',
  figueira: 'Figueira',
  florai: 'Floraí',
  'flor da serra do sul': 'Flor da Serra do Sul',
  floresta_: 'Floresta',
  florestopolis: 'Florestópolis',
  florida: 'Flórida',
  'formosa do oeste': 'Formosa do Oeste',
  'foz do iguacu': 'Foz do Iguaçu',
  'foz do jordao': 'Foz do Jordão',
  'francisco alves': 'Francisco Alves',
  'francisco beltrao': 'Francisco Beltrão',
  'general carneiro_': 'General Carneiro',
  'godoy moreira': 'Godoy Moreira',
  goioere: 'Goioerê',
  goioxim: 'Goioxim',
  'grandes rios': 'Grandes Rios',
  guaira: 'Guaíra',
  guairaca: 'Guairaçá',
  guamiranga: 'Guamiranga',
  guapirama: 'Guapirama',
  guaporema: 'Guaporema',
  guaraci: 'Guaraci',
  guaraniacu: 'Guaraniaçu',
  guarapuava: 'Guarapuava',
  guaraquecaba: 'Guaraqueçaba',
  guaratuba: 'Guaratuba',
  'honorio serpa': 'Honório Serpa',
  ibaiti: 'Ibaiti',
  ibema: 'Ibema',
  ibipora: 'Ibiporã',
  icaraima: 'Icaraíma',
  iguaracu: 'Iguaraçu',
  iguatu_: 'Iguatu',
  imbau: 'Imbaú',
  imbituva: 'Imbituva',
  'inacio martins': 'Inácio Martins',
  inaja_: 'Inajá',
  indianopolis_: 'Indianópolis',
  ipiranga: 'Ipiranga',
  ipora_: 'Iporã',
  'iracema do oeste': 'Iracema do Oeste',
  irati: 'Irati',
  iretama: 'Iretama',
  itaguaje: 'Itaguajé',
  itaipulandia: 'Itaipulândia',
  itambaraca: 'Itambaracá',
  itambe__: 'Itambé',
  "itapejara d'oeste": "Itapejara d'Oeste",
  itaperucu: 'Itaperuçu',
  'itauna do sul': 'Itaúna do Sul',
  ivai: 'Ivaí',
  ivaipora: 'Ivaiporã',
  ivate: 'Ivaté',
  ivatuba: 'Ivatuba',
  jaboti: 'Jaboti',
  jacarezinho: 'Jacarezinho',
  jaguapita: 'Jaguapitã',
  jaguariaiva: 'Jaguariaíva',
  'jandaia do sul': 'Jandaia do Sul',
  janiopolis: 'Janiópolis',
  japira: 'Japira',
  japura_: 'Japurá',
  'jardim alegre': 'Jardim Alegre',
  'jardim olinda': 'Jardim Olinda',
  jataizinho: 'Jataizinho',
  jesuitas: 'Jesuítas',
  'joaquim tavora': 'Joaquim Távora',
  'jundiai do sul': 'Jundiaí do Sul',
  juranda: 'Juranda',
  jussara__: 'Jussara',
  kalore: 'Kaloré',
  lapa: 'Lapa',
  laranjal_: 'Laranjal',
  'laranjeiras do sul': 'Laranjeiras do Sul',
  leopolis: 'Leópolis',
  lidianopolis: 'Lidianópolis',
  lindoeste: 'Lindoeste',
  loanda: 'Loanda',
  lobato: 'Lobato',
  londrina: 'Londrina',
  luisiana: 'Luisiana',
  lunardelli: 'Lunardelli',
  lupionopolis: 'Lupionópolis',
  mallet: 'Mallet',
  mambore: 'Mamborê',
  mandaguacu: 'Mandaguaçu',
  mandaguari: 'Mandaguari',
  mandirituba: 'Mandirituba',
  manfrinopolis: 'Manfrinópolis',
  mangueirinha: 'Mangueirinha',
  'manoel ribas': 'Manoel Ribas',
  'marechal candido rondon': 'Marechal Cândido Rondon',
  'maria helena': 'Maria Helena',
  marialva: 'Marialva',
  'marilandia do sul': 'Marilândia do Sul',
  marilena: 'Marilena',
  mariluz: 'Mariluz',
  maringa: 'Maringá',
  mariopolis: 'Mariópolis',
  maripa: 'Maripá',
  marmeleiro: 'Marmeleiro',
  marquinho: 'Marquinho',
  marumbi: 'Marumbi',
  matelandia: 'Matelândia',
  matinhos: 'Matinhos',
  'mato rico': 'Mato Rico',
  'maua da serra': 'Mauá da Serra',
  medianeira: 'Medianeira',
  mercedes: 'Mercedes',
  mirador_: 'Mirador',
  miraselva: 'Miraselva',
  missal: 'Missal',
  'moreira sales': 'Moreira Sales',
  morretes: 'Morretes',
  'munhoz de mello': 'Munhoz de Mello',
  'nossa senhora das gracas': 'Nossa Senhora das Graças',
  'nova alianca do ivai': 'Nova Aliança do Ivaí',
  'nova america da colina': 'Nova América da Colina',
  'nova aurora_': 'Nova Aurora',
  'nova cantu': 'Nova Cantu',
  'nova esperanca': 'Nova Esperança',
  'nova esperanca do sudoeste': 'Nova Esperança do Sudoeste',
  'nova fatima_': 'Nova Fátima',
  'nova laranjeiras': 'Nova Laranjeiras',
  'nova londrina': 'Nova Londrina',
  'nova olimpia_': 'Nova Olímpia',
  'nova prata do iguacu': 'Nova Prata do Iguaçu',
  'nova santa barbara': 'Nova Santa Bárbara',
  'nova santa rosa': 'Nova Santa Rosa',
  'nova tebas': 'Nova Tebas',
  'novo itacolomi': 'Novo Itacolomi',
  ortigueira: 'Ortigueira',
  ourizona: 'Ourizona',
  'ouro verde do oeste': 'Ouro Verde do Oeste',
  paicandu: 'Paiçandu',
  palmas: 'Palmas',
  palmeira: 'Palmeira',
  palmital: 'Palmital',
  palotina: 'Palotina',
  'paraiso do norte': 'Paraíso do Norte',
  paranacity: 'Paranacity',
  paranagua: 'Paranaguá',
  paranapoema: 'Paranapoema',
  paranavai: 'Paranavaí',
  'pato bragado': 'Pato Bragado',
  'pato branco': 'Pato Branco',
  'paula freitas': 'Paula Freitas',
  'paulo frontin': 'Paulo Frontin',
  peabiru: 'Peabiru',
  perobal: 'Perobal',
  perola: 'Pérola',
  "perola d'oeste": "Pérola d'Oeste",
  pien: 'Piên',
  pinhais: 'Pinhais',
  pinhalao: 'Pinhalão',
  'pinhal de sao bento': 'Pinhal de São Bento',
  pinhao: 'Pinhão',
  'pirai do sul': 'Piraí do Sul',
  piraquara: 'Piraquara',
  pitanga: 'Pitanga',
  pitangueiras: 'Pitangueiras',
  'planaltina do parana': 'Planaltina do Paraná',
  planalto_: 'Planalto',
  'ponta grossa': 'Ponta Grossa',
  'pontal do parana': 'Pontal do Paraná',
  porecatu: 'Porecatu',
  'porto amazonas': 'Porto Amazonas',
  'porto barreiro': 'Porto Barreiro',
  'porto rico': 'Porto Rico',
  'porto vitoria': 'Porto Vitória',
  'prado ferreira': 'Prado Ferreira',
  pranchita: 'Pranchita',
  'presidente castelo branco': 'Presidente Castelo Branco',
  'primeiro de maio': 'Primeiro de Maio',
  prudentopolis: 'Prudentópolis',
  'quarto centenario': 'Quarto Centenário',
  quatigua: 'Quatiguá',
  'quatro barras': 'Quatro Barras',
  'quatro pontes': 'Quatro Pontes',
  'quedas do iguacu': 'Quedas do Iguaçu',
  'querencia do norte': 'Querência do Norte',
  'quinta do sol': 'Quinta do Sol',
  quitandinha: 'Quitandinha',
  ramilandia: 'Ramilândia',
  "rancho alegre d'oeste": "Rancho Alegre d'Oeste",
  'rancho alegre': 'Rancho Alegre',
  realeza: 'Realeza',
  reboucas: 'Rebouças',
  renascenca: 'Renascença',
  'reserva do iguacu': 'Reserva do Iguaçu',
  reserva: 'Reserva',
  'ribeirao claro': 'Ribeirão Claro',
  'ribeirao do pinhal': 'Ribeirão do Pinhal',
  'rio azul': 'Rio Azul',
  'rio bom': 'Rio Bom',
  'rio bonito do iguacu': 'Rio Bonito do Iguaçu',
  'rio branco do ivai': 'Rio Branco do Ivaí',
  'rio branco do sul': 'Rio Branco do Sul',
  'rio negro_': 'Rio Negro',
  rolandia: 'Rolândia',
  roncador: 'Roncador',
  rondon: 'Rondon',
  'rosario do ivai': 'Rosário do Ivaí',
  sabaudia: 'Sabáudia',
  'salgado filho': 'Salgado Filho',
  'salto do itarare': 'Salto do Itararé',
  'salto do lontra': 'Salto do Lontra',
  'santa amelia': 'Santa Amélia',
  'santa cecilia do pavao': 'Santa Cecília do Pavão',
  'santa cruz de monte castelo': 'Santa Cruz de Monte Castelo',
  'santa fe': 'Santa Fé',
  'santa helena__': 'Santa Helena',
  'santa ines___': 'Santa Inês',
  'santa isabel do ivai': 'Santa Isabel do Ivaí',
  'santa izabel do oeste': 'Santa Izabel do Oeste',
  'santa lucia': 'Santa Lúcia',
  'santa maria do oeste': 'Santa Maria do Oeste',
  'santa mariana': 'Santa Mariana',
  'santa monica': 'Santa Mônica',
  'santana do itarare': 'Santana do Itararé',
  'santa tereza do oeste': 'Santa Tereza do Oeste',
  'santa terezinha de itaipu': 'Santa Terezinha de Itaipu',
  'santo antonio da platina': 'Santo Antônio da Platina',
  'santo antonio do caiua': 'Santo Antônio do Caiuá',
  'santo antonio do paraiso': 'Santo Antônio do Paraíso',
  'santo antonio do sudoeste': 'Santo Antônio do Sudoeste',
  'santo inacio': 'Santo Inácio',
  'sao carlos do ivai': 'São Carlos do Ivaí',
  'sao jeronimo da serra': 'São Jerônimo da Serra',
  'sao joao_': 'São João',
  'sao joao do caiua': 'São João do Caiuá',
  'sao joao do ivai': 'São João do Ivaí',
  'sao joao do triunfo': 'São João do Triunfo',
  "sao jorge d'oeste": "São Jorge d'Oeste",
  'sao jorge do ivai': 'São Jorge do Ivaí',
  'sao jorge do patrocinio': 'São Jorge do Patrocínio',
  'sao jose da boa vista': 'São José da Boa Vista',
  'sao jose das palmeiras': 'São José das Palmeiras',
  'sao jose dos pinhais': 'São José dos Pinhais',
  'sao manoel do parana': 'São Manoel do Paraná',
  'sao mateus do sul': 'São Mateus do Sul',
  'sao miguel do iguacu': 'São Miguel do Iguaçu',
  'sao pedro do iguacu': 'São Pedro do Iguaçu',
  'sao pedro do ivai': 'São Pedro do Ivaí',
  'sao pedro do parana': 'São Pedro do Paraná',
  'sao sebastiao da amoreira': 'São Sebastião da Amoreira',
  'sao tome': 'São Tomé',
  sapopema: 'Sapopema',
  sarandi: 'Sarandi',
  'saudade do iguacu': 'Saudade do Iguaçu',
  senges: 'Sengés',
  'serranopolis do iguacu': 'Serranópolis do Iguaçu',
  sertaneja: 'Sertaneja',
  sertanopolis: 'Sertanópolis',
  'siqueira campos': 'Siqueira Campos',
  sulina: 'Sulina',
  tamarana: 'Tamarana',
  tamboara: 'Tamboara',
  tapejara: 'Tapejara',
  tapira_: 'Tapira',
  'teixeira soares': 'Teixeira Soares',
  'telemaco borba': 'Telêmaco Borba',
  'terra boa': 'Terra Boa',
  'terra rica': 'Terra Rica',
  'terra roxa': 'Terra Roxa',
  tibagi: 'Tibagi',
  'tijucas do sul': 'Tijucas do Sul',
  toledo_: 'Toledo',
  tomazina: 'Tomazina',
  'tres barras do parana': 'Três Barras do Paraná',
  'tunas do parana': 'Tunas do Paraná',
  'tuneiras do oeste': 'Tuneiras do Oeste',
  tupassi: 'Tupãssi',
  turvo: 'Turvo',
  ubirata: 'Ubiratã',
  umuarama: 'Umuarama',
  'uniao da vitoria': 'União da Vitória',
  uniflor: 'Uniflor',
  urai: 'Uraí',
  ventania: 'Ventania',
  'vera cruz do oeste': 'Vera Cruz do Oeste',
  vere: 'Verê',
  virmond: 'Virmond',
  vitorino: 'Vitorino',
  'wenceslau braz_': 'Wenceslau Braz',
  xambre: 'Xambrê',
};
