export const cities = {
  abatia: { name: 'Abatiá', state: 'PR' },
  adrianopolis: { name: 'Adrianópolis', state: 'PR' },
  'agudos do sul': { name: 'Agudos do Sul', state: 'PR' },
  'almirante tamandare': { name: 'Almirante Tamandaré', state: 'PR' },
  'altamira do parana': { name: 'Altamira do Paraná', state: 'PR' },
  altonia: { name: 'Altônia', state: 'PR' },
  'alto paraiso': { name: 'Alto Paraíso', state: 'PR' },
  'alto parana': { name: 'Alto Paraná', state: 'PR' },
  'alto piquiri': { name: 'Alto Piquiri', state: 'PR' },
  'alvorada do sul': { name: 'Alvorada do Sul', state: 'PR' },
  amapora: { name: 'Amaporã', state: 'PR' },
  ampere: { name: 'Ampére', state: 'PR' },
  anahy: { name: 'Anahy', state: 'PR' },
  andira: { name: 'Andirá', state: 'PR' },
  angulo: { name: 'Ângulo', state: 'PR' },
  antonina: { name: 'Antonina', state: 'PR' },
  'antonio olinto': { name: 'Antônio Olinto', state: 'PR' },
  apucarana: { name: 'Apucarana', state: 'PR' },
  arapongas: { name: 'Arapongas', state: 'PR' },
  arapoti: { name: 'Arapoti', state: 'PR' },
  arapua_: { name: 'Arapuã', state: 'PR' },
  araruna_: { name: 'Araruna', state: 'PR' },
  araucaria: { name: 'Araucária', state: 'PR' },
  'ariranha do ivai': { name: 'Ariranha do Ivaí', state: 'PR' },
  assai: { name: 'Assaí', state: 'PR' },
  'assis chateaubriand': { name: 'Assis Chateaubriand', state: 'PR' },
  astorga: { name: 'Astorga', state: 'PR' },
  atalaia_: { name: 'Atalaia', state: 'PR' },
  'balsa nova': { name: 'Balsa Nova', state: 'PR' },
  bandeirantes_: { name: 'Bandeirantes', state: 'PR' },
  'barbosa ferraz': { name: 'Barbosa Ferraz', state: 'PR' },
  barracao: { name: 'Barracão', state: 'PR' },
  'barra do jacare': { name: 'Barra do Jacaré', state: 'PR' },
  'bela vista da caroba': { name: 'Bela Vista da Caroba', state: 'PR' },
  'bela vista do paraiso': { name: 'Bela Vista do Paraíso', state: 'PR' },
  bituruna: { name: 'Bituruna', state: 'PR' },
  'boa esperanca__': { name: 'Boa Esperança', state: 'PR' },
  'boa esperanca do iguacu': { name: 'Boa Esperança do Iguaçu', state: 'PR' },
  'boa ventura de sao roque': { name: 'Boa Ventura de São Roque', state: 'PR' },
  'boa vista da aparecida': { name: 'Boa Vista da Aparecida', state: 'PR' },
  'bocaiuva do sul': { name: 'Bocaiúva do Sul', state: 'PR' },
  'bom jesus do sul': { name: 'Bom Jesus do Sul', state: 'PR' },
  'bom sucesso__': { name: 'Bom Sucesso', state: 'PR' },
  'bom sucesso do sul': { name: 'Bom Sucesso do Sul', state: 'PR' },
  borrazopolis: { name: 'Borrazópolis', state: 'PR' },
  braganey: { name: 'Braganey', state: 'PR' },
  'brasilandia do sul': { name: 'Brasilândia do Sul', state: 'PR' },
  cafeara: { name: 'Cafeara', state: 'PR' },
  cafelandia: { name: 'Cafelândia', state: 'PR' },
  'cafezal do sul': { name: 'Cafezal do Sul', state: 'PR' },
  california: { name: 'Califórnia', state: 'PR' },
  cambara: { name: 'Cambará', state: 'PR' },
  cambe: { name: 'Cambé', state: 'PR' },
  cambira: { name: 'Cambira', state: 'PR' },
  'campina da lagoa': { name: 'Campina da Lagoa', state: 'PR' },
  'campina do simao': { name: 'Campina do Simão', state: 'PR' },
  'campina grande do sul': { name: 'Campina Grande do Sul', state: 'PR' },
  'campo bonito': { name: 'Campo Bonito', state: 'PR' },
  'campo do tenente': { name: 'Campo do Tenente', state: 'PR' },
  'campo largo': { name: 'Campo Largo', state: 'PR' },
  'campo magro': { name: 'Campo Magro', state: 'PR' },
  'campo mourao': { name: 'Campo Mourão', state: 'PR' },
  'candido de abreu': { name: 'Cândido de Abreu', state: 'PR' },
  candoi: { name: 'Candói', state: 'PR' },
  cantagalo_: { name: 'Cantagalo', state: 'PR' },
  capanema_: { name: 'Capanema', state: 'PR' },
  'capitao leonidas marques': { name: 'Capitão Leônidas Marques', state: 'PR' },
  carambei: { name: 'Carambeí', state: 'PR' },
  carlopolis: { name: 'Carlópolis', state: 'PR' },
  cascavel_: { name: 'Cascavel', state: 'PR' },
  castro: { name: 'Castro', state: 'PR' },
  catanduvas: { name: 'Catanduvas', state: 'PR' },
  'centenario do sul': { name: 'Centenário do Sul', state: 'PR' },
  'cerro azul': { name: 'Cerro Azul', state: 'PR' },
  'ceu azul': { name: 'Céu Azul', state: 'PR' },
  chopinzinho: { name: 'Chopinzinho', state: 'PR' },
  cianorte: { name: 'Cianorte', state: 'PR' },
  'cidade gaucha': { name: 'Cidade Gaúcha', state: 'PR' },
  clevelandia: { name: 'Clevelândia', state: 'PR' },
  colombo: { name: 'Colombo', state: 'PR' },
  colorado: { name: 'Colorado', state: 'PR' },
  congonhinhas: { name: 'Congonhinhas', state: 'PR' },
  'conselheiro mairinck': { name: 'Conselheiro Mairinck', state: 'PR' },
  contenda: { name: 'Contenda', state: 'PR' },
  corbelia: { name: 'Corbélia', state: 'PR' },
  'cornelio procopio': { name: 'Cornélio Procópio', state: 'PR' },
  'coronel domingos soares': { name: 'Coronel Domingos Soares', state: 'PR' },
  'coronel vivida': { name: 'Coronel Vivida', state: 'PR' },
  'corumbatai do sul': { name: 'Corumbataí do Sul', state: 'PR' },
  'cruzeiro do iguacu': { name: 'Cruzeiro do Iguaçu', state: 'PR' },
  'cruzeiro do oeste': { name: 'Cruzeiro do Oeste', state: 'PR' },
  'cruzeiro do sul_': { name: 'Cruzeiro do Sul', state: 'PR' },
  'cruz machado': { name: 'Cruz Machado', state: 'PR' },
  cruzmaltina: { name: 'Cruzmaltina', state: 'PR' },
  curitiba: { name: 'Curitiba', state: 'PR' },
  curiuva: { name: 'Curiúva', state: 'PR' },
  "diamante d'oeste": { name: "Diamante d'Oeste", state: 'PR' },
  'diamante do norte': { name: 'Diamante do Norte', state: 'PR' },
  'diamante do sul': { name: 'Diamante do Sul', state: 'PR' },
  'dois vizinhos': { name: 'Dois Vizinhos', state: 'PR' },
  douradina_: { name: 'Douradina', state: 'PR' },
  'doutor camargo': { name: 'Doutor Camargo', state: 'PR' },
  'doutor ulysses': { name: 'Doutor Ulysses', state: 'PR' },
  'eneas marques': { name: 'Enéas Marques', state: 'PR' },
  'engenheiro beltrao': { name: 'Engenheiro Beltrão', state: 'PR' },
  'entre rios do oeste': { name: 'Entre Rios do Oeste', state: 'PR' },
  'esperanca nova': { name: 'Esperança Nova', state: 'PR' },
  'espigao alto do iguacu': { name: 'Espigão Alto do Iguaçu', state: 'PR' },
  farol: { name: 'Farol', state: 'PR' },
  faxinal: { name: 'Faxinal', state: 'PR' },
  'fazenda rio grande': { name: 'Fazenda Rio Grande', state: 'PR' },
  fenix: { name: 'Fênix', state: 'PR' },
  'fernandes pinheiro': { name: 'Fernandes Pinheiro', state: 'PR' },
  figueira: { name: 'Figueira', state: 'PR' },
  florai: { name: 'Floraí', state: 'PR' },
  'flor da serra do sul': { name: 'Flor da Serra do Sul', state: 'PR' },
  floresta_: { name: 'Floresta', state: 'PR' },
  florestopolis: { name: 'Florestópolis', state: 'PR' },
  florida: { name: 'Flórida', state: 'PR' },
  'formosa do oeste': { name: 'Formosa do Oeste', state: 'PR' },
  'foz do iguacu': { name: 'Foz do Iguaçu', state: 'PR' },
  'foz do jordao': { name: 'Foz do Jordão', state: 'PR' },
  'francisco alves': { name: 'Francisco Alves', state: 'PR' },
  'francisco beltrao': { name: 'Francisco Beltrão', state: 'PR' },
  'general carneiro_': { name: 'General Carneiro', state: 'PR' },
  'godoy moreira': { name: 'Godoy Moreira', state: 'PR' },
  goioere: { name: 'Goioerê', state: 'PR' },
  goioxim: { name: 'Goioxim', state: 'PR' },
  'grandes rios': { name: 'Grandes Rios', state: 'PR' },
  guaira: { name: 'Guaíra', state: 'PR' },
  guairaca: { name: 'Guairaçá', state: 'PR' },
  guamiranga: { name: 'Guamiranga', state: 'PR' },
  guapirama: { name: 'Guapirama', state: 'PR' },
  guaporema: { name: 'Guaporema', state: 'PR' },
  guaraci: { name: 'Guaraci', state: 'PR' },
  guaraniacu: { name: 'Guaraniaçu', state: 'PR' },
  guarapuava: { name: 'Guarapuava', state: 'PR' },
  guaraquecaba: { name: 'Guaraqueçaba', state: 'PR' },
  guaratuba: { name: 'Guaratuba', state: 'PR' },
  'honorio serpa': { name: 'Honório Serpa', state: 'PR' },
  ibaiti: { name: 'Ibaiti', state: 'PR' },
  ibema: { name: 'Ibema', state: 'PR' },
  ibipora: { name: 'Ibiporã', state: 'PR' },
  icaraima: { name: 'Icaraíma', state: 'PR' },
  iguaracu: { name: 'Iguaraçu', state: 'PR' },
  iguatu_: { name: 'Iguatu', state: 'PR' },
  imbau: { name: 'Imbaú', state: 'PR' },
  imbituva: { name: 'Imbituva', state: 'PR' },
  'inacio martins': { name: 'Inácio Martins', state: 'PR' },
  inaja_: { name: 'Inajá', state: 'PR' },
  indianopolis_: { name: 'Indianópolis', state: 'PR' },
  ipiranga: { name: 'Ipiranga', state: 'PR' },
  ipora_: { name: 'Iporã', state: 'PR' },
  'iracema do oeste': { name: 'Iracema do Oeste', state: 'PR' },
  irati: { name: 'Irati', state: 'PR' },
  iretama: { name: 'Iretama', state: 'PR' },
  itaguaje: { name: 'Itaguajé', state: 'PR' },
  itaipulandia: { name: 'Itaipulândia', state: 'PR' },
  itambaraca: { name: 'Itambaracá', state: 'PR' },
  itambe__: { name: 'Itambé', state: 'PR' },
  "itapejara d'oeste": { name: "Itapejara d'Oeste", state: 'PR' },
  itaperucu: { name: 'Itaperuçu', state: 'PR' },
  'itauna do sul': { name: 'Itaúna do Sul', state: 'PR' },
  ivai: { name: 'Ivaí', state: 'PR' },
  ivaipora: { name: 'Ivaiporã', state: 'PR' },
  ivate: { name: 'Ivaté', state: 'PR' },
  ivatuba: { name: 'Ivatuba', state: 'PR' },
  jaboti: { name: 'Jaboti', state: 'PR' },
  jacarezinho: { name: 'Jacarezinho', state: 'PR' },
  jaguapita: { name: 'Jaguapitã', state: 'PR' },
  jaguariaiva: { name: 'Jaguariaíva', state: 'PR' },
  'jandaia do sul': { name: 'Jandaia do Sul', state: 'PR' },
  janiopolis: { name: 'Janiópolis', state: 'PR' },
  japira: { name: 'Japira', state: 'PR' },
  japura_: { name: 'Japurá', state: 'PR' },
  'jardim alegre': { name: 'Jardim Alegre', state: 'PR' },
  'jardim olinda': { name: 'Jardim Olinda', state: 'PR' },
  jataizinho: { name: 'Jataizinho', state: 'PR' },
  jesuitas: { name: 'Jesuítas', state: 'PR' },
  'joaquim tavora': { name: 'Joaquim Távora', state: 'PR' },
  'jundiai do sul': { name: 'Jundiaí do Sul', state: 'PR' },
  juranda: { name: 'Juranda', state: 'PR' },
  jussara__: { name: 'Jussara', state: 'PR' },
  kalore: { name: 'Kaloré', state: 'PR' },
  lapa: { name: 'Lapa', state: 'PR' },
  laranjal_: { name: 'Laranjal', state: 'PR' },
  'laranjeiras do sul': { name: 'Laranjeiras do Sul', state: 'PR' },
  leopolis: { name: 'Leópolis', state: 'PR' },
  lidianopolis: { name: 'Lidianópolis', state: 'PR' },
  lindoeste: { name: 'Lindoeste', state: 'PR' },
  loanda: { name: 'Loanda', state: 'PR' },
  lobato: { name: 'Lobato', state: 'PR' },
  londrina: { name: 'Londrina', state: 'PR' },
  luisiana: { name: 'Luisiana', state: 'PR' },
  lunardelli: { name: 'Lunardelli', state: 'PR' },
  lupionopolis: { name: 'Lupionópolis', state: 'PR' },
  mallet: { name: 'Mallet', state: 'PR' },
  mambore: { name: 'Mamborê', state: 'PR' },
  mandaguacu: { name: 'Mandaguaçu', state: 'PR' },
  mandaguari: { name: 'Mandaguari', state: 'PR' },
  mandirituba: { name: 'Mandirituba', state: 'PR' },
  manfrinopolis: { name: 'Manfrinópolis', state: 'PR' },
  mangueirinha: { name: 'Mangueirinha', state: 'PR' },
  'manoel ribas': { name: 'Manoel Ribas', state: 'PR' },
  'marechal candido rondon': { name: 'Marechal Cândido Rondon', state: 'PR' },
  'maria helena': { name: 'Maria Helena', state: 'PR' },
  marialva: { name: 'Marialva', state: 'PR' },
  'marilandia do sul': { name: 'Marilândia do Sul', state: 'PR' },
  marilena: { name: 'Marilena', state: 'PR' },
  mariluz: { name: 'Mariluz', state: 'PR' },
  maringa: { name: 'Maringá', state: 'PR' },
  mariopolis: { name: 'Mariópolis', state: 'PR' },
  maripa: { name: 'Maripá', state: 'PR' },
  marmeleiro: { name: 'Marmeleiro', state: 'PR' },
  marquinho: { name: 'Marquinho', state: 'PR' },
  marumbi: { name: 'Marumbi', state: 'PR' },
  matelandia: { name: 'Matelândia', state: 'PR' },
  matinhos: { name: 'Matinhos', state: 'PR' },
  'mato rico': { name: 'Mato Rico', state: 'PR' },
  'maua da serra': { name: 'Mauá da Serra', state: 'PR' },
  medianeira: { name: 'Medianeira', state: 'PR' },
  mercedes: { name: 'Mercedes', state: 'PR' },
  mirador_: { name: 'Mirador', state: 'PR' },
  miraselva: { name: 'Miraselva', state: 'PR' },
  missal: { name: 'Missal', state: 'PR' },
  'moreira sales': { name: 'Moreira Sales', state: 'PR' },
  morretes: { name: 'Morretes', state: 'PR' },
  'munhoz de mello': { name: 'Munhoz de Mello', state: 'PR' },
  'nossa senhora das gracas': { name: 'Nossa Senhora das Graças', state: 'PR' },
  'nova alianca do ivai': { name: 'Nova Aliança do Ivaí', state: 'PR' },
  'nova america da colina': { name: 'Nova América da Colina', state: 'PR' },
  'nova aurora_': { name: 'Nova Aurora', state: 'PR' },
  'nova cantu': { name: 'Nova Cantu', state: 'PR' },
  'nova esperanca': { name: 'Nova Esperança', state: 'PR' },
  'nova esperanca do sudoeste': { name: 'Nova Esperança do Sudoeste', state: 'PR' },
  'nova fatima_': { name: 'Nova Fátima', state: 'PR' },
  'nova laranjeiras': { name: 'Nova Laranjeiras', state: 'PR' },
  'nova londrina': { name: 'Nova Londrina', state: 'PR' },
  'nova olimpia_': { name: 'Nova Olímpia', state: 'PR' },
  'nova prata do iguacu': { name: 'Nova Prata do Iguaçu', state: 'PR' },
  'nova santa barbara': { name: 'Nova Santa Bárbara', state: 'PR' },
  'nova santa rosa': { name: 'Nova Santa Rosa', state: 'PR' },
  'nova tebas': { name: 'Nova Tebas', state: 'PR' },
  'novo itacolomi': { name: 'Novo Itacolomi', state: 'PR' },
  ortigueira: { name: 'Ortigueira', state: 'PR' },
  ourizona: { name: 'Ourizona', state: 'PR' },
  'ouro verde do oeste': { name: 'Ouro Verde do Oeste', state: 'PR' },
  paicandu: { name: 'Paiçandu', state: 'PR' },
  palmas: { name: 'Palmas', state: 'PR' },
  palmeira: { name: 'Palmeira', state: 'PR' },
  palmital: { name: 'Palmital', state: 'PR' },
  palotina: { name: 'Palotina', state: 'PR' },
  'paraiso do norte': { name: 'Paraíso do Norte', state: 'PR' },
  paranacity: { name: 'Paranacity', state: 'PR' },
  paranagua: { name: 'Paranaguá', state: 'PR' },
  paranapoema: { name: 'Paranapoema', state: 'PR' },
  paranavai: { name: 'Paranavaí', state: 'PR' },
  'pato bragado': { name: 'Pato Bragado', state: 'PR' },
  'pato branco': { name: 'Pato Branco', state: 'PR' },
  'paula freitas': { name: 'Paula Freitas', state: 'PR' },
  'paulo frontin': { name: 'Paulo Frontin', state: 'PR' },
  peabiru: { name: 'Peabiru', state: 'PR' },
  perobal: { name: 'Perobal', state: 'PR' },
  perola: { name: 'Pérola', state: 'PR' },
  "perola d'oeste": { name: "Pérola d'Oeste", state: 'PR' },
  pien: { name: 'Piên', state: 'PR' },
  pinhais: { name: 'Pinhais', state: 'PR' },
  pinhalao: { name: 'Pinhalão', state: 'PR' },
  'pinhal de sao bento': { name: 'Pinhal de São Bento', state: 'PR' },
  pinhao: { name: 'Pinhão', state: 'PR' },
  'pirai do sul': { name: 'Piraí do Sul', state: 'PR' },
  piraquara: { name: 'Piraquara', state: 'PR' },
  pitanga: { name: 'Pitanga', state: 'PR' },
  pitangueiras: { name: 'Pitangueiras', state: 'PR' },
  'planaltina do parana': { name: 'Planaltina do Paraná', state: 'PR' },
  planalto_: { name: 'Planalto', state: 'PR' },
  'ponta grossa': { name: 'Ponta Grossa', state: 'PR' },
  'pontal do parana': { name: 'Pontal do Paraná', state: 'PR' },
  porecatu: { name: 'Porecatu', state: 'PR' },
  'porto amazonas': { name: 'Porto Amazonas', state: 'PR' },
  'porto barreiro': { name: 'Porto Barreiro', state: 'PR' },
  'porto rico': { name: 'Porto Rico', state: 'PR' },
  'porto vitoria': { name: 'Porto Vitória', state: 'PR' },
  'prado ferreira': { name: 'Prado Ferreira', state: 'PR' },
  pranchita: { name: 'Pranchita', state: 'PR' },
  'presidente castelo branco': { name: 'Presidente Castelo Branco', state: 'PR' },
  'primeiro de maio': { name: 'Primeiro de Maio', state: 'PR' },
  prudentopolis: { name: 'Prudentópolis', state: 'PR' },
  'quarto centenario': { name: 'Quarto Centenário', state: 'PR' },
  quatigua: { name: 'Quatiguá', state: 'PR' },
  'quatro barras': { name: 'Quatro Barras', state: 'PR' },
  'quatro pontes': { name: 'Quatro Pontes', state: 'PR' },
  'quedas do iguacu': { name: 'Quedas do Iguaçu', state: 'PR' },
  'querencia do norte': { name: 'Querência do Norte', state: 'PR' },
  'quinta do sol': { name: 'Quinta do Sol', state: 'PR' },
  quitandinha: { name: 'Quitandinha', state: 'PR' },
  ramilandia: { name: 'Ramilândia', state: 'PR' },
  "rancho alegre d'oeste": { name: "Rancho Alegre d'Oeste", state: 'PR' },
  'rancho alegre': { name: 'Rancho Alegre', state: 'PR' },
  realeza: { name: 'Realeza', state: 'PR' },
  reboucas: { name: 'Rebouças', state: 'PR' },
  renascenca: { name: 'Renascença', state: 'PR' },
  'reserva do iguacu': { name: 'Reserva do Iguaçu', state: 'PR' },
  reserva: { name: 'Reserva', state: 'PR' },
  'ribeirao claro': { name: 'Ribeirão Claro', state: 'PR' },
  'ribeirao do pinhal': { name: 'Ribeirão do Pinhal', state: 'PR' },
  'rio azul': { name: 'Rio Azul', state: 'PR' },
  'rio bom': { name: 'Rio Bom', state: 'PR' },
  'rio bonito do iguacu': { name: 'Rio Bonito do Iguaçu', state: 'PR' },
  'rio branco do ivai': { name: 'Rio Branco do Ivaí', state: 'PR' },
  'rio branco do sul': { name: 'Rio Branco do Sul', state: 'PR' },
  'rio negro_': { name: 'Rio Negro', state: 'PR' },
  rolandia: { name: 'Rolândia', state: 'PR' },
  roncador: { name: 'Roncador', state: 'PR' },
  rondon: { name: 'Rondon', state: 'PR' },
  'rosario do ivai': { name: 'Rosário do Ivaí', state: 'PR' },
  sabaudia: { name: 'Sabáudia', state: 'PR' },
  'salgado filho': { name: 'Salgado Filho', state: 'PR' },
  'salto do itarare': { name: 'Salto do Itararé', state: 'PR' },
  'salto do lontra': { name: 'Salto do Lontra', state: 'PR' },
  'santa amelia': { name: 'Santa Amélia', state: 'PR' },
  'santa cecilia do pavao': { name: 'Santa Cecília do Pavão', state: 'PR' },
  'santa cruz de monte castelo': { name: 'Santa Cruz de Monte Castelo', state: 'PR' },
  'santa fe': { name: 'Santa Fé', state: 'PR' },
  'santa helena__': { name: 'Santa Helena', state: 'PR' },
  'santa ines___': { name: 'Santa Inês', state: 'PR' },
  'santa isabel do ivai': { name: 'Santa Isabel do Ivaí', state: 'PR' },
  'santa izabel do oeste': { name: 'Santa Izabel do Oeste', state: 'PR' },
  'santa lucia': { name: 'Santa Lúcia', state: 'PR' },
  'santa maria do oeste': { name: 'Santa Maria do Oeste', state: 'PR' },
  'santa mariana': { name: 'Santa Mariana', state: 'PR' },
  'santa monica': { name: 'Santa Mônica', state: 'PR' },
  'santana do itarare': { name: 'Santana do Itararé', state: 'PR' },
  'santa tereza do oeste': { name: 'Santa Tereza do Oeste', state: 'PR' },
  'santa terezinha de itaipu': { name: 'Santa Terezinha de Itaipu', state: 'PR' },
  'santo antonio da platina': { name: 'Santo Antônio da Platina', state: 'PR' },
  'santo antonio do caiua': { name: 'Santo Antônio do Caiuá', state: 'PR' },
  'santo antonio do paraiso': { name: 'Santo Antônio do Paraíso', state: 'PR' },
  'santo antonio do sudoeste': { name: 'Santo Antônio do Sudoeste', state: 'PR' },
  'santo inacio': { name: 'Santo Inácio', state: 'PR' },
  'sao carlos do ivai': { name: 'São Carlos do Ivaí', state: 'PR' },
  'sao jeronimo da serra': { name: 'São Jerônimo da Serra', state: 'PR' },
  'sao joao_': { name: 'São João', state: 'PR' },
  'sao joao do caiua': { name: 'São João do Caiuá', state: 'PR' },
  'sao joao do ivai': { name: 'São João do Ivaí', state: 'PR' },
  'sao joao do triunfo': { name: 'São João do Triunfo', state: 'PR' },
  "sao jorge d'oeste": { name: "São Jorge d'Oeste", state: 'PR' },
  'sao jorge do ivai': { name: 'São Jorge do Ivaí', state: 'PR' },
  'sao jorge do patrocinio': { name: 'São Jorge do Patrocínio', state: 'PR' },
  'sao jose da boa vista': { name: 'São José da Boa Vista', state: 'PR' },
  'sao jose das palmeiras': { name: 'São José das Palmeiras', state: 'PR' },
  'sao jose dos pinhais': { name: 'São José dos Pinhais', state: 'PR' },
  'sao manoel do parana': { name: 'São Manoel do Paraná', state: 'PR' },
  'sao mateus do sul': { name: 'São Mateus do Sul', state: 'PR' },
  'sao miguel do iguacu': { name: 'São Miguel do Iguaçu', state: 'PR' },
  'sao pedro do iguacu': { name: 'São Pedro do Iguaçu', state: 'PR' },
  'sao pedro do ivai': { name: 'São Pedro do Ivaí', state: 'PR' },
  'sao pedro do parana': { name: 'São Pedro do Paraná', state: 'PR' },
  'sao sebastiao da amoreira': { name: 'São Sebastião da Amoreira', state: 'PR' },
  'sao tome': { name: 'São Tomé', state: 'PR' },
  sapopema: { name: 'Sapopema', state: 'PR' },
  sarandi: { name: 'Sarandi', state: 'PR' },
  'saudade do iguacu': { name: 'Saudade do Iguaçu', state: 'PR' },
  senges: { name: 'Sengés', state: 'PR' },
  'serranopolis do iguacu': { name: 'Serranópolis do Iguaçu', state: 'PR' },
  sertaneja: { name: 'Sertaneja', state: 'PR' },
  sertanopolis: { name: 'Sertanópolis', state: 'PR' },
  'siqueira campos': { name: 'Siqueira Campos', state: 'PR' },
  sulina: { name: 'Sulina', state: 'PR' },
  tamarana: { name: 'Tamarana', state: 'PR' },
  tamboara: { name: 'Tamboara', state: 'PR' },
  tapejara: { name: 'Tapejara', state: 'PR' },
  tapira_: { name: 'Tapira', state: 'PR' },
  'teixeira soares': { name: 'Teixeira Soares', state: 'PR' },
  'telemaco borba': { name: 'Telêmaco Borba', state: 'PR' },
  'terra boa': { name: 'Terra Boa', state: 'PR' },
  'terra rica': { name: 'Terra Rica', state: 'PR' },
  'terra roxa': { name: 'Terra Roxa', state: 'PR' },
  tibagi: { name: 'Tibagi', state: 'PR' },
  'tijucas do sul': { name: 'Tijucas do Sul', state: 'PR' },
  toledo_: { name: 'Toledo', state: 'PR' },
  tomazina: { name: 'Tomazina', state: 'PR' },
  'tres barras do parana': { name: 'Três Barras do Paraná', state: 'PR' },
  'tunas do parana': { name: 'Tunas do Paraná', state: 'PR' },
  'tuneiras do oeste': { name: 'Tuneiras do Oeste', state: 'PR' },
  tupassi: { name: 'Tupãssi', state: 'PR' },
  turvo: { name: 'Turvo', state: 'PR' },
  ubirata: { name: 'Ubiratã', state: 'PR' },
  umuarama: { name: 'Umuarama', state: 'PR' },
  'uniao da vitoria': { name: 'União da Vitória', state: 'PR' },
  uniflor: { name: 'Uniflor', state: 'PR' },
  urai: { name: 'Uraí', state: 'PR' },
  ventania: { name: 'Ventania', state: 'PR' },
  'vera cruz do oeste': { name: 'Vera Cruz do Oeste', state: 'PR' },
  vere: { name: 'Verê', state: 'PR' },
  virmond: { name: 'Virmond', state: 'PR' },
  vitorino: { name: 'Vitorino', state: 'PR' },
  'wenceslau braz_': { name: 'Wenceslau Braz', state: 'PR' },
  xambre: { name: 'Xambrê', state: 'PR' },
};
