export const cities = {
  'angra dos reis': 'Angra dos Reis',
  aperibe: 'Aperibé',
  araruama: 'Araruama',
  areal: 'Areal',
  'armacao dos buzios': 'Armação dos Búzios',
  'arraial do cabo': 'Arraial do Cabo',
  'barra do pirai': 'Barra do Piraí',
  'barra mansa': 'Barra Mansa',
  'belford roxo': 'Belford Roxo',
  'bom jardim__': 'Bom Jardim',
  'bom jesus do itabapoana': 'Bom Jesus do Itabapoana',
  'cabo frio': 'Cabo Frio',
  'cachoeiras de macacu': 'Cachoeiras de Macacu',
  cambuci: 'Cambuci',
  'campos dos goytacazes': 'Campos dos Goytacazes',
  cantagalo__: 'Cantagalo',
  carapebus: 'Carapebus',
  'cardoso moreira': 'Cardoso Moreira',
  carmo: 'Carmo',
  'casimiro de abreu': 'Casimiro de Abreu',
  'comendador levy gasparian': 'Comendador Levy Gasparian',
  'conceicao de macabu': 'Conceição de Macabu',
  cordeiro: 'Cordeiro',
  'duas barras': 'Duas Barras',
  'duque de caxias': 'Duque de Caxias',
  'engenheiro paulo de frontin': 'Engenheiro Paulo de Frontin',
  guapimirim: 'Guapimirim',
  'iguaba grande': 'Iguaba Grande',
  itaborai: 'Itaboraí',
  itaguai: 'Itaguaí',
  italva: 'Italva',
  itaocara: 'Itaocara',
  itaperuna: 'Itaperuna',
  itatiaia: 'Itatiaia',
  japeri: 'Japeri',
  'laje do muriae': 'Laje do Muriaé',
  macae: 'Macaé',
  macuco: 'Macuco',
  mage: 'Magé',
  mangaratiba: 'Mangaratiba',
  marica: 'Maricá',
  mendes: 'Mendes',
  mesquita_: 'Mesquita',
  'miguel pereira': 'Miguel Pereira',
  miracema: 'Miracema',
  natividade: 'Natividade',
  nilopolis: 'Nilópolis',
  niteroi: 'Niterói',
  'nova friburgo': 'Nova Friburgo',
  'nova iguacu': 'Nova Iguaçu',
  paracambi: 'Paracambi',
  'paraiba do sul': 'Paraíba do Sul',
  paraty: 'Paraty',
  'paty do alferes': 'Paty do Alferes',
  petropolis: 'Petrópolis',
  pinheiral: 'Pinheiral',
  pirai: 'Piraí',
  porciuncula: 'Porciúncula',
  'porto real': 'Porto Real',
  quatis: 'Quatis',
  queimados: 'Queimados',
  quissama: 'Quissamã',
  resende: 'Resende',
  'rio bonito': 'Rio Bonito',
  'rio claro': 'Rio Claro',
  'rio das flores': 'Rio das Flores',
  'rio das ostras': 'Rio das Ostras',
  'rio de janeiro': 'Rio de Janeiro',
  'santa maria madalena': 'Santa Maria Madalena',
  'santo antonio de padua': 'Santo Antônio de Pádua',
  'sao fidelis': 'São Fidélis',
  'sao francisco de itabapoana': 'São Francisco de Itabapoana',
  'sao goncalo': 'São Gonçalo',
  'sao joao da barra': 'São João da Barra',
  'sao joao de meriti': 'São João de Meriti',
  'sao jose de uba': 'São José de Ubá',
  'sao jose do vale do rio preto': 'São José do Vale do Rio Preto',
  'sao pedro da aldeia': 'São Pedro da Aldeia',
  'sao sebastiao do alto': 'São Sebastião do Alto',
  sapucaia_: 'Sapucaia',
  saquarema: 'Saquarema',
  seropedica: 'Seropédica',
  'silva jardim': 'Silva Jardim',
  sumidouro: 'Sumidouro',
  tangua: 'Tanguá',
  teresopolis: 'Teresópolis',
  'trajano de moraes': 'Trajano de Moraes',
  'tres rios': 'Três Rios',
  valenca_: 'Valença',
  'varre-sai': 'Varre-Sai',
  vassouras: 'Vassouras',
  'volta redonda': 'Volta Redonda',
};
