export const cities = {
  'angra dos reis': { name: 'Angra dos Reis', state: 'RJ' },
  aperibe: { name: 'Aperibé', state: 'RJ' },
  araruama: { name: 'Araruama', state: 'RJ' },
  areal: { name: 'Areal', state: 'RJ' },
  'armacao dos buzios': { name: 'Armação dos Búzios', state: 'RJ' },
  'arraial do cabo': { name: 'Arraial do Cabo', state: 'RJ' },
  'barra do pirai': { name: 'Barra do Piraí', state: 'RJ' },
  'barra mansa': { name: 'Barra Mansa', state: 'RJ' },
  'belford roxo': { name: 'Belford Roxo', state: 'RJ' },
  'bom jardim__': { name: 'Bom Jardim', state: 'RJ' },
  'bom jesus do itabapoana': { name: 'Bom Jesus do Itabapoana', state: 'RJ' },
  'cabo frio': { name: 'Cabo Frio', state: 'RJ' },
  'cachoeiras de macacu': { name: 'Cachoeiras de Macacu', state: 'RJ' },
  cambuci: { name: 'Cambuci', state: 'RJ' },
  'campos dos goytacazes': { name: 'Campos dos Goytacazes', state: 'RJ' },
  cantagalo__: { name: 'Cantagalo', state: 'RJ' },
  carapebus: { name: 'Carapebus', state: 'RJ' },
  'cardoso moreira': { name: 'Cardoso Moreira', state: 'RJ' },
  carmo: { name: 'Carmo', state: 'RJ' },
  'casimiro de abreu': { name: 'Casimiro de Abreu', state: 'RJ' },
  'comendador levy gasparian': { name: 'Comendador Levy Gasparian', state: 'RJ' },
  'conceicao de macabu': { name: 'Conceição de Macabu', state: 'RJ' },
  cordeiro: { name: 'Cordeiro', state: 'RJ' },
  'duas barras': { name: 'Duas Barras', state: 'RJ' },
  'duque de caxias': { name: 'Duque de Caxias', state: 'RJ' },
  'engenheiro paulo de frontin': { name: 'Engenheiro Paulo de Frontin', state: 'RJ' },
  guapimirim: { name: 'Guapimirim', state: 'RJ' },
  'iguaba grande': { name: 'Iguaba Grande', state: 'RJ' },
  itaborai: { name: 'Itaboraí', state: 'RJ' },
  itaguai: { name: 'Itaguaí', state: 'RJ' },
  italva: { name: 'Italva', state: 'RJ' },
  itaocara: { name: 'Itaocara', state: 'RJ' },
  itaperuna: { name: 'Itaperuna', state: 'RJ' },
  itatiaia: { name: 'Itatiaia', state: 'RJ' },
  japeri: { name: 'Japeri', state: 'RJ' },
  'laje do muriae': { name: 'Laje do Muriaé', state: 'RJ' },
  macae: { name: 'Macaé', state: 'RJ' },
  macuco: { name: 'Macuco', state: 'RJ' },
  mage: { name: 'Magé', state: 'RJ' },
  mangaratiba: { name: 'Mangaratiba', state: 'RJ' },
  marica: { name: 'Maricá', state: 'RJ' },
  mendes: { name: 'Mendes', state: 'RJ' },
  mesquita_: { name: 'Mesquita', state: 'RJ' },
  'miguel pereira': { name: 'Miguel Pereira', state: 'RJ' },
  miracema: { name: 'Miracema', state: 'RJ' },
  natividade: { name: 'Natividade', state: 'RJ' },
  nilopolis: { name: 'Nilópolis', state: 'RJ' },
  niteroi: { name: 'Niterói', state: 'RJ' },
  'nova friburgo': { name: 'Nova Friburgo', state: 'RJ' },
  'nova iguacu': { name: 'Nova Iguaçu', state: 'RJ' },
  paracambi: { name: 'Paracambi', state: 'RJ' },
  'paraiba do sul': { name: 'Paraíba do Sul', state: 'RJ' },
  paraty: { name: 'Paraty', state: 'RJ' },
  'paty do alferes': { name: 'Paty do Alferes', state: 'RJ' },
  petropolis: { name: 'Petrópolis', state: 'RJ' },
  pinheiral: { name: 'Pinheiral', state: 'RJ' },
  pirai: { name: 'Piraí', state: 'RJ' },
  porciuncula: { name: 'Porciúncula', state: 'RJ' },
  'porto real': { name: 'Porto Real', state: 'RJ' },
  quatis: { name: 'Quatis', state: 'RJ' },
  queimados: { name: 'Queimados', state: 'RJ' },
  quissama: { name: 'Quissamã', state: 'RJ' },
  resende: { name: 'Resende', state: 'RJ' },
  'rio bonito': { name: 'Rio Bonito', state: 'RJ' },
  'rio claro': { name: 'Rio Claro', state: 'RJ' },
  'rio das flores': { name: 'Rio das Flores', state: 'RJ' },
  'rio das ostras': { name: 'Rio das Ostras', state: 'RJ' },
  'rio de janeiro': { name: 'Rio de Janeiro', state: 'RJ' },
  'santa maria madalena': { name: 'Santa Maria Madalena', state: 'RJ' },
  'santo antonio de padua': { name: 'Santo Antônio de Pádua', state: 'RJ' },
  'sao fidelis': { name: 'São Fidélis', state: 'RJ' },
  'sao francisco de itabapoana': { name: 'São Francisco de Itabapoana', state: 'RJ' },
  'sao goncalo': { name: 'São Gonçalo', state: 'RJ' },
  'sao joao da barra': { name: 'São João da Barra', state: 'RJ' },
  'sao joao de meriti': { name: 'São João de Meriti', state: 'RJ' },
  'sao jose de uba': { name: 'São José de Ubá', state: 'RJ' },
  'sao jose do vale do rio preto': { name: 'São José do Vale do Rio Preto', state: 'RJ' },
  'sao pedro da aldeia': { name: 'São Pedro da Aldeia', state: 'RJ' },
  'sao sebastiao do alto': { name: 'São Sebastião do Alto', state: 'RJ' },
  sapucaia_: { name: 'Sapucaia', state: 'RJ' },
  saquarema: { name: 'Saquarema', state: 'RJ' },
  seropedica: { name: 'Seropédica', state: 'RJ' },
  'silva jardim': { name: 'Silva Jardim', state: 'RJ' },
  sumidouro: { name: 'Sumidouro', state: 'RJ' },
  tangua: { name: 'Tanguá', state: 'RJ' },
  teresopolis: { name: 'Teresópolis', state: 'RJ' },
  'trajano de moraes': { name: 'Trajano de Moraes', state: 'RJ' },
  'tres rios': { name: 'Três Rios', state: 'RJ' },
  valenca_: { name: 'Valença', state: 'RJ' },
  'varre-sai': { name: 'Varre-Sai', state: 'RJ' },
  vassouras: { name: 'Vassouras', state: 'RJ' },
  'volta redonda': { name: 'Volta Redonda', state: 'RJ' },
};
