export const cities = {
  acari: 'Acari',
  'afonso bezerra': 'Afonso Bezerra',
  'agua nova': 'Água Nova',
  alexandria: 'Alexandria',
  'almino afonso': 'Almino Afonso',
  'alto do rodrigues': 'Alto do Rodrigues',
  angicos: 'Angicos',
  'antonio martins': 'Antônio Martins',
  apodi: 'Apodi',
  'areia branca': 'Areia Branca',
  'arez (rio grande do norte)': 'Arez (Rio Grande do Norte)',
  assu: 'Assu',
  'baia formosa': 'Baía Formosa',
  barauna_: 'Baraúna',
  barcelona: 'Barcelona',
  'bento fernandes': 'Bento Fernandes',
  'boa saude': 'Boa Saúde',
  bodo: 'Bodó',
  'bom jesus__': 'Bom Jesus',
  brejinho_: 'Brejinho',
  'caicara do norte': 'Caiçara do Norte',
  'caicara do rio do vento': 'Caiçara do Rio do Vento',
  caico: 'Caicó',
  'campo grande__': 'Campo Grande',
  'campo redondo': 'Campo Redondo',
  canguaretama: 'Canguaretama',
  caraubas_: 'Caraúbas',
  'carnauba dos dantas': 'Carnaúba dos Dantas',
  carnaubais: 'Carnaubais',
  'ceara-mirim': 'Ceará-Mirim',
  'cerro cora': 'Cerro Corá',
  'coronel ezequiel': 'Coronel Ezequiel',
  'coronel joao pessoa': 'Coronel João Pessoa',
  cruzeta: 'Cruzeta',
  'currais novos': 'Currais Novos',
  'doutor severiano': 'Doutor Severiano',
  encanto: 'Encanto',
  equador: 'Equador',
  'espirito santo': 'Espírito Santo',
  extremoz: 'Extremoz',
  'felipe guerra': 'Felipe Guerra',
  'fernando pedroza': 'Fernando Pedroza',
  florania: 'Florânia',
  'francisco dantas': 'Francisco Dantas',
  'frutuoso gomes': 'Frutuoso Gomes',
  galinhos: 'Galinhos',
  goianinha: 'Goianinha',
  'governador dix-sept rosado': 'Governador Dix-Sept Rosado',
  grossos: 'Grossos',
  guamare: 'Guamaré',
  'ielmo marinho': 'Ielmo Marinho',
  ipanguacu: 'Ipanguaçu',
  ipueira: 'Ipueira',
  itaja_: 'Itajá',
  itau: 'Itaú',
  jacana: 'Jaçanã',
  jandaira_: 'Jandaíra',
  janduis: 'Janduís',
  japi: 'Japi',
  'jardim de angicos': 'Jardim de Angicos',
  'jardim de piranhas': 'Jardim de Piranhas',
  'jardim do serido': 'Jardim do Seridó',
  'joao camara': 'João Câmara',
  'joao dias': 'João Dias',
  'jose da penha': 'José da Penha',
  jucurutu: 'Jucurutu',
  jundia_: 'Jundiá',
  "lagoa d'anta": "Lagoa d'Anta",
  'lagoa de pedras': 'Lagoa de Pedras',
  'lagoa de velhos': 'Lagoa de Velhos',
  'lagoa nova': 'Lagoa Nova',
  'lagoa salgada': 'Lagoa Salgada',
  lajes: 'Lajes',
  'lajes pintadas': 'Lajes Pintadas',
  lucrecia: 'Lucrécia',
  'luis gomes': 'Luís Gomes',
  macaiba: 'Macaíba',
  macau: 'Macau',
  'major sales': 'Major Sales',
  'marcelino vieira': 'Marcelino Vieira',
  martins: 'Martins',
  maxaranguape: 'Maxaranguape',
  'messias targino': 'Messias Targino',
  montanhas: 'Montanhas',
  'monte alegre_': 'Monte Alegre',
  'monte das gameleiras': 'Monte das Gameleiras',
  mossoro: 'Mossoró',
  natal: 'Natal',
  'nisia floresta': 'Nísia Floresta',
  'nova cruz': 'Nova Cruz',
  "olho d'agua do borges": "Olho d'Água do Borges",
  'ouro branco__': 'Ouro Branco',
  parana: 'Paraná',
  parau: 'Paraú',
  parazinho: 'Parazinho',
  parelhas: 'Parelhas',
  parnamirim_: 'Parnamirim',
  'passa-e-fica': 'Passa-e-Fica',
  passagem_: 'Passagem',
  patu: 'Patu',
  'pau dos ferros': 'Pau dos Ferros',
  'pedra grande': 'Pedra Grande',
  'pedra preta_': 'Pedra Preta',
  'pedro avelino': 'Pedro Avelino',
  'pedro velho': 'Pedro Velho',
  pendencias: 'Pendências',
  piloes_: 'Pilões',
  'poco branco': 'Poço Branco',
  portalegre: 'Portalegre',
  'porto do mangue': 'Porto do Mangue',
  pureza: 'Pureza',
  'rafael fernandes': 'Rafael Fernandes',
  'rafael godeiro': 'Rafael Godeiro',
  'riacho da cruz': 'Riacho da Cruz',
  'riacho de santana_': 'Riacho de Santana',
  riachuelo: 'Riachuelo',
  'rio do fogo': 'Rio do Fogo',
  'rodolfo fernandes': 'Rodolfo Fernandes',
  'ruy barbosa_': 'Ruy Barbosa',
  'santa cruz__': 'Santa Cruz',
  'santa maria': 'Santa Maria',
  'santana do matos': 'Santana do Matos',
  'santana do serido': 'Santana do Seridó',
  'santo antonio': 'Santo Antônio',
  'sao bento do norte': 'São Bento do Norte',
  'sao bento do trairi': 'São Bento do Trairi',
  'sao fernando': 'São Fernando',
  'sao francisco do oeste': 'São Francisco do Oeste',
  'sao goncalo do amarante_': 'São Gonçalo do Amarante',
  'sao joao do sabugi': 'São João do Sabugi',
  'sao jose de mipibu': 'São José de Mipibu',
  'sao jose do campestre': 'São José do Campestre',
  'sao jose do serido': 'São José do Seridó',
  'sao miguel': 'São Miguel',
  'sao miguel do gostoso': 'São Miguel do Gostoso',
  'sao paulo do potengi': 'São Paulo do Potengi',
  'sao pedro': 'São Pedro',
  'sao rafael': 'São Rafael',
  'sao tome_': 'São Tomé',
  'sao vicente': 'São Vicente',
  'senador eloi de souza': 'Senador Elói de Souza',
  'senador georgino avelino': 'Senador Georgino Avelino',
  'serra caiada': 'Serra Caiada',
  'serra de sao bento': 'Serra de São Bento',
  'serra do mel': 'Serra do Mel',
  'serra negra do norte': 'Serra Negra do Norte',
  serrinha_: 'Serrinha',
  'serrinha dos pintos': 'Serrinha dos Pintos',
  'severiano melo': 'Severiano Melo',
  'sitio novo_': 'Sítio Novo',
  'taboleiro grande': 'Taboleiro Grande',
  taipu: 'Taipu',
  tangara: 'Tangará',
  'tenente ananias': 'Tenente Ananias',
  'tenente laurentino cruz': 'Tenente Laurentino Cruz',
  'tibau do sul': 'Tibau do Sul',
  tibau: 'Tibau',
  'timbauba dos batistas': 'Timbaúba dos Batistas',
  touros: 'Touros',
  'triunfo potiguar': 'Triunfo Potiguar',
  umarizal: 'Umarizal',
  upanema: 'Upanema',
  varzea_: 'Várzea',
  'venha-ver': 'Venha-Ver',
  'vera cruz_': 'Vera Cruz',
  vicosa__: 'Viçosa',
  'vila flor': 'Vila Flor',
};
