export const cities = {
  "alta floresta d'oeste": "Alta Floresta d'Oeste",
  'alto alegre dos parecis': 'Alto Alegre dos Parecis',
  'alto paraiso_': 'Alto Paraíso',
  "alvorada d'oeste": "Alvorada d'Oeste",
  ariquemes: 'Ariquemes',
  buritis_: 'Buritis',
  cabixi: 'Cabixi',
  cacaulandia: 'Cacaulândia',
  cacoal: 'Cacoal',
  'campo novo de rondonia': 'Campo Novo de Rondônia',
  'candeias do jamari': 'Candeias do Jamari',
  castanheiras: 'Castanheiras',
  cerejeiras: 'Cerejeiras',
  chupinguaia: 'Chupinguaia',
  'colorado do oeste': 'Colorado do Oeste',
  corumbiara: 'Corumbiara',
  'costa marques': 'Costa Marques',
  cujubim: 'Cujubim',
  "espigao d'oeste": "Espigão d'Oeste",
  'governador jorge teixeira': 'Governador Jorge Teixeira',
  'guajara-mirim': 'Guajará-Mirim',
  'itapua do oeste': 'Itapuã do Oeste',
  jaru: 'Jaru',
  'ji-parana': 'Ji-Paraná',
  "machadinho d'oeste": "Machadinho d'Oeste",
  'ministro andreazza': 'Ministro Andreazza',
  'mirante da serra': 'Mirante da Serra',
  'monte negro': 'Monte Negro',
  "nova brasilandia d'oeste": "Nova Brasilândia d'Oeste",
  'nova mamore': 'Nova Mamoré',
  'nova uniao_': 'Nova União',
  'novo horizonte do oeste': 'Novo Horizonte do Oeste',
  'ouro preto do oeste': 'Ouro Preto do Oeste',
  parecis: 'Parecis',
  'pimenta bueno': 'Pimenta Bueno',
  'pimenteiras do oeste': 'Pimenteiras do Oeste',
  'porto velho': 'Porto Velho',
  'presidente medici_': 'Presidente Médici',
  'primavera de rondonia': 'Primavera de Rondônia',
  'rio crespo': 'Rio Crespo',
  'rolim de moura': 'Rolim de Moura',
  "santa luzia d'oeste": "Santa Luzia d'Oeste",
  "sao felipe d'oeste": "São Felipe d'Oeste",
  'sao francisco do guapore': 'São Francisco do Guaporé',
  'sao miguel do guapore': 'São Miguel do Guaporé',
  seringueiras: 'Seringueiras',
  teixeiropolis: 'Teixeirópolis',
  theobroma: 'Theobroma',
  urupa: 'Urupá',
  'vale do anari': 'Vale do Anari',
  'vale do paraiso': 'Vale do Paraíso',
  vilhena: 'Vilhena',
};
