export const cities = {
  "alta floresta d'oeste": { name: "Alta Floresta d'Oeste", state: 'RO' },
  'alto alegre dos parecis': { name: 'Alto Alegre dos Parecis', state: 'RO' },
  'alto paraiso_': { name: 'Alto Paraíso', state: 'RO' },
  "alvorada d'oeste": { name: "Alvorada d'Oeste", state: 'RO' },
  ariquemes: { name: 'Ariquemes', state: 'RO' },
  buritis_: { name: 'Buritis', state: 'RO' },
  cabixi: { name: 'Cabixi', state: 'RO' },
  cacaulandia: { name: 'Cacaulândia', state: 'RO' },
  cacoal: { name: 'Cacoal', state: 'RO' },
  'campo novo de rondonia': { name: 'Campo Novo de Rondônia', state: 'RO' },
  'candeias do jamari': { name: 'Candeias do Jamari', state: 'RO' },
  castanheiras: { name: 'Castanheiras', state: 'RO' },
  cerejeiras: { name: 'Cerejeiras', state: 'RO' },
  chupinguaia: { name: 'Chupinguaia', state: 'RO' },
  'colorado do oeste': { name: 'Colorado do Oeste', state: 'RO' },
  corumbiara: { name: 'Corumbiara', state: 'RO' },
  'costa marques': { name: 'Costa Marques', state: 'RO' },
  cujubim: { name: 'Cujubim', state: 'RO' },
  "espigao d'oeste": { name: "Espigão d'Oeste", state: 'RO' },
  'governador jorge teixeira': { name: 'Governador Jorge Teixeira', state: 'RO' },
  'guajara-mirim': { name: 'Guajará-Mirim', state: 'RO' },
  'itapua do oeste': { name: 'Itapuã do Oeste', state: 'RO' },
  jaru: { name: 'Jaru', state: 'RO' },
  'ji-parana': { name: 'Ji-Paraná', state: 'RO' },
  "machadinho d'oeste": { name: "Machadinho d'Oeste", state: 'RO' },
  'ministro andreazza': { name: 'Ministro Andreazza', state: 'RO' },
  'mirante da serra': { name: 'Mirante da Serra', state: 'RO' },
  'monte negro': { name: 'Monte Negro', state: 'RO' },
  "nova brasilandia d'oeste": { name: "Nova Brasilândia d'Oeste", state: 'RO' },
  'nova mamore': { name: 'Nova Mamoré', state: 'RO' },
  'nova uniao_': { name: 'Nova União', state: 'RO' },
  'novo horizonte do oeste': { name: 'Novo Horizonte do Oeste', state: 'RO' },
  'ouro preto do oeste': { name: 'Ouro Preto do Oeste', state: 'RO' },
  parecis: { name: 'Parecis', state: 'RO' },
  'pimenta bueno': { name: 'Pimenta Bueno', state: 'RO' },
  'pimenteiras do oeste': { name: 'Pimenteiras do Oeste', state: 'RO' },
  'porto velho': { name: 'Porto Velho', state: 'RO' },
  'presidente medici_': { name: 'Presidente Médici', state: 'RO' },
  'primavera de rondonia': { name: 'Primavera de Rondônia', state: 'RO' },
  'rio crespo': { name: 'Rio Crespo', state: 'RO' },
  'rolim de moura': { name: 'Rolim de Moura', state: 'RO' },
  "santa luzia d'oeste": { name: "Santa Luzia d'Oeste", state: 'RO' },
  "sao felipe d'oeste": { name: "São Felipe d'Oeste", state: 'RO' },
  'sao francisco do guapore': { name: 'São Francisco do Guaporé', state: 'RO' },
  'sao miguel do guapore': { name: 'São Miguel do Guaporé', state: 'RO' },
  seringueiras: { name: 'Seringueiras', state: 'RO' },
  teixeiropolis: { name: 'Teixeirópolis', state: 'RO' },
  theobroma: { name: 'Theobroma', state: 'RO' },
  urupa: { name: 'Urupá', state: 'RO' },
  'vale do anari': { name: 'Vale do Anari', state: 'RO' },
  'vale do paraiso': { name: 'Vale do Paraíso', state: 'RO' },
  vilhena: { name: 'Vilhena', state: 'RO' },
};
