export const cities = {
  'alto alegre': 'Alto Alegre',
  amajari: 'Amajari',
  'boa vista_': 'Boa Vista',
  bonfim_: 'Bonfim',
  canta: 'Cantá',
  caracarai: 'Caracaraí',
  caroebe: 'Caroebe',
  iracema_: 'Iracema',
  mucajai: 'Mucajaí',
  normandia: 'Normandia',
  pacaraima: 'Pacaraima',
  rorainopolis: 'Rorainópolis',
  'sao joao da baliza': 'São João da Baliza',
  'sao luiz': 'São Luiz',
  uiramuta: 'Uiramutã',
};
