export const cities = {
  acegua: 'Aceguá',
  'agua santa': 'Água Santa',
  agudo: 'Agudo',
  ajuricaba: 'Ajuricaba',
  alecrim: 'Alecrim',
  alegrete: 'Alegrete',
  alegria: 'Alegria',
  'almirante tamandare do sul': 'Almirante Tamandaré do Sul',
  alpestre: 'Alpestre',
  'alto alegre_': 'Alto Alegre',
  'alto feliz': 'Alto Feliz',
  alvorada: 'Alvorada',
  'amaral ferrador': 'Amaral Ferrador',
  'ametista do sul': 'Ametista do Sul',
  'andre da rocha': 'André da Rocha',
  'anta gorda': 'Anta Gorda',
  'antonio prado': 'Antônio Prado',
  arambare: 'Arambaré',
  ararica: 'Araricá',
  aratiba: 'Aratiba',
  'arroio do meio': 'Arroio do Meio',
  'arroio do padre': 'Arroio do Padre',
  'arroio do sal': 'Arroio do Sal',
  'arroio dos ratos': 'Arroio dos Ratos',
  'arroio do tigre': 'Arroio do Tigre',
  'arroio grande': 'Arroio Grande',
  arvorezinha: 'Arvorezinha',
  'augusto pestana': 'Augusto Pestana',
  aurea: 'Áurea',
  bage: 'Bagé',
  'balneario pinhal': 'Balneário Pinhal',
  barao: 'Barão',
  'barao de cotegipe': 'Barão de Cotegipe',
  'barao do triunfo': 'Barão do Triunfo',
  barracao_: 'Barracão',
  'barra do guarita': 'Barra do Guarita',
  'barra do quarai': 'Barra do Quaraí',
  'barra do ribeiro': 'Barra do Ribeiro',
  'barra do rio azul': 'Barra do Rio Azul',
  'barra funda': 'Barra Funda',
  'barros cassal': 'Barros Cassal',
  'benjamin constant do sul': 'Benjamin Constant do Sul',
  'bento goncalves': 'Bento Gonçalves',
  'boa vista das missoes': 'Boa Vista das Missões',
  'boa vista do burica': 'Boa Vista do Buricá',
  'boa vista do cadeado': 'Boa Vista do Cadeado',
  'boa vista do incra': 'Boa Vista do Incra',
  'boa vista do sul': 'Boa Vista do Sul',
  'bom jesus___': 'Bom Jesus',
  'bom principio': 'Bom Princípio',
  'bom progresso': 'Bom Progresso',
  'bom retiro do sul': 'Bom Retiro do Sul',
  'boqueirao do leao': 'Boqueirão do Leão',
  bossoroca: 'Bossoroca',
  bozano: 'Bozano',
  braga: 'Braga',
  brochier: 'Brochier',
  butia: 'Butiá',
  'cacapava do sul': 'Caçapava do Sul',
  cacequi: 'Cacequi',
  'cachoeira do sul': 'Cachoeira do Sul',
  cachoeirinha_: 'Cachoeirinha',
  'cacique doble': 'Cacique Doble',
  caibate: 'Caibaté',
  caicara_: 'Caiçara',
  camaqua: 'Camaquã',
  camargo: 'Camargo',
  'cambara do sul': 'Cambará do Sul',
  'campestre da serra': 'Campestre da Serra',
  'campina das missoes': 'Campina das Missões',
  'campinas do sul': 'Campinas do Sul',
  'campo bom': 'Campo Bom',
  'campo novo': 'Campo Novo',
  'campos borges': 'Campos Borges',
  candelaria: 'Candelária',
  'candido godoi': 'Cândido Godói',
  candiota: 'Candiota',
  canela: 'Canela',
  cangucu: 'Canguçu',
  canoas: 'Canoas',
  'canudos do vale': 'Canudos do Vale',
  'capao bonito do sul': 'Capão Bonito do Sul',
  'capao da canoa': 'Capão da Canoa',
  'capao do cipo': 'Capão do Cipó',
  'capao do leao': 'Capão do Leão',
  'capela de santana': 'Capela de Santana',
  capitao: 'Capitão',
  'capivari do sul': 'Capivari do Sul',
  caraa: 'Caraá',
  carazinho: 'Carazinho',
  'carlos barbosa': 'Carlos Barbosa',
  'carlos gomes': 'Carlos Gomes',
  casca: 'Casca',
  caseiros: 'Caseiros',
  catuipe: 'Catuípe',
  'caxias do sul': 'Caxias do Sul',
  centenario: 'Centenário',
  cerrito: 'Cerrito',
  'cerro branco': 'Cerro Branco',
  'cerro grande': 'Cerro Grande',
  'cerro grande do sul': 'Cerro Grande do Sul',
  'cerro largo': 'Cerro Largo',
  chapada: 'Chapada',
  charqueadas: 'Charqueadas',
  charrua: 'Charrua',
  chiapetta: 'Chiapetta',
  chui: 'Chuí',
  chuvisca: 'Chuvisca',
  cidreira: 'Cidreira',
  ciriaco: 'Ciríaco',
  colinas_: 'Colinas',
  colorado_: 'Colorado',
  condor: 'Condor',
  constantina: 'Constantina',
  'coqueiro baixo': 'Coqueiro Baixo',
  'coqueiros do sul': 'Coqueiros do Sul',
  'coronel barros': 'Coronel Barros',
  'coronel bicaco': 'Coronel Bicaco',
  'coronel pilar': 'Coronel Pilar',
  cotipora: 'Cotiporã',
  coxilha: 'Coxilha',
  crissiumal: 'Crissiumal',
  cristal: 'Cristal',
  'cristal do sul': 'Cristal do Sul',
  'cruz alta': 'Cruz Alta',
  cruzaltense: 'Cruzaltense',
  'cruzeiro do sul__': 'Cruzeiro do Sul',
  'david canabarro': 'David Canabarro',
  derrubadas: 'Derrubadas',
  'dezesseis de novembro': 'Dezesseis de Novembro',
  'dilermando de aguiar': 'Dilermando de Aguiar',
  'dois irmaos': 'Dois Irmãos',
  'dois irmaos das missoes': 'Dois Irmãos das Missões',
  'dois lajeados': 'Dois Lajeados',
  'dom feliciano': 'Dom Feliciano',
  'dom pedrito': 'Dom Pedrito',
  'dom pedro de alcantara': 'Dom Pedro de Alcântara',
  'dona francisca': 'Dona Francisca',
  'doutor mauricio cardoso': 'Doutor Maurício Cardoso',
  'doutor ricardo': 'Doutor Ricardo',
  'eldorado do sul': 'Eldorado do Sul',
  encantado: 'Encantado',
  'encruzilhada do sul': 'Encruzilhada do Sul',
  'engenho velho': 'Engenho Velho',
  'entre ijuis': 'Entre Ijuís',
  'entre rios do sul': 'Entre Rios do Sul',
  erebango: 'Erebango',
  erechim: 'Erechim',
  ernestina: 'Ernestina',
  'erval grande': 'Erval Grande',
  'erval seco': 'Erval Seco',
  esmeralda: 'Esmeralda',
  'esperanca do sul': 'Esperança do Sul',
  espumoso: 'Espumoso',
  estacao: 'Estação',
  'estancia velha': 'Estância Velha',
  esteio: 'Esteio',
  estrela: 'Estrela',
  'estrela velha': 'Estrela Velha',
  'eugenio de castro': 'Eugênio de Castro',
  'fagundes varela': 'Fagundes Varela',
  farroupilha: 'Farroupilha',
  'faxinal do soturno': 'Faxinal do Soturno',
  faxinalzinho: 'Faxinalzinho',
  'fazenda vilanova': 'Fazenda Vilanova',
  feliz: 'Feliz',
  'flores da cunha': 'Flores da Cunha',
  'floriano peixoto': 'Floriano Peixoto',
  'fontoura xavier': 'Fontoura Xavier',
  formigueiro: 'Formigueiro',
  forquetinha: 'Forquetinha',
  'fortaleza dos valos': 'Fortaleza dos Valos',
  'frederico westphalen': 'Frederico Westphalen',
  garibaldi: 'Garibaldi',
  garruchos: 'Garruchos',
  gaurama: 'Gaurama',
  'general camara': 'General Câmara',
  gentil: 'Gentil',
  'getulio vargas': 'Getúlio Vargas',
  girua: 'Giruá',
  glorinha: 'Glorinha',
  gramado: 'Gramado',
  'gramado dos loureiros': 'Gramado dos Loureiros',
  'gramado xavier': 'Gramado Xavier',
  gravatai: 'Gravataí',
  guabiju: 'Guabiju',
  guaiba: 'Guaíba',
  guapore: 'Guaporé',
  'guarani das missoes': 'Guarani das Missões',
  harmonia: 'Harmonia',
  herval: 'Herval',
  herveiras: 'Herveiras',
  horizontina: 'Horizontina',
  'hulha negra': 'Hulha Negra',
  humaita_: 'Humaitá',
  ibarama: 'Ibarama',
  ibiaca: 'Ibiaçá',
  ibiraiaras: 'Ibiraiaras',
  ibirapuita: 'Ibirapuitã',
  ibiruba: 'Ibirubá',
  igrejinha: 'Igrejinha',
  ijui: 'Ijuí',
  ilopolis: 'Ilópolis',
  imbe: 'Imbé',
  imigrante: 'Imigrante',
  independencia_: 'Independência',
  inhacora: 'Inhacorá',
  ipe: 'Ipê',
  'ipiranga do sul': 'Ipiranga do Sul',
  irai: 'Iraí',
  itaara: 'Itaara',
  itacurubi: 'Itacurubi',
  itapuca: 'Itapuca',
  itaqui: 'Itaqui',
  itati: 'Itati',
  'itatiba do sul': 'Itatiba do Sul',
  ivora: 'Ivorá',
  ivoti: 'Ivoti',
  jaboticaba: 'Jaboticaba',
  jacuizinho: 'Jacuizinho',
  jacutinga_: 'Jacutinga',
  jaguarao: 'Jaguarão',
  jaguari: 'Jaguari',
  jaquirana: 'Jaquirana',
  jari: 'Jari',
  joia: 'Jóia',
  'julio de castilhos': 'Júlio de Castilhos',
  'lagoa bonita do sul': 'Lagoa Bonita do Sul',
  'lagoa dos tres cantos': 'Lagoa dos Três Cantos',
  lagoao: 'Lagoão',
  'lagoa vermelha': 'Lagoa Vermelha',
  lajeado: 'Lajeado',
  'lajeado do bugre': 'Lajeado do Bugre',
  'lavras do sul': 'Lavras do Sul',
  'liberato salzano': 'Liberato Salzano',
  'lindolfo collor': 'Lindolfo Collor',
  'linha nova': 'Linha Nova',
  macambara: 'Maçambará',
  machadinho: 'Machadinho',
  mampituba: 'Mampituba',
  'manoel viana': 'Manoel Viana',
  maquine: 'Maquiné',
  marata: 'Maratá',
  marau_: 'Marau',
  'marcelino ramos': 'Marcelino Ramos',
  'mariana pimentel': 'Mariana Pimentel',
  'mariano moro': 'Mariano Moro',
  'marques de souza': 'Marques de Souza',
  mata: 'Mata',
  'mato castelhano': 'Mato Castelhano',
  'mato leitao': 'Mato Leitão',
  'mato queimado': 'Mato Queimado',
  'maximiliano de almeida': 'Maximiliano de Almeida',
  'minas do leao': 'Minas do Leão',
  miraguai: 'Miraguaí',
  montauri: 'Montauri',
  'monte alegre dos campos': 'Monte Alegre dos Campos',
  'monte belo do sul': 'Monte Belo do Sul',
  montenegro: 'Montenegro',
  mormaco: 'Mormaço',
  'morrinhos do sul': 'Morrinhos do Sul',
  'morro redondo': 'Morro Redondo',
  'morro reuter': 'Morro Reuter',
  mostardas: 'Mostardas',
  mucum: 'Muçum',
  'muitos capoes': 'Muitos Capões',
  muliterno: 'Muliterno',
  'nao-me-toque': 'Não-Me-Toque',
  'nicolau vergueiro': 'Nicolau Vergueiro',
  nonoai: 'Nonoai',
  'nova alvorada': 'Nova Alvorada',
  'nova araca': 'Nova Araçá',
  'nova bassano': 'Nova Bassano',
  'nova boa vista': 'Nova Boa Vista',
  'nova brescia': 'Nova Bréscia',
  'nova candelaria': 'Nova Candelária',
  'nova esperanca do sul': 'Nova Esperança do Sul',
  'nova hartz': 'Nova Hartz',
  'nova padua': 'Nova Pádua',
  'nova palma': 'Nova Palma',
  'nova petropolis': 'Nova Petrópolis',
  'nova prata': 'Nova Prata',
  'nova ramada': 'Nova Ramada',
  'nova roma do sul': 'Nova Roma do Sul',
  'nova santa rita_': 'Nova Santa Rita',
  'novo barreiro': 'Novo Barreiro',
  'novo cabrais': 'Novo Cabrais',
  'novo hamburgo': 'Novo Hamburgo',
  'novo machado': 'Novo Machado',
  'novo tiradentes': 'Novo Tiradentes',
  'novo xingu': 'Novo Xingu',
  osorio: 'Osório',
  'paim filho': 'Paim Filho',
  'palmares do sul': 'Palmares do Sul',
  'palmeira das missoes': 'Palmeira das Missões',
  palmitinho: 'Palmitinho',
  panambi: 'Panambi',
  'pantano grande': 'Pantano Grande',
  parai: 'Paraí',
  'paraiso do sul': 'Paraíso do Sul',
  'pareci novo': 'Pareci Novo',
  parobe: 'Parobé',
  'passa-sete': 'Passa-Sete',
  'passo do sobrado': 'Passo do Sobrado',
  'passo fundo': 'Passo Fundo',
  'paulo bento': 'Paulo Bento',
  paverama: 'Paverama',
  'pedras altas': 'Pedras Altas',
  'pedro osorio': 'Pedro Osório',
  pejucara: 'Pejuçara',
  pelotas: 'Pelotas',
  'picada cafe': 'Picada Café',
  pinhal: 'Pinhal',
  'pinhal da serra': 'Pinhal da Serra',
  'pinhal grande': 'Pinhal Grande',
  'pinheirinho do vale': 'Pinheirinho do Vale',
  'pinheiro machado': 'Pinheiro Machado',
  'pinto bandeira': 'Pinto Bandeira',
  pirapo: 'Pirapó',
  piratini: 'Piratini',
  planalto__: 'Planalto',
  'poco das antas': 'Poço das Antas',
  pontao: 'Pontão',
  'ponte preta': 'Ponte Preta',
  portao: 'Portão',
  'porto alegre': 'Porto Alegre',
  'porto lucena': 'Porto Lucena',
  'porto maua': 'Porto Mauá',
  'porto vera cruz': 'Porto Vera Cruz',
  'porto xavier': 'Porto Xavier',
  'pouso novo': 'Pouso Novo',
  'presidente lucena': 'Presidente Lucena',
  progresso: 'Progresso',
  'protasio alves': 'Protásio Alves',
  putinga: 'Putinga',
  quarai: 'Quaraí',
  'quatro irmaos': 'Quatro Irmãos',
  quevedos: 'Quevedos',
  'quinze de novembro': 'Quinze de Novembro',
  redentora: 'Redentora',
  relvado: 'Relvado',
  'restinga seca': 'Restinga Sêca',
  'rio dos indios': 'Rio dos Índios',
  'rio grande': 'Rio Grande',
  'rio pardo': 'Rio Pardo',
  riozinho: 'Riozinho',
  'roca sales': 'Roca Sales',
  'rodeio bonito': 'Rodeio Bonito',
  rolador: 'Rolador',
  rolante: 'Rolante',
  'ronda alta': 'Ronda Alta',
  rondinha: 'Rondinha',
  'roque gonzales': 'Roque Gonzales',
  'rosario do sul': 'Rosário do Sul',
  'sagrada familia': 'Sagrada Família',
  'saldanha marinho': 'Saldanha Marinho',
  'salto do jacui': 'Salto do Jacuí',
  'salvador das missoes': 'Salvador das Missões',
  'salvador do sul': 'Salvador do Sul',
  sananduva: 'Sananduva',
  'santa barbara do sul': 'Santa Bárbara do Sul',
  'santa cecilia do sul': 'Santa Cecília do Sul',
  'santa clara do sul': 'Santa Clara do Sul',
  'santa cruz do sul': 'Santa Cruz do Sul',
  'santa margarida do sul': 'Santa Margarida do Sul',
  'santa maria_': 'Santa Maria',
  'santa maria do herval': 'Santa Maria do Herval',
  'santana da boa vista': 'Santana da Boa Vista',
  "sant'ana do livramento": "Sant'Ana do Livramento",
  'santa rosa': 'Santa Rosa',
  'santa tereza': 'Santa Tereza',
  'santa vitoria do palmar': 'Santa Vitória do Palmar',
  santiago: 'Santiago',
  'santo angelo': 'Santo Ângelo',
  'santo antonio da patrulha': 'Santo Antônio da Patrulha',
  'santo antonio das missoes': 'Santo Antônio das Missões',
  'santo antonio do palma': 'Santo Antônio do Palma',
  'santo antonio do planalto': 'Santo Antônio do Planalto',
  'santo augusto': 'Santo Augusto',
  'santo cristo': 'Santo Cristo',
  'santo expedito do sul': 'Santo Expedito do Sul',
  'sao borja': 'São Borja',
  'sao domingos do sul': 'São Domingos do Sul',
  'sao francisco de assis': 'São Francisco de Assis',
  'sao francisco de paula_': 'São Francisco de Paula',
  'sao gabriel_': 'São Gabriel',
  'sao jeronimo': 'São Jerônimo',
  'sao joao da urtiga': 'São João da Urtiga',
  'sao joao do polesine': 'São João do Polêsine',
  'sao jorge': 'São Jorge',
  'sao jose das missoes': 'São José das Missões',
  'sao jose do herval': 'São José do Herval',
  'sao jose do hortencio': 'São José do Hortêncio',
  'sao jose do inhacora': 'São José do Inhacorá',
  'sao jose do norte': 'São José do Norte',
  'sao jose do ouro': 'São José do Ouro',
  'sao jose dos ausentes': 'São José dos Ausentes',
  'sao jose do sul': 'São José do Sul',
  'sao leopoldo': 'São Leopoldo',
  'sao lourenco do sul': 'São Lourenço do Sul',
  'sao luiz gonzaga': 'São Luiz Gonzaga',
  'sao marcos': 'São Marcos',
  'sao martinho': 'São Martinho',
  'sao martinho da serra': 'São Martinho da Serra',
  'sao miguel das missoes': 'São Miguel das Missões',
  'sao nicolau': 'São Nicolau',
  'sao paulo das missoes': 'São Paulo das Missões',
  'sao pedro da serra': 'São Pedro da Serra',
  'sao pedro das missoes': 'São Pedro das Missões',
  'sao pedro do butia': 'São Pedro do Butiá',
  'sao pedro do sul': 'São Pedro do Sul',
  'sao sebastiao do cai': 'São Sebastião do Caí',
  'sao sepe': 'São Sepé',
  'sao valentim': 'São Valentim',
  'sao valentim do sul': 'São Valentim do Sul',
  'sao valerio do sul': 'São Valério do Sul',
  'sao vendelino': 'São Vendelino',
  'sao vicente do sul': 'São Vicente do Sul',
  sapiranga: 'Sapiranga',
  'sapucaia do sul': 'Sapucaia do Sul',
  sarandi_: 'Sarandi',
  seberi: 'Seberi',
  'sede nova': 'Sede Nova',
  segredo: 'Segredo',
  selbach: 'Selbach',
  'senador salgado filho': 'Senador Salgado Filho',
  'sentinela do sul': 'Sentinela do Sul',
  'serafina correa': 'Serafina Corrêa',
  serio: 'Sério',
  sertao: 'Sertão',
  'sertao santana': 'Sertão Santana',
  'sete de setembro': 'Sete de Setembro',
  'severiano de almeida': 'Severiano de Almeida',
  'silveira martins': 'Silveira Martins',
  sinimbu: 'Sinimbu',
  sobradinho_: 'Sobradinho',
  soledade_: 'Soledade',
  tabai: 'Tabaí',
  tapejara_: 'Tapejara',
  tapera: 'Tapera',
  tapes: 'Tapes',
  taquara: 'Taquara',
  taquari: 'Taquari',
  'taquarucu do sul': 'Taquaruçu do Sul',
  tavares_: 'Tavares',
  'tenente portela': 'Tenente Portela',
  'terra de areia': 'Terra de Areia',
  teutonia: 'Teutônia',
  'tio hugo': 'Tio Hugo',
  'tiradentes do sul': 'Tiradentes do Sul',
  toropi: 'Toropi',
  torres: 'Torres',
  tramandai: 'Tramandaí',
  travesseiro: 'Travesseiro',
  'tres arroios': 'Três Arroios',
  'tres cachoeiras': 'Três Cachoeiras',
  'tres coroas': 'Três Coroas',
  'tres de maio': 'Três de Maio',
  'tres forquilhas': 'Três Forquilhas',
  'tres palmeiras': 'Três Palmeiras',
  'tres passos': 'Três Passos',
  'trindade do sul': 'Trindade do Sul',
  triunfo__: 'Triunfo',
  tucunduva: 'Tucunduva',
  tunas: 'Tunas',
  'tupanci do sul': 'Tupanci do Sul',
  tupancireta: 'Tupanciretã',
  tupandi: 'Tupandi',
  tuparendi: 'Tuparendi',
  turucu: 'Turuçu',
  ubiretama: 'Ubiretama',
  'uniao da serra': 'União da Serra',
  unistalda: 'Unistalda',
  uruguaiana: 'Uruguaiana',
  vacaria: 'Vacaria',
  'vale do sol': 'Vale do Sol',
  'vale real': 'Vale Real',
  'vale verde': 'Vale Verde',
  vanini: 'Vanini',
  'venancio aires': 'Venâncio Aires',
  'vera cruz__': 'Vera Cruz',
  veranopolis: 'Veranópolis',
  'vespasiano correa': 'Vespasiano Corrêa',
  viadutos: 'Viadutos',
  viamao: 'Viamão',
  'vicente dutra': 'Vicente Dutra',
  'victor graeff': 'Victor Graeff',
  'vila flores': 'Vila Flores',
  'vila langaro': 'Vila Lângaro',
  'vila maria': 'Vila Maria',
  'vila nova do sul': 'Vila Nova do Sul',
  'vista alegre': 'Vista Alegre',
  'vista alegre do prata': 'Vista Alegre do Prata',
  'vista gaucha': 'Vista Gaúcha',
  'vitoria das missoes': 'Vitória das Missões',
  westfalia: 'Westfália',
  'xangri-la': 'Xangri-lá',
};
