export const cities = {
  acegua: { name: 'Aceguá', state: 'RS' },
  'agua santa': { name: 'Água Santa', state: 'RS' },
  agudo: { name: 'Agudo', state: 'RS' },
  ajuricaba: { name: 'Ajuricaba', state: 'RS' },
  alecrim: { name: 'Alecrim', state: 'RS' },
  alegrete: { name: 'Alegrete', state: 'RS' },
  alegria: { name: 'Alegria', state: 'RS' },
  'almirante tamandare do sul': { name: 'Almirante Tamandaré do Sul', state: 'RS' },
  alpestre: { name: 'Alpestre', state: 'RS' },
  'alto alegre_': { name: 'Alto Alegre', state: 'RS' },
  'alto feliz': { name: 'Alto Feliz', state: 'RS' },
  alvorada: { name: 'Alvorada', state: 'RS' },
  'amaral ferrador': { name: 'Amaral Ferrador', state: 'RS' },
  'ametista do sul': { name: 'Ametista do Sul', state: 'RS' },
  'andre da rocha': { name: 'André da Rocha', state: 'RS' },
  'anta gorda': { name: 'Anta Gorda', state: 'RS' },
  'antonio prado': { name: 'Antônio Prado', state: 'RS' },
  arambare: { name: 'Arambaré', state: 'RS' },
  ararica: { name: 'Araricá', state: 'RS' },
  aratiba: { name: 'Aratiba', state: 'RS' },
  'arroio do meio': { name: 'Arroio do Meio', state: 'RS' },
  'arroio do padre': { name: 'Arroio do Padre', state: 'RS' },
  'arroio do sal': { name: 'Arroio do Sal', state: 'RS' },
  'arroio dos ratos': { name: 'Arroio dos Ratos', state: 'RS' },
  'arroio do tigre': { name: 'Arroio do Tigre', state: 'RS' },
  'arroio grande': { name: 'Arroio Grande', state: 'RS' },
  arvorezinha: { name: 'Arvorezinha', state: 'RS' },
  'augusto pestana': { name: 'Augusto Pestana', state: 'RS' },
  aurea: { name: 'Áurea', state: 'RS' },
  bage: { name: 'Bagé', state: 'RS' },
  'balneario pinhal': { name: 'Balneário Pinhal', state: 'RS' },
  barao: { name: 'Barão', state: 'RS' },
  'barao de cotegipe': { name: 'Barão de Cotegipe', state: 'RS' },
  'barao do triunfo': { name: 'Barão do Triunfo', state: 'RS' },
  barracao_: { name: 'Barracão', state: 'RS' },
  'barra do guarita': { name: 'Barra do Guarita', state: 'RS' },
  'barra do quarai': { name: 'Barra do Quaraí', state: 'RS' },
  'barra do ribeiro': { name: 'Barra do Ribeiro', state: 'RS' },
  'barra do rio azul': { name: 'Barra do Rio Azul', state: 'RS' },
  'barra funda': { name: 'Barra Funda', state: 'RS' },
  'barros cassal': { name: 'Barros Cassal', state: 'RS' },
  'benjamin constant do sul': { name: 'Benjamin Constant do Sul', state: 'RS' },
  'bento goncalves': { name: 'Bento Gonçalves', state: 'RS' },
  'boa vista das missoes': { name: 'Boa Vista das Missões', state: 'RS' },
  'boa vista do burica': { name: 'Boa Vista do Buricá', state: 'RS' },
  'boa vista do cadeado': { name: 'Boa Vista do Cadeado', state: 'RS' },
  'boa vista do incra': { name: 'Boa Vista do Incra', state: 'RS' },
  'boa vista do sul': { name: 'Boa Vista do Sul', state: 'RS' },
  'bom jesus___': { name: 'Bom Jesus', state: 'RS' },
  'bom principio': { name: 'Bom Princípio', state: 'RS' },
  'bom progresso': { name: 'Bom Progresso', state: 'RS' },
  'bom retiro do sul': { name: 'Bom Retiro do Sul', state: 'RS' },
  'boqueirao do leao': { name: 'Boqueirão do Leão', state: 'RS' },
  bossoroca: { name: 'Bossoroca', state: 'RS' },
  bozano: { name: 'Bozano', state: 'RS' },
  braga: { name: 'Braga', state: 'RS' },
  brochier: { name: 'Brochier', state: 'RS' },
  butia: { name: 'Butiá', state: 'RS' },
  'cacapava do sul': { name: 'Caçapava do Sul', state: 'RS' },
  cacequi: { name: 'Cacequi', state: 'RS' },
  'cachoeira do sul': { name: 'Cachoeira do Sul', state: 'RS' },
  cachoeirinha_: { name: 'Cachoeirinha', state: 'RS' },
  'cacique doble': { name: 'Cacique Doble', state: 'RS' },
  caibate: { name: 'Caibaté', state: 'RS' },
  caicara_: { name: 'Caiçara', state: 'RS' },
  camaqua: { name: 'Camaquã', state: 'RS' },
  camargo: { name: 'Camargo', state: 'RS' },
  'cambara do sul': { name: 'Cambará do Sul', state: 'RS' },
  'campestre da serra': { name: 'Campestre da Serra', state: 'RS' },
  'campina das missoes': { name: 'Campina das Missões', state: 'RS' },
  'campinas do sul': { name: 'Campinas do Sul', state: 'RS' },
  'campo bom': { name: 'Campo Bom', state: 'RS' },
  'campo novo': { name: 'Campo Novo', state: 'RS' },
  'campos borges': { name: 'Campos Borges', state: 'RS' },
  candelaria: { name: 'Candelária', state: 'RS' },
  'candido godoi': { name: 'Cândido Godói', state: 'RS' },
  candiota: { name: 'Candiota', state: 'RS' },
  canela: { name: 'Canela', state: 'RS' },
  cangucu: { name: 'Canguçu', state: 'RS' },
  canoas: { name: 'Canoas', state: 'RS' },
  'canudos do vale': { name: 'Canudos do Vale', state: 'RS' },
  'capao bonito do sul': { name: 'Capão Bonito do Sul', state: 'RS' },
  'capao da canoa': { name: 'Capão da Canoa', state: 'RS' },
  'capao do cipo': { name: 'Capão do Cipó', state: 'RS' },
  'capao do leao': { name: 'Capão do Leão', state: 'RS' },
  'capela de santana': { name: 'Capela de Santana', state: 'RS' },
  capitao: { name: 'Capitão', state: 'RS' },
  'capivari do sul': { name: 'Capivari do Sul', state: 'RS' },
  caraa: { name: 'Caraá', state: 'RS' },
  carazinho: { name: 'Carazinho', state: 'RS' },
  'carlos barbosa': { name: 'Carlos Barbosa', state: 'RS' },
  'carlos gomes': { name: 'Carlos Gomes', state: 'RS' },
  casca: { name: 'Casca', state: 'RS' },
  caseiros: { name: 'Caseiros', state: 'RS' },
  catuipe: { name: 'Catuípe', state: 'RS' },
  'caxias do sul': { name: 'Caxias do Sul', state: 'RS' },
  centenario: { name: 'Centenário', state: 'RS' },
  cerrito: { name: 'Cerrito', state: 'RS' },
  'cerro branco': { name: 'Cerro Branco', state: 'RS' },
  'cerro grande': { name: 'Cerro Grande', state: 'RS' },
  'cerro grande do sul': { name: 'Cerro Grande do Sul', state: 'RS' },
  'cerro largo': { name: 'Cerro Largo', state: 'RS' },
  chapada: { name: 'Chapada', state: 'RS' },
  charqueadas: { name: 'Charqueadas', state: 'RS' },
  charrua: { name: 'Charrua', state: 'RS' },
  chiapetta: { name: 'Chiapetta', state: 'RS' },
  chui: { name: 'Chuí', state: 'RS' },
  chuvisca: { name: 'Chuvisca', state: 'RS' },
  cidreira: { name: 'Cidreira', state: 'RS' },
  ciriaco: { name: 'Ciríaco', state: 'RS' },
  colinas_: { name: 'Colinas', state: 'RS' },
  colorado_: { name: 'Colorado', state: 'RS' },
  condor: { name: 'Condor', state: 'RS' },
  constantina: { name: 'Constantina', state: 'RS' },
  'coqueiro baixo': { name: 'Coqueiro Baixo', state: 'RS' },
  'coqueiros do sul': { name: 'Coqueiros do Sul', state: 'RS' },
  'coronel barros': { name: 'Coronel Barros', state: 'RS' },
  'coronel bicaco': { name: 'Coronel Bicaco', state: 'RS' },
  'coronel pilar': { name: 'Coronel Pilar', state: 'RS' },
  cotipora: { name: 'Cotiporã', state: 'RS' },
  coxilha: { name: 'Coxilha', state: 'RS' },
  crissiumal: { name: 'Crissiumal', state: 'RS' },
  cristal: { name: 'Cristal', state: 'RS' },
  'cristal do sul': { name: 'Cristal do Sul', state: 'RS' },
  'cruz alta': { name: 'Cruz Alta', state: 'RS' },
  cruzaltense: { name: 'Cruzaltense', state: 'RS' },
  'cruzeiro do sul__': { name: 'Cruzeiro do Sul', state: 'RS' },
  'david canabarro': { name: 'David Canabarro', state: 'RS' },
  derrubadas: { name: 'Derrubadas', state: 'RS' },
  'dezesseis de novembro': { name: 'Dezesseis de Novembro', state: 'RS' },
  'dilermando de aguiar': { name: 'Dilermando de Aguiar', state: 'RS' },
  'dois irmaos': { name: 'Dois Irmãos', state: 'RS' },
  'dois irmaos das missoes': { name: 'Dois Irmãos das Missões', state: 'RS' },
  'dois lajeados': { name: 'Dois Lajeados', state: 'RS' },
  'dom feliciano': { name: 'Dom Feliciano', state: 'RS' },
  'dom pedrito': { name: 'Dom Pedrito', state: 'RS' },
  'dom pedro de alcantara': { name: 'Dom Pedro de Alcântara', state: 'RS' },
  'dona francisca': { name: 'Dona Francisca', state: 'RS' },
  'doutor mauricio cardoso': { name: 'Doutor Maurício Cardoso', state: 'RS' },
  'doutor ricardo': { name: 'Doutor Ricardo', state: 'RS' },
  'eldorado do sul': { name: 'Eldorado do Sul', state: 'RS' },
  encantado: { name: 'Encantado', state: 'RS' },
  'encruzilhada do sul': { name: 'Encruzilhada do Sul', state: 'RS' },
  'engenho velho': { name: 'Engenho Velho', state: 'RS' },
  'entre ijuis': { name: 'Entre Ijuís', state: 'RS' },
  'entre rios do sul': { name: 'Entre Rios do Sul', state: 'RS' },
  erebango: { name: 'Erebango', state: 'RS' },
  erechim: { name: 'Erechim', state: 'RS' },
  ernestina: { name: 'Ernestina', state: 'RS' },
  'erval grande': { name: 'Erval Grande', state: 'RS' },
  'erval seco': { name: 'Erval Seco', state: 'RS' },
  esmeralda: { name: 'Esmeralda', state: 'RS' },
  'esperanca do sul': { name: 'Esperança do Sul', state: 'RS' },
  espumoso: { name: 'Espumoso', state: 'RS' },
  estacao: { name: 'Estação', state: 'RS' },
  'estancia velha': { name: 'Estância Velha', state: 'RS' },
  esteio: { name: 'Esteio', state: 'RS' },
  estrela: { name: 'Estrela', state: 'RS' },
  'estrela velha': { name: 'Estrela Velha', state: 'RS' },
  'eugenio de castro': { name: 'Eugênio de Castro', state: 'RS' },
  'fagundes varela': { name: 'Fagundes Varela', state: 'RS' },
  farroupilha: { name: 'Farroupilha', state: 'RS' },
  'faxinal do soturno': { name: 'Faxinal do Soturno', state: 'RS' },
  faxinalzinho: { name: 'Faxinalzinho', state: 'RS' },
  'fazenda vilanova': { name: 'Fazenda Vilanova', state: 'RS' },
  feliz: { name: 'Feliz', state: 'RS' },
  'flores da cunha': { name: 'Flores da Cunha', state: 'RS' },
  'floriano peixoto': { name: 'Floriano Peixoto', state: 'RS' },
  'fontoura xavier': { name: 'Fontoura Xavier', state: 'RS' },
  formigueiro: { name: 'Formigueiro', state: 'RS' },
  forquetinha: { name: 'Forquetinha', state: 'RS' },
  'fortaleza dos valos': { name: 'Fortaleza dos Valos', state: 'RS' },
  'frederico westphalen': { name: 'Frederico Westphalen', state: 'RS' },
  garibaldi: { name: 'Garibaldi', state: 'RS' },
  garruchos: { name: 'Garruchos', state: 'RS' },
  gaurama: { name: 'Gaurama', state: 'RS' },
  'general camara': { name: 'General Câmara', state: 'RS' },
  gentil: { name: 'Gentil', state: 'RS' },
  'getulio vargas': { name: 'Getúlio Vargas', state: 'RS' },
  girua: { name: 'Giruá', state: 'RS' },
  glorinha: { name: 'Glorinha', state: 'RS' },
  gramado: { name: 'Gramado', state: 'RS' },
  'gramado dos loureiros': { name: 'Gramado dos Loureiros', state: 'RS' },
  'gramado xavier': { name: 'Gramado Xavier', state: 'RS' },
  gravatai: { name: 'Gravataí', state: 'RS' },
  guabiju: { name: 'Guabiju', state: 'RS' },
  guaiba: { name: 'Guaíba', state: 'RS' },
  guapore: { name: 'Guaporé', state: 'RS' },
  'guarani das missoes': { name: 'Guarani das Missões', state: 'RS' },
  harmonia: { name: 'Harmonia', state: 'RS' },
  herval: { name: 'Herval', state: 'RS' },
  herveiras: { name: 'Herveiras', state: 'RS' },
  horizontina: { name: 'Horizontina', state: 'RS' },
  'hulha negra': { name: 'Hulha Negra', state: 'RS' },
  humaita_: { name: 'Humaitá', state: 'RS' },
  ibarama: { name: 'Ibarama', state: 'RS' },
  ibiaca: { name: 'Ibiaçá', state: 'RS' },
  ibiraiaras: { name: 'Ibiraiaras', state: 'RS' },
  ibirapuita: { name: 'Ibirapuitã', state: 'RS' },
  ibiruba: { name: 'Ibirubá', state: 'RS' },
  igrejinha: { name: 'Igrejinha', state: 'RS' },
  ijui: { name: 'Ijuí', state: 'RS' },
  ilopolis: { name: 'Ilópolis', state: 'RS' },
  imbe: { name: 'Imbé', state: 'RS' },
  imigrante: { name: 'Imigrante', state: 'RS' },
  independencia_: { name: 'Independência', state: 'RS' },
  inhacora: { name: 'Inhacorá', state: 'RS' },
  ipe: { name: 'Ipê', state: 'RS' },
  'ipiranga do sul': { name: 'Ipiranga do Sul', state: 'RS' },
  irai: { name: 'Iraí', state: 'RS' },
  itaara: { name: 'Itaara', state: 'RS' },
  itacurubi: { name: 'Itacurubi', state: 'RS' },
  itapuca: { name: 'Itapuca', state: 'RS' },
  itaqui: { name: 'Itaqui', state: 'RS' },
  itati: { name: 'Itati', state: 'RS' },
  'itatiba do sul': { name: 'Itatiba do Sul', state: 'RS' },
  ivora: { name: 'Ivorá', state: 'RS' },
  ivoti: { name: 'Ivoti', state: 'RS' },
  jaboticaba: { name: 'Jaboticaba', state: 'RS' },
  jacuizinho: { name: 'Jacuizinho', state: 'RS' },
  jacutinga_: { name: 'Jacutinga', state: 'RS' },
  jaguarao: { name: 'Jaguarão', state: 'RS' },
  jaguari: { name: 'Jaguari', state: 'RS' },
  jaquirana: { name: 'Jaquirana', state: 'RS' },
  jari: { name: 'Jari', state: 'RS' },
  joia: { name: 'Jóia', state: 'RS' },
  'julio de castilhos': { name: 'Júlio de Castilhos', state: 'RS' },
  'lagoa bonita do sul': { name: 'Lagoa Bonita do Sul', state: 'RS' },
  'lagoa dos tres cantos': { name: 'Lagoa dos Três Cantos', state: 'RS' },
  lagoao: { name: 'Lagoão', state: 'RS' },
  'lagoa vermelha': { name: 'Lagoa Vermelha', state: 'RS' },
  lajeado: { name: 'Lajeado', state: 'RS' },
  'lajeado do bugre': { name: 'Lajeado do Bugre', state: 'RS' },
  'lavras do sul': { name: 'Lavras do Sul', state: 'RS' },
  'liberato salzano': { name: 'Liberato Salzano', state: 'RS' },
  'lindolfo collor': { name: 'Lindolfo Collor', state: 'RS' },
  'linha nova': { name: 'Linha Nova', state: 'RS' },
  macambara: { name: 'Maçambará', state: 'RS' },
  machadinho: { name: 'Machadinho', state: 'RS' },
  mampituba: { name: 'Mampituba', state: 'RS' },
  'manoel viana': { name: 'Manoel Viana', state: 'RS' },
  maquine: { name: 'Maquiné', state: 'RS' },
  marata: { name: 'Maratá', state: 'RS' },
  marau_: { name: 'Marau', state: 'RS' },
  'marcelino ramos': { name: 'Marcelino Ramos', state: 'RS' },
  'mariana pimentel': { name: 'Mariana Pimentel', state: 'RS' },
  'mariano moro': { name: 'Mariano Moro', state: 'RS' },
  'marques de souza': { name: 'Marques de Souza', state: 'RS' },
  mata: { name: 'Mata', state: 'RS' },
  'mato castelhano': { name: 'Mato Castelhano', state: 'RS' },
  'mato leitao': { name: 'Mato Leitão', state: 'RS' },
  'mato queimado': { name: 'Mato Queimado', state: 'RS' },
  'maximiliano de almeida': { name: 'Maximiliano de Almeida', state: 'RS' },
  'minas do leao': { name: 'Minas do Leão', state: 'RS' },
  miraguai: { name: 'Miraguaí', state: 'RS' },
  montauri: { name: 'Montauri', state: 'RS' },
  'monte alegre dos campos': { name: 'Monte Alegre dos Campos', state: 'RS' },
  'monte belo do sul': { name: 'Monte Belo do Sul', state: 'RS' },
  montenegro: { name: 'Montenegro', state: 'RS' },
  mormaco: { name: 'Mormaço', state: 'RS' },
  'morrinhos do sul': { name: 'Morrinhos do Sul', state: 'RS' },
  'morro redondo': { name: 'Morro Redondo', state: 'RS' },
  'morro reuter': { name: 'Morro Reuter', state: 'RS' },
  mostardas: { name: 'Mostardas', state: 'RS' },
  mucum: { name: 'Muçum', state: 'RS' },
  'muitos capoes': { name: 'Muitos Capões', state: 'RS' },
  muliterno: { name: 'Muliterno', state: 'RS' },
  'nao-me-toque': { name: 'Não-Me-Toque', state: 'RS' },
  'nicolau vergueiro': { name: 'Nicolau Vergueiro', state: 'RS' },
  nonoai: { name: 'Nonoai', state: 'RS' },
  'nova alvorada': { name: 'Nova Alvorada', state: 'RS' },
  'nova araca': { name: 'Nova Araçá', state: 'RS' },
  'nova bassano': { name: 'Nova Bassano', state: 'RS' },
  'nova boa vista': { name: 'Nova Boa Vista', state: 'RS' },
  'nova brescia': { name: 'Nova Bréscia', state: 'RS' },
  'nova candelaria': { name: 'Nova Candelária', state: 'RS' },
  'nova esperanca do sul': { name: 'Nova Esperança do Sul', state: 'RS' },
  'nova hartz': { name: 'Nova Hartz', state: 'RS' },
  'nova padua': { name: 'Nova Pádua', state: 'RS' },
  'nova palma': { name: 'Nova Palma', state: 'RS' },
  'nova petropolis': { name: 'Nova Petrópolis', state: 'RS' },
  'nova prata': { name: 'Nova Prata', state: 'RS' },
  'nova ramada': { name: 'Nova Ramada', state: 'RS' },
  'nova roma do sul': { name: 'Nova Roma do Sul', state: 'RS' },
  'nova santa rita_': { name: 'Nova Santa Rita', state: 'RS' },
  'novo barreiro': { name: 'Novo Barreiro', state: 'RS' },
  'novo cabrais': { name: 'Novo Cabrais', state: 'RS' },
  'novo hamburgo': { name: 'Novo Hamburgo', state: 'RS' },
  'novo machado': { name: 'Novo Machado', state: 'RS' },
  'novo tiradentes': { name: 'Novo Tiradentes', state: 'RS' },
  'novo xingu': { name: 'Novo Xingu', state: 'RS' },
  osorio: { name: 'Osório', state: 'RS' },
  'paim filho': { name: 'Paim Filho', state: 'RS' },
  'palmares do sul': { name: 'Palmares do Sul', state: 'RS' },
  'palmeira das missoes': { name: 'Palmeira das Missões', state: 'RS' },
  palmitinho: { name: 'Palmitinho', state: 'RS' },
  panambi: { name: 'Panambi', state: 'RS' },
  'pantano grande': { name: 'Pantano Grande', state: 'RS' },
  parai: { name: 'Paraí', state: 'RS' },
  'paraiso do sul': { name: 'Paraíso do Sul', state: 'RS' },
  'pareci novo': { name: 'Pareci Novo', state: 'RS' },
  parobe: { name: 'Parobé', state: 'RS' },
  'passa-sete': { name: 'Passa-Sete', state: 'RS' },
  'passo do sobrado': { name: 'Passo do Sobrado', state: 'RS' },
  'passo fundo': { name: 'Passo Fundo', state: 'RS' },
  'paulo bento': { name: 'Paulo Bento', state: 'RS' },
  paverama: { name: 'Paverama', state: 'RS' },
  'pedras altas': { name: 'Pedras Altas', state: 'RS' },
  'pedro osorio': { name: 'Pedro Osório', state: 'RS' },
  pejucara: { name: 'Pejuçara', state: 'RS' },
  pelotas: { name: 'Pelotas', state: 'RS' },
  'picada cafe': { name: 'Picada Café', state: 'RS' },
  pinhal: { name: 'Pinhal', state: 'RS' },
  'pinhal da serra': { name: 'Pinhal da Serra', state: 'RS' },
  'pinhal grande': { name: 'Pinhal Grande', state: 'RS' },
  'pinheirinho do vale': { name: 'Pinheirinho do Vale', state: 'RS' },
  'pinheiro machado': { name: 'Pinheiro Machado', state: 'RS' },
  'pinto bandeira': { name: 'Pinto Bandeira', state: 'RS' },
  pirapo: { name: 'Pirapó', state: 'RS' },
  piratini: { name: 'Piratini', state: 'RS' },
  planalto__: { name: 'Planalto', state: 'RS' },
  'poco das antas': { name: 'Poço das Antas', state: 'RS' },
  pontao: { name: 'Pontão', state: 'RS' },
  'ponte preta': { name: 'Ponte Preta', state: 'RS' },
  portao: { name: 'Portão', state: 'RS' },
  'porto alegre': { name: 'Porto Alegre', state: 'RS' },
  'porto lucena': { name: 'Porto Lucena', state: 'RS' },
  'porto maua': { name: 'Porto Mauá', state: 'RS' },
  'porto vera cruz': { name: 'Porto Vera Cruz', state: 'RS' },
  'porto xavier': { name: 'Porto Xavier', state: 'RS' },
  'pouso novo': { name: 'Pouso Novo', state: 'RS' },
  'presidente lucena': { name: 'Presidente Lucena', state: 'RS' },
  progresso: { name: 'Progresso', state: 'RS' },
  'protasio alves': { name: 'Protásio Alves', state: 'RS' },
  putinga: { name: 'Putinga', state: 'RS' },
  quarai: { name: 'Quaraí', state: 'RS' },
  'quatro irmaos': { name: 'Quatro Irmãos', state: 'RS' },
  quevedos: { name: 'Quevedos', state: 'RS' },
  'quinze de novembro': { name: 'Quinze de Novembro', state: 'RS' },
  redentora: { name: 'Redentora', state: 'RS' },
  relvado: { name: 'Relvado', state: 'RS' },
  'restinga seca': { name: 'Restinga Sêca', state: 'RS' },
  'rio dos indios': { name: 'Rio dos Índios', state: 'RS' },
  'rio grande': { name: 'Rio Grande', state: 'RS' },
  'rio pardo': { name: 'Rio Pardo', state: 'RS' },
  riozinho: { name: 'Riozinho', state: 'RS' },
  'roca sales': { name: 'Roca Sales', state: 'RS' },
  'rodeio bonito': { name: 'Rodeio Bonito', state: 'RS' },
  rolador: { name: 'Rolador', state: 'RS' },
  rolante: { name: 'Rolante', state: 'RS' },
  'ronda alta': { name: 'Ronda Alta', state: 'RS' },
  rondinha: { name: 'Rondinha', state: 'RS' },
  'roque gonzales': { name: 'Roque Gonzales', state: 'RS' },
  'rosario do sul': { name: 'Rosário do Sul', state: 'RS' },
  'sagrada familia': { name: 'Sagrada Família', state: 'RS' },
  'saldanha marinho': { name: 'Saldanha Marinho', state: 'RS' },
  'salto do jacui': { name: 'Salto do Jacuí', state: 'RS' },
  'salvador das missoes': { name: 'Salvador das Missões', state: 'RS' },
  'salvador do sul': { name: 'Salvador do Sul', state: 'RS' },
  sananduva: { name: 'Sananduva', state: 'RS' },
  'santa barbara do sul': { name: 'Santa Bárbara do Sul', state: 'RS' },
  'santa cecilia do sul': { name: 'Santa Cecília do Sul', state: 'RS' },
  'santa clara do sul': { name: 'Santa Clara do Sul', state: 'RS' },
  'santa cruz do sul': { name: 'Santa Cruz do Sul', state: 'RS' },
  'santa margarida do sul': { name: 'Santa Margarida do Sul', state: 'RS' },
  'santa maria_': { name: 'Santa Maria', state: 'RS' },
  'santa maria do herval': { name: 'Santa Maria do Herval', state: 'RS' },
  'santana da boa vista': { name: 'Santana da Boa Vista', state: 'RS' },
  "sant'ana do livramento": { name: "Sant'Ana do Livramento", state: 'RS' },
  'santa rosa': { name: 'Santa Rosa', state: 'RS' },
  'santa tereza': { name: 'Santa Tereza', state: 'RS' },
  'santa vitoria do palmar': { name: 'Santa Vitória do Palmar', state: 'RS' },
  santiago: { name: 'Santiago', state: 'RS' },
  'santo angelo': { name: 'Santo Ângelo', state: 'RS' },
  'santo antonio da patrulha': { name: 'Santo Antônio da Patrulha', state: 'RS' },
  'santo antonio das missoes': { name: 'Santo Antônio das Missões', state: 'RS' },
  'santo antonio do palma': { name: 'Santo Antônio do Palma', state: 'RS' },
  'santo antonio do planalto': { name: 'Santo Antônio do Planalto', state: 'RS' },
  'santo augusto': { name: 'Santo Augusto', state: 'RS' },
  'santo cristo': { name: 'Santo Cristo', state: 'RS' },
  'santo expedito do sul': { name: 'Santo Expedito do Sul', state: 'RS' },
  'sao borja': { name: 'São Borja', state: 'RS' },
  'sao domingos do sul': { name: 'São Domingos do Sul', state: 'RS' },
  'sao francisco de assis': { name: 'São Francisco de Assis', state: 'RS' },
  'sao francisco de paula_': { name: 'São Francisco de Paula', state: 'RS' },
  'sao gabriel_': { name: 'São Gabriel', state: 'RS' },
  'sao jeronimo': { name: 'São Jerônimo', state: 'RS' },
  'sao joao da urtiga': { name: 'São João da Urtiga', state: 'RS' },
  'sao joao do polesine': { name: 'São João do Polêsine', state: 'RS' },
  'sao jorge': { name: 'São Jorge', state: 'RS' },
  'sao jose das missoes': { name: 'São José das Missões', state: 'RS' },
  'sao jose do herval': { name: 'São José do Herval', state: 'RS' },
  'sao jose do hortencio': { name: 'São José do Hortêncio', state: 'RS' },
  'sao jose do inhacora': { name: 'São José do Inhacorá', state: 'RS' },
  'sao jose do norte': { name: 'São José do Norte', state: 'RS' },
  'sao jose do ouro': { name: 'São José do Ouro', state: 'RS' },
  'sao jose dos ausentes': { name: 'São José dos Ausentes', state: 'RS' },
  'sao jose do sul': { name: 'São José do Sul', state: 'RS' },
  'sao leopoldo': { name: 'São Leopoldo', state: 'RS' },
  'sao lourenco do sul': { name: 'São Lourenço do Sul', state: 'RS' },
  'sao luiz gonzaga': { name: 'São Luiz Gonzaga', state: 'RS' },
  'sao marcos': { name: 'São Marcos', state: 'RS' },
  'sao martinho': { name: 'São Martinho', state: 'RS' },
  'sao martinho da serra': { name: 'São Martinho da Serra', state: 'RS' },
  'sao miguel das missoes': { name: 'São Miguel das Missões', state: 'RS' },
  'sao nicolau': { name: 'São Nicolau', state: 'RS' },
  'sao paulo das missoes': { name: 'São Paulo das Missões', state: 'RS' },
  'sao pedro da serra': { name: 'São Pedro da Serra', state: 'RS' },
  'sao pedro das missoes': { name: 'São Pedro das Missões', state: 'RS' },
  'sao pedro do butia': { name: 'São Pedro do Butiá', state: 'RS' },
  'sao pedro do sul': { name: 'São Pedro do Sul', state: 'RS' },
  'sao sebastiao do cai': { name: 'São Sebastião do Caí', state: 'RS' },
  'sao sepe': { name: 'São Sepé', state: 'RS' },
  'sao valentim': { name: 'São Valentim', state: 'RS' },
  'sao valentim do sul': { name: 'São Valentim do Sul', state: 'RS' },
  'sao valerio do sul': { name: 'São Valério do Sul', state: 'RS' },
  'sao vendelino': { name: 'São Vendelino', state: 'RS' },
  'sao vicente do sul': { name: 'São Vicente do Sul', state: 'RS' },
  sapiranga: { name: 'Sapiranga', state: 'RS' },
  'sapucaia do sul': { name: 'Sapucaia do Sul', state: 'RS' },
  sarandi_: { name: 'Sarandi', state: 'RS' },
  seberi: { name: 'Seberi', state: 'RS' },
  'sede nova': { name: 'Sede Nova', state: 'RS' },
  segredo: { name: 'Segredo', state: 'RS' },
  selbach: { name: 'Selbach', state: 'RS' },
  'senador salgado filho': { name: 'Senador Salgado Filho', state: 'RS' },
  'sentinela do sul': { name: 'Sentinela do Sul', state: 'RS' },
  'serafina correa': { name: 'Serafina Corrêa', state: 'RS' },
  serio: { name: 'Sério', state: 'RS' },
  sertao: { name: 'Sertão', state: 'RS' },
  'sertao santana': { name: 'Sertão Santana', state: 'RS' },
  'sete de setembro': { name: 'Sete de Setembro', state: 'RS' },
  'severiano de almeida': { name: 'Severiano de Almeida', state: 'RS' },
  'silveira martins': { name: 'Silveira Martins', state: 'RS' },
  sinimbu: { name: 'Sinimbu', state: 'RS' },
  sobradinho_: { name: 'Sobradinho', state: 'RS' },
  soledade_: { name: 'Soledade', state: 'RS' },
  tabai: { name: 'Tabaí', state: 'RS' },
  tapejara_: { name: 'Tapejara', state: 'RS' },
  tapera: { name: 'Tapera', state: 'RS' },
  tapes: { name: 'Tapes', state: 'RS' },
  taquara: { name: 'Taquara', state: 'RS' },
  taquari: { name: 'Taquari', state: 'RS' },
  'taquarucu do sul': { name: 'Taquaruçu do Sul', state: 'RS' },
  tavares_: { name: 'Tavares', state: 'RS' },
  'tenente portela': { name: 'Tenente Portela', state: 'RS' },
  'terra de areia': { name: 'Terra de Areia', state: 'RS' },
  teutonia: { name: 'Teutônia', state: 'RS' },
  'tio hugo': { name: 'Tio Hugo', state: 'RS' },
  'tiradentes do sul': { name: 'Tiradentes do Sul', state: 'RS' },
  toropi: { name: 'Toropi', state: 'RS' },
  torres: { name: 'Torres', state: 'RS' },
  tramandai: { name: 'Tramandaí', state: 'RS' },
  travesseiro: { name: 'Travesseiro', state: 'RS' },
  'tres arroios': { name: 'Três Arroios', state: 'RS' },
  'tres cachoeiras': { name: 'Três Cachoeiras', state: 'RS' },
  'tres coroas': { name: 'Três Coroas', state: 'RS' },
  'tres de maio': { name: 'Três de Maio', state: 'RS' },
  'tres forquilhas': { name: 'Três Forquilhas', state: 'RS' },
  'tres palmeiras': { name: 'Três Palmeiras', state: 'RS' },
  'tres passos': { name: 'Três Passos', state: 'RS' },
  'trindade do sul': { name: 'Trindade do Sul', state: 'RS' },
  triunfo__: { name: 'Triunfo', state: 'RS' },
  tucunduva: { name: 'Tucunduva', state: 'RS' },
  tunas: { name: 'Tunas', state: 'RS' },
  'tupanci do sul': { name: 'Tupanci do Sul', state: 'RS' },
  tupancireta: { name: 'Tupanciretã', state: 'RS' },
  tupandi: { name: 'Tupandi', state: 'RS' },
  tuparendi: { name: 'Tuparendi', state: 'RS' },
  turucu: { name: 'Turuçu', state: 'RS' },
  ubiretama: { name: 'Ubiretama', state: 'RS' },
  'uniao da serra': { name: 'União da Serra', state: 'RS' },
  unistalda: { name: 'Unistalda', state: 'RS' },
  uruguaiana: { name: 'Uruguaiana', state: 'RS' },
  vacaria: { name: 'Vacaria', state: 'RS' },
  'vale do sol': { name: 'Vale do Sol', state: 'RS' },
  'vale real': { name: 'Vale Real', state: 'RS' },
  'vale verde': { name: 'Vale Verde', state: 'RS' },
  vanini: { name: 'Vanini', state: 'RS' },
  'venancio aires': { name: 'Venâncio Aires', state: 'RS' },
  'vera cruz__': { name: 'Vera Cruz', state: 'RS' },
  veranopolis: { name: 'Veranópolis', state: 'RS' },
  'vespasiano correa': { name: 'Vespasiano Corrêa', state: 'RS' },
  viadutos: { name: 'Viadutos', state: 'RS' },
  viamao: { name: 'Viamão', state: 'RS' },
  'vicente dutra': { name: 'Vicente Dutra', state: 'RS' },
  'victor graeff': { name: 'Victor Graeff', state: 'RS' },
  'vila flores': { name: 'Vila Flores', state: 'RS' },
  'vila langaro': { name: 'Vila Lângaro', state: 'RS' },
  'vila maria': { name: 'Vila Maria', state: 'RS' },
  'vila nova do sul': { name: 'Vila Nova do Sul', state: 'RS' },
  'vista alegre': { name: 'Vista Alegre', state: 'RS' },
  'vista alegre do prata': { name: 'Vista Alegre do Prata', state: 'RS' },
  'vista gaucha': { name: 'Vista Gaúcha', state: 'RS' },
  'vitoria das missoes': { name: 'Vitória das Missões', state: 'RS' },
  westfalia: { name: 'Westfália', state: 'RS' },
  'xangri-la': { name: 'Xangri-lá', state: 'RS' },
};
