export const cities = {
  'abdon batista': 'Abdon Batista',
  'abelardo luz': 'Abelardo Luz',
  agrolandia: 'Agrolândia',
  agronomica: 'Agronômica',
  'agua doce': 'Água Doce',
  'aguas de chapeco': 'Águas de Chapecó',
  'aguas frias': 'Águas Frias',
  'aguas mornas': 'Águas Mornas',
  'alfredo wagner': 'Alfredo Wagner',
  'alto bela vista': 'Alto Bela Vista',
  anchieta_: 'Anchieta',
  angelina: 'Angelina',
  'anita garibaldi': 'Anita Garibaldi',
  anitapolis: 'Anitápolis',
  'antonio carlos_': 'Antônio Carlos',
  apiuna: 'Apiúna',
  arabuta: 'Arabutã',
  araquari: 'Araquari',
  ararangua: 'Araranguá',
  armazem: 'Armazém',
  'arroio trinta': 'Arroio Trinta',
  arvoredo: 'Arvoredo',
  ascurra: 'Ascurra',
  atalanta: 'Atalanta',
  aurora_: 'Aurora',
  'balneario arroio do silva': 'Balneário Arroio do Silva',
  'balneario barra do sul': 'Balneário Barra do Sul',
  'balneario camboriu': 'Balneário Camboriú',
  'balneario gaivota': 'Balneário Gaivota',
  'balneario picarras': 'Balneário Piçarras',
  'balneario rincao': 'Balneário Rincão',
  bandeirante: 'Bandeirante',
  'barra bonita': 'Barra Bonita',
  'barra velha': 'Barra Velha',
  'bela vista do toldo': 'Bela Vista do Toldo',
  belmonte_: 'Belmonte',
  'benedito novo': 'Benedito Novo',
  biguacu: 'Biguaçu',
  blumenau: 'Blumenau',
  'bocaina do sul': 'Bocaina do Sul',
  bombinhas: 'Bombinhas',
  'bom jardim da serra': 'Bom Jardim da Serra',
  'bom jesus____': 'Bom Jesus',
  'bom jesus do oeste': 'Bom Jesus do Oeste',
  'bom retiro': 'Bom Retiro',
  botuvera: 'Botuverá',
  'braco do norte': 'Braço do Norte',
  'braco do trombudo': 'Braço do Trombudo',
  brunopolis: 'Brunópolis',
  brusque: 'Brusque',
  cacador: 'Caçador',
  caibi: 'Caibi',
  calmon: 'Calmon',
  camboriu: 'Camboriú',
  'campo alegre_': 'Campo Alegre',
  'campo belo do sul': 'Campo Belo do Sul',
  'campo ere': 'Campo Erê',
  'campos novos': 'Campos Novos',
  canelinha: 'Canelinha',
  canoinhas: 'Canoinhas',
  'capao alto': 'Capão Alto',
  capinzal: 'Capinzal',
  'capivari de baixo': 'Capivari de Baixo',
  catanduvas_: 'Catanduvas',
  'caxambu do sul': 'Caxambu do Sul',
  'celso ramos': 'Celso Ramos',
  'cerro negro': 'Cerro Negro',
  'chapadao do lageado': 'Chapadão do Lageado',
  chapeco: 'Chapecó',
  'cocal do sul': 'Cocal do Sul',
  concordia: 'Concórdia',
  'cordilheira alta': 'Cordilheira Alta',
  'coronel freitas': 'Coronel Freitas',
  'coronel martins': 'Coronel Martins',
  'correia pinto': 'Correia Pinto',
  corupa: 'Corupá',
  criciuma: 'Criciúma',
  'cunha pora': 'Cunha Porã',
  cunhatai: 'Cunhataí',
  curitibanos: 'Curitibanos',
  descanso: 'Descanso',
  'dionisio cerqueira': 'Dionísio Cerqueira',
  'dona emma': 'Dona Emma',
  'doutor pedrinho': 'Doutor Pedrinho',
  'entre rios_': 'Entre Rios',
  ermo: 'Ermo',
  'erval velho': 'Erval Velho',
  'faxinal dos guedes': 'Faxinal dos Guedes',
  'flor do sertao': 'Flor do Sertão',
  florianopolis: 'Florianópolis',
  'formosa do sul': 'Formosa do Sul',
  forquilhinha: 'Forquilhinha',
  fraiburgo: 'Fraiburgo',
  'frei rogerio': 'Frei Rogério',
  galvao: 'Galvão',
  garopaba: 'Garopaba',
  garuva: 'Garuva',
  gaspar: 'Gaspar',
  'governador celso ramos': 'Governador Celso Ramos',
  'grao-para': 'Grão-Pará',
  gravatal: 'Gravatal',
  guabiruba: 'Guabiruba',
  guaraciaba_: 'Guaraciaba',
  guaramirim: 'Guaramirim',
  'guaruja do sul': 'Guarujá do Sul',
  guatambu: 'Guatambu',
  "herval d'oeste": "Herval d'Oeste",
  ibiam: 'Ibiam',
  ibicare: 'Ibicaré',
  ibirama: 'Ibirama',
  icara: 'Içara',
  ilhota: 'Ilhota',
  imarui: 'Imaruí',
  imbituba: 'Imbituba',
  imbuia: 'Imbuia',
  indaial: 'Indaial',
  iomere: 'Iomerê',
  ipira: 'Ipira',
  'ipora do oeste': 'Iporã do Oeste',
  ipuacu: 'Ipuaçu',
  ipumirim: 'Ipumirim',
  iraceminha: 'Iraceminha',
  irani: 'Irani',
  irati_: 'Irati',
  irineopolis: 'Irineópolis',
  ita: 'Itá',
  itaiopolis: 'Itaiópolis',
  itajai: 'Itajaí',
  itapema: 'Itapema',
  itapiranga_: 'Itapiranga',
  itapoa: 'Itapoá',
  ituporanga: 'Ituporanga',
  jabora: 'Jaborá',
  'jacinto machado': 'Jacinto Machado',
  jaguaruna: 'Jaguaruna',
  'jaragua do sul': 'Jaraguá do Sul',
  jardinopolis: 'Jardinópolis',
  joacaba: 'Joaçaba',
  joinville: 'Joinville',
  'jose boiteux': 'José Boiteux',
  jupia: 'Jupiá',
  lacerdopolis: 'Lacerdópolis',
  lages: 'Lages',
  laguna: 'Laguna',
  'lajeado grande': 'Lajeado Grande',
  laurentino: 'Laurentino',
  'lauro muller': 'Lauro Müller',
  'lebon regis': 'Lebon Régis',
  'leoberto leal': 'Leoberto Leal',
  'lindoia do sul': 'Lindóia do Sul',
  lontras: 'Lontras',
  'luiz alves': 'Luiz Alves',
  luzerna: 'Luzerna',
  macieira: 'Macieira',
  mafra: 'Mafra',
  'major gercino': 'Major Gercino',
  'major vieira': 'Major Vieira',
  maracaja: 'Maracajá',
  maravilha_: 'Maravilha',
  marema: 'Marema',
  massaranduba_: 'Massaranduba',
  'matos costa': 'Matos Costa',
  meleiro: 'Meleiro',
  'mirim doce': 'Mirim Doce',
  modelo: 'Modelo',
  mondai: 'Mondaí',
  'monte carlo': 'Monte Carlo',
  'monte castelo': 'Monte Castelo',
  'morro da fumaca': 'Morro da Fumaça',
  'morro grande': 'Morro Grande',
  navegantes: 'Navegantes',
  'nova erechim': 'Nova Erechim',
  'nova itaberaba': 'Nova Itaberaba',
  'nova trento': 'Nova Trento',
  'nova veneza_': 'Nova Veneza',
  'novo horizonte_': 'Novo Horizonte',
  orleans: 'Orleans',
  'otacilio costa': 'Otacílio Costa',
  ouro: 'Ouro',
  'ouro verde': 'Ouro Verde',
  paial: 'Paial',
  painel: 'Painel',
  palhoca: 'Palhoça',
  'palma sola': 'Palma Sola',
  palmeira_: 'Palmeira',
  palmitos: 'Palmitos',
  papanduva: 'Papanduva',
  paraiso: 'Paraíso',
  'passo de torres': 'Passo de Torres',
  'passos maia': 'Passos Maia',
  'paulo lopes': 'Paulo Lopes',
  'pedras grandes': 'Pedras Grandes',
  penha: 'Penha',
  peritiba: 'Peritiba',
  'pescaria brava': 'Pescaria Brava',
  petrolandia_: 'Petrolândia',
  pinhalzinho: 'Pinhalzinho',
  'pinheiro preto': 'Pinheiro Preto',
  piratuba: 'Piratuba',
  'planalto alegre': 'Planalto Alegre',
  pomerode: 'Pomerode',
  'ponte alta': 'Ponte Alta',
  'ponte alta do norte': 'Ponte Alta do Norte',
  'ponte serrada': 'Ponte Serrada',
  'porto belo': 'Porto Belo',
  'porto uniao': 'Porto União',
  'pouso redondo': 'Pouso Redondo',
  'praia grande': 'Praia Grande',
  'presidente castello branco': 'Presidente Castello Branco',
  'presidente getulio': 'Presidente Getúlio',
  'presidente nereu': 'Presidente Nereu',
  princesa: 'Princesa',
  quilombo: 'Quilombo',
  'rancho queimado': 'Rancho Queimado',
  'rio das antas': 'Rio das Antas',
  'rio do campo': 'Rio do Campo',
  'rio do oeste': 'Rio do Oeste',
  'rio dos cedros': 'Rio dos Cedros',
  'rio do sul': 'Rio do Sul',
  'rio fortuna': 'Rio Fortuna',
  'rio negrinho': 'Rio Negrinho',
  'rio rufino': 'Rio Rufino',
  riqueza: 'Riqueza',
  rodeio: 'Rodeio',
  romelandia: 'Romelândia',
  salete: 'Salete',
  saltinho: 'Saltinho',
  'salto veloso': 'Salto Veloso',
  sangao: 'Sangão',
  'santa cecilia_': 'Santa Cecília',
  'santa helena___': 'Santa Helena',
  'santa rosa de lima': 'Santa Rosa de Lima',
  'santa rosa do sul': 'Santa Rosa do Sul',
  'santa terezinha___': 'Santa Terezinha',
  'santa terezinha do progresso': 'Santa Terezinha do Progresso',
  'santiago do sul': 'Santiago do Sul',
  'santo amaro da imperatriz': 'Santo Amaro da Imperatriz',
  'sao bento do sul': 'São Bento do Sul',
  'sao bernardino': 'São Bernardino',
  'sao bonifacio': 'São Bonifácio',
  'sao carlos': 'São Carlos',
  'sao cristovao do sul': 'São Cristóvão do Sul',
  'sao domingos___': 'São Domingos',
  'sao francisco do sul': 'São Francisco do Sul',
  'sao joao batista_': 'São João Batista',
  'sao joao do itaperiu': 'São João do Itaperiú',
  'sao joao do oeste': 'São João do Oeste',
  'sao joao do sul': 'São João do Sul',
  'sao joaquim': 'São Joaquim',
  'sao jose': 'São José',
  'sao jose do cedro': 'São José do Cedro',
  'sao jose do cerrito': 'São José do Cerrito',
  'sao lourenco do oeste': 'São Lourenço do Oeste',
  'sao ludgero': 'São Ludgero',
  'sao martinho_': 'São Martinho',
  'sao miguel da boa vista': 'São Miguel da Boa Vista',
  'sao miguel do oeste': 'São Miguel do Oeste',
  'sao pedro de alcantara': 'São Pedro de Alcântara',
  saudades: 'Saudades',
  schroeder: 'Schroeder',
  seara: 'Seara',
  'serra alta': 'Serra Alta',
  sideropolis: 'Siderópolis',
  sombrio: 'Sombrio',
  'sul brasil': 'Sul Brasil',
  taio: 'Taió',
  tangara_: 'Tangará',
  tigrinhos: 'Tigrinhos',
  tijucas: 'Tijucas',
  'timbe do sul': 'Timbé do Sul',
  timbo: 'Timbó',
  'timbo grande': 'Timbó Grande',
  'tres barras': 'Três Barras',
  treviso: 'Treviso',
  'treze de maio': 'Treze de Maio',
  'treze tilias': 'Treze Tílias',
  'trombudo central': 'Trombudo Central',
  tubarao: 'Tubarão',
  tunapolis: 'Tunápolis',
  turvo_: 'Turvo',
  'uniao do oeste': 'União do Oeste',
  urubici: 'Urubici',
  urupema: 'Urupema',
  urussanga: 'Urussanga',
  vargeao: 'Vargeão',
  vargem: 'Vargem',
  'vargem bonita_': 'Vargem Bonita',
  'vidal ramos': 'Vidal Ramos',
  videira: 'Videira',
  'vitor meireles': 'Vitor Meireles',
  witmarsum: 'Witmarsum',
  xanxere: 'Xanxerê',
  xavantina: 'Xavantina',
  xaxim: 'Xaxim',
  zortea: 'Zortéa',
};
