export const cities = {
  'amparo de sao francisco': { name: 'Amparo de São Francisco', state: 'SE' },
  aquidaba: { name: 'Aquidabã', state: 'SE' },
  aracaju: { name: 'Aracaju', state: 'SE' },
  araua: { name: 'Arauá', state: 'SE' },
  'areia branca_': { name: 'Areia Branca', state: 'SE' },
  'barra dos coqueiros': { name: 'Barra dos Coqueiros', state: 'SE' },
  boquim: { name: 'Boquim', state: 'SE' },
  'brejo grande': { name: 'Brejo Grande', state: 'SE' },
  'campo do brito': { name: 'Campo do Brito', state: 'SE' },
  canhoba: { name: 'Canhoba', state: 'SE' },
  'caninde de sao francisco': { name: 'Canindé de São Francisco', state: 'SE' },
  capela_: { name: 'Capela', state: 'SE' },
  carira: { name: 'Carira', state: 'SE' },
  carmopolis: { name: 'Carmópolis', state: 'SE' },
  'cedro de sao joao': { name: 'Cedro de São João', state: 'SE' },
  cristinapolis: { name: 'Cristinápolis', state: 'SE' },
  cumbe: { name: 'Cumbe', state: 'SE' },
  'divina pastora': { name: 'Divina Pastora', state: 'SE' },
  estancia: { name: 'Estância', state: 'SE' },
  'feira nova_': { name: 'Feira Nova', state: 'SE' },
  'frei paulo': { name: 'Frei Paulo', state: 'SE' },
  gararu: { name: 'Gararu', state: 'SE' },
  'general maynard': { name: 'General Maynard', state: 'SE' },
  'graccho cardoso': { name: 'Graccho Cardoso', state: 'SE' },
  'ilha das flores': { name: 'Ilha das Flores', state: 'SE' },
  indiaroba: { name: 'Indiaroba', state: 'SE' },
  itabaiana_: { name: 'Itabaiana', state: 'SE' },
  itabaianinha: { name: 'Itabaianinha', state: 'SE' },
  itabi: { name: 'Itabi', state: 'SE' },
  "itaporanga d'ajuda": { name: "Itaporanga d'Ajuda", state: 'SE' },
  japaratuba: { name: 'Japaratuba', state: 'SE' },
  japoata: { name: 'Japoatã', state: 'SE' },
  lagarto: { name: 'Lagarto', state: 'SE' },
  laranjeiras: { name: 'Laranjeiras', state: 'SE' },
  macambira: { name: 'Macambira', state: 'SE' },
  'malhada dos bois': { name: 'Malhada dos Bois', state: 'SE' },
  malhador: { name: 'Malhador', state: 'SE' },
  maruim: { name: 'Maruim', state: 'SE' },
  'moita bonita': { name: 'Moita Bonita', state: 'SE' },
  'monte alegre de sergipe': { name: 'Monte Alegre de Sergipe', state: 'SE' },
  muribeca: { name: 'Muribeca', state: 'SE' },
  neopolis: { name: 'Neópolis', state: 'SE' },
  'nossa senhora aparecida': { name: 'Nossa Senhora Aparecida', state: 'SE' },
  'nossa senhora da gloria': { name: 'Nossa Senhora da Glória', state: 'SE' },
  'nossa senhora das dores': { name: 'Nossa Senhora das Dores', state: 'SE' },
  'nossa senhora de lourdes': { name: 'Nossa Senhora de Lourdes', state: 'SE' },
  'nossa senhora do socorro': { name: 'Nossa Senhora do Socorro', state: 'SE' },
  pacatuba_: { name: 'Pacatuba', state: 'SE' },
  'pedra mole': { name: 'Pedra Mole', state: 'SE' },
  pedrinhas: { name: 'Pedrinhas', state: 'SE' },
  pinhao_: { name: 'Pinhão', state: 'SE' },
  pirambu: { name: 'Pirambu', state: 'SE' },
  'poco redondo': { name: 'Poço Redondo', state: 'SE' },
  'poco verde': { name: 'Poço Verde', state: 'SE' },
  'porto da folha': { name: 'Porto da Folha', state: 'SE' },
  propria: { name: 'Propriá', state: 'SE' },
  'riachao do dantas': { name: 'Riachão do Dantas', state: 'SE' },
  riachuelo_: { name: 'Riachuelo', state: 'SE' },
  ribeiropolis: { name: 'Ribeirópolis', state: 'SE' },
  'rosario do catete': { name: 'Rosário do Catete', state: 'SE' },
  salgado: { name: 'Salgado', state: 'SE' },
  'santa luzia do itanhi': { name: 'Santa Luzia do Itanhi', state: 'SE' },
  'santana do sao francisco': { name: 'Santana do São Francisco', state: 'SE' },
  'santa rosa de lima_': { name: 'Santa Rosa de Lima', state: 'SE' },
  'santo amaro das brotas': { name: 'Santo Amaro das Brotas', state: 'SE' },
  'sao cristovao': { name: 'São Cristóvão', state: 'SE' },
  'sao domingos____': { name: 'São Domingos', state: 'SE' },
  'sao francisco__': { name: 'São Francisco', state: 'SE' },
  'sao miguel do aleixo': { name: 'São Miguel do Aleixo', state: 'SE' },
  'simao dias': { name: 'Simão Dias', state: 'SE' },
  siriri: { name: 'Siriri', state: 'SE' },
  telha: { name: 'Telha', state: 'SE' },
  'tobias barreto': { name: 'Tobias Barreto', state: 'SE' },
  'tomar do geru': { name: 'Tomar do Geru', state: 'SE' },
  umbauba: { name: 'Umbaúba', state: 'SE' },
};
