export const cities = {
  'amparo de sao francisco': 'Amparo de São Francisco',
  aquidaba: 'Aquidabã',
  aracaju: 'Aracaju',
  araua: 'Arauá',
  'areia branca_': 'Areia Branca',
  'barra dos coqueiros': 'Barra dos Coqueiros',
  boquim: 'Boquim',
  'brejo grande': 'Brejo Grande',
  'campo do brito': 'Campo do Brito',
  canhoba: 'Canhoba',
  'caninde de sao francisco': 'Canindé de São Francisco',
  capela_: 'Capela',
  carira: 'Carira',
  carmopolis: 'Carmópolis',
  'cedro de sao joao': 'Cedro de São João',
  cristinapolis: 'Cristinápolis',
  cumbe: 'Cumbe',
  'divina pastora': 'Divina Pastora',
  estancia: 'Estância',
  'feira nova_': 'Feira Nova',
  'frei paulo': 'Frei Paulo',
  gararu: 'Gararu',
  'general maynard': 'General Maynard',
  'graccho cardoso': 'Graccho Cardoso',
  'ilha das flores': 'Ilha das Flores',
  indiaroba: 'Indiaroba',
  itabaiana_: 'Itabaiana',
  itabaianinha: 'Itabaianinha',
  itabi: 'Itabi',
  "itaporanga d'ajuda": "Itaporanga d'Ajuda",
  japaratuba: 'Japaratuba',
  japoata: 'Japoatã',
  lagarto: 'Lagarto',
  laranjeiras: 'Laranjeiras',
  macambira: 'Macambira',
  'malhada dos bois': 'Malhada dos Bois',
  malhador: 'Malhador',
  maruim: 'Maruim',
  'moita bonita': 'Moita Bonita',
  'monte alegre de sergipe': 'Monte Alegre de Sergipe',
  muribeca: 'Muribeca',
  neopolis: 'Neópolis',
  'nossa senhora aparecida': 'Nossa Senhora Aparecida',
  'nossa senhora da gloria': 'Nossa Senhora da Glória',
  'nossa senhora das dores': 'Nossa Senhora das Dores',
  'nossa senhora de lourdes': 'Nossa Senhora de Lourdes',
  'nossa senhora do socorro': 'Nossa Senhora do Socorro',
  pacatuba_: 'Pacatuba',
  'pedra mole': 'Pedra Mole',
  pedrinhas: 'Pedrinhas',
  pinhao_: 'Pinhão',
  pirambu: 'Pirambu',
  'poco redondo': 'Poço Redondo',
  'poco verde': 'Poço Verde',
  'porto da folha': 'Porto da Folha',
  propria: 'Propriá',
  'riachao do dantas': 'Riachão do Dantas',
  riachuelo_: 'Riachuelo',
  ribeiropolis: 'Ribeirópolis',
  'rosario do catete': 'Rosário do Catete',
  salgado: 'Salgado',
  'santa luzia do itanhi': 'Santa Luzia do Itanhi',
  'santana do sao francisco': 'Santana do São Francisco',
  'santa rosa de lima_': 'Santa Rosa de Lima',
  'santo amaro das brotas': 'Santo Amaro das Brotas',
  'sao cristovao': 'São Cristóvão',
  'sao domingos____': 'São Domingos',
  'sao francisco__': 'São Francisco',
  'sao miguel do aleixo': 'São Miguel do Aleixo',
  'simao dias': 'Simão Dias',
  siriri: 'Siriri',
  telha: 'Telha',
  'tobias barreto': 'Tobias Barreto',
  'tomar do geru': 'Tomar do Geru',
  umbauba: 'Umbaúba',
};
