export const cities = {
  adamantina: 'Adamantina',
  adolfo: 'Adolfo',
  aguai: 'Aguaí',
  'aguas da prata': 'Águas da Prata',
  'aguas de lindoia': 'Águas de Lindóia',
  'aguas de santa barbara': 'Águas de Santa Bárbara',
  'aguas de sao pedro': 'Águas de São Pedro',
  agudos: 'Agudos',
  alambari: 'Alambari',
  'alfredo marcondes': 'Alfredo Marcondes',
  altair: 'Altair',
  altinopolis: 'Altinópolis',
  'alto alegre__': 'Alto Alegre',
  aluminio: 'Alumínio',
  'alvares florence': 'Álvares Florence',
  'alvares machado': 'Álvares Machado',
  'alvaro de carvalho': 'Álvaro de Carvalho',
  alvinlandia: 'Alvinlândia',
  americana: 'Americana',
  'americo brasiliense': 'Américo Brasiliense',
  'americo de campos': 'Américo de Campos',
  amparo_: 'Amparo',
  analandia: 'Analândia',
  andradina: 'Andradina',
  angatuba: 'Angatuba',
  anhembi: 'Anhembi',
  anhumas: 'Anhumas',
  aparecida_: 'Aparecida',
  "aparecida d'oeste": "Aparecida d'Oeste",
  apiai: 'Apiaí',
  aracariguama: 'Araçariguama',
  aracatuba: 'Araçatuba',
  'aracoiaba da serra': 'Araçoiaba da Serra',
  aramina: 'Aramina',
  arandu: 'Arandu',
  arapei: 'Arapeí',
  araraquara: 'Araraquara',
  araras: 'Araras',
  'arco-iris': 'Arco-Íris',
  arealva: 'Arealva',
  areias: 'Areias',
  areiopolis: 'Areiópolis',
  ariranha: 'Ariranha',
  'artur nogueira': 'Artur Nogueira',
  aruja: 'Arujá',
  aspasia: 'Aspásia',
  assis: 'Assis',
  atibaia: 'Atibaia',
  auriflama: 'Auriflama',
  avai: 'Avaí',
  avanhandava: 'Avanhandava',
  avare: 'Avaré',
  'bady bassitt': 'Bady Bassitt',
  balbinos: 'Balbinos',
  balsamo: 'Bálsamo',
  bananal: 'Bananal',
  'barao de antonina': 'Barão de Antonina',
  barbosa: 'Barbosa',
  bariri: 'Bariri',
  'barra bonita_': 'Barra Bonita',
  'barra do chapeu': 'Barra do Chapéu',
  'barra do turvo': 'Barra do Turvo',
  barretos: 'Barretos',
  barrinha: 'Barrinha',
  barueri: 'Barueri',
  bastos: 'Bastos',
  batatais: 'Batatais',
  bauru: 'Bauru',
  bebedouro: 'Bebedouro',
  'bento de abreu': 'Bento de Abreu',
  'bernardino de campos': 'Bernardino de Campos',
  bertioga: 'Bertioga',
  bilac: 'Bilac',
  birigui: 'Birigui',
  'biritiba mirim': 'Biritiba Mirim',
  'boa esperanca do sul': 'Boa Esperança do Sul',
  bocaina_: 'Bocaina',
  bofete: 'Bofete',
  boituva: 'Boituva',
  'bom jesus dos perdoes': 'Bom Jesus dos Perdões',
  'bom sucesso de itarare': 'Bom Sucesso de Itararé',
  bora: 'Borá',
  boraceia: 'Boraceia',
  borborema_: 'Borborema',
  borebi: 'Borebi',
  botucatu: 'Botucatu',
  'braganca paulista': 'Bragança Paulista',
  brauna: 'Braúna',
  'brejo alegre': 'Brejo Alegre',
  brodowski: 'Brodowski',
  brotas: 'Brotas',
  buri: 'Buri',
  buritama: 'Buritama',
  buritizal: 'Buritizal',
  'cabralia paulista': 'Cabrália Paulista',
  cabreuva: 'Cabreúva',
  cacapava: 'Caçapava',
  'cachoeira paulista': 'Cachoeira Paulista',
  caconde: 'Caconde',
  cafelandia_: 'Cafelândia',
  caiabu: 'Caiabu',
  caieiras: 'Caieiras',
  caiua: 'Caiuá',
  cajamar: 'Cajamar',
  cajati: 'Cajati',
  cajobi: 'Cajobi',
  cajuru: 'Cajuru',
  'campina do monte alegre': 'Campina do Monte Alegre',
  campinas: 'Campinas',
  'campo limpo paulista': 'Campo Limpo Paulista',
  'campos do jordao': 'Campos do Jordão',
  'campos novos paulista': 'Campos Novos Paulista',
  cananeia: 'Cananéia',
  canas: 'Canas',
  'candido mota': 'Cândido Mota',
  'candido rodrigues': 'Cândido Rodrigues',
  canitar: 'Canitar',
  'capao bonito': 'Capão Bonito',
  'capela do alto': 'Capela do Alto',
  capivari: 'Capivari',
  caraguatatuba: 'Caraguatatuba',
  carapicuiba: 'Carapicuíba',
  cardoso: 'Cardoso',
  'casa branca': 'Casa Branca',
  'cassia dos coqueiros': 'Cássia dos Coqueiros',
  castilho: 'Castilho',
  catanduva: 'Catanduva',
  catigua: 'Catiguá',
  cedral_: 'Cedral',
  'cerqueira cesar': 'Cerqueira César',
  cerquilho: 'Cerquilho',
  'cesario lange': 'Cesário Lange',
  charqueada: 'Charqueada',
  chavantes: 'Chavantes',
  clementina: 'Clementina',
  colina: 'Colina',
  colombia: 'Colômbia',
  conchal: 'Conchal',
  conchas: 'Conchas',
  cordeiropolis: 'Cordeirópolis',
  coroados: 'Coroados',
  'coronel macedo': 'Coronel Macedo',
  corumbatai: 'Corumbataí',
  cosmopolis: 'Cosmópolis',
  cosmorama: 'Cosmorama',
  cotia: 'Cotia',
  cravinhos: 'Cravinhos',
  'cristais paulista': 'Cristais Paulista',
  cruzalia: 'Cruzália',
  cruzeiro: 'Cruzeiro',
  cubatao: 'Cubatão',
  cunha: 'Cunha',
  descalvado: 'Descalvado',
  diadema: 'Diadema',
  'dirce reis': 'Dirce Reis',
  divinolandia: 'Divinolândia',
  dobrada: 'Dobrada',
  'dois corregos': 'Dois Córregos',
  dolcinopolis: 'Dolcinópolis',
  dourado: 'Dourado',
  dracena: 'Dracena',
  duartina: 'Duartina',
  dumont: 'Dumont',
  echapora: 'Echaporã',
  eldorado_: 'Eldorado',
  'elias fausto': 'Elias Fausto',
  elisiario: 'Elisiário',
  embauba: 'Embaúba',
  'embu das artes': 'Embu das Artes',
  'embu-guacu': 'Embu-Guaçu',
  emilianopolis: 'Emilianópolis',
  'engenheiro coelho': 'Engenheiro Coelho',
  'espirito santo do pinhal': 'Espírito Santo do Pinhal',
  'espirito santo do turvo': 'Espírito Santo do Turvo',
  'estiva gerbi': 'Estiva Gerbi',
  "estrela d'oeste": "Estrela d'Oeste",
  'estrela do norte_': 'Estrela do Norte',
  'euclides da cunha paulista': 'Euclides da Cunha Paulista',
  fartura: 'Fartura',
  fernandopolis: 'Fernandópolis',
  'fernando prestes': 'Fernando Prestes',
  fernao: 'Fernão',
  'ferraz de vasconcelos': 'Ferraz de Vasconcelos',
  'flora rica': 'Flora Rica',
  floreal: 'Floreal',
  'florida paulista': 'Flórida Paulista',
  florinea: 'Florínea',
  franca: 'Franca',
  'francisco morato': 'Francisco Morato',
  'franco da rocha': 'Franco da Rocha',
  'gabriel monteiro': 'Gabriel Monteiro',
  galia: 'Gália',
  garca: 'Garça',
  'gastao vidigal': 'Gastão Vidigal',
  'gaviao peixoto': 'Gavião Peixoto',
  'general salgado': 'General Salgado',
  getulina: 'Getulina',
  glicerio: 'Glicério',
  guaicara: 'Guaiçara',
  guaimbe: 'Guaimbê',
  guaira_: 'Guaíra',
  guapiacu: 'Guapiaçu',
  guapiara: 'Guapiara',
  guara: 'Guará',
  guaracai: 'Guaraçaí',
  guaraci_: 'Guaraci',
  "guarani d'oeste": "Guarani d'Oeste",
  guaranta: 'Guarantã',
  guararapes: 'Guararapes',
  guararema: 'Guararema',
  guaratingueta: 'Guaratinguetá',
  guarei: 'Guareí',
  guariba: 'Guariba',
  guaruja: 'Guarujá',
  guarulhos: 'Guarulhos',
  guatapara: 'Guatapará',
  guzolandia: 'Guzolândia',
  herculandia: 'Herculândia',
  holambra: 'Holambra',
  hortolandia: 'Hortolândia',
  iacanga: 'Iacanga',
  iacri: 'Iacri',
  iaras: 'Iaras',
  ibate: 'Ibaté',
  ibira: 'Ibirá',
  ibirarema: 'Ibirarema',
  ibitinga: 'Ibitinga',
  ibiuna: 'Ibiúna',
  icem: 'Icém',
  iepe: 'Iepê',
  'igaracu do tiete': 'Igaraçu do Tietê',
  igarapava: 'Igarapava',
  igarata: 'Igaratá',
  iguape: 'Iguape',
  ilhabela: 'Ilhabela',
  'ilha comprida': 'Ilha Comprida',
  'ilha solteira': 'Ilha Solteira',
  indaiatuba: 'Indaiatuba',
  indiana: 'Indiana',
  indiapora: 'Indiaporã',
  'inubia paulista': 'Inúbia Paulista',
  ipaussu: 'Ipaussu',
  ipero: 'Iperó',
  ipeuna: 'Ipeúna',
  ipigua: 'Ipiguá',
  iporanga: 'Iporanga',
  ipua: 'Ipuã',
  iracemapolis: 'Iracemápolis',
  irapua: 'Irapuã',
  irapuru: 'Irapuru',
  itabera: 'Itaberá',
  itai: 'Itaí',
  itajobi: 'Itajobi',
  itaju: 'Itaju',
  itanhaem: 'Itanhaém',
  itaoca: 'Itaoca',
  'itapecerica da serra': 'Itapecerica da Serra',
  itapetininga: 'Itapetininga',
  itapeva_: 'Itapeva',
  itapevi: 'Itapevi',
  itapira: 'Itapira',
  'itapirapua paulista': 'Itapirapuã Paulista',
  itapolis: 'Itápolis',
  itaporanga_: 'Itaporanga',
  itapui: 'Itapuí',
  itapura: 'Itapura',
  itaquaquecetuba: 'Itaquaquecetuba',
  itarare: 'Itararé',
  itariri: 'Itariri',
  itatiba: 'Itatiba',
  itatinga: 'Itatinga',
  itirapina: 'Itirapina',
  itirapua: 'Itirapuã',
  itobi: 'Itobi',
  itu: 'Itu',
  itupeva: 'Itupeva',
  ituverava: 'Ituverava',
  jaborandi_: 'Jaborandi',
  jaboticabal: 'Jaboticabal',
  jacarei: 'Jacareí',
  jaci: 'Jaci',
  jacupiranga: 'Jacupiranga',
  jaguariuna: 'Jaguariúna',
  jales: 'Jales',
  jambeiro: 'Jambeiro',
  jandira: 'Jandira',
  jardinopolis_: 'Jardinópolis',
  jarinu: 'Jarinu',
  jau: 'Jaú',
  jeriquara: 'Jeriquara',
  joanopolis: 'Joanópolis',
  'joao ramalho': 'João Ramalho',
  'jose bonifacio': 'José Bonifácio',
  'julio mesquita': 'Júlio Mesquita',
  jumirim: 'Jumirim',
  jundiai: 'Jundiaí',
  junqueiropolis: 'Junqueirópolis',
  juquia: 'Juquiá',
  juquitiba: 'Juquitiba',
  lagoinha: 'Lagoinha',
  'laranjal paulista': 'Laranjal Paulista',
  lavinia: 'Lavínia',
  lavrinhas: 'Lavrinhas',
  leme: 'Leme',
  'lencois paulista': 'Lençóis Paulista',
  limeira: 'Limeira',
  lindoia: 'Lindóia',
  lins: 'Lins',
  lorena: 'Lorena',
  lourdes: 'Lourdes',
  louveira: 'Louveira',
  lucelia: 'Lucélia',
  lucianopolis: 'Lucianópolis',
  'luiz antonio': 'Luiz Antônio',
  luisiania: 'Luisiânia',
  lupercio: 'Lupércio',
  lutecia: 'Lutécia',
  macatuba: 'Macatuba',
  macaubal: 'Macaubal',
  macedonia: 'Macedônia',
  magda: 'Magda',
  mairinque: 'Mairinque',
  mairipora: 'Mairiporã',
  manduri: 'Manduri',
  'maraba paulista': 'Marabá Paulista',
  maracai: 'Maracaí',
  marapoama: 'Marapoama',
  mariapolis: 'Mariápolis',
  marilia: 'Marília',
  marinopolis: 'Marinópolis',
  martinopolis: 'Martinópolis',
  matao: 'Matão',
  maua: 'Mauá',
  mendonca: 'Mendonça',
  meridiano: 'Meridiano',
  mesopolis: 'Mesópolis',
  miguelopolis: 'Miguelópolis',
  'mineiros do tiete': 'Mineiros do Tietê',
  miracatu: 'Miracatu',
  'mira estrela': 'Mira Estrela',
  mirandopolis: 'Mirandópolis',
  'mirante do paranapanema': 'Mirante do Paranapanema',
  mirassol: 'Mirassol',
  mirassolandia: 'Mirassolândia',
  mococa: 'Mococa',
  'mogi das cruzes': 'Mogi das Cruzes',
  'mogi guacu': 'Mogi Guaçu',
  'mogi mirim': 'Mogi Mirim',
  mombuca: 'Mombuca',
  moncoes: 'Monções',
  mongagua: 'Mongaguá',
  'monte alegre do sul': 'Monte Alegre do Sul',
  'monte alto': 'Monte Alto',
  'monte aprazivel': 'Monte Aprazível',
  'monte azul paulista': 'Monte Azul Paulista',
  'monte castelo_': 'Monte Castelo',
  'monteiro lobato': 'Monteiro Lobato',
  'monte mor': 'Monte Mor',
  'morro agudo': 'Morro Agudo',
  morungaba: 'Morungaba',
  motuca: 'Motuca',
  'murutinga do sul': 'Murutinga do Sul',
  nantes: 'Nantes',
  narandiba: 'Narandiba',
  'natividade da serra': 'Natividade da Serra',
  'nazare paulista': 'Nazaré Paulista',
  'neves paulista': 'Neves Paulista',
  nhandeara: 'Nhandeara',
  nipoa: 'Nipoã',
  'nova alianca': 'Nova Aliança',
  'nova campina': 'Nova Campina',
  'nova canaa paulista': 'Nova Canaã Paulista',
  'nova castilho': 'Nova Castilho',
  'nova europa': 'Nova Europa',
  'nova granada': 'Nova Granada',
  'nova guataporanga': 'Nova Guataporanga',
  'nova independencia': 'Nova Independência',
  novais: 'Novais',
  'nova luzitania': 'Nova Luzitânia',
  'nova odessa': 'Nova Odessa',
  'novo horizonte__': 'Novo Horizonte',
  nuporanga: 'Nuporanga',
  ocaucu: 'Ocauçu',
  oleo: 'Óleo',
  olimpia: 'Olímpia',
  'onda verde': 'Onda Verde',
  oriente: 'Oriente',
  orindiuva: 'Orindiúva',
  orlandia: 'Orlândia',
  osasco: 'Osasco',
  'oscar bressane': 'Oscar Bressane',
  'osvaldo cruz': 'Osvaldo Cruz',
  ourinhos: 'Ourinhos',
  ouroeste: 'Ouroeste',
  'ouro verde_': 'Ouro Verde',
  pacaembu: 'Pacaembu',
  palestina_: 'Palestina',
  'palmares paulista': 'Palmares Paulista',
  "palmeira d'oeste": "Palmeira d'Oeste",
  palmital_: 'Palmital',
  panorama: 'Panorama',
  'paraguacu paulista': 'Paraguaçu Paulista',
  paraibuna: 'Paraibuna',
  paraiso_: 'Paraíso',
  paranapanema: 'Paranapanema',
  paranapua: 'Paranapuã',
  parapua: 'Parapuã',
  pardinho: 'Pardinho',
  'pariquera-acu': 'Pariquera-Açu',
  parisi: 'Parisi',
  'patrocinio paulista': 'Patrocínio Paulista',
  pauliceia: 'Paulicéia',
  paulinia: 'Paulínia',
  paulistania: 'Paulistânia',
  'paulo de faria': 'Paulo de Faria',
  pederneiras: 'Pederneiras',
  'pedra bela': 'Pedra Bela',
  pedranopolis: 'Pedranópolis',
  pedregulho: 'Pedregulho',
  pedreira: 'Pedreira',
  'pedrinhas paulista': 'Pedrinhas Paulista',
  'pedro de toledo': 'Pedro de Toledo',
  penapolis: 'Penápolis',
  'pereira barreto': 'Pereira Barreto',
  pereiras: 'Pereiras',
  peruibe: 'Peruíbe',
  piacatu: 'Piacatu',
  piedade: 'Piedade',
  'pilar do sul': 'Pilar do Sul',
  pindamonhangaba: 'Pindamonhangaba',
  pindorama: 'Pindorama',
  pinhalzinho_: 'Pinhalzinho',
  piquerobi: 'Piquerobi',
  piquete: 'Piquete',
  piracaia: 'Piracaia',
  piracicaba: 'Piracicaba',
  piraju: 'Piraju',
  pirajui: 'Pirajuí',
  pirangi: 'Pirangi',
  'pirapora do bom jesus': 'Pirapora do Bom Jesus',
  pirapozinho: 'Pirapozinho',
  pirassununga: 'Pirassununga',
  piratininga: 'Piratininga',
  pitangueiras_: 'Pitangueiras',
  planalto___: 'Planalto',
  platina: 'Platina',
  poa: 'Poá',
  poloni: 'Poloni',
  pompeia: 'Pompeia',
  pongai: 'Pongaí',
  pontal: 'Pontal',
  pontalinda: 'Pontalinda',
  'pontes gestal': 'Pontes Gestal',
  populina: 'Populina',
  porangaba: 'Porangaba',
  'porto feliz': 'Porto Feliz',
  'porto ferreira': 'Porto Ferreira',
  potim: 'Potim',
  potirendaba: 'Potirendaba',
  pracinha: 'Pracinha',
  pradopolis: 'Pradópolis',
  'praia grande_': 'Praia Grande',
  pratania: 'Pratânia',
  'presidente alves': 'Presidente Alves',
  'presidente bernardes_': 'Presidente Bernardes',
  'presidente epitacio': 'Presidente Epitácio',
  'presidente prudente': 'Presidente Prudente',
  'presidente venceslau': 'Presidente Venceslau',
  promissao: 'Promissão',
  quadra: 'Quadra',
  quata: 'Quatá',
  queiroz: 'Queiroz',
  queluz: 'Queluz',
  quintana: 'Quintana',
  rafard: 'Rafard',
  rancharia: 'Rancharia',
  'redencao da serra': 'Redenção da Serra',
  'regente feijo': 'Regente Feijó',
  reginopolis: 'Reginópolis',
  registro: 'Registro',
  restinga: 'Restinga',
  ribeira: 'Ribeira',
  'ribeirao bonito': 'Ribeirão Bonito',
  'ribeirao branco': 'Ribeirão Branco',
  'ribeirao corrente': 'Ribeirão Corrente',
  'ribeirao dos indios': 'Ribeirão dos Índios',
  'ribeirao do sul': 'Ribeirão do Sul',
  'ribeirao grande': 'Ribeirão Grande',
  'ribeirao pires': 'Ribeirão Pires',
  'ribeirao preto': 'Ribeirão Preto',
  rifaina: 'Rifaina',
  rincao: 'Rincão',
  rinopolis: 'Rinópolis',
  'rio claro_': 'Rio Claro',
  'rio das pedras': 'Rio das Pedras',
  'rio grande da serra': 'Rio Grande da Serra',
  riolandia: 'Riolândia',
  riversul: 'Riversul',
  rosana: 'Rosana',
  roseira: 'Roseira',
  rubiacea: 'Rubiácea',
  rubineia: 'Rubineia',
  sabino: 'Sabino',
  sagres: 'Sagres',
  sales: 'Sales',
  'sales oliveira': 'Sales Oliveira',
  salesopolis: 'Salesópolis',
  salmourao: 'Salmourão',
  saltinho_: 'Saltinho',
  salto: 'Salto',
  'salto de pirapora': 'Salto de Pirapora',
  'salto grande': 'Salto Grande',
  sandovalina: 'Sandovalina',
  'santa adelia': 'Santa Adélia',
  'santa albertina': 'Santa Albertina',
  "santa barbara d'oeste": "Santa Bárbara d'Oeste",
  'santa branca': 'Santa Branca',
  "santa clara d'oeste": "Santa Clara d'Oeste",
  'santa cruz da conceicao': 'Santa Cruz da Conceição',
  'santa cruz da esperanca': 'Santa Cruz da Esperança',
  'santa cruz das palmeiras': 'Santa Cruz das Palmeiras',
  'santa cruz do rio pardo': 'Santa Cruz do Rio Pardo',
  'santa ernestina': 'Santa Ernestina',
  'santa fe do sul': 'Santa Fé do Sul',
  'santa gertrudes': 'Santa Gertrudes',
  'santa isabel_': 'Santa Isabel',
  'santa lucia_': 'Santa Lúcia',
  'santa maria da serra': 'Santa Maria da Serra',
  'santa mercedes': 'Santa Mercedes',
  'santana da ponte pensa': 'Santana da Ponte Pensa',
  'santana de parnaiba': 'Santana de Parnaíba',
  "santa rita d'oeste": "Santa Rita d'Oeste",
  'santa rita do passa quatro': 'Santa Rita do Passa Quatro',
  'santa rosa de viterbo': 'Santa Rosa de Viterbo',
  'santa salete': 'Santa Salete',
  'santo anastacio': 'Santo Anastácio',
  'santo andre_': 'Santo André',
  'santo antonio da alegria': 'Santo Antônio da Alegria',
  'santo antonio de posse': 'Santo Antônio de Posse',
  'santo antonio do aracangua': 'Santo Antônio do Aracanguá',
  'santo antonio do jardim': 'Santo Antônio do Jardim',
  'santo antonio do pinhal': 'Santo Antônio do Pinhal',
  'santo expedito': 'Santo Expedito',
  'santopolis do aguapei': 'Santópolis do Aguapeí',
  santos: 'Santos',
  'sao bento do sapucai': 'São Bento do Sapucaí',
  'sao bernardo do campo': 'São Bernardo do Campo',
  'sao caetano do sul': 'São Caetano do Sul',
  'sao carlos_': 'São Carlos',
  'sao francisco___': 'São Francisco',
  'sao joao da boa vista': 'São João da Boa Vista',
  'sao joao das duas pontes': 'São João das Duas Pontes',
  'sao joao de iracema': 'São João de Iracema',
  "sao joao do pau-d'alho": "São João do Pau-d'Alho",
  'sao joaquim da barra': 'São Joaquim da Barra',
  'sao jose da bela vista': 'São José da Bela Vista',
  'sao jose do barreiro': 'São José do Barreiro',
  'sao jose do rio pardo': 'São José do Rio Pardo',
  'sao jose do rio preto': 'São José do Rio Preto',
  'sao jose dos campos': 'São José dos Campos',
  'sao lourenco da serra': 'São Lourenço da Serra',
  'sao luiz do paraitinga': 'São Luiz do Paraitinga',
  'sao manuel': 'São Manuel',
  'sao miguel arcanjo': 'São Miguel Arcanjo',
  'sao paulo': 'São Paulo',
  'sao pedro_': 'São Pedro',
  'sao pedro do turvo': 'São Pedro do Turvo',
  'sao roque': 'São Roque',
  'sao sebastiao_': 'São Sebastião',
  'sao sebastiao da grama': 'São Sebastião da Grama',
  'sao simao_': 'São Simão',
  'sao vicente_': 'São Vicente',
  sarapui: 'Sarapuí',
  sarutaia: 'Sarutaiá',
  'sebastianopolis do sul': 'Sebastianópolis do Sul',
  'serra azul': 'Serra Azul',
  serrana: 'Serrana',
  'serra negra': 'Serra Negra',
  sertaozinho_: 'Sertãozinho',
  'sete barras': 'Sete Barras',
  severinia: 'Severínia',
  silveiras: 'Silveiras',
  socorro: 'Socorro',
  sorocaba: 'Sorocaba',
  'sud mennucci': 'Sud Mennucci',
  sumare: 'Sumaré',
  suzanapolis: 'Suzanápolis',
  suzano: 'Suzano',
  tabapua: 'Tabapuã',
  tabatinga_: 'Tabatinga',
  'taboao da serra': 'Taboão da Serra',
  taciba: 'Taciba',
  taguai: 'Taguaí',
  taiacu: 'Taiaçu',
  taiuva: 'Taiuva',
  tambau: 'Tambaú',
  tanabi: 'Tanabi',
  tapirai_: 'Tapiraí',
  tapiratiba: 'Tapiratiba',
  taquaral: 'Taquaral',
  taquaritinga: 'Taquaritinga',
  taquarituba: 'Taquarituba',
  taquarivai: 'Taquarivaí',
  tarabai: 'Tarabai',
  taruma: 'Tarumã',
  tatui: 'Tatuí',
  taubate: 'Taubaté',
  tejupa: 'Tejupá',
  'teodoro sampaio_': 'Teodoro Sampaio',
  'terra roxa_': 'Terra Roxa',
  tiete: 'Tietê',
  timburi: 'Timburi',
  'torre de pedra': 'Torre de Pedra',
  torrinha: 'Torrinha',
  trabiju: 'Trabiju',
  tremembe: 'Tremembé',
  'tres fronteiras': 'Três Fronteiras',
  tuiuti: 'Tuiuti',
  tupa: 'Tupã',
  'tupi paulista': 'Tupi Paulista',
  turiuba: 'Turiúba',
  turmalina_: 'Turmalina',
  ubarana: 'Ubarana',
  ubatuba: 'Ubatuba',
  ubirajara: 'Ubirajara',
  uchoa: 'Uchoa',
  'uniao paulista': 'União Paulista',
  urania: 'Urânia',
  uru: 'Uru',
  urupes: 'Urupês',
  'valentim gentil': 'Valentim Gentil',
  valinhos: 'Valinhos',
  valparaiso: 'Valparaíso',
  vargem_: 'Vargem',
  'vargem grande do sul': 'Vargem Grande do Sul',
  'vargem grande paulista': 'Vargem Grande Paulista',
  'varzea paulista': 'Várzea Paulista',
  'vera cruz___': 'Vera Cruz',
  vinhedo: 'Vinhedo',
  viradouro: 'Viradouro',
  'vista alegre do alto': 'Vista Alegre do Alto',
  'vitoria brasil': 'Vitória Brasil',
  votorantim: 'Votorantim',
  votuporanga: 'Votuporanga',
  zacarias: 'Zacarias',
};
