export const cities = {
  abreulandia: 'Abreulândia',
  aguiarnopolis: 'Aguiarnópolis',
  'alianca do tocantins': 'Aliança do Tocantins',
  almas: 'Almas',
  alvorada_: 'Alvorada',
  ananas: 'Ananás',
  angico: 'Angico',
  'aparecida do rio negro': 'Aparecida do Rio Negro',
  aragominas: 'Aragominas',
  araguacema: 'Araguacema',
  araguacu: 'Araguaçu',
  araguaina: 'Araguaína',
  araguana_: 'Araguanã',
  araguatins: 'Araguatins',
  arapoema: 'Arapoema',
  arraias: 'Arraias',
  augustinopolis: 'Augustinópolis',
  'aurora do tocantins': 'Aurora do Tocantins',
  'axixa do tocantins': 'Axixá do Tocantins',
  babaculandia: 'Babaçulândia',
  'bandeirantes do tocantins': 'Bandeirantes do Tocantins',
  'barra do ouro': 'Barra do Ouro',
  barrolandia: 'Barrolândia',
  'bernardo sayao': 'Bernardo Sayão',
  'bom jesus do tocantins_': 'Bom Jesus do Tocantins',
  'brasilandia do tocantins': 'Brasilândia do Tocantins',
  'brejinho de nazare': 'Brejinho de Nazaré',
  'buriti do tocantins': 'Buriti do Tocantins',
  cachoeirinha__: 'Cachoeirinha',
  'campos lindos': 'Campos Lindos',
  'cariri do tocantins': 'Cariri do Tocantins',
  carmolandia: 'Carmolândia',
  'carrasco bonito': 'Carrasco Bonito',
  caseara: 'Caseara',
  centenario_: 'Centenário',
  'chapada de areia': 'Chapada de Areia',
  'chapada da natividade': 'Chapada da Natividade',
  'colinas do tocantins': 'Colinas do Tocantins',
  colmeia: 'Colméia',
  combinado: 'Combinado',
  'conceicao do tocantins': 'Conceição do Tocantins',
  'couto magalhaes': 'Couto Magalhães',
  cristalandia: 'Cristalândia',
  'crixas do tocantins': 'Crixás do Tocantins',
  darcinopolis: 'Darcinópolis',
  dianopolis: 'Dianópolis',
  'divinopolis do tocantins': 'Divinópolis do Tocantins',
  'dois irmaos do tocantins': 'Dois Irmãos do Tocantins',
  duere: 'Dueré',
  esperantina_: 'Esperantina',
  fatima_: 'Fátima',
  figueiropolis: 'Figueirópolis',
  filadelfia_: 'Filadélfia',
  'formoso do araguaia': 'Formoso do Araguaia',
  goianorte: 'Goianorte',
  goiatins: 'Goiatins',
  guarai: 'Guaraí',
  gurupi: 'Gurupi',
  ipueiras_: 'Ipueiras',
  itacaja: 'Itacajá',
  itaguatins: 'Itaguatins',
  itapiratins: 'Itapiratins',
  'itapora do tocantins': 'Itaporã do Tocantins',
  'jau do tocantins': 'Jaú do Tocantins',
  juarina: 'Juarina',
  'lagoa da confusao': 'Lagoa da Confusão',
  'lagoa do tocantins': 'Lagoa do Tocantins',
  lajeado_: 'Lajeado',
  lavandeira: 'Lavandeira',
  lizarda: 'Lizarda',
  luzinopolis: 'Luzinópolis',
  'marianopolis do tocantins': 'Marianópolis do Tocantins',
  mateiros: 'Mateiros',
  'maurilandia do tocantins': 'Maurilândia do Tocantins',
  'miracema do tocantins': 'Miracema do Tocantins',
  miranorte: 'Miranorte',
  'monte do carmo': 'Monte do Carmo',
  'monte santo do tocantins': 'Monte Santo do Tocantins',
  muricilandia: 'Muricilândia',
  natividade_: 'Natividade',
  nazare_: 'Nazaré',
  'nova olinda__': 'Nova Olinda',
  'nova rosalandia': 'Nova Rosalândia',
  'novo acordo': 'Novo Acordo',
  'novo alegre': 'Novo Alegre',
  'novo jardim': 'Novo Jardim',
  'oliveira de fatima': 'Oliveira de Fátima',
  palmas_: 'Palmas',
  palmeirante: 'Palmeirante',
  'palmeiras do tocantins': 'Palmeiras do Tocantins',
  palmeiropolis: 'Palmeirópolis',
  'paraiso do tocantins': 'Paraíso do Tocantins',
  parana_: 'Paranã',
  "pau-d'arco_": "Pau-d'Arco",
  'pedro afonso': 'Pedro Afonso',
  peixe: 'Peixe',
  pequizeiro: 'Pequizeiro',
  'pindorama do tocantins': 'Pindorama do Tocantins',
  piraque: 'Piraquê',
  pium: 'Pium',
  'ponte alta do bom jesus': 'Ponte Alta do Bom Jesus',
  'ponte alta do tocantins': 'Ponte Alta do Tocantins',
  'porto alegre do tocantins': 'Porto Alegre do Tocantins',
  'porto nacional': 'Porto Nacional',
  'praia norte': 'Praia Norte',
  'presidente kennedy_': 'Presidente Kennedy',
  pugmil: 'Pugmil',
  recursolandia: 'Recursolândia',
  riachinho_: 'Riachinho',
  'rio da conceicao': 'Rio da Conceição',
  'rio dos bois': 'Rio dos Bois',
  'rio sono': 'Rio Sono',
  sampaio: 'Sampaio',
  sandolandia: 'Sandolândia',
  'santa fe do araguaia': 'Santa Fé do Araguaia',
  'santa maria do tocantins': 'Santa Maria do Tocantins',
  'santa rita do tocantins': 'Santa Rita do Tocantins',
  'santa rosa do tocantins': 'Santa Rosa do Tocantins',
  'santa tereza do tocantins': 'Santa Tereza do Tocantins',
  'santa terezinha do tocantins': 'Santa Terezinha do Tocantins',
  'sao bento do tocantins': 'São Bento do Tocantins',
  'sao felix do tocantins': 'São Félix do Tocantins',
  'sao miguel do tocantins': 'São Miguel do Tocantins',
  'sao salvador do tocantins': 'São Salvador do Tocantins',
  'sao sebastiao do tocantins': 'São Sebastião do Tocantins',
  'sao valerio': 'São Valério',
  silvanopolis: 'Silvanópolis',
  'sitio novo do tocantins': 'Sítio Novo do Tocantins',
  sucupira: 'Sucupira',
  tabocao: 'Tabocão',
  taguatinga: 'Taguatinga',
  'taipas do tocantins': 'Taipas do Tocantins',
  talisma: 'Talismã',
  tocantinia: 'Tocantínia',
  tocantinopolis: 'Tocantinópolis',
  tupirama: 'Tupirama',
  tupiratins: 'Tupiratins',
  wanderlandia: 'Wanderlândia',
  xambioa: 'Xambioá',
};
