export const cities = {
  abreulandia: { name: 'Abreulândia', state: 'TO' },
  aguiarnopolis: { name: 'Aguiarnópolis', state: 'TO' },
  'alianca do tocantins': { name: 'Aliança do Tocantins', state: 'TO' },
  almas: { name: 'Almas', state: 'TO' },
  alvorada_: { name: 'Alvorada', state: 'TO' },
  ananas: { name: 'Ananás', state: 'TO' },
  angico: { name: 'Angico', state: 'TO' },
  'aparecida do rio negro': { name: 'Aparecida do Rio Negro', state: 'TO' },
  aragominas: { name: 'Aragominas', state: 'TO' },
  araguacema: { name: 'Araguacema', state: 'TO' },
  araguacu: { name: 'Araguaçu', state: 'TO' },
  araguaina: { name: 'Araguaína', state: 'TO' },
  araguana_: { name: 'Araguanã', state: 'TO' },
  araguatins: { name: 'Araguatins', state: 'TO' },
  arapoema: { name: 'Arapoema', state: 'TO' },
  arraias: { name: 'Arraias', state: 'TO' },
  augustinopolis: { name: 'Augustinópolis', state: 'TO' },
  'aurora do tocantins': { name: 'Aurora do Tocantins', state: 'TO' },
  'axixa do tocantins': { name: 'Axixá do Tocantins', state: 'TO' },
  babaculandia: { name: 'Babaçulândia', state: 'TO' },
  'bandeirantes do tocantins': { name: 'Bandeirantes do Tocantins', state: 'TO' },
  'barra do ouro': { name: 'Barra do Ouro', state: 'TO' },
  barrolandia: { name: 'Barrolândia', state: 'TO' },
  'bernardo sayao': { name: 'Bernardo Sayão', state: 'TO' },
  'bom jesus do tocantins_': { name: 'Bom Jesus do Tocantins', state: 'TO' },
  'brasilandia do tocantins': { name: 'Brasilândia do Tocantins', state: 'TO' },
  'brejinho de nazare': { name: 'Brejinho de Nazaré', state: 'TO' },
  'buriti do tocantins': { name: 'Buriti do Tocantins', state: 'TO' },
  cachoeirinha__: { name: 'Cachoeirinha', state: 'TO' },
  'campos lindos': { name: 'Campos Lindos', state: 'TO' },
  'cariri do tocantins': { name: 'Cariri do Tocantins', state: 'TO' },
  carmolandia: { name: 'Carmolândia', state: 'TO' },
  'carrasco bonito': { name: 'Carrasco Bonito', state: 'TO' },
  caseara: { name: 'Caseara', state: 'TO' },
  centenario_: { name: 'Centenário', state: 'TO' },
  'chapada de areia': { name: 'Chapada de Areia', state: 'TO' },
  'chapada da natividade': { name: 'Chapada da Natividade', state: 'TO' },
  'colinas do tocantins': { name: 'Colinas do Tocantins', state: 'TO' },
  colmeia: { name: 'Colméia', state: 'TO' },
  combinado: { name: 'Combinado', state: 'TO' },
  'conceicao do tocantins': { name: 'Conceição do Tocantins', state: 'TO' },
  'couto magalhaes': { name: 'Couto Magalhães', state: 'TO' },
  cristalandia: { name: 'Cristalândia', state: 'TO' },
  'crixas do tocantins': { name: 'Crixás do Tocantins', state: 'TO' },
  darcinopolis: { name: 'Darcinópolis', state: 'TO' },
  dianopolis: { name: 'Dianópolis', state: 'TO' },
  'divinopolis do tocantins': { name: 'Divinópolis do Tocantins', state: 'TO' },
  'dois irmaos do tocantins': { name: 'Dois Irmãos do Tocantins', state: 'TO' },
  duere: { name: 'Dueré', state: 'TO' },
  esperantina_: { name: 'Esperantina', state: 'TO' },
  fatima_: { name: 'Fátima', state: 'TO' },
  figueiropolis: { name: 'Figueirópolis', state: 'TO' },
  filadelfia_: { name: 'Filadélfia', state: 'TO' },
  'formoso do araguaia': { name: 'Formoso do Araguaia', state: 'TO' },
  goianorte: { name: 'Goianorte', state: 'TO' },
  goiatins: { name: 'Goiatins', state: 'TO' },
  guarai: { name: 'Guaraí', state: 'TO' },
  gurupi: { name: 'Gurupi', state: 'TO' },
  ipueiras_: { name: 'Ipueiras', state: 'TO' },
  itacaja: { name: 'Itacajá', state: 'TO' },
  itaguatins: { name: 'Itaguatins', state: 'TO' },
  itapiratins: { name: 'Itapiratins', state: 'TO' },
  'itapora do tocantins': { name: 'Itaporã do Tocantins', state: 'TO' },
  'jau do tocantins': { name: 'Jaú do Tocantins', state: 'TO' },
  juarina: { name: 'Juarina', state: 'TO' },
  'lagoa da confusao': { name: 'Lagoa da Confusão', state: 'TO' },
  'lagoa do tocantins': { name: 'Lagoa do Tocantins', state: 'TO' },
  lajeado_: { name: 'Lajeado', state: 'TO' },
  lavandeira: { name: 'Lavandeira', state: 'TO' },
  lizarda: { name: 'Lizarda', state: 'TO' },
  luzinopolis: { name: 'Luzinópolis', state: 'TO' },
  'marianopolis do tocantins': { name: 'Marianópolis do Tocantins', state: 'TO' },
  mateiros: { name: 'Mateiros', state: 'TO' },
  'maurilandia do tocantins': { name: 'Maurilândia do Tocantins', state: 'TO' },
  'miracema do tocantins': { name: 'Miracema do Tocantins', state: 'TO' },
  miranorte: { name: 'Miranorte', state: 'TO' },
  'monte do carmo': { name: 'Monte do Carmo', state: 'TO' },
  'monte santo do tocantins': { name: 'Monte Santo do Tocantins', state: 'TO' },
  muricilandia: { name: 'Muricilândia', state: 'TO' },
  natividade_: { name: 'Natividade', state: 'TO' },
  nazare_: { name: 'Nazaré', state: 'TO' },
  'nova olinda__': { name: 'Nova Olinda', state: 'TO' },
  'nova rosalandia': { name: 'Nova Rosalândia', state: 'TO' },
  'novo acordo': { name: 'Novo Acordo', state: 'TO' },
  'novo alegre': { name: 'Novo Alegre', state: 'TO' },
  'novo jardim': { name: 'Novo Jardim', state: 'TO' },
  'oliveira de fatima': { name: 'Oliveira de Fátima', state: 'TO' },
  palmas_: { name: 'Palmas', state: 'TO' },
  palmeirante: { name: 'Palmeirante', state: 'TO' },
  'palmeiras do tocantins': { name: 'Palmeiras do Tocantins', state: 'TO' },
  palmeiropolis: { name: 'Palmeirópolis', state: 'TO' },
  'paraiso do tocantins': { name: 'Paraíso do Tocantins', state: 'TO' },
  parana_: { name: 'Paranã', state: 'TO' },
  "pau-d'arco_": { name: "Pau-d'Arco", state: 'TO' },
  'pedro afonso': { name: 'Pedro Afonso', state: 'TO' },
  peixe: { name: 'Peixe', state: 'TO' },
  pequizeiro: { name: 'Pequizeiro', state: 'TO' },
  'pindorama do tocantins': { name: 'Pindorama do Tocantins', state: 'TO' },
  piraque: { name: 'Piraquê', state: 'TO' },
  pium: { name: 'Pium', state: 'TO' },
  'ponte alta do bom jesus': { name: 'Ponte Alta do Bom Jesus', state: 'TO' },
  'ponte alta do tocantins': { name: 'Ponte Alta do Tocantins', state: 'TO' },
  'porto alegre do tocantins': { name: 'Porto Alegre do Tocantins', state: 'TO' },
  'porto nacional': { name: 'Porto Nacional', state: 'TO' },
  'praia norte': { name: 'Praia Norte', state: 'TO' },
  'presidente kennedy_': { name: 'Presidente Kennedy', state: 'TO' },
  pugmil: { name: 'Pugmil', state: 'TO' },
  recursolandia: { name: 'Recursolândia', state: 'TO' },
  riachinho_: { name: 'Riachinho', state: 'TO' },
  'rio da conceicao': { name: 'Rio da Conceição', state: 'TO' },
  'rio dos bois': { name: 'Rio dos Bois', state: 'TO' },
  'rio sono': { name: 'Rio Sono', state: 'TO' },
  sampaio: { name: 'Sampaio', state: 'TO' },
  sandolandia: { name: 'Sandolândia', state: 'TO' },
  'santa fe do araguaia': { name: 'Santa Fé do Araguaia', state: 'TO' },
  'santa maria do tocantins': { name: 'Santa Maria do Tocantins', state: 'TO' },
  'santa rita do tocantins': { name: 'Santa Rita do Tocantins', state: 'TO' },
  'santa rosa do tocantins': { name: 'Santa Rosa do Tocantins', state: 'TO' },
  'santa tereza do tocantins': { name: 'Santa Tereza do Tocantins', state: 'TO' },
  'santa terezinha do tocantins': { name: 'Santa Terezinha do Tocantins', state: 'TO' },
  'sao bento do tocantins': { name: 'São Bento do Tocantins', state: 'TO' },
  'sao felix do tocantins': { name: 'São Félix do Tocantins', state: 'TO' },
  'sao miguel do tocantins': { name: 'São Miguel do Tocantins', state: 'TO' },
  'sao salvador do tocantins': { name: 'São Salvador do Tocantins', state: 'TO' },
  'sao sebastiao do tocantins': { name: 'São Sebastião do Tocantins', state: 'TO' },
  'sao valerio': { name: 'São Valério', state: 'TO' },
  silvanopolis: { name: 'Silvanópolis', state: 'TO' },
  'sitio novo do tocantins': { name: 'Sítio Novo do Tocantins', state: 'TO' },
  sucupira: { name: 'Sucupira', state: 'TO' },
  tabocao: { name: 'Tabocão', state: 'TO' },
  taguatinga: { name: 'Taguatinga', state: 'TO' },
  'taipas do tocantins': { name: 'Taipas do Tocantins', state: 'TO' },
  talisma: { name: 'Talismã', state: 'TO' },
  tocantinia: { name: 'Tocantínia', state: 'TO' },
  tocantinopolis: { name: 'Tocantinópolis', state: 'TO' },
  tupirama: { name: 'Tupirama', state: 'TO' },
  tupiratins: { name: 'Tupiratins', state: 'TO' },
  wanderlandia: { name: 'Wanderlândia', state: 'TO' },
  xambioa: { name: 'Xambioá', state: 'TO' },
};
