export const brazilianStates = {
  AC: { name: 'Acre', cities: import('./cities/AC') },
  AL: { name: 'Alagoas', cities: import('./cities/AL') },
  AP: { name: 'Amapá', cities: import('./cities/AP') },
  AM: { name: 'Amazonas', cities: import('./cities/AM') },
  BA: { name: 'Bahia', cities: import('./cities/BA') },
  CE: { name: 'Ceará', cities: import('./cities/CE') },
  ES: { name: 'Espírito Santo', cities: import('./cities/ES') },
  GO: { name: 'Goiás', cities: import('./cities/GO') },
  MA: { name: 'Maranhão', cities: import('./cities/MA') },
  MT: { name: 'Mato Grosso', cities: import('./cities/MT') },
  MS: { name: 'Mato Grosso do Sul', cities: import('./cities/MS') },
  MG: { name: 'Minas Gerais', cities: import('./cities/MG') },
  PA: { name: 'Pará', cities: import('./cities/PA') },
  PB: { name: 'Paraíba', cities: import('./cities/PB') },
  PR: { name: 'Paraná', cities: import('./cities/PR') },
  PE: { name: 'Pernambuco', cities: import('./cities/PE') },
  PI: { name: 'Piauí', cities: import('./cities/PI') },
  RJ: { name: 'Rio de Janeiro', cities: import('./cities/RJ') },
  RN: { name: 'Rio Grande do Norte', cities: import('./cities/RN') },
  RS: { name: 'Rio Grande do Sul', cities: import('./cities/RS') },
  RO: { name: 'Rondônia', cities: import('./cities/RO') },
  RR: { name: 'Roraima', cities: import('./cities/RR') },
  SC: { name: 'Santa Catarina', cities: import('./cities/SC') },
  SP: { name: 'São Paulo', cities: import('./cities/SP') },
  SE: { name: 'Sergipe', cities: import('./cities/SE') },
  TO: { name: 'Tocantins', cities: import('./cities/TO') },
  DF: { name: 'Distrito Federal', cities: import('./cities/DF') },
};
