export const brazilianStates = {
  AC: { name: 'Acre', cities: import('./cities/AC.TS') },
  AL: { name: 'Alagoas', cities: import('./cities/AL.TS') },
  AP: { name: 'Amapá', cities: import('./cities/AP.TS') },
  AM: { name: 'Amazonas', cities: import('./cities/AM.TS') },
  BA: { name: 'Bahia', cities: import('./cities/BA.TS') },
  CE: { name: 'Ceará', cities: import('./cities/CE.TS') },
  ES: { name: 'Espírito Santo', cities: import('./cities/ES.TS') },
  GO: { name: 'Goiás', cities: import('./cities/GO.TS') },
  MA: { name: 'Maranhão', cities: import('./cities/MA.TS') },
  MT: { name: 'Mato Grosso', cities: import('./cities/MT.TS') },
  MS: { name: 'Mato Grosso do Sul', cities: import('./cities/MS.TS') },
  MG: { name: 'Minas Gerais', cities: import('./cities/MG.TS') },
  PA: { name: 'Pará', cities: import('./cities/PA.TS') },
  PB: { name: 'Paraíba', cities: import('./cities/PB.TS') },
  PR: { name: 'Paraná', cities: import('./cities/PR.TS') },
  PE: { name: 'Pernambuco', cities: import('./cities/PE.TS') },
  PI: { name: 'Piauí', cities: import('./cities/PI.TS') },
  RJ: { name: 'Rio de Janeiro', cities: import('./cities/RJ.TS') },
  RN: { name: 'Rio Grande do Norte', cities: import('./cities/RN.TS') },
  RS: { name: 'Rio Grande do Sul', cities: import('./cities/RS.TS') },
  RO: { name: 'Rondônia', cities: import('./cities/RO.TS') },
  RR: { name: 'Roraima', cities: import('./cities/RR.TS') },
  SC: { name: 'Santa Catarina', cities: import('./cities/SC.TS') },
  SP: { name: 'São Paulo', cities: import('./cities/SP.TS') },
  SE: { name: 'Sergipe', cities: import('./cities/SE.TS') },
  TO: { name: 'Tocantins', cities: import('./cities/TO.TS') },
  DF: { name: 'Distrito Federal', cities: import('./cities/DF.TS') },
};
